var annotated_dup =
[
    [ "rsj", "namespacersj.html", "namespacersj" ],
    [ "std", null, [
      [ "hash< rsj::MidiMessageId >", "structstd_1_1hash_3_01rsj_1_1_midi_message_id_01_4.html", "structstd_1_1hash_3_01rsj_1_1_midi_message_id_01_4" ]
    ] ],
    [ "CCoptions", "class_c_coptions.html", "class_c_coptions" ],
    [ "ChannelModel", "class_channel_model.html", "class_channel_model" ],
    [ "CommandMenu", "class_command_menu.html", "class_command_menu" ],
    [ "CommandSet", "class_command_set.html", "class_command_set" ],
    [ "CommandTable", "class_command_table.html", "class_command_table" ],
    [ "CommandTableModel", "class_command_table_model.html", "class_command_table_model" ],
    [ "ControlsModel", "class_controls_model.html", "class_controls_model" ],
    [ "DebugInfo", "class_debug_info.html", "class_debug_info" ],
    [ "Listener", "classjuce_1_1_text_editor_1_1_listener.html", null ],
    [ "Listener", "classjuce_1_1_button_1_1_listener.html", null ],
    [ "LrIpcIn", "class_lr_ipc_in.html", "class_lr_ipc_in" ],
    [ "LrIpcOut", "class_lr_ipc_out.html", "class_lr_ipc_out" ],
    [ "MainContentComponent", "class_main_content_component.html", "class_main_content_component" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MIDI2LRApplication", "class_m_i_d_i2_l_r_application.html", "class_m_i_d_i2_l_r_application" ],
    [ "MidiReceiver", "class_midi_receiver.html", "class_midi_receiver" ],
    [ "MidiSender", "class_midi_sender.html", "class_midi_sender" ],
    [ "NrpnFilter", "class_nrpn_filter.html", "class_nrpn_filter" ],
    [ "Profile", "class_profile.html", "class_profile" ],
    [ "ProfileManager", "class_profile_manager.html", "class_profile_manager" ],
    [ "PWoptions", "class_p_woptions.html", "class_p_woptions" ],
    [ "ResizableChild", "class_resizable_child.html", "class_resizable_child" ],
    [ "ResizableLayout", "class_resizable_layout.html", "class_resizable_layout" ],
    [ "SettingsComponent", "class_settings_component.html", "class_settings_component" ],
    [ "SettingsManager", "class_settings_manager.html", "class_settings_manager" ],
    [ "TextButtonAligned", "class_text_button_aligned.html", "class_text_button_aligned" ],
    [ "TopLevelResizableLayout", "class_top_level_resizable_layout.html", "class_top_level_resizable_layout" ],
    [ "VersionChecker", "class_version_checker.html", "class_version_checker" ]
];