var annotated_dup =
[
    [ "MIDI2LR", "namespace_m_i_d_i2_l_r.html", "namespace_m_i_d_i2_l_r" ],
    [ "std", null, [
      [ "hash< MIDI_Message >", "structstd_1_1hash_3_01_m_i_d_i___message_01_4.html", "structstd_1_1hash_3_01_m_i_d_i___message_01_4" ],
      [ "hash< String >", "structstd_1_1hash_3_01_string_01_4.html", "structstd_1_1hash_3_01_string_01_4" ]
    ] ],
    [ "abstract", "classabstract.html", "classabstract" ],
    [ "CommandMap", "class_command_map.html", "class_command_map" ],
    [ "CommandMenu", "class_command_menu.html", "class_command_menu" ],
    [ "CommandTable", "class_command_table.html", "class_command_table" ],
    [ "CommandTableModel", "class_command_table_model.html", "class_command_table_model" ],
    [ "ISingleton", "class_i_singleton.html", null ],
    [ "LR_IPC_IN", "class_l_r___i_p_c___i_n.html", "class_l_r___i_p_c___i_n" ],
    [ "LR_IPC_OUT", "class_l_r___i_p_c___o_u_t.html", "class_l_r___i_p_c___o_u_t" ],
    [ "LRCommandList", "class_l_r_command_list.html", null ],
    [ "LRConnectionListener", "class_l_r_connection_listener.html", "class_l_r_connection_listener" ],
    [ "MainContentComponent", "class_main_content_component.html", "class_main_content_component" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MIDI2LRApplication", "class_m_i_d_i2_l_r_application.html", "class_m_i_d_i2_l_r_application" ],
    [ "MIDI_Message", "struct_m_i_d_i___message.html", "struct_m_i_d_i___message" ],
    [ "MIDICommandListener", "class_m_i_d_i_command_listener.html", "class_m_i_d_i_command_listener" ],
    [ "MIDIProcessor", "class_m_i_d_i_processor.html", "class_m_i_d_i_processor" ],
    [ "MIDISender", "class_m_i_d_i_sender.html", "class_m_i_d_i_sender" ],
    [ "Observer", "class_observer.html", "class_observer" ],
    [ "ProfileChangeListener", "class_profile_change_listener.html", "class_profile_change_listener" ],
    [ "ProfileManager", "class_profile_manager.html", "class_profile_manager" ],
    [ "ResizableChild", "class_resizable_child.html", "class_resizable_child" ],
    [ "ResizableLayout", "class_resizable_layout.html", "class_resizable_layout" ],
    [ "sealed", "classsealed.html", "classsealed" ],
    [ "SendKeys", "class_send_keys.html", "class_send_keys" ],
    [ "SettingsComponent", "class_settings_component.html", "class_settings_component" ],
    [ "SettingsManager", "class_settings_manager.html", "class_settings_manager" ],
    [ "Singleton", "class_singleton.html", null ],
    [ "SingletonMgr", "class_singleton_mgr.html", null ],
    [ "Subject", "class_subject.html", "class_subject" ],
    [ "TopLevelResizableLayout", "class_top_level_resizable_layout.html", "class_top_level_resizable_layout" ],
    [ "VersionChecker", "class_version_checker.html", "class_version_checker" ]
];