var annotated_dup =
[
    [ "gsl", "namespacegsl.html", "namespacegsl" ],
    [ "mir", "namespacemir.html", "namespacemir" ],
    [ "RSJ", "namespace_r_s_j.html", "namespace_r_s_j" ],
    [ "std", null, [
      [ "hash< MIDI_Message_ID >", "structstd_1_1hash_3_01_m_i_d_i___message___i_d_01_4.html", "structstd_1_1hash_3_01_m_i_d_i___message___i_d_01_4" ]
    ] ],
    [ "CCoptions", "class_c_coptions.html", "class_c_coptions" ],
    [ "ChannelModel", "class_channel_model.html", "class_channel_model" ],
    [ "CommandMap", "class_command_map.html", "class_command_map" ],
    [ "CommandMenu", "class_command_menu.html", "class_command_menu" ],
    [ "CommandTable", "class_command_table.html", "class_command_table" ],
    [ "CommandTableModel", "class_command_table_model.html", "class_command_table_model" ],
    [ "ControlsModel", "class_controls_model.html", "class_controls_model" ],
    [ "LR_IPC_IN", "class_l_r___i_p_c___i_n.html", "class_l_r___i_p_c___i_n" ],
    [ "LR_IPC_OUT", "class_l_r___i_p_c___o_u_t.html", "class_l_r___i_p_c___o_u_t" ],
    [ "LRCommandList", "class_l_r_command_list.html", null ],
    [ "MainContentComponent", "class_main_content_component.html", "class_main_content_component" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MIDI2LRApplication", "class_m_i_d_i2_l_r_application.html", "class_m_i_d_i2_l_r_application" ],
    [ "MIDI_Message_ID", "struct_m_i_d_i___message___i_d.html", "struct_m_i_d_i___message___i_d" ],
    [ "MIDIProcessor", "class_m_i_d_i_processor.html", "class_m_i_d_i_processor" ],
    [ "MIDISender", "class_m_i_d_i_sender.html", "class_m_i_d_i_sender" ],
    [ "NRPN_Filter", "class_n_r_p_n___filter.html", "class_n_r_p_n___filter" ],
    [ "NRPN_Message", "class_n_r_p_n___message.html", "class_n_r_p_n___message" ],
    [ "ProfileManager", "class_profile_manager.html", "class_profile_manager" ],
    [ "PWoptions", "class_p_woptions.html", "class_p_woptions" ],
    [ "ResizableChild", "class_resizable_child.html", "class_resizable_child" ],
    [ "ResizableLayout", "class_resizable_layout.html", "class_resizable_layout" ],
    [ "SettingsComponent", "class_settings_component.html", "class_settings_component" ],
    [ "SettingsManager", "class_settings_manager.html", "class_settings_manager" ],
    [ "Subject", "class_subject.html", "class_subject" ],
    [ "threadsafe_queue", "classthreadsafe__queue.html", "classthreadsafe__queue" ],
    [ "TopLevelResizableLayout", "class_top_level_resizable_layout.html", "class_top_level_resizable_layout" ],
    [ "VersionChecker", "class_version_checker.html", "class_version_checker" ]
];