MIDI2LR: LrIpcIn Class Reference
LrIpcIn Class Reference final
#include <LR_IPC_In.h>
Public Member Functions
LrIpcIn (ControlsModel &c_model, ProfileManager &profile_manager, CommandMap &command_map)
LrIpcIn (const LrIpcIn &other)=delete
LrIpcIn (LrIpcIn &&other)=delete
~LrIpcIn ()
void Init (std::shared_ptr< MidiSender > midi_sender)
LrIpcIn & operator= (const LrIpcIn &other)=delete
LrIpcIn & operator= (LrIpcIn &&other)=delete
void PleaseStopThread ()
Private Member Functions
void ProcessLine ()
void run () override
void timerCallback () override
Private Attributes
CommandMap & command_map_
ControlsModel & controls_model_
moodycamel::BlockingReaderWriterQueue< std::string > line_
std::shared_ptr< MidiSender > midi_sender_ {nullptr}
std::future< void > process_line_future_
ProfileManager & profile_manager_
juce::StreamingSocket socket_ {}
bool thread_started_ {false}
std::mutex timer_mutex_
bool timer_off_ {false}
Constructor & Destructor Documentation
LrIpcIn() [1/3]
LrIpcIn::LrIpcIn (ControlsModel & c_model, ProfileManager & profile_manager, CommandMap & command_map)
     : juce::Thread{"LR_IPC_IN"}, command_map_{command_map}, controls_model_{c_model},
       profile_manager_{profile_manager}
 {
 }
~LrIpcIn()
LrIpcIn::~LrIpcIn ()
 {
    try {
       {
          auto lock = std::lock_guard(timer_mutex_);
          timer_off_ = true;
          juce::Timer::stopTimer();
       }
       if (!juce::Thread::stopThread(kStopWait))
          rsj::Log("stopThread failed in LrIpcIn destructor");
       if (const auto m = line_.size_approx())
          rsj::Log(juce::String(m) + " left in queue in LrIpcIn destructor");
       std::string line_copy{};
       while (line_.try_dequeue(line_copy)) {
          /* pump the queue empty */
       }
       line_.enqueue(kTerminate);
       socket_.close();
    }
    catch (...) {
       rsj::LogAndAlertError("Exception thrown in LrIpcIn destructor.");
       std::terminate();
    }
 }
LrIpcIn() [2/3]
LrIpcIn::LrIpcIn (const LrIpcIn & other) delete
LrIpcIn() [3/3]
LrIpcIn::LrIpcIn (LrIpcIn && other) delete
Member Function Documentation
Init()
void LrIpcIn::Init (std::shared_ptr< MidiSender > midi_sender)
 {
    try {
       midi_sender_ = std::move(midi_sender);
       // start the timer
       juce::Timer::startTimer(kConnectTimer);
       process_line_future_ = std::async(std::launch::async, &LrIpcIn::ProcessLine, this);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
operator=() [1/2]
LrIpcIn& LrIpcIn::operator= (const LrIpcIn & other) delete
operator=() [2/2]
LrIpcIn& LrIpcIn::operator= (LrIpcIn && other) delete
PleaseStopThread()
void LrIpcIn::PleaseStopThread ()
 {
    juce::Thread::signalThreadShouldExit();
    juce::Thread::notify();
 }
ProcessLine()
void LrIpcIn::ProcessLine () private
 {
    using namespace std::literals::string_literals;
    try {
 #pragma warning(suppress : 26426)
       const static std::unordered_map<std::string, int> kCmds = {
           {"SwitchProfile"s, 1}, {"SendKey"s, 2}, {"TerminateApplication"s, 3}};
       do {
          // process input into [parameter] [Value]
          std::string line_copy{};
          if (!line_.try_dequeue(line_copy))
             line_.wait_dequeue(line_copy);
          if (line_copy == kTerminate)
             return;
          std::string_view v{line_copy};
          Trim(v);
          auto value_string{v.substr(v.find_first_of(" \t\n") + 1)};
          value_string.remove_prefix(
              std::min(value_string.find_first_not_of(" \t\n"), value_string.size()));
          const auto command{std::string(
              v.substr(0, v.find_first_of(" \t\n")))}; // use this a lot, so convert to string once
          switch (kCmds.count(command) ? kCmds.at(command) : 0) {
          case 1: // SwitchProfile
             profile_manager_.SwitchToProfile(std::string(value_string));
             break;
          case 2: // SendKey
          {
             const auto modifiers = std::stoi(std::string(value_string));
             // trim twice on purpose: first digit, then spaces, as key may be digit
             value_string.remove_prefix(
                 std::min(value_string.find_first_not_of("0123456789"), value_string.size()));
             value_string.remove_prefix(
                 std::min(value_string.find_first_not_of(" \t\n"), value_string.size()));
             rsj::SendKeyDownUp(std::string(value_string), modifiers);
             break;
          }
          case 3: // TerminateApplication
             juce::JUCEApplication::getInstance()->systemRequestedQuit();
             return;
          case 0:
             // send associated messages to MIDI OUT devices
             if (midi_sender_) {
                const auto original_value = std::stod(std::string(value_string));
                for (const auto msg : command_map_.GetMessagesForCommand(command)) {
                   short msgtype{0};
                   switch (msg->msg_id_type) {
                   case rsj::MsgIdEnum::kNote:
                      msgtype = rsj::kNoteOnFlag;
                      break;
                   case rsj::MsgIdEnum::kCc:
                      msgtype = rsj::kCcFlag;
                      break;
                   case rsj::MsgIdEnum::kPitchBend:
                      msgtype = rsj::kPwFlag;
                   }
                   const auto value = controls_model_.PluginToController(msgtype,
                       gsl::narrow_cast<size_t>(msg->channel - 1),
                       gsl::narrow_cast<short>(msg->data), original_value);
                   if (midi_sender_) {
                      switch (msgtype) {
                      case rsj::kNoteOnFlag:
                         midi_sender_->SendNoteOn(msg->channel, msg->data, value);
                         break;
                      case rsj::kCcFlag:
                         if (controls_model_.GetCcMethod(gsl::narrow_cast<size_t>(msg->channel - 1),
                                 gsl::narrow_cast<short>(msg->data))
                             == rsj::CCmethod::kAbsolute)
                            midi_sender_->SendCc(msg->channel, msg->data, value);
                         break;
                      case rsj::kPwFlag:
                         midi_sender_->SendPitchWheel(msg->channel, value);
                         break;
                      default:
                         Ensures(!"Unexpected result for msgtype");
                      }
                   }
                }
             }
             break;
          default:
             Ensures(!"Unexpected result for cmds");
          }
       } while (true);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
run()
void LrIpcIn::run () override private
 {
    try {
       auto _ = gsl::finally([this] {
          auto lock = std::lock_guard(timer_mutex_);
          timer_off_ = true;
          juce::Timer::stopTimer();
       });
       while (!juce::Thread::threadShouldExit()) {
          std::array<char, kBufferSize> line{}; // zero filled by {} initialization
          // if not connected, executes a wait 333 then goes back to while. if connected, tries to
          // read a line, checks thread status and connection status before each read attempt.
          // Doesn't terminate thread if disconnected, as currently don't have graceful way to
          // restart thread.
          if (!socket_.isConnected()) {
             juce::Thread::wait(kNotConnectedWait);
          } // end if (is not connected)
          else {
             line.fill(0); // zero out buffer
             auto size_read = 0;
             // parse input until we have a line, then process that line, quit if connection lost
             while ((size_read == 0 || line.at(gsl::narrow_cast<size_t>(size_read) - 1) != '\n')
                    && socket_.isConnected()) {
                if (juce::Thread::threadShouldExit())
                   return; // after final action
                const auto wait_status = socket_.waitUntilReady(true, kReadyWait);
                switch (wait_status) {
                case -1:
 #pragma warning(suppress : 26438)
                   goto dumpLine; // read line failed, break out of switch and while
                case 0:
                   juce::Thread::wait(kEmptyWait);
                   break; // try again to read until char shows up
                case 1:
                   switch (socket_.read(&line.at(size_read), 1, false)) {
                   case -1:
 #pragma warning(suppress : 26438)
                      goto dumpLine; // read error
                   case 1:
                      size_read++;
                      break;
                   case 0:
                      // waitUntilReady returns 1 but read will is 0: it's an indication of a broken
                      // socket.
                      juce::JUCEApplication::getInstance()->systemRequestedQuit();
                      break;
                   default:
                      Ensures(!"Unexpected value for read status");
                   }
                   break;
                default:
                   Ensures(!"Unexpected value for wait_status");
                }
             } // end while !\n and is connected
             // if lose connection, line may not be terminated
             {
                std::string param{line.data()};
                if (param.back() == '\n') {
                   line_.enqueue(std::move(param));
                }
             } // scope param
          dumpLine: /* empty statement */;
          } // end else (is connected)
       }    // while not threadshouldexit, finally handles exit code
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
timerCallback()
void LrIpcIn::timerCallback () override private
 {
    try {
       auto lock = std::lock_guard(timer_mutex_);
       if (!timer_off_ && !socket_.isConnected() && !juce::Thread::threadShouldExit()) {
          if (socket_.connect(kHost, kLrInPort, kConnectTryTime))
             if (!thread_started_) {
                juce::Thread::startThread(); // avoid starting thread during shutdown
                thread_started_ = true;
             }
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
Member Data Documentation
command_map_
CommandMap& LrIpcIn::command_map_ private
controls_model_
ControlsModel& LrIpcIn::controls_model_ private
line_
moodycamel::BlockingReaderWriterQueue<std::string> LrIpcIn::line_ private
midi_sender_
std::shared_ptr<MidiSender> LrIpcIn::midi_sender_ {nullptr} private
process_line_future_
std::future<void> LrIpcIn::process_line_future_ private
profile_manager_
ProfileManager& LrIpcIn::profile_manager_ private
socket_
juce::StreamingSocket LrIpcIn::socket_ {} private
thread_started_
bool LrIpcIn::thread_started_ {false} private
timer_mutex_
std::mutex LrIpcIn::timer_mutex_ mutable private
timer_off_
bool LrIpcIn::timer_off_ {false} private
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/LR_IPC_In.h
D:/Users/Rory/source/repos/MIDI2LR/Source/LR_IPC_In.cpp