MIDI2LR: NrpnFilter Class Reference
NrpnFilter Class Reference
#include <NrpnMessage.h>
Public Member Functions
rsj::Nrpn GetNrpnIfReady (short channel)
bool IsInProcess (short channel) const
bool ProcessMidi (short channel, short control, short value)
Private Attributes
std::array< NrpnMessage, 16 > nrpn_messages_ {}
Member Function Documentation
GetNrpnIfReady()
rsj::Nrpn NrpnFilter::GetNrpnIfReady (short channel) inline
    {
       try {
          Expects(channel <= 15 && channel >= 0);
          return nrpn_messages_.at(channel & 0xF).GetNrpnIfReady();
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::ExceptionResponse(), and rsj::NumToChars().
IsInProcess()
bool NrpnFilter::IsInProcess (short channel) const inline
{
       try {
          Expects(channel <= 15 && channel >= 0);
          return nrpn_messages_.at(channel & 0xF).IsInProcess();
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::ExceptionResponse(), and rsj::NumToChars().
ProcessMidi()
bool NrpnFilter::ProcessMidi (short channel, short control, short value) inline
    {
       try {
          Expects(channel <= 15 && channel >= 0);
          return nrpn_messages_.at(channel & 0xF).ProcessMidi(control, value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Member Data Documentation
nrpn_messages_
std::array<NrpnMessage, 16> NrpnFilter::nrpn_messages_ {} private
The documentation for this class was generated from the following file:
D:/Users/Rory/source/repos/MIDI2LR/Source/NrpnMessage.h