MIDI2LR: MidiProcessor Class Reference
MidiProcessor Class Reference final
#include <MIDIProcessor.h>
Public Member Functions
MidiProcessor ()=default
MidiProcessor (const MidiProcessor &other)=delete
MidiProcessor (MidiProcessor &&other)=delete
~MidiProcessor ()
template<class T >
void AddCallback (T *const object, void(T::*const mf)(rsj::MidiMessage))
void Init ()
MidiProcessor & operator= (const MidiProcessor &other)=delete
MidiProcessor & operator= (MidiProcessor &&other)=delete
void RescanDevices ()
Private Member Functions
void DispatchMessages ()
void handleIncomingMidiMessage (juce::MidiInput *, const juce::MidiMessage &) override
void InitDevices ()
Private Attributes
std::vector< std::function< void(rsj::MidiMessage)> > callbacks_
std::vector< std::unique_ptr< juce::MidiInput > > devices_
std::future< void > dispatch_messages_future_
moodycamel::BlockingConcurrentQueue< rsj::MidiMessage > messages_
NrpnFilter nrpn_filter_
Constructor & Destructor Documentation
MidiProcessor() [1/3]
MidiProcessor::MidiProcessor () default
~MidiProcessor()
MidiProcessor::~MidiProcessor ()
References rsj::MidiMessage::MidiMessage().
 {
    for (const auto& dev : devices_) {
       dev->stop();
       rsj::Log("Stopped input device " + dev->getName());
    }
    if (const auto m = messages_.size_approx())
       rsj::Log(juce::String(m) + " left in queue in MidiProcessor destructor");
    moodycamel::ConsumerToken ctok(messages_);
    rsj::MidiMessage message_copy{};
    while (messages_.try_dequeue(ctok, message_copy)) {
       /* pump the queue empty */
    }
    messages_.enqueue(kTerminate);
 }
MidiProcessor() [2/3]
MidiProcessor::MidiProcessor (const MidiProcessor & other) delete
MidiProcessor() [3/3]
MidiProcessor::MidiProcessor (MidiProcessor && other) delete
Member Function Documentation
AddCallback()
template<class T > void MidiProcessor::AddCallback (T *const object, void(T::*)(rsj::MidiMessage) mf) inline
References devices_.
    {
       callbacks_.emplace_back(std::bind(mf, object, std::placeholders::_1));
    }
DispatchMessages()
void MidiProcessor::DispatchMessages () private
References rsj::ExceptionResponse(), and rsj::operator==().
 {
    try {
       static thread_local moodycamel::ConsumerToken ctok(messages_);
       do {
          rsj::MidiMessage message_copy;
          if (!messages_.try_dequeue(ctok, message_copy))
             messages_.wait_dequeue(message_copy);
          if (message_copy == kTerminate)
             return;
          for (const auto& cb : callbacks_)
             cb(message_copy);
       } while (true);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
handleIncomingMidiMessage()
void MidiProcessor::handleIncomingMidiMessage (juce::MidiInput * , const juce::MidiMessage & message) override private
References rsj::ExceptionResponse(), rsj::kCcFlag, and rsj::MidiMessage::message_type_byte.
 {
    try {
       // this procedure is in near-real-time, so must return quickly.
       // will place message in multithreaded queue and let separate process handle the messages
       static const thread_local moodycamel::ProducerToken ptok(messages_);
       const rsj::MidiMessage mess{message};
       switch (mess.message_type_byte) {
       case rsj::kCcFlag:
          if (nrpn_filter_.ProcessMidi(mess.channel, mess.number, mess.value)) { // true if nrpn
                                                                                 // piece
             const auto nrpn = nrpn_filter_.GetNrpnIfReady(mess.channel);
             if (nrpn.is_valid) { // send when finished
                const auto n_message{
                    rsj::MidiMessage{rsj::kCcFlag, mess.channel, nrpn.control, nrpn.value}};
                messages_.enqueue(ptok, n_message);
             }
             break; // finished with nrpn piece
          }
          [[fallthrough]]; // if not nrpn, handle like other messages
       case rsj::kNoteOnFlag:
       case rsj::kPwFlag:
          messages_.enqueue(ptok, mess);
          break;
       default:; // no action if other type of MIDI message
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
Init()
void MidiProcessor::Init ()
References rsj::ExceptionResponse(), and InitDevices().
 {
    try {
       InitDevices();
       dispatch_messages_future_ =
           std::async(std::launch::async, &MidiProcessor::DispatchMessages, this);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
InitDevices()
void MidiProcessor::InitDevices () private
References rsj::ExceptionResponse().
Referenced by Init(), and RescanDevices().
 {
    try {
       for (auto idx = 0; idx < juce::MidiInput::getDevices().size(); ++idx) {
          const auto dev = juce::MidiInput::openDevice(idx, this);
          if (dev) {
             devices_.emplace_back(dev);
             dev->start();
             rsj::Log("Opened input device " + dev->getName());
          }
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
operator=() [1/2]
MidiProcessor& MidiProcessor::operator= (const MidiProcessor & other) delete
operator=() [2/2]
MidiProcessor& MidiProcessor::operator= (MidiProcessor && other) delete
RescanDevices()
void MidiProcessor::RescanDevices ()
References rsj::ExceptionResponse(), and InitDevices().
 {
    try {
       for (const auto& dev : devices_) {
          dev->stop();
          rsj::Log("Stopped input device " + dev->getName());
       }
       devices_.clear();
       rsj::Log("Cleared input devices");
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
    InitDevices(); // initdevices has own try catch block
 }
Member Data Documentation
callbacks_
std::vector<std::function<void(rsj::MidiMessage)> > MidiProcessor::callbacks_ private
devices_
std::vector<std::unique_ptr<juce::MidiInput> > MidiProcessor::devices_ private
Referenced by AddCallback().
dispatch_messages_future_
std::future<void> MidiProcessor::dispatch_messages_future_ private
messages_
moodycamel::BlockingConcurrentQueue<rsj::MidiMessage> MidiProcessor::messages_ private
nrpn_filter_
NrpnFilter MidiProcessor::nrpn_filter_ private
The documentation for this class was generated from the following files:
Q:/Documents/GitHub/MIDI2LR/Source/MIDIProcessor.h
Q:/Documents/GitHub/MIDI2LR/Source/MIDIProcessor.cpp