MIDI2LR: CommandMenu Class Reference
CommandMenu Class Reference final
#include <CommandMenu.h>
Public Member Functions
CommandMenu (const rsj::MidiMessageId &message)
void Init (CommandMap *map_command) noexcept
void SetMsg (const rsj::MidiMessageId &message) noexcept
void SetSelectedItem (size_t index)
Private Member Functions
void clicked (const juce::ModifierKeys &modifiers) override
Private Attributes
CommandMap * command_map_ {nullptr}
const std::vector< std::vector< std::string > > menu_entries_
const std::vector< juce::String > menus_
rsj::MidiMessageId message_
size_t selected_item_ {std::numeric_limits<size_t>::max()}
Constructor & Destructor Documentation
CommandMenu()
CommandMenu::CommandMenu (const rsj::MidiMessageId & message) explicit
References CommandMenu().
Referenced by CommandMenu().
                                                             : juce
    ::TextButton{"Unmapped"},
        menus_({"Keyboard Shortcuts for User", "Library filter", "General", "Library", "Develop",
            "Basic", "Tone Curve", "HSL / Color / B&W", "Reset HSL / Color / B&W", "Split Toning",
            "Detail", "Lens Corrections", "Transform", "Effects", "Camera Calibration",
            "Develop Presets", "Keywords", "Local Adjustments", "Crop",
            "Go to Tool, Module, or Panel", "Secondary Display", "Profiles", "Next/Prev Profile"}),
        menu_entries_({LrCommandList::KeyShortcuts, LrCommandList::Filters, LrCommandList::General,
            LrCommandList::Library, LrCommandList::Develop, LrCommandList::BasicAdjustments,
            LrCommandList::ToneCurve, LrCommandList::Mixer, LrCommandList::ResetMixer,
            LrCommandList::SplitToning, LrCommandList::Detail, LrCommandList::LensCorrections,
            LrCommandList::Transform, LrCommandList::Effects, LrCommandList::Calibration,
            LrCommandList::DevelopPresets, LrCommandList::Keywords, LrCommandList::LocalAdjustments,
            LrCommandList::Crop, LrCommandList::ToolModulePanel, LrCommandList::SecondaryDisplay,
            LrCommandList::ProgramProfiles, LrCommandList::NextPrevProfile}),
        message_{message}
    {
    }
 catch (const std::exception& e) {
    rsj::ExceptionResponse(typeid(this).name(), __func__, e);
    throw;
 }
Member Function Documentation
clicked()
void CommandMenu::clicked (const juce::ModifierKeys & modifiers) override private
References command_map_, rsj::ExceptionResponse(), rsj::kCc, rsj::kPitchBend, message_, rsj::MidiMessageId::msg_id_type, CommandMap::RemoveMessage(), and selected_item_.
 {
    try {
       if (modifiers.isPopupMenu()) {
          switch (message_.msg_id_type) {
          case rsj::MsgIdEnum::kCc: {
             CCoptions ccopt;
             ccopt.BindToControl(
                 gsl::narrow_cast<short>(message_.channel - 1), // convert 1-based to 0-based
                 gsl::narrow_cast<short>(message_.controller));
             juce::DialogWindow::showModalDialog(
                 "Adjust CC dialog", &ccopt, nullptr, juce::Colour::fromRGB(0xFF, 0xFF, 0xFF), true);
             break;
          }
          case rsj::MsgIdEnum::kPitchBend: {
             PWoptions pwopt;
             pwopt.BindToControl(
                 gsl::narrow_cast<short>(message_.channel - 1)); // convert 1-based to 0 based
             juce::DialogWindow::showModalDialog(
                 "Adjust PW dialog", &pwopt, nullptr, juce::Colour::fromRGB(0xFF, 0xFF, 0xFF), true);
             break;
          }
          default:
              /* do nothing for other types of controllers */;
          }
       }
       else {
          size_t index = 1;
          auto submenu_tick_set = false;
          juce::PopupMenu main_menu;
          main_menu.addItem(gsl::narrow_cast<int>(index), "Unmapped", true,
              submenu_tick_set = index == selected_item_);
          index++;
          // add each submenu
          for (size_t menu_index = 0; menu_index < menus_.size(); ++menu_index) {
             juce::PopupMenu sub_menu;
             for (const auto& command : menu_entries_.at(menu_index)) {
                auto already_mapped = false;
                if (index - 1 < LrCommandList::LrStringList.size() && command_map_)
                   already_mapped = command_map_->CommandHasAssociatedMessage(
                       LrCommandList::LrStringList.at(index - 1));
                // add each submenu entry, ticking the previously selected entry and
                // disabling a previously mapped entry
                if (already_mapped)
                   sub_menu.addColouredItem(gsl::narrow_cast<int>(index), command,
                       juce::Colours::red, true, index == selected_item_);
                else
                   sub_menu.addItem(
                       gsl::narrow_cast<int>(index), command, true, index == selected_item_);
                index++;
             }
             // set whether or not the submenu is ticked (true if one of the submenu's
             // entries is selected)
             main_menu.addSubMenu(menus_.at(menu_index), sub_menu, true, nullptr,
                 selected_item_ < index && !submenu_tick_set);
             submenu_tick_set |= selected_item_ < index && !submenu_tick_set;
          }
          const auto result = gsl::narrow_cast<size_t>(main_menu.show());
          if (result && command_map_) {
             // user chose a different command, remove previous command mapping
             // associated to this menu
             if (selected_item_ < std::numeric_limits<size_t>::max())
                command_map_->RemoveMessage(message_);
             if (result - 1 < LrCommandList::LrStringList.size())
                setButtonText(LrCommandList::LrStringList.at(result - 1));
             else
                setButtonText(LrCommandList::NextPrevProfile.at(
                    result - 1 - LrCommandList::LrStringList.size()));
             selected_item_ = result;
             // Map the selected command to the CC
             command_map_->AddCommandforMessage(result - 1, message_);
          }
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
Init()
void CommandMenu::Init (CommandMap * map_command) noexcept
References command_map_.
 {
    command_map_ = map_command;
 }
SetMsg()
void CommandMenu::SetMsg (const rsj::MidiMessageId & message) noexcept
References message_.
 {
    message_ = message;
 }
SetSelectedItem()
void CommandMenu::SetSelectedItem (size_t index)
References rsj::ExceptionResponse(), and selected_item_.
 {
    try {
       selected_item_ = index;
       if (index - 1 < LrCommandList::LrStringList.size())
          setButtonText(LrCommandList::LrStringList.at(index - 1));
       else
          setButtonText(
              LrCommandList::NextPrevProfile.at(index - 1 - LrCommandList::LrStringList.size()));
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
Member Data Documentation
command_map_
CommandMap* CommandMenu::command_map_ {nullptr} private
Referenced by clicked(), and Init().
menu_entries_
const std::vector<std::vector<std::string> > CommandMenu::menu_entries_ private
menus_
const std::vector<juce::String> CommandMenu::menus_ private
message_
rsj::MidiMessageId CommandMenu::message_ private
Referenced by clicked(), and SetMsg().
selected_item_
size_t CommandMenu::selected_item_ {std::numeric_limits<size_t>::max()} private
Referenced by clicked(), and SetSelectedItem().
The documentation for this class was generated from the following files:
Q:/Documents/GitHub/MIDI2LR/Source/CommandMenu.h
Q:/Documents/GitHub/MIDI2LR/Source/CommandMenu.cpp