MIDI2LR: NrpnMessage Class Reference
NrpnMessage Class Reference
#include <NrpnMessage.h>
Public Member Functions
NrpnMessage ()=default
~NrpnMessage ()=default
rsj::Nrpn GetNrpnIfReady () noexcept
bool IsInProcess () const noexcept
bool ProcessMidi (short control, short value) noexcept(kNdebug)
Private Member Functions
void Clear () noexcept
short GetControl () const noexcept
short GetValue () const noexcept
bool IsReady () const noexcept
void SetControlLsb (short val) noexcept(kNdebug)
void SetControlMsb (short val) noexcept(kNdebug)
void SetValueLsb (short val) noexcept(kNdebug)
void SetValueMsb (short val) noexcept(kNdebug)
Private Attributes
short control_lsb_ {0}
short control_msb_ {0}
rsj::RelaxTTasSpinLock data_guard_
std::queue< rsj::Nrpn > nrpn_queued_ {}
rsj::RelaxTTasSpinLock queue_guard_
unsigned char ready_ {0}
short value_lsb_ {0}
short value_msb_ {0}
Constructor & Destructor Documentation
NrpnMessage()
NrpnMessage::NrpnMessage () default
~NrpnMessage()
NrpnMessage::~NrpnMessage () default
Member Function Documentation
Clear()
void NrpnMessage::Clear () private noexcept
References control_lsb_, control_msb_, ready_, value_lsb_, and value_msb_.
Referenced by ProcessMidi().
 {
     ready_ = 0;
     control_msb_ = 0;
     control_lsb_ = 0;
     value_msb_ = 0;
     value_lsb_ = 0;
 }
GetControl()
short NrpnMessage::GetControl () const inline private noexcept
References control_lsb_, and control_msb_.
 {
     return (control_msb_ << 7) + control_lsb_;
 }
GetNrpnIfReady()
rsj::Nrpn NrpnMessage::GetNrpnIfReady () noexcept
References rsj::kInvalidNrpn, and queue_guard_.
 {
     std::lock_guard<decltype(queue_guard_)> lock(queue_guard_);
     if (!nrpn_queued_.empty()) {
         const auto retval{nrpn_queued_.front()};
         nrpn_queued_.pop();
         return retval;
     }
     return rsj::kInvalidNrpn;
 }
GetValue()
short NrpnMessage::GetValue () const inline private noexcept
References value_lsb_, and value_msb_.
 {
     return (value_msb_ << 7) + value_lsb_;
 }
IsInProcess()
bool NrpnMessage::IsInProcess () const inline noexcept
References data_guard_, and ready_.
 {
     std::lock_guard<decltype(data_guard_)> lock(data_guard_);
     return ready_ != 0;
 }
IsReady()
bool NrpnMessage::IsReady () const inline private noexcept
References ready_.
Referenced by ProcessMidi().
 {
     return ready_ == 0b1111;
 }
ProcessMidi()
bool NrpnMessage::ProcessMidi (short control, short value) noexcept
References Clear(), data_guard_, IsReady(), queue_guard_, ready_, SetControlLsb(), SetControlMsb(), SetValueLsb(), and SetValueMsb().
 {
     Expects(value <= 0x7Fu);
     Expects(control <= 0x7Fu);
     auto ret_val = true;
     switch (control) {
         case 6:
         {
             std::lock(data_guard_, queue_guard_);
             std::lock_guard<decltype(data_guard_)> dlock(data_guard_, std::adopt_lock);
             std::lock_guard<decltype(queue_guard_)> qlock(queue_guard_, std::adopt_lock);
             if (ready_ >= 0b11) {
                 SetValueMsb(value);
                 if (IsReady()) {
                     nrpn_queued_.emplace(true, GetControl(), GetValue());
                     Clear();
                 }
             }
             else
                 ret_val = false;
             break;
         }
         case 38u:
         {
             std::lock(data_guard_, queue_guard_);
             std::lock_guard<decltype(data_guard_)> dlock(data_guard_, std::adopt_lock);
             std::lock_guard<decltype(queue_guard_)> qlock(queue_guard_, std::adopt_lock);
             if (ready_ >= 0b11) {
                 SetValueLsb(value);
                 if (IsReady()) {
                     nrpn_queued_.emplace(true, GetControl(), GetValue());
                     Clear();
                 }
             }
             else
                 ret_val = false;
             break;
         }
         case 98u:
         {
             std::lock_guard<decltype(data_guard_)> lock(data_guard_);
             SetControlLsb(value);
         }
         break;
         case 99u:
         {
             std::lock_guard<decltype(data_guard_)> lock(data_guard_);
             SetControlMsb(value);
         }
         break;
         default: //not an expected nrpn control #, handle as typical midi message
             ret_val = false;
     }
     return ret_val;
 }
SetControlLsb()
void NrpnMessage::SetControlLsb (short val) inline private noexcept
References control_lsb_, and ready_.
Referenced by ProcessMidi().
 {
     Expects(val <= 0x7Fu);
     control_lsb_ = val & 0x7Fu;
     ready_ |= 0b10;
 }
SetControlMsb()
void NrpnMessage::SetControlMsb (short val) inline private noexcept
References control_msb_, and ready_.
Referenced by ProcessMidi().
 {
     Expects(val <= 0x7Fu);
     control_msb_ = val & 0x7Fu;
     ready_ |= 0b1;
 }
SetValueLsb()
void NrpnMessage::SetValueLsb (short val) inline private noexcept
References ready_, and value_lsb_.
Referenced by ProcessMidi().
 {
     Expects(val <= 0x7Fu);
     value_lsb_ = val & 0x7Fu;
     ready_ |= 0b1000;
 }
SetValueMsb()
void NrpnMessage::SetValueMsb (short val) inline private noexcept
References ready_, and value_msb_.
Referenced by ProcessMidi().
 {
     Expects(val <= 0x7Fu);
     value_msb_ = val & 0x7Fu;
     ready_ |= 0b100;  //"Magic number" false alarm //-V112
 }
Member Data Documentation
control_lsb_
short NrpnMessage::control_lsb_ {0} private
Referenced by Clear(), GetControl(), and SetControlLsb().
control_msb_
short NrpnMessage::control_msb_ {0} private
Referenced by Clear(), GetControl(), and SetControlMsb().
data_guard_
rsj::RelaxTTasSpinLock NrpnMessage::data_guard_ mutable private
Referenced by IsInProcess(), and ProcessMidi().
nrpn_queued_
std::queue<rsj::Nrpn> NrpnMessage::nrpn_queued_ {} private
queue_guard_
rsj::RelaxTTasSpinLock NrpnMessage::queue_guard_ mutable private
Referenced by GetNrpnIfReady(), and ProcessMidi().
ready_
unsigned char NrpnMessage::ready_ {0} private
Referenced by Clear(), IsInProcess(), IsReady(), ProcessMidi(), SetControlLsb(), SetControlMsb(), SetValueLsb(), and SetValueMsb().
value_lsb_
short NrpnMessage::value_lsb_ {0} private
Referenced by Clear(), GetValue(), and SetValueLsb().
value_msb_
short NrpnMessage::value_msb_ {0} private
Referenced by Clear(), GetValue(), and SetValueMsb().
The documentation for this class was generated from the following files:
Q:/Documents/GitHub/MIDI2LR/Source/NrpnMessage.h
Q:/Documents/GitHub/MIDI2LR/Source/NrpnMessage.cpp