MIDI2LR: SettingsManager Class Reference
SettingsManager Class Reference final
#include <SettingsManager.h>
Public Member Functions
SettingsManager (ProfileManager &profile_manager, std::weak_ptr< LrIpcOut > &&lr_ipc_out)
SettingsManager (const SettingsManager &other)=delete
SettingsManager (SettingsManager &&other)=delete
~SettingsManager ()=default
int GetAutoHideTime () const noexcept
int GetLastVersionFound () const noexcept
bool GetPickupEnabled () const noexcept
juce::String GetProfileDirectory () const noexcept
SettingsManager & operator= (const SettingsManager &other)=delete
SettingsManager & operator= (SettingsManager &&other)=delete
void SetAutoHideTime (int new_time)
void SetLastVersionFound (int version_number)
void SetPickupEnabled (bool enabled)
void SetProfileDirectory (const juce::String &profile_directory)
Private Member Functions
void ConnectionCallback (bool, bool)
Private Attributes
std::weak_ptr< LrIpcOut > lr_ipc_out_
ProfileManager & profile_manager_
std::unique_ptr< juce::PropertiesFile > properties_file_
Constructor & Destructor Documentation
SettingsManager() [1/3]
SettingsManager::SettingsManager (ProfileManager & profile_manager, std::weak_ptr< LrIpcOut > && lr_ipc_out)
     : profile_manager_{profile_manager}, lr_ipc_out_{std::move(lr_ipc_out)}
 {
    try {
       juce::PropertiesFile::Options file_options;
       file_options.applicationName = "MIDI2LR";
       file_options.commonToAllUsers = false;
       file_options.filenameSuffix = "xml";
       file_options.osxLibrarySubFolder = "Application Support/MIDI2LR";
       file_options.storageFormat = juce::PropertiesFile::storeAsXML;
       properties_file_ = std::make_unique<juce::PropertiesFile>(file_options);
       if (const auto ptr = lr_ipc_out_.lock())
          // add ourselves as a listener to LR_IPC_OUT so that we can send plugin
          // settings on connection
          ptr->AddCallback(this, &SettingsManager::ConnectionCallback);
       // set the profile directory
       profile_manager_.SetProfileDirectory(GetProfileDirectory());
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References profile_manager_.
~SettingsManager()
SettingsManager::~SettingsManager () default
SettingsManager() [2/3]
SettingsManager::SettingsManager (const SettingsManager & other) delete
SettingsManager() [3/3]
SettingsManager::SettingsManager (SettingsManager && other) delete
Member Function Documentation
ConnectionCallback()
void SettingsManager::ConnectionCallback (bool connected, bool blocked) private
 {
    try {
       if (connected && !blocked)
          if (const auto ptr = lr_ipc_out_.lock()) {
             DebugInfo db{GetProfileDirectory()};
             ptr->SendCommand("Pickup "s + (GetPickupEnabled() ? '1' : '0') + '\n');
             rsj::Log(GetPickupEnabled() ? "Pickup is enabled" : "Pickup is disabled");
             // rest of info about app is logged by DebugInfo
             ptr->SendCommand("AppInfoClear 1\n"s);
             for (const auto& info : db.GetInfo()) {
                ptr->SendCommand("AppInfo "s + info + '\n');
             }
             ptr->SendCommand("AppInfoDone 1\n"s);
          }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
GetAutoHideTime()
int SettingsManager::GetAutoHideTime () const noexcept
 {
    return properties_file_->getIntValue(kAutoHideSection, 0);
 }
GetLastVersionFound()
int SettingsManager::GetLastVersionFound () const noexcept
 {
    return properties_file_->getIntValue("LastVersionFound", 0);
 }
Referenced by VersionChecker::run().
GetPickupEnabled()
bool SettingsManager::GetPickupEnabled () const noexcept
 {
    return properties_file_->getBoolValue("pickup_enabled", true);
 }
GetProfileDirectory()
juce::String SettingsManager::GetProfileDirectory () const noexcept
 {
    return properties_file_->getValue("profile_directory");
 }
operator=() [1/2]
SettingsManager& SettingsManager::operator= (const SettingsManager & other) delete
operator=() [2/2]
SettingsManager& SettingsManager::operator= (SettingsManager && other) delete
SetAutoHideTime()
void SettingsManager::SetAutoHideTime (int new_time)
 {
    try {
       properties_file_->setValue(kAutoHideSection, new_time);
       properties_file_->saveIfNeeded();
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
SetLastVersionFound()
void SettingsManager::SetLastVersionFound (int version_number)
 {
    try {
       properties_file_->setValue("LastVersionFound", version_number);
       if (!properties_file_->saveIfNeeded())
          rsj::Log("SettingsManager::SetLastVersionFound saveIfNeeded failed. Directory "
                   + GetProfileDirectory());
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Referenced by VersionChecker::run().
SetPickupEnabled()
void SettingsManager::SetPickupEnabled (bool enabled)
 {
    try {
       properties_file_->setValue("pickup_enabled", enabled);
       properties_file_->saveIfNeeded();
       if (const auto ptr = lr_ipc_out_.lock())
          ptr->SendCommand("Pickup "s + (enabled ? '1' : '0') + '\n');
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
SetProfileDirectory()
void SettingsManager::SetProfileDirectory (const juce::String & profile_directory)
 {
    try {
       properties_file_->setValue("profile_directory", profile_directory);
       if (!properties_file_->saveIfNeeded())
          rsj::Log("SettingsManager::SetProfileDirectory saveIfNeeded failed. Directory "
                   + profile_directory);
       profile_manager_.SetProfileDirectory(profile_directory);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Member Data Documentation
lr_ipc_out_
std::weak_ptr<LrIpcOut> SettingsManager::lr_ipc_out_ private
profile_manager_
ProfileManager& SettingsManager::profile_manager_ private
Referenced by SettingsManager().
properties_file_
std::unique_ptr<juce::PropertiesFile> SettingsManager::properties_file_ private
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/SettingsManager.h
D:/Users/Rory/source/repos/MIDI2LR/Source/SettingsManager.cpp