MIDI2LR: TopLevelResizableLayout Class Reference
TopLevelResizableLayout Class Reference
#include <ResizableLayout.h>
Classes
class Constrainer
Public Member Functions
TopLevelResizableLayout (juce::Component *owner)
void setAsConstrainerFor (juce::ResizableWindow *window)
Public Member Functions inherited from ResizableLayout
ResizableLayout (juce::Component *owner)
~ResizableLayout ()
void activateLayout (bool isActive=true) noexcept
void addToLayout (juce::Component *component, const juce::Point< int > &topLeft, const juce::Point< int > &bottomRight=juce::Point< int >{-1, -1}, Style style=styleStretch)
void recalculateLayout () const
void removeFromLayout (juce::Component *component) noexcept
void updateLayoutFor (juce::Component *component) noexcept
Public Member Functions inherited from ResizableChild
ResizableChild () noexcept
virtual ~ResizableChild ()=default
int getMaximumHeight () const noexcept
int getMaximumWidth () const noexcept
int getMinimumHeight () const noexcept
int getMinimumWidth () const noexcept
void setMaximumHeight (int maximumHeight) noexcept
void setMaximumSize (int maximumWidth, int maximumHeight) noexcept
void setMaximumWidth (int maximumWidth) noexcept
void setMinimumHeight (int minimumHeight) noexcept
void setMinimumSize (int minimumWidth, int minimumHeight) noexcept
void setMinimumWidth (int minimumWidth) noexcept
void setSizeLimits (int minimumWidth, int minimumHeight, int maximumWidth, int maximumHeight) noexcept
Private Attributes
Constrainer m_constrainer
Additional Inherited Members
Public Types inherited from ResizableLayout
enum { anchorUnit = 100 }
enum Style { styleStretch, styleFixedAspect }
Static Public Member Functions inherited from ResizableLayout
static juce::Rectangle< int > calcBoundsOfChildren (juce::Component *parent) noexcept
Constructor & Destructor Documentation
TopLevelResizableLayout()
TopLevelResizableLayout::TopLevelResizableLayout (juce::Component * owner)
     : ResizableLayout(owner), m_constrainer(this)
 {
 }
References TopLevelResizableLayout::Constrainer::Constrainer(), m_constrainer, and TopLevelResizableLayout().
Referenced by TopLevelResizableLayout().
Member Function Documentation
setAsConstrainerFor()
void TopLevelResizableLayout::setAsConstrainerFor (juce::ResizableWindow * window)
 {
    window->setConstrainer(&m_constrainer);
 }
Member Data Documentation
m_constrainer
Constrainer TopLevelResizableLayout::m_constrainer private
Referenced by TopLevelResizableLayout().
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/ResizableLayout.h
D:/Users/Rory/source/repos/MIDI2LR/Source/ResizableLayout.cpp