MIDI2LR: ProfileManager Class Reference
ProfileManager Class Reference final
#include <ProfileManager.h>
Public Member Functions
ProfileManager (ControlsModel &c_model, Profile &profile, std::weak_ptr< LrIpcOut > &&out, MidiReceiver &midi_receiver) noexcept
ProfileManager (const ProfileManager &other)=delete
ProfileManager (ProfileManager &&other)=delete
~ProfileManager ()=default
template<class T >
void AddCallback (T *const object, void(T::*const mf)(juce::XmlElement *, const juce::String &))
const juce::String & GetProfileDirectory () const noexcept
ProfileManager & operator= (const ProfileManager &other)=delete
ProfileManager & operator= (ProfileManager &&other)=delete
void SetProfileDirectory (const juce::File &directory)
void SwitchToProfile (int profile_index)
void SwitchToProfile (const juce::String &profile)
Private Types
enum SwitchState { SwitchState::kNone, SwitchState::kPrev, SwitchState::kNext }
Private Member Functions
void ConnectionCallback (bool, bool)
const std::vector< juce::String > & GetMenuItems () const noexcept
void handleAsyncUpdate () override
void MapCommand (const rsj::MidiMessageId &msg)
void MidiCmdCallback (rsj::MidiMessage)
void SwitchToNextProfile ()
void SwitchToPreviousProfile ()
Private Attributes
std::vector< std::function< void(juce::XmlElement *, const juce::String &)> > callbacks_
ControlsModel & controls_model_
Profile & current_profile_
int current_profile_index_ {0}
std::weak_ptr< LrIpcOut > lr_ipc_out_
juce::File profile_location_
std::vector< juce::String > profiles_
SwitchState switch_state_ {SwitchState::kNone}
Member Enumeration Documentation
SwitchState
enum ProfileManager::SwitchState strong private
Enumerator
kNone
kPrev
kNext
{
       kNone,
       kPrev,
       kNext,
    };
Constructor & Destructor Documentation
ProfileManager() [1/3]
ProfileManager::ProfileManager (ControlsModel & c_model, Profile & profile, std::weak_ptr< LrIpcOut > && out, MidiReceiver & midi_receiver) noexcept
     : current_profile_{profile}, controls_model_{c_model}, lr_ipc_out_{std::move(out)}
 {
    midi_receiver.AddCallback(this, &ProfileManager::MidiCmdCallback);
    if (const auto ptr = lr_ipc_out_.lock())
       // add ourselves as a listener to LR_IPC_OUT so that we can send plugin
       // settings on connection
       ptr->AddCallback(this, &ProfileManager::ConnectionCallback);
 }
References current_profile_.
~ProfileManager()
ProfileManager::~ProfileManager () default
ProfileManager() [2/3]
ProfileManager::ProfileManager (const ProfileManager & other) delete
ProfileManager() [3/3]
ProfileManager::ProfileManager (ProfileManager && other) delete
Member Function Documentation
AddCallback()
template<class T > void ProfileManager::AddCallback (T *const object, void(T::*)(juce::XmlElement *, const juce::String &) mf) inline
    {
       try {
          using namespace std::placeholders;
          if (object && mf) // only store non-empty functions
             callbacks_.emplace_back(std::bind(mf, object, _1, _2));
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References callbacks_.
ConnectionCallback()
void ProfileManager::ConnectionCallback (bool connected, bool blocked) private
 {
    try {
       if (connected && !blocked) {
          if (const auto ptr = lr_ipc_out_.lock()) {
             ptr->SendCommand("ChangedToDirectory "s
                              + juce::File::addTrailingSeparator(profile_location_.getFullPathName())
                                    .toStdString()
                              + '\n');
          }
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
GetMenuItems()
const std::vector< juce::String > & ProfileManager::GetMenuItems () const private noexcept
 {
    return profiles_;
 }
GetProfileDirectory()
const juce::String& ProfileManager::GetProfileDirectory () const inline noexcept
    {
       return profile_location_.getFullPathName();
    }
handleAsyncUpdate()
void ProfileManager::handleAsyncUpdate () override private
 {
    try {
       switch (switch_state_) {
       case SwitchState::kPrev:
          SwitchToPreviousProfile();
          switch_state_ = SwitchState::kNone;
          break;
       case SwitchState::kNext:
          SwitchToNextProfile();
          switch_state_ = SwitchState::kNone;
          break;
       default:
          break;
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), rsj::ExceptionResponse(), kNext, kNone, kPrev, switch_state_, SwitchToNextProfile(), and SwitchToPreviousProfile().
MapCommand()
void ProfileManager::MapCommand (const rsj::MidiMessageId & msg) private
 {
    try {
       const auto cmd = current_profile_.GetCommandForMessage(msg);
       if (cmd == "PrevPro"s) {
          switch_state_ = SwitchState::kPrev;
          triggerAsyncUpdate();
       }
       else if (cmd == "NextPro"s) {
          switch_state_ = SwitchState::kNext;
          triggerAsyncUpdate();
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), rsj::ExceptionResponse(), kNext, kPrev, and switch_state_.
Referenced by MidiCmdCallback().
MidiCmdCallback()
void ProfileManager::MidiCmdCallback (rsj::MidiMessage mm) private
 {
    try {
       const rsj::MidiMessageId cc = mm;
       // return if the value isn't high enough (notes may be < 1), or the command isn't a valid
       // profile-related command
       if (controls_model_.ControllerToPlugin(mm) < 0.4 || !current_profile_.MessageExistsInMap(cc))
          return;
       MapCommand(cc);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), ControlsModel::ControllerToPlugin(), controls_model_, current_profile_, rsj::ExceptionResponse(), and MapCommand().
operator=() [1/2]
ProfileManager& ProfileManager::operator= (const ProfileManager & other) delete
operator=() [2/2]
ProfileManager& ProfileManager::operator= (ProfileManager && other) delete
SetProfileDirectory()
void ProfileManager::SetProfileDirectory (const juce::File & directory)
 {
    try {
       profile_location_ = directory;
       juce::Array<juce::File> file_array;
       directory.findChildFiles(file_array, juce::File::findFiles, false, "*.xml");
       file_array.sort();
       profiles_.clear();
       for (const auto& file : file_array)
          profiles_.emplace_back(file.getFileName());
       if (!profiles_.empty())
          SwitchToProfile(profiles_.at(0));
       current_profile_index_ = 0;
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), current_profile_index_, and rsj::ExceptionResponse().
SwitchToNextProfile()
void ProfileManager::SwitchToNextProfile () private
 {
    try {
       if (++current_profile_index_ == gsl::narrow_cast<int>(profiles_.size()))
          current_profile_index_ = 0;
       SwitchToProfile(current_profile_index_);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), current_profile_index_, rsj::ExceptionResponse(), and SwitchToProfile().
Referenced by handleAsyncUpdate().
SwitchToPreviousProfile()
void ProfileManager::SwitchToPreviousProfile () private
 {
    try {
       if (--current_profile_index_ < 0)
          current_profile_index_ = gsl::narrow_cast<int>(profiles_.size()) - 1;
       SwitchToProfile(current_profile_index_);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), current_profile_index_, rsj::ExceptionResponse(), and SwitchToProfile().
Referenced by handleAsyncUpdate().
SwitchToProfile() [1/2]
void ProfileManager::SwitchToProfile (int profile_index)
 {
    try {
       if (profile_index >= 0 && profile_index < gsl::narrow_cast<int>(profiles_.size())) {
          SwitchToProfile(profiles_.at(gsl::narrow_cast<size_t>(profile_index)));
          current_profile_index_ = profile_index;
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), current_profile_index_, and rsj::ExceptionResponse().
Referenced by MainContentComponent::Init(), SwitchToNextProfile(), and SwitchToPreviousProfile().
SwitchToProfile() [2/2]
void ProfileManager::SwitchToProfile (const juce::String & profile)
 {
    try {
       const auto profile_file = profile_location_.getChildFile(profile);
       if (profile_file.exists()) {
          if (const auto parsed{juce::XmlDocument::parse(profile_file)}) {
             const std::unique_ptr<juce::XmlElement> xml_element{parsed};
             for (const auto& cb : callbacks_)
                cb(xml_element.get(), profile);
             if (const auto ptr = lr_ipc_out_.lock()) {
                auto command =
                    "ChangedToDirectory "s
                    + juce::File::addTrailingSeparator(profile_location_.getFullPathName())
                          .toStdString()
                    + '\n';
                ptr->SendCommand(std::move(command));
                command = "ChangedToFile "s + profile.toStdString() + '\n';
                ptr->SendCommand(std::move(command));
             }
          }
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
Member Data Documentation
callbacks_
std::vector<std::function<void(juce::XmlElement*, const juce::String&)> > ProfileManager::callbacks_ private
Referenced by AddCallback().
controls_model_
ControlsModel& ProfileManager::controls_model_ private
Referenced by MidiCmdCallback().
current_profile_
Profile& ProfileManager::current_profile_ private
Referenced by MidiCmdCallback(), and ProfileManager().
current_profile_index_
int ProfileManager::current_profile_index_ {0} private
Referenced by SetProfileDirectory(), SwitchToNextProfile(), SwitchToPreviousProfile(), and SwitchToProfile().
lr_ipc_out_
std::weak_ptr<LrIpcOut> ProfileManager::lr_ipc_out_ private
profile_location_
juce::File ProfileManager::profile_location_ private
profiles_
std::vector<juce::String> ProfileManager::profiles_ private
switch_state_
SwitchState ProfileManager::switch_state_ {SwitchState::kNone} private
Referenced by handleAsyncUpdate(), and MapCommand().
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/ProfileManager.h
D:/Users/Rory/source/repos/MIDI2LR/Source/ProfileManager.cpp