MIDI2LR: MidiSender Class Reference
MidiSender Class Reference
#include <MIDISender.h>
Public Member Functions
MidiSender (Devices &devices) noexcept
void RescanDevices ()
void Send (rsj::MidiMessageId id, int value) const
void Start ()
Private Member Functions
void InitDevices ()
Private Attributes
Devices & devices_
std::vector< std::unique_ptr< juce::MidiOutput > > output_devices_
Constructor & Destructor Documentation
MidiSender()
MidiSender::MidiSender (Devices & devices) inline explicit noexcept
 : devices_(devices) {}
References devices_.
Member Function Documentation
InitDevices()
void MidiSender::InitDevices () private
 {
    try {
       const auto available_devices {juce::MidiOutput::getAvailableDevices()};
       for (const auto& device : available_devices) {
          auto open_device {juce::MidiOutput::openDevice(device.identifier)};
          if (open_device) {
             const auto devname {open_device->getName().toStdString()};
             if constexpr (MSWindows) {
                if (devname != "Microsoft GS Wavetable Synth"
                    && devices_.EnabledOrNew(open_device->getDeviceInfo(), "output")) {
                   rsj::Log(fmt::format(FMT_STRING("Opened output device {}."), devname));
                   output_devices_.emplace_back(std::move(open_device));
                }
                else
                   rsj::Log(fmt::format(FMT_STRING("Ignored output device {}."), devname));
             }
             else {
                if (devices_.EnabledOrNew(open_device->getDeviceInfo(), "output")) {
                   rsj::Log(fmt::format(FMT_STRING("Opened output device {}."), devname));
                   output_devices_.emplace_back(std::move(open_device));
                }
                else
                   rsj::Log(fmt::format(FMT_STRING("Ignored output device {}."), devname));
             }
          }
       } /* devices that are skipped have their pointers deleted and are automatically closed*/
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
Referenced by RescanDevices(), and Start().
RescanDevices()
void MidiSender::RescanDevices ()
 {
    try {
       output_devices_.clear();
       rsj::Log("Cleared output devices.");
       InitDevices();
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References InitDevices().
Send()
void MidiSender::Send (rsj::MidiMessageId id, int value) const
 {
    try {
       if (id.msg_id_type == rsj::MessageType::Pw) {
          const auto msg {juce::MidiMessage::pitchWheel(id.channel, value)};
          for (const auto& dev : output_devices_)
             dev->sendMessageNow(msg);
       }
       else if (id.msg_id_type == rsj::MessageType::NoteOn) {
          const auto msg {juce::MidiMessage::noteOn(
              id.channel, id.control_number, gsl::narrow_cast<juce::uint8>(value))};
          for (const auto& dev : output_devices_)
             dev->sendMessageNow(msg);
       }
       else if (id.msg_id_type == rsj::MessageType::Cc) {
          if (id.control_number < 128) {
             /* regular message */
             const auto msg {
                 juce::MidiMessage::controllerEvent(id.channel, id.control_number, value)};
             for (const auto& dev : output_devices_)
                dev->sendMessageNow(msg);
          }
          else {
             /* NRPN */
             const auto msg_parm_msb {
                 juce::MidiMessage::controllerEvent(id.channel, 99, id.control_number >> 7 & 0x7F)};
             const auto msg_parm_lsb {
                 juce::MidiMessage::controllerEvent(id.channel, 98, id.control_number & 0x7f)};
             const auto msg_val_msb {
                 juce::MidiMessage::controllerEvent(id.channel, 6, value >> 7 & 0x7F)};
             const auto msg_val_lsb {
                 juce::MidiMessage::controllerEvent(id.channel, 38, value & 0x7f)};
             for (const auto& dev : output_devices_) {
                dev->sendMessageNow(msg_parm_msb);
                dev->sendMessageNow(msg_parm_lsb);
                dev->sendMessageNow(msg_val_msb);
                dev->sendMessageNow(msg_val_lsb);
             }
          }
       }
       else {
          constexpr auto msge {"MIDISender: Unexpected data type: {:n}."};
          const auto msgt {juce::translate(msge).toStdString()};
          rsj::LogAndAlertError(
              fmt::format(msgt, id.msg_id_type), fmt::format(msge, id.msg_id_type));
       }
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References rsj::AppLogFilePath(), rsj::Cc, rsj::MidiMessageId::control_number, rsj::MidiMessageId::msg_id_type, rsj::NoteOn, and rsj::Pw.
Start()
void MidiSender::Start ()
 {
    try {
       InitDevices();
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References InitDevices().
Member Data Documentation
devices_
Devices& MidiSender::devices_ private
Referenced by MidiSender().
output_devices_
std::vector<std::unique_ptr<juce::MidiOutput> > MidiSender::output_devices_ private
The documentation for this class was generated from the following files:
C:/Users/rsjaf/source/repos/MIDI2LR/src/application/MIDISender.h
C:/Users/rsjaf/source/repos/MIDI2LR/src/application/MIDISender.cpp