MIDI2LR: ChannelModel Class Reference
ChannelModel Class Reference
#include <ControlsModel.h>
Public Member Functions
ChannelModel ()
ChannelModel (const ChannelModel &)=delete
ChannelModel (ChannelModel &&)=delete
~ChannelModel ()=default
double ControllerToPlugin (short controltype, size_t controlnumber, short value)
short GetCcMax (size_t controlnumber) const
rsj::CCmethod GetCcMethod (size_t controlnumber) const
short GetCcMin (size_t controlnumber) const
short GetPwMax () const noexcept
short GetPwMin () const noexcept
short MeasureChange (short controltype, size_t controlnumber, short value)
ChannelModel & operator= (const ChannelModel &)=delete
ChannelModel & operator= (ChannelModel &&)=delete
short PluginToController (short controltype, size_t controlnumber, double value)
void SetCc (size_t controlnumber, short min, short max, rsj::CCmethod controltype)
void SetCcAll (size_t controlnumber, short min, short max, rsj::CCmethod controltype)
void SetCcMax (size_t controlnumber, short value)
void SetCcMethod (size_t controlnumber, rsj::CCmethod value)
void SetCcMin (size_t controlnumber, short value)
void SetPwMax (short value) noexcept
void SetPwMin (short value) noexcept
short SetToCenter (short controltype, size_t controlnumber)
Private Member Functions
void ActiveToSaved () const
void CcDefaults ()
short CenterCc (size_t controlnumber) const noexcept
short CenterPw () const noexcept
bool IsNRPN_ (size_t controlnumber) const noexcept(kNdebug)
template<class Archive >
void load (Archive &archive, uint32_t const version)
double OffsetResult (short diff, size_t controlnumber)
template<class Archive >
void save (Archive &archive, uint32_t const version) const
void SavedToActive ()
Private Attributes
std::array< short, kMaxControls > cc_high_ {}
std::array< short, kMaxControls > cc_low_ {}
std::array< rsj::CCmethod, kMaxControls > cc_method_ {}
std::array< short, kMaxControls > current_v_ {}
rsj::RelaxTTasSpinLock current_v_mtx_
std::atomic< short > pitch_wheel_current_ {0}
short pitch_wheel_max_ {kMaxNrpn}
short pitch_wheel_min_ {0}
std::vector< rsj::SettingsStruct > settings_to_save_ {}
Static Private Attributes
static constexpr short kBit14 = 0x2000
static constexpr short kBit7 = 0x40
static constexpr short kLow13Bits = 0x1FFF
static constexpr short kLow6Bits = 0x3F
static constexpr size_t kMaxControls = 0x4000
static constexpr short kMaxMidi = 0x7F
static constexpr short kMaxMidiHalf = kMaxMidi / 2
static constexpr short kMaxNrpn = 0x3FFF
static constexpr short kMaxNrpnHalf = kMaxNrpn / 2
static constexpr rsj::TimeType kUpdateDelay = 250
Friends
class cereal::access
Constructor & Destructor Documentation
ChannelModel() [1/3]
ChannelModel::ChannelModel ()
 {
    CcDefaults();
    // load settings
 }
~ChannelModel()
ChannelModel::~ChannelModel () default
ChannelModel() [2/3]
ChannelModel::ChannelModel (const ChannelModel &) delete
ChannelModel() [3/3]
ChannelModel::ChannelModel (ChannelModel &&) delete
Member Function Documentation
ActiveToSaved()
void ChannelModel::ActiveToSaved () const private
 {
    settings_to_save_.clear();
    for (short i = 0; i <= kMaxMidi; ++i)
       if (cc_method_.at(i) != rsj::CCmethod::kAbsolute || cc_high_.at(i) != kMaxMidi
           || cc_low_.at(i) != 0)
          settings_to_save_.emplace_back(i, cc_low_.at(i), cc_high_.at(i), cc_method_.at(i));
    for (short i = kMaxMidi + 1; i <= kMaxNrpn; ++i)
       if (cc_method_.at(i) != rsj::CCmethod::kAbsolute || cc_high_.at(i) != kMaxNrpn
           || cc_low_.at(i) != 0)
          settings_to_save_.emplace_back(i, cc_low_.at(i), cc_high_.at(i), cc_method_.at(i));
 }
CcDefaults()
void ChannelModel::CcDefaults () private
 {
    try {
       // program defaults
       cc_low_.fill(0);
       cc_high_.fill(0x3FFF); // XCode throws linker error when use ChannelModel::kMaxNRPN here
       cc_method_.fill(rsj::CCmethod::kAbsolute);
       // no lock as this function called in non-multithreaded manner
       current_v_.fill(short{8191});
       for (size_t a = 0; a <= kMaxMidi; ++a) {
          cc_high_.at(a) = kMaxMidi;
          current_v_.at(a) = kMaxMidiHalf;
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
CenterCc()
short ChannelModel::CenterCc (size_t controlnumber) const inline private noexcept
    {
       return (cc_high_.at(controlnumber) - cc_low_.at(controlnumber)) / 2
              + cc_low_.at(controlnumber)
              + (cc_high_.at(controlnumber) - cc_low_.at(controlnumber)) % 2;
    }
CenterPw()
short ChannelModel::CenterPw () const inline private noexcept
    {
       return (pitch_wheel_max_ - pitch_wheel_min_) / 2 + pitch_wheel_min_
              + (pitch_wheel_max_ - pitch_wheel_min_) % 2;
    }
References pitch_wheel_max_, and pitch_wheel_min_.
ControllerToPlugin()
double ChannelModel::ControllerToPlugin (short controltype, size_t controlnumber, short value)
 {
    try {
       Expects(
           (controltype == rsj::kCcFlag && cc_method_.at(controlnumber) == rsj::CCmethod::kAbsolute)
               ? (cc_low_.at(controlnumber) < cc_high_.at(controlnumber))
               : 1);
       Expects((controltype == rsj::kPwFlag) ? (pitch_wheel_max_ > pitch_wheel_min_) : 1);
       Expects((controltype == rsj::kPwFlag) ? value >= pitch_wheel_min_ && value <= pitch_wheel_max_
                                             : 1);
       // note that the value is not msb,lsb, but rather the calculated value. Since lsb is only 7
       // bits, high bits are shifted one right when placed into short.
       switch (controltype) {
       case rsj::kPwFlag:
          pitch_wheel_current_.store(value, std::memory_order_release);
          // TODO(C26451): short mixed with double: can it overflow?
          return static_cast<double>(value - pitch_wheel_min_)
                 / static_cast<double>(pitch_wheel_max_ - pitch_wheel_min_);
       case rsj::kCcFlag:
          switch (cc_method_.at(controlnumber)) {
          case rsj::CCmethod::kAbsolute: {
             auto lock = std::lock_guard(current_v_mtx_);
             current_v_.at(controlnumber) = value;
          }
             // TODO(C26451): short mixed with double: can it overflow?
             return static_cast<double>(value - cc_low_.at(controlnumber))
                    / static_cast<double>(cc_high_.at(controlnumber) - cc_low_.at(controlnumber));
          case rsj::CCmethod::kBinaryOffset:
             if (IsNRPN_(controlnumber))
                return OffsetResult(value - kBit14, controlnumber);
             return OffsetResult(value - kBit7, controlnumber);
          case rsj::CCmethod::kSignMagnitude:
             if (IsNRPN_(controlnumber))
                return OffsetResult(value & kBit14 ? -(value & kLow13Bits) : value, controlnumber);
             return OffsetResult(value & kBit7 ? -(value & kLow6Bits) : value, controlnumber);
          case rsj::CCmethod::
              kTwosComplement: // see
                               // https://en.wikipedia.org/wiki/Signed_number_representations#Two.27s_complement
             if (IsNRPN_(controlnumber)) // flip twos comp and subtract--independent of processor
                                         // architecture
                return OffsetResult(
                    value & kBit14 ? -((value ^ kMaxNrpn) + 1) : value, controlnumber);
             return OffsetResult(value & kBit7 ? -((value ^ kMaxMidi) + 1) : value, controlnumber);
          default:
             Ensures(!"Should be unreachable code in ControllerToPlugin--unknown CCmethod");
             return 0.0;
          }
       case rsj::kNoteOnFlag:
          return static_cast<double>(value)
                 / static_cast<double>((IsNRPN_(controlnumber) ? kMaxNrpn : kMaxMidi));
       case rsj::kNoteOffFlag:
          return 0.0;
       default:
          Ensures(!"Should be unreachable code in ControllerToPlugin--unknown control type");
          return 0.0;
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
GetCcMax()
short ChannelModel::GetCcMax (size_t controlnumber) const inline
    {
       try {
          return cc_high_.at(controlnumber);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
GetCcMethod()
rsj::CCmethod ChannelModel::GetCcMethod (size_t controlnumber) const inline
{
       try {
          return cc_method_.at(controlnumber);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }[[nodiscard]] short GetCcMax(size_t controlnumber) const
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
GetCcMin()
short ChannelModel::GetCcMin (size_t controlnumber) const inline
{
       try {
          return cc_low_.at(controlnumber);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }[[nodiscard]] short GetPwMax() const noexcept
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
GetPwMax()
short ChannelModel::GetPwMax () const inline noexcept
    {
       return pitch_wheel_max_;
    }
References pitch_wheel_max_.
GetPwMin()
short ChannelModel::GetPwMin () const inline noexcept
    {
       return pitch_wheel_min_;
    }
References pitch_wheel_min_.
IsNRPN_()
bool ChannelModel::IsNRPN_ (size_t controlnumber) const inline private noexcept
    {
       Expects(controlnumber <= kMaxNrpn);
       return controlnumber > kMaxMidi;
    }
References kMaxMidi.
load()
template<class Archive > void ChannelModel::load (Archive & archive, uint32_t const version) private
 {
    try {
       switch (version) {
       case 1:
          archive(cc_method_, cc_high_, cc_low_, pitch_wheel_max_, pitch_wheel_min_);
          break;
       case 2:
          archive(settings_to_save_);
          SavedToActive();
          break;
       case 3:
          archive(settings_to_save_, cereal::make_nvp("PWmax", pitch_wheel_max_),
              cereal::make_nvp("PWmin", pitch_wheel_min_));
          SavedToActive();
          break;
       default:
          rsj::LogAndAlertError("Archive version not acceptable");
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
MeasureChange()
short ChannelModel::MeasureChange (short controltype, size_t controlnumber, short value)
 {
    try {
       Expects(
           (controltype == rsj::kCcFlag && cc_method_.at(controlnumber) == rsj::CCmethod::kAbsolute)
               ? (cc_low_.at(controlnumber) < cc_high_.at(controlnumber))
               : 1);
       Expects((controltype == rsj::kPwFlag) ? (pitch_wheel_max_ > pitch_wheel_min_) : 1);
       Expects((controltype == rsj::kPwFlag) ? value >= pitch_wheel_min_ && value <= pitch_wheel_max_
                                             : 1);
       // note that the value is not msb,lsb, but rather the calculated value. Since lsb is only 7
       // bits, high bits are shifted one right when placed into short.
       switch (controltype) {
       case rsj::kPwFlag: {
          return value - pitch_wheel_current_.exchange(value);
       }
       case rsj::kCcFlag:
          switch (cc_method_.at(controlnumber)) {
          case rsj::CCmethod::kAbsolute: {
             auto lock = std::lock_guard(current_v_mtx_);
             const short diff = value - current_v_.at(controlnumber);
             current_v_.at(controlnumber) = value;
             return diff;
          }
          case rsj::CCmethod::kBinaryOffset:
             if (IsNRPN_(controlnumber))
                return value - kBit14;
             return value - kBit7;
          case rsj::CCmethod::kSignMagnitude:
             if (IsNRPN_(controlnumber))
                return value & kBit14 ? -(value & kLow13Bits) : value;
             return value & kBit7 ? -(value & kLow6Bits) : value;
          case rsj::CCmethod::
              kTwosComplement: // see
                               // https://en.wikipedia.org/wiki/Signed_number_representations#Two.27s_complement
             if (IsNRPN_(controlnumber)) // flip twos comp and subtract--independent of processor
                                         // architecture
                return value & kBit14 ? -((value ^ kMaxNrpn) + 1) : value;
             return value & kBit7 ? -((value ^ kMaxMidi) + 1) : value;
          default:
             Ensures(!"Should be unreachable code in ControllerToPlugin--unknown CCmethod");
             return short{0};
          }
       case rsj::kNoteOnFlag:
          return short{0};
       case rsj::kNoteOffFlag:
          return short{0};
       default:
          Ensures(!"Should be unreachable code in ControllerToPlugin--unknown control type");
          return short{0};
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
OffsetResult()
double ChannelModel::OffsetResult (short diff, size_t controlnumber) private
 {
    try {
       Expects(cc_high_.at(controlnumber) > 0); // CCLow will always be 0 for offset controls
       Expects(diff <= kMaxNrpn && diff >= -kMaxNrpn);
       Expects(controlnumber <= kMaxNrpn);
       auto lock = std::lock_guard(current_v_mtx_);
       current_v_.at(controlnumber) += diff;
       if (current_v_.at(controlnumber) < 0) { // fix currentV
          current_v_.at(controlnumber) = 0;
          return 0.0;
       }
       if (current_v_.at(controlnumber) > cc_high_.at(controlnumber)) { // fix currentV
          current_v_.at(controlnumber) = cc_high_.at(controlnumber);
          return 1.0;
       }
       return static_cast<double>(current_v_.at(controlnumber))
              / static_cast<double>(cc_high_.at(controlnumber));
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
operator=() [1/2]
ChannelModel& ChannelModel::operator= (const ChannelModel &) delete
operator=() [2/2]
ChannelModel& ChannelModel::operator= (ChannelModel &&) delete
PluginToController()
short ChannelModel::PluginToController (short controltype, size_t controlnumber, double value)
 {
    try {
       Expects(controlnumber <= kMaxNrpn);
       Expects(value >= 0.0 && value <= 1.0);
       switch (controltype) {
       case rsj::kPwFlag: {
          // TODO(C26451): short mixed with double: can it overflow?
          const short newv = std::clamp(
              gsl::narrow_cast<short>(juce::roundToInt(value * (pitch_wheel_max_ - pitch_wheel_min_))
                                      + pitch_wheel_min_),
              pitch_wheel_min_, pitch_wheel_max_);
          pitch_wheel_current_.store(newv, std::memory_order_release);
          return newv;
       }
       case rsj::kCcFlag: {
          // TODO(C26451): short mixed with double: can it overflow?
          const short newv = std::clamp(
              gsl::narrow_cast<short>(
                  juce::roundToInt(value * (cc_high_.at(controlnumber) - cc_low_.at(controlnumber)))
                  + cc_low_.at(controlnumber)),
              cc_low_.at(controlnumber), cc_high_.at(controlnumber));
          {
             auto lock = std::lock_guard(current_v_mtx_);
             current_v_.at(controlnumber) = newv;
          }
          return newv;
       }
       case rsj::kNoteOnFlag:
          return kMaxMidi;
       default:
          Ensures(!"Unexpected control type");
       }
       return 0;
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
save()
template<class Archive > void ChannelModel::save (Archive & archive, uint32_t const version) const private
 {
    try {
       switch (version) {
       case 1:
          archive(cc_method_, cc_high_, cc_low_, pitch_wheel_max_, pitch_wheel_min_);
          break;
       case 2:
          ActiveToSaved();
          archive(settings_to_save_);
          break;
       case 3:
          ActiveToSaved();
          archive(settings_to_save_, cereal::make_nvp("PWmax", pitch_wheel_max_),
              cereal::make_nvp("PWmin", pitch_wheel_min_));
          break;
       default:
          rsj::LogAndAlertError("Wrong archive version specified for save");
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
SavedToActive()
void ChannelModel::SavedToActive () private
 {
    CcDefaults();
    for (const auto& set : settings_to_save_)
       SetCc(set.number, set.low, set.high, set.method);
 }
SetCc()
void ChannelModel::SetCc (size_t controlnumber, short min, short max, rsj::CCmethod controltype)
 {
    SetCcMethod(controlnumber, controltype); // has to be set before others or ranges won't be
                                             // correct
    SetCcMin(controlnumber, min);
    SetCcMax(controlnumber, max);
 }
SetCcAll()
void ChannelModel::SetCcAll (size_t controlnumber, short min, short max, rsj::CCmethod controltype)
 {
    if (IsNRPN_(controlnumber))
       for (short a = kMaxMidi + 1; a <= kMaxNrpn; ++a)
          SetCc(a, min, max, controltype);
    else
       for (short a = 0; a <= kMaxMidi; ++a)
          SetCc(a, min, max, controltype);
 }
SetCcMax()
void ChannelModel::SetCcMax (size_t controlnumber, short value)
 {
    try {
       Expects(controlnumber <= kMaxNrpn);
       Expects(value <= kMaxNrpn);
       Expects(value >= 0);
       if (cc_method_.at(controlnumber) != rsj::CCmethod::kAbsolute)
          cc_high_.at(controlnumber) = value < 0 ? 1000 : value;
       else {
          const auto max = IsNRPN_(controlnumber) ? kMaxNrpn : kMaxMidi;
          cc_high_.at(controlnumber) =
              value <= cc_low_.at(controlnumber) || value > max ? max : value;
       }
       // no lock as this function called in non-multithreaded manner
       current_v_.at(controlnumber) = CenterCc(controlnumber);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
SetCcMethod()
void ChannelModel::SetCcMethod (size_t controlnumber, rsj::CCmethod value) inline
    {
       try {
          cc_method_.at(controlnumber) = value;
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
SetCcMin()
void ChannelModel::SetCcMin (size_t controlnumber, short value)
 {
    try {
       Expects(controlnumber <= kMaxNrpn);
       if (cc_method_.at(controlnumber) != rsj::CCmethod::kAbsolute)
          cc_low_.at(controlnumber) = 0;
       else
          cc_low_.at(controlnumber) = value < 0 || value >= cc_high_.at(controlnumber) ? 0 : value;
       // no lock as this function called in non-multithreaded manner
       current_v_.at(controlnumber) = CenterCc(controlnumber);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
SetPwMax()
void ChannelModel::SetPwMax (short value) noexcept
 {
    pitch_wheel_max_ = (value > kMaxNrpn || value <= pitch_wheel_min_) ? kMaxNrpn : value;
    pitch_wheel_current_.store(CenterPw(), std::memory_order_relaxed);
 }
SetPwMin()
void ChannelModel::SetPwMin (short value) noexcept
 {
    pitch_wheel_min_ = (value < 0 || value >= pitch_wheel_max_) ? 0 : value;
    pitch_wheel_current_.store(CenterPw(), std::memory_order_relaxed);
 }
SetToCenter()
short ChannelModel::SetToCenter (short controltype, size_t controlnumber)
 {
    try {
       short retval{0};
       switch (controltype) {
       case rsj::kPwFlag:
          retval = CenterPw();
          pitch_wheel_current_.store(retval, std::memory_order_release);
          break;
       case rsj::kCcFlag:
          if (cc_method_.at(controlnumber) == rsj::CCmethod::kAbsolute) {
             auto lock = std::lock_guard(current_v_mtx_);
             retval = CenterCc(controlnumber);
             current_v_.at(controlnumber) = retval;
          }
          break;
       default:
           /* */;
       }
       return retval;
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
cc_high_
std::array<short, kMaxControls> ChannelModel::cc_high_ {} private
cc_low_
std::array<short, kMaxControls> ChannelModel::cc_low_ {} private
cc_method_
std::array<rsj::CCmethod, kMaxControls> ChannelModel::cc_method_ {} private
current_v_
std::array<short, kMaxControls> ChannelModel::current_v_ {} private
current_v_mtx_
rsj::RelaxTTasSpinLock ChannelModel::current_v_mtx_ mutable private
kBit14
constexpr short ChannelModel::kBit14 = 0x2000 static private
kBit7
constexpr short ChannelModel::kBit7 = 0x40 static private
kLow13Bits
constexpr short ChannelModel::kLow13Bits = 0x1FFF static private
kLow6Bits
constexpr short ChannelModel::kLow6Bits = 0x3F static private
kMaxControls
constexpr size_t ChannelModel::kMaxControls = 0x4000 static private
kMaxMidi
constexpr short ChannelModel::kMaxMidi = 0x7F static private
Referenced by IsNRPN_().
kMaxMidiHalf
constexpr short ChannelModel::kMaxMidiHalf = kMaxMidi / 2 static private
kMaxNrpn
constexpr short ChannelModel::kMaxNrpn = 0x3FFF static private
kMaxNrpnHalf
constexpr short ChannelModel::kMaxNrpnHalf = kMaxNrpn / 2 static private
kUpdateDelay
constexpr rsj::TimeType ChannelModel::kUpdateDelay = 250 static private
pitch_wheel_current_
std::atomic<short> ChannelModel::pitch_wheel_current_ {0} private
pitch_wheel_max_
short ChannelModel::pitch_wheel_max_ {kMaxNrpn} private
Referenced by CenterPw(), and GetPwMax().
pitch_wheel_min_
short ChannelModel::pitch_wheel_min_ {0} private
Referenced by CenterPw(), and GetPwMin().
settings_to_save_
std::vector<rsj::SettingsStruct> ChannelModel::settings_to_save_ {} mutable private
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/ControlsModel.h
D:/Users/Rory/source/repos/MIDI2LR/Source/ControlsModel.cpp