MIDI2LR: SendKeys Class Reference
SendKeys Class Reference
A send keys.
Public Member Functions
SendKeys () noexcept
~SendKeys ()
void SendKeyDownUp (const std::string &key, bool Alt, bool Control, bool Shift) const
Sends a key down up.
Detailed Description
A send keys.
Constructor & Destructor Documentation
SendKeys::SendKeys () noexcept
SendKeys::~SendKeys ()
References SendKeyDownUp().
Member Function Documentation
void SendKeys::SendKeyDownUp (const std::string & key, bool Alt, bool Control, bool Shift) const
Sends a key down up.
Parameters
key The key.
Alt true to alternate.
Control true to control.
Shift true to shift.
Referenced by LR_IPC_IN::run(), and ~SendKeys().
The documentation for this class was generated from the following files:
Q:/Documents/GitHub/MIDI2LR/Source/SendKeys.h
Q:/Documents/GitHub/MIDI2LR/Source/SendKeys.cpp