MIDI2LR: LrIpcOut::Recenter Class Reference
LrIpcOut::Recenter Class Reference final
Public Member Functions
Recenter (LrIpcOut &owner) noexcept
void SetMidiMessage (rsj::MidiMessage mm)
Private Member Functions
void timerCallback () override
Private Attributes
rsj::MidiMessage mm_ {}
rsj::RelaxTTasSpinLock mtx_
LrIpcOut & owner_
Constructor & Destructor Documentation
Recenter()
LrIpcOut::Recenter::Recenter (LrIpcOut & owner) inline explicit noexcept
 : owner_{owner} {}
Member Function Documentation
SetMidiMessage()
void LrIpcOut::Recenter::SetMidiMessage (rsj::MidiMessage mm)
 {
    try {
       auto lock = std::lock_guard(mtx_);
       mm_ = mm;
       juce::Timer::startTimer(kRecenterTimer);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
timerCallback()
void LrIpcOut::Recenter::timerCallback () override private
 {
    try {
       rsj::MidiMessage local_mm{};
       {
          auto lock = std::lock_guard(mtx_);
          juce::Timer::stopTimer();
          local_mm = mm_;
       }
       const auto center = owner_.controls_model_.SetToCenter(local_mm);
       // send center to control//
       switch (local_mm.message_type_byte) {
       case rsj::MessageType::Pw: {
          owner_.midi_sender_->SendPitchWheel(local_mm.channel + 1, center);
          break;
       }
       case rsj::MessageType::Cc: {
          owner_.midi_sender_->SendCc(local_mm.channel + 1, local_mm.control_number, center);
          break;
       }
       default:
           /* no action */;
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::Cc, rsj::ExceptionResponse(), rsj::MidiMessage::message_type_byte, rsj::MidiMessage::MidiMessage(), rsj::NumToChars(), rsj::Pw, and ControlsModel::SetToCenter().
Member Data Documentation
mm_
rsj::MidiMessage LrIpcOut::Recenter::mm_ {} private
mtx_
rsj::RelaxTTasSpinLock LrIpcOut::Recenter::mtx_ private
owner_
LrIpcOut& LrIpcOut::Recenter::owner_ private
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/LR_IPC_Out.h
D:/Users/Rory/source/repos/MIDI2LR/Source/LR_IPC_Out.cpp