MIDI2LR: gsl::not_null< T > Class Template Reference
gsl::not_null< T > Class Template Reference
#include <GSL.h>
Public Member Functions
gsl_api not_null (T t)
gsl_api not_null (not_null const &other)
template<typename U >
gsl_api not_null (not_null< U > const &other)
gsl_api T get () const
gsl_api operator T () const
gsl_api bool operator!= (T const &rhs) const
gsl_api T operator-> () const
gsl_api not_null & operator= (T const &t)
gsl_api not_null & operator= (not_null const &other)
template<typename U >
gsl_api not_null & operator= (not_null< U > const &other)
gsl_api bool operator== (T const &rhs) const
Detailed Description
template<class T>
class gsl::not_null< T >
Definition at line 383 of file GSL.h.
Constructor & Destructor Documentation
template<class T > gsl_api gsl::not_null< T >::not_null (T t) inline
Definition at line 385 of file GSL.h.
References gsl::not_null< T >::operator=().
template<class T > gsl_api gsl::not_null< T >::not_null (not_null< T > const & other) inline
Definition at line 392 of file GSL.h.
References gsl::not_null< T >::operator=().
template<class T > template<typename U > gsl_api gsl::not_null< T >::not_null (not_null< U > const & other) inline
Definition at line 413 of file GSL.h.
References gsl::not_null< T >::operator=().
Member Function Documentation
template<class T > gsl_api T gsl::not_null< T >::get () const inline
Definition at line 432 of file GSL.h.
References gsl::not_null< T >::operator=().
template<class T > gsl_api gsl::not_null< T >::operator T () const inline
Definition at line 440 of file GSL.h.
References gsl::not_null< T >::operator=().
template<class T > gsl_api bool gsl::not_null< T >::operator!= (T const & rhs) const inline
Definition at line 450 of file GSL.h.
References gsl::not_null< T >::operator=().
template<class T > gsl_api T gsl::not_null< T >::operator-> () const inline
Definition at line 443 of file GSL.h.
References gsl::not_null< T >::operator=().
template<class T > gsl_api not_null& gsl::not_null< T >::operator= (T const & t) inline
Definition at line 388 of file GSL.h.
References gsl::not_null< T >::operator=().
template<class T > gsl_api not_null& gsl::not_null< T >::operator= (not_null< T > const & other) inline
Definition at line 393 of file GSL.h.
References gsl::not_null< T >::operator=().
template<class T > template<typename U > gsl_api not_null& gsl::not_null< T >::operator= (not_null< U > const & other) inline
Definition at line 416 of file GSL.h.
References gsl::not_null< T >::operator=().
Referenced by gsl::not_null< T >::get(), gsl::not_null< T >::not_null(), gsl::not_null< T >::operator T(), gsl::not_null< T >::operator!=(), gsl::not_null< T >::operator->(), gsl::not_null< T >::operator=(), and gsl::not_null< T >::operator==().
template<class T > gsl_api bool gsl::not_null< T >::operator== (T const & rhs) const inline
Definition at line 447 of file GSL.h.
References gsl::not_null< T >::operator=().
The documentation for this class was generated from the following file:
Q:/Documents/GitHub/MIDI2LR/Source/Utilities/GSL.h