MIDI2LR: MidiReceiver Class Reference
MidiReceiver Class Reference final
#include <MIDIReceiver.h>
Public Member Functions
MidiReceiver ()=default
MidiReceiver (const MidiReceiver &other)=delete
MidiReceiver (MidiReceiver &&other)=delete
~MidiReceiver ()
template<class T >
void AddCallback (T *const object, void(T::*const mf)(rsj::MidiMessage))
MidiReceiver & operator= (const MidiReceiver &other)=delete
MidiReceiver & operator= (MidiReceiver &&other)=delete
void RescanDevices ()
void Start ()
Private Member Functions
void DispatchMessages ()
void handleIncomingMidiMessage (juce::MidiInput *, const juce::MidiMessage &) override
void InitDevices ()
void TryToOpen ()
Private Attributes
std::vector< std::function< void(rsj::MidiMessage)> > callbacks_
std::vector< std::unique_ptr< juce::MidiInput > > devices_
std::future< void > dispatch_messages_future_
moodycamel::BlockingConcurrentQueue< rsj::MidiMessage > messages_
NrpnFilter nrpn_filter_
Constructor & Destructor Documentation
MidiReceiver() [1/3]
MidiReceiver::MidiReceiver () default
~MidiReceiver()
MidiReceiver::~MidiReceiver ()
 {
    try {
       for (const auto& dev : devices_) {
          dev->stop();
          rsj::Log("Stopped input device " + dev->getName());
       }
       if (const auto m = messages_.size_approx())
          rsj::Log(juce::String(m) + " left in queue in MidiReceiver destructor");
       moodycamel::ConsumerToken ctok(messages_);
       rsj::MidiMessage message_copy{};
       while (messages_.try_dequeue(ctok, message_copy)) {
          /* pump the queue empty */
       }
       messages_.enqueue(kTerminate);
    }
    catch (const std::exception& e) {
       rsj::LogAndAlertError(juce::String("Exception in MidiReceiver Destructor. ") + e.what());
       std::terminate();
    }
    catch (...) {
       rsj::LogAndAlertError("Exception in MidiReceiver Destructor. Non-standard exception.");
       std::terminate();
    }
 }
References rsj::MidiMessage::MidiMessage(), and rsj::NumToChars().
MidiReceiver() [2/3]
MidiReceiver::MidiReceiver (const MidiReceiver & other) delete
MidiReceiver() [3/3]
MidiReceiver::MidiReceiver (MidiReceiver && other) delete
Member Function Documentation
AddCallback()
template<class T > void MidiReceiver::AddCallback (T *const object, void(T::*)(rsj::MidiMessage) mf) inline
    {
       try {
          using namespace std::placeholders;
          if (object && mf) // only store non-empty functions
             callbacks_.emplace_back(std::bind(mf, object, _1));
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References devices_.
DispatchMessages()
void MidiReceiver::DispatchMessages () private
 {
    try {
       static thread_local moodycamel::ConsumerToken ctok(messages_);
       do {
          rsj::MidiMessage message_copy;
          if (!messages_.try_dequeue(ctok, message_copy))
             messages_.wait_dequeue(ctok, message_copy);
          if (message_copy == kTerminate)
             return;
          for (const auto& cb : callbacks_)
 #pragma warning(suppress : 26489) // false alarm, checked for existence before adding to callbacks_
             cb(message_copy);
       } while (true);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), rsj::NumToChars(), and rsj::operator==().
handleIncomingMidiMessage()
void MidiReceiver::handleIncomingMidiMessage (juce::MidiInput * , const juce::MidiMessage & message) override private
 {
    try {
       // this procedure is in near-real-time, so must return quickly.
       // will place message in multithreaded queue and let separate process handle the messages
       static const thread_local moodycamel::ProducerToken ptok(messages_);
       const rsj::MidiMessage mess{message};
       switch (mess.message_type_byte) {
       case rsj::kCcFlag:
          if (nrpn_filter_.ProcessMidi(mess.channel, mess.number, mess.value)) { // true if nrpn
                                                                                 // piece
             const auto nrpn = nrpn_filter_.GetNrpnIfReady(mess.channel);
             if (nrpn.is_valid) { // send when finished
                const auto n_message{
                    rsj::MidiMessage{rsj::kCcFlag, mess.channel, nrpn.control, nrpn.value}};
                messages_.enqueue(ptok, n_message);
             }
             break; // finished with nrpn piece
          }
          [[fallthrough]]; // if not nrpn, handle like other messages
       case rsj::kNoteOnFlag:
       case rsj::kPwFlag:
          messages_.enqueue(ptok, mess);
          break;
       default:; // no action if other type of MIDI message
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), rsj::kCcFlag, rsj::MidiMessage::message_type_byte, and rsj::NumToChars().
InitDevices()
void MidiReceiver::InitDevices () private
 {
    using namespace std::chrono_literals;
    try {
       rsj::Log("Trying to open input devices");
       TryToOpen();
       if (devices_.empty()) // encountering errors first try on MacOS
       {
          rsj::Log("Retrying to open input devices");
          rsj::SleepTimedLogged("Open input devices", 20ms);
          TryToOpen();
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), rsj::NumToChars(), and TryToOpen().
Referenced by RescanDevices(), and Start().
operator=() [1/2]
MidiReceiver& MidiReceiver::operator= (const MidiReceiver & other) delete
operator=() [2/2]
MidiReceiver& MidiReceiver::operator= (MidiReceiver && other) delete
RescanDevices()
void MidiReceiver::RescanDevices ()
 {
    try {
       for (const auto& dev : devices_) {
          dev->stop();
          rsj::Log("Stopped input device " + dev->getName());
       }
       devices_.clear();
       rsj::Log("Cleared input devices");
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
    InitDevices(); // initdevices has own try catch block
 }
References rsj::ExceptionResponse(), InitDevices(), and rsj::NumToChars().
Start()
void MidiReceiver::Start ()
 {
    try {
       InitDevices();
       dispatch_messages_future_ =
           std::async(std::launch::async, &MidiReceiver::DispatchMessages, this);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), InitDevices(), and rsj::NumToChars().
TryToOpen()
void MidiReceiver::TryToOpen () private
 {
    try {
       for (auto idx = 0; idx < juce::MidiInput::getDevices().size(); ++idx) {
          const auto dev = juce::MidiInput::openDevice(idx, this);
          if (dev) {
             devices_.emplace_back(dev);
             dev->start();
             rsj::Log("Opened input device " + dev->getName());
          }
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Referenced by InitDevices().
Member Data Documentation
callbacks_
std::vector<std::function<void(rsj::MidiMessage)> > MidiReceiver::callbacks_ private
devices_
std::vector<std::unique_ptr<juce::MidiInput> > MidiReceiver::devices_ private
Referenced by AddCallback().
dispatch_messages_future_
std::future<void> MidiReceiver::dispatch_messages_future_ private
messages_
moodycamel::BlockingConcurrentQueue<rsj::MidiMessage> MidiReceiver::messages_ private
nrpn_filter_
NrpnFilter MidiReceiver::nrpn_filter_ private
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/MIDIReceiver.h
D:/Users/Rory/source/repos/MIDI2LR/Source/MIDIReceiver.cpp