MIDI2LR: LrIpcOut::ConnectTimer Class Reference
LrIpcOut::ConnectTimer Class Reference final
Public Member Functions
ConnectTimer (LrIpcOut &owner) noexcept
void Start ()
void Stop ()
Private Member Functions
void timerCallback () override
Private Attributes
std::mutex connect_mutex_
LrIpcOut & owner_
bool timer_off_ {false}
Constructor & Destructor Documentation
ConnectTimer()
LrIpcOut::ConnectTimer::ConnectTimer (LrIpcOut & owner) inline explicit noexcept
 : owner_(owner) {}
Member Function Documentation
Start()
void LrIpcOut::ConnectTimer::Start ()
 {
    try {
       auto lock = std::lock_guard(connect_mutex_);
       juce::Timer::startTimer(kConnectTimer);
       timer_off_ = false;
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Stop()
void LrIpcOut::ConnectTimer::Stop ()
 {
    try {
       auto lock = std::lock_guard(connect_mutex_);
       juce::Timer::stopTimer();
       timer_off_ = true;
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
timerCallback()
void LrIpcOut::ConnectTimer::timerCallback () override private
 {
    try {
       auto lock = std::lock_guard(connect_mutex_);
       if (!timer_off_ && !owner_.juce::InterprocessConnection::isConnected())
          owner_.juce::InterprocessConnection::connectToSocket(kHost, kLrOutPort, kConnectTryTime);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Member Data Documentation
connect_mutex_
std::mutex LrIpcOut::ConnectTimer::connect_mutex_ mutable private
owner_
LrIpcOut& LrIpcOut::ConnectTimer::owner_ private
timer_off_
bool LrIpcOut::ConnectTimer::timer_off_ {false} private
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/LR_IPC_Out.h
D:/Users/Rory/source/repos/MIDI2LR/Source/LR_IPC_Out.cpp