MIDI2LR: MIDI2LRApplication Class Reference
MIDI2LRApplication Class Reference final
Public Member Functions
void anotherInstanceStarted (const juce::String &command_line) override
void anotherInstanceStarted (const juce::String &command_line) override
const juce::String getApplicationName () override
const juce::String getApplicationName () override
const juce::String getApplicationVersion () override
const juce::String getApplicationVersion () override
void initialise (const juce::String &command_line) override
void initialise (const juce::String &command_line) override
bool moreThanOneInstanceAllowed () noexcept override
bool moreThanOneInstanceAllowed () noexcept override
void shutdown () override
void shutdown () override
void systemRequestedQuit () override
void systemRequestedQuit () override
void unhandledException (const std::exception *e, const juce::String &source_filename, int lineNumber) override
void unhandledException (const std::exception *e, const juce::String &source_filename, int lineNumber) override
Private Member Functions
void DefaultProfileSave ()
void DefaultProfileSave ()
void LoadControlsModel ()
void LoadControlsModel ()
void SaveControlsModel () const
void SaveControlsModel () const
void SetAppFont () const
void SetAppFont () const
Private Attributes
const CommandSet command_set_ {}
ControlsModel controls_model_ {}
Devices devices_ {}
UpdateCurrentLogger dummy_ {logger_.get()}
std::unique_ptr< juce::FileLogger > logger_
LookAndFeelMIDI2LR look_feel_
LrIpcIn lr_ipc_in_ {controls_model_, profile_manager_, profile_, midi_sender_}
LrIpcOut lr_ipc_out_ {controls_model_, profile_, midi_sender_, midi_receiver_}
std::unique_ptr< MainWindow > main_window_ {nullptr}
MidiReceiver midi_receiver_ {devices_}
MidiSender midi_sender_ {devices_}
Profile profile_ {command_set_}
ProfileManager profile_manager_ {controls_model_, profile_, lr_ipc_out_, midi_receiver_}
SettingsManager settings_manager_ {profile_manager_, lr_ipc_out_}
VersionChecker version_checker_ {settings_manager_}
Member Function Documentation
anotherInstanceStarted() [1/2]
void MIDI2LRApplication::anotherInstanceStarted (const juce::String & command_line) inline override
    {
       if (command_line == kShutDownString)
          systemRequestedQuit();
    }
anotherInstanceStarted() [2/2]
void MIDI2LRApplication::anotherInstanceStarted (const juce::String & command_line) inline override
    {
       if (command_line == kShutDownString)
          systemRequestedQuit();
    }
References systemRequestedQuit().
DefaultProfileSave() [1/2]
void MIDI2LRApplication::DefaultProfileSave () inline private
    {
       try {
          const auto file_name {rsj::AppDataFilePath(kDefaultsFile)};
          const auto profile_file {juce::File(file_name.data())};
          profile_.ToXmlFile(profile_file);
          rsj::Log(fmt::format(FMT_STRING("Default profile saved to {}."),
              profile_file.getFullPathName().toStdString()));
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
          throw;
       }
    }
DefaultProfileSave() [2/2]
void MIDI2LRApplication::DefaultProfileSave () inline private
    {
       try {
          const auto file_name {rsj::AppDataFilePath(kDefaultsFile)};
          const auto profile_file {juce::File(file_name.data())};
          profile_.ToXmlFile(profile_file);
          rsj::Log(fmt::format(FMT_STRING("Default profile saved to {}."),
              profile_file.getFullPathName().toStdString()));
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
          throw;
       }
    }
Referenced by shutdown().
getApplicationName() [1/2]
const juce::String MIDI2LRApplication::getApplicationName () inline override
    {
       return ProjectInfo::projectName;
    }
getApplicationName() [2/2]
const juce::String MIDI2LRApplication::getApplicationName () inline override
    {
       return ProjectInfo::projectName;
    }
getApplicationVersion() [1/2]
const juce::String MIDI2LRApplication::getApplicationVersion () inline override
    {
       return ProjectInfo::versionString;
    }
getApplicationVersion() [2/2]
const juce::String MIDI2LRApplication::getApplicationVersion () inline override
    {
       return ProjectInfo::versionString;
    }
initialise() [1/2]
void MIDI2LRApplication::initialise (const juce::String & command_line) inline override
    {
       try {
          /*Called when the application starts. This will be called once to let the application do
           * whatever initialization it needs, create its windows, etc. After the method returns, the
           * normal event - dispatch loop will be run, until the quit() method is called, at which
           * point the shutdown() method will be called to let the application clear up anything it
           * needs to delete. If during the initialise() method, the application decides not to
           * start-up after all, it can just call the quit() method and the event loop won't be
           * run. */
          if (command_line != kShutDownString) {
             _mm_setcsr(_mm_getcsr() | 0x8040);
             CCoptions::LinkToControlsModel(&controls_model_);
             PWoptions::LinkToControlsModel(&controls_model_);
             juce::LookAndFeel::setDefaultLookAndFeel(&look_feel_);
             /* set language and load appropriate fonts and files */
             SetAppFont();
             LoadControlsModel();
             /* need to start main window before ipc so it's already registered its callbacks and can
              * receive messages */
             main_window_ =
                 std::make_unique<MainWindow>(getApplicationName(), command_set_, profile_,
                     profile_manager_, settings_manager_, lr_ipc_out_, midi_receiver_, midi_sender_);
             midi_receiver_.Start();
             midi_sender_.Start();
             lr_ipc_out_.Start();
             lr_ipc_in_.Start();
             /* Check for latest version */
             version_checker_.Start();
          }
          else {
             quit();
          }
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
          throw;
       }
    }
References LoadControlsModel(), and SetAppFont().
initialise() [2/2]
void MIDI2LRApplication::initialise (const juce::String & command_line) inline override
    {
       try {
          /*Called when the application starts. This will be called once to let the application do
           * whatever initialization it needs, create its windows, etc. After the method returns, the
           * normal event - dispatch loop will be run, until the quit() method is called, at which
           * point the shutdown() method will be called to let the application clear up anything it
           * needs to delete. If during the initialise() method, the application decides not to
           * start-up after all, it can just call the quit() method and the event loop won't be
           * run. */
          if (command_line != kShutDownString) {
             _mm_setcsr(_mm_getcsr() | 0x8040);
             CCoptions::LinkToControlsModel(&controls_model_);
             PWoptions::LinkToControlsModel(&controls_model_);
             juce::LookAndFeel::setDefaultLookAndFeel(&look_feel_);
             /* set language and load appropriate fonts and files */
             SetAppFont();
             LoadControlsModel();
             /* need to start main window before ipc so it's already registered its callbacks and can
              * receive messages */
             main_window_ =
                 std::make_unique<MainWindow>(getApplicationName(), command_set_, profile_,
                     profile_manager_, settings_manager_, lr_ipc_out_, midi_receiver_, midi_sender_);
             midi_receiver_.Start();
             midi_sender_.Start();
             lr_ipc_out_.Start();
             lr_ipc_in_.Start();
             /* Check for latest version */
             version_checker_.Start();
          }
          else {
             quit();
          }
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
          throw;
       }
    }
LoadControlsModel() [1/2]
void MIDI2LRApplication::LoadControlsModel () inline private
    {
       try {
 #ifdef FILESYSTEM_AVAILABLE_MIDI2LR
          const fs::path px {rsj::AppDataFilePath(kSettingsFileX)};
 #else
          const auto px {rsj::AppDataFilePath(kSettingsFileX)};
 #endif
          std::ifstream in_file {px};
          if (in_file.is_open() && !in_file.eof()) {
 #pragma warning(suppress : 26414) /* too large to construct on stack */
             const auto iarchive {std::make_unique<cereal::XMLInputArchive>(in_file)};
             (*iarchive)(controls_model_);
 #ifdef FILESYSTEM_AVAILABLE_MIDI2LR
             rsj::Log(fmt::format(
                 FMT_STRING("ControlsModel archive in Main loaded from {}."), px.string()));
 #else
             rsj::Log(fmt::format(FMT_STRING("ControlsModel archive in Main loaded from {}."), px));
 #endif
          }
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
       }
    }
LoadControlsModel() [2/2]
void MIDI2LRApplication::LoadControlsModel () inline private
    {
       try {
 #ifdef FILESYSTEM_AVAILABLE_MIDI2LR
          const fs::path px {rsj::AppDataFilePath(kSettingsFileX)};
 #else
          const auto px {rsj::AppDataFilePath(kSettingsFileX)};
 #endif
          std::ifstream in_file {px};
          if (in_file.is_open() && !in_file.eof()) {
 #pragma warning(suppress : 26414) /* too large to construct on stack */
             const auto iarchive {std::make_unique<cereal::XMLInputArchive>(in_file)};
             (*iarchive)(controls_model_);
 #ifdef FILESYSTEM_AVAILABLE_MIDI2LR
             rsj::Log(fmt::format(
                 FMT_STRING("ControlsModel archive in Main loaded from {}."), px.string()));
 #else
             rsj::Log(fmt::format(FMT_STRING("ControlsModel archive in Main loaded from {}."), px));
 #endif
          }
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
       }
    }
Referenced by initialise().
moreThanOneInstanceAllowed() [1/2]
bool MIDI2LRApplication::moreThanOneInstanceAllowed () inline override noexcept
    {
       return false;
    }
moreThanOneInstanceAllowed() [2/2]
bool MIDI2LRApplication::moreThanOneInstanceAllowed () inline override noexcept
    {
       return false;
    }
SaveControlsModel() [1/2]
void MIDI2LRApplication::SaveControlsModel () const inline private
    {
       try {
 #ifdef FILESYSTEM_AVAILABLE_MIDI2LR
          const fs::path p {rsj::AppDataFilePath(kSettingsFileX)};
 #else
          const auto p {rsj::AppDataFilePath(kSettingsFileX)};
 #endif
          std::ofstream outfile {p, std::ios::trunc};
          if (outfile.is_open()) {
 #pragma warning(suppress : 26414) /* too large to construct on stack */
             const auto oarchive {std::make_unique<cereal::XMLOutputArchive>(outfile)};
             (*oarchive)(controls_model_);
 #ifdef FILESYSTEM_AVAILABLE_MIDI2LR
             rsj::Log(
                 fmt::format(FMT_STRING("ControlsModel archive in Main saved to {}."), p.string()));
 #else
             rsj::Log(fmt::format(FMT_STRING("ControlsModel archive in Main saved to {}."), p));
 #endif
          }
          else
             rsj::LogAndAlertError(
                 juce::translate("Unable to save settings.xml"), "Unable to save settings.xml");
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
       }
    }
Referenced by shutdown().
SaveControlsModel() [2/2]
void MIDI2LRApplication::SaveControlsModel () const inline private
    {
       try {
 #ifdef FILESYSTEM_AVAILABLE_MIDI2LR
          const fs::path p {rsj::AppDataFilePath(kSettingsFileX)};
 #else
          const auto p {rsj::AppDataFilePath(kSettingsFileX)};
 #endif
          std::ofstream outfile {p, std::ios::trunc};
          if (outfile.is_open()) {
 #pragma warning(suppress : 26414) /* too large to construct on stack */
             const auto oarchive {std::make_unique<cereal::XMLOutputArchive>(outfile)};
             (*oarchive)(controls_model_);
 #ifdef FILESYSTEM_AVAILABLE_MIDI2LR
             rsj::Log(
                 fmt::format(FMT_STRING("ControlsModel archive in Main saved to {}."), p.string()));
 #else
             rsj::Log(fmt::format(FMT_STRING("ControlsModel archive in Main saved to {}."), p));
 #endif
          }
          else
             rsj::LogAndAlertError(
                 juce::translate("Unable to save settings.xml"), "Unable to save settings.xml");
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
       }
    }
SetAppFont() [1/2]
void MIDI2LRApplication::SetAppFont () const inline private
    {
       /* juce (as of July 2018) uses the following font defaults taken from juce_mac_Fonts.mm and
        * juce_wind32_Fonts.cpp. Sans defaults do not support Asian languages.
        * SEE:https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list avoiding fonts
        * added in windows 10 to support people using earlier Windows versions
        * SEE:https://docs.microsoft.com/en-us/windows/desktop/uxguide/vis-fonts
        * SEE:https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/loc-international-fonts
        * but Meiryo UI doesn't work well on my computer, so using MS UI Gothic instead for ja.
        * PingFang added in 10.11 El Capitan as new Chinese UI fonts
        *
        * Juce defaults:
        *                MacOS            Windows
        *        Sans    Lucida Grande    Verdana
        *        Serif   Times New Roman  Times New Roman
        *        Fixed   Menlo            Lucida Console
        */
       try {
          const auto& lang {command_set_.GetLanguage()};
          juce::String font1_name;
          juce::String font2_name;
          if (lang == "ko")
             font1_name = "NotoSansKR-Regular.otf";
          else if (lang == "zh_tw")
             font1_name = "NotoSansTC-Regular.otf";
          else if (lang == "zh_cn")
             font1_name = "NotoSansSC-Regular.otf";
          else if (lang == "ja")
             font1_name = "NotoSansJP-Regular.otf";
          else {
             font1_name = "NotoSans-Regular-Plus-Thai.ttf";
             font2_name = "NotoSans-Bold-plus-Thai.ttf";
          }
          juce::MemoryBlock font_data {};
          auto font_file = juce::File::getSpecialLocation(juce::File::currentApplicationFile)
                               .getSiblingFile(font1_name);
          if (font_file.loadFileAsData(font_data))
             juce::LookAndFeel::getDefaultLookAndFeel().setDefaultSansSerifTypeface(
                 juce::Typeface::createSystemTypefaceFor(font_data.getData(), font_data.getSize()));
          else
             rsj::Log(fmt::format(
                 FMT_STRING("Unable to load primary font file {}."), font1_name.toStdString()));
          if (font2_name.isNotEmpty()) {
             font_data.reset();
             font_file = juce::File::getSpecialLocation(juce::File::currentApplicationFile)
                             .getSiblingFile(font2_name);
             if (font_file.loadFileAsData(font_data))
                juce::Typeface::createSystemTypefaceFor(font_data.getData(), font_data.getSize());
             else
                rsj::Log(fmt::format(
                    FMT_STRING("Unable to load bold font file {}."), font2_name.toStdString()));
          }
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
          throw;
       }
    }
Referenced by initialise().
SetAppFont() [2/2]
void MIDI2LRApplication::SetAppFont () const inline private
    {
       /* juce (as of July 2018) uses the following font defaults taken from juce_mac_Fonts.mm and
        * juce_wind32_Fonts.cpp. Sans defaults do not support Asian languages.
        * SEE:https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list avoiding fonts
        * added in windows 10 to support people using earlier Windows versions
        * SEE:https://docs.microsoft.com/en-us/windows/desktop/uxguide/vis-fonts
        * SEE:https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/loc-international-fonts
        * but Meiryo UI doesn't work well on my computer, so using MS UI Gothic instead for ja.
        * PingFang added in 10.11 El Capitan as new Chinese UI fonts
        *
        * Juce defaults:
        *                MacOS            Windows
        *        Sans    Lucida Grande    Verdana
        *        Serif   Times New Roman  Times New Roman
        *        Fixed   Menlo            Lucida Console
        */
       try {
          const auto& lang {command_set_.GetLanguage()};
          juce::String font1_name;
          juce::String font2_name;
          if (lang == "ko")
             font1_name = "NotoSansKR-Regular.otf";
          else if (lang == "zh_tw")
             font1_name = "NotoSansTC-Regular.otf";
          else if (lang == "zh_cn")
             font1_name = "NotoSansSC-Regular.otf";
          else if (lang == "ja")
             font1_name = "NotoSansJP-Regular.otf";
          else {
             font1_name = "NotoSans-Regular-Plus-Thai.ttf";
             font2_name = "NotoSans-Bold-plus-Thai.ttf";
          }
          juce::MemoryBlock font_data {};
          auto font_file = juce::File::getSpecialLocation(juce::File::currentApplicationFile)
                               .getSiblingFile(font1_name);
          if (font_file.loadFileAsData(font_data))
             juce::LookAndFeel::getDefaultLookAndFeel().setDefaultSansSerifTypeface(
                 juce::Typeface::createSystemTypefaceFor(font_data.getData(), font_data.getSize()));
          else
             rsj::Log(fmt::format(
                 FMT_STRING("Unable to load primary font file {}."), font1_name.toStdString()));
          if (font2_name.isNotEmpty()) {
             font_data.reset();
             font_file = juce::File::getSpecialLocation(juce::File::currentApplicationFile)
                             .getSiblingFile(font2_name);
             if (font_file.loadFileAsData(font_data))
                juce::Typeface::createSystemTypefaceFor(font_data.getData(), font_data.getSize());
             else
                rsj::Log(fmt::format(
                    FMT_STRING("Unable to load bold font file {}."), font2_name.toStdString()));
          }
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
          throw;
       }
    }
shutdown() [1/2]
void MIDI2LRApplication::shutdown () inline override
    {
       /*Called to allow the application to clear up before exiting. After JUCEApplication::quit()
        * has been called, the event-dispatch loop will terminate, and this method will get called
        * to allow the application to sort itself out. Be careful that nothing happens in this method
        * that might rely on messages being sent, or any kind of window activity, because the message
        * loop is no longer running at this point. */
       /*Primary goals: 1) remove callbacks in LR_IPC_Out and MIDIReceiver before the callee is
        * destroyed, 2) stop additional threads in VersionChecker, LR_IPC_In, LR_IPC_Out and
        * MIDIReceiver. Add to this list if new threads or callback lists are developed in this
        * app. */
       midi_receiver_.Stop();
       lr_ipc_in_.Stop();
       lr_ipc_out_.Stop();
       version_checker_.Stop();
       DefaultProfileSave();
       SaveControlsModel();
       settings_manager_.SetDefaultProfile(main_window_->GetProfileName());
       /* (delete our window) */
       main_window_.reset();
       juce::Logger::setCurrentLogger(nullptr);
    }
References DefaultProfileSave(), and SaveControlsModel().
shutdown() [2/2]
void MIDI2LRApplication::shutdown () inline override
    {
       /*Called to allow the application to clear up before exiting. After JUCEApplication::quit()
        * has been called, the event-dispatch loop will terminate, and this method will get called
        * to allow the application to sort itself out. Be careful that nothing happens in this method
        * that might rely on messages being sent, or any kind of window activity, because the message
        * loop is no longer running at this point. */
       /*Primary goals: 1) remove callbacks in LR_IPC_Out and MIDIReceiver before the callee is
        * destroyed, 2) stop additional threads in VersionChecker, LR_IPC_In, LR_IPC_Out and
        * MIDIReceiver. Add to this list if new threads or callback lists are developed in this
        * app. */
       midi_receiver_.Stop();
       lr_ipc_in_.Stop();
       lr_ipc_out_.Stop();
       version_checker_.Stop();
       DefaultProfileSave();
       SaveControlsModel();
       settings_manager_.SetDefaultProfile(main_window_->GetProfileName());
       /* (delete our window) */
       main_window_.reset();
       juce::Logger::setCurrentLogger(nullptr);
    }
systemRequestedQuit() [1/2]
void MIDI2LRApplication::systemRequestedQuit () inline override
    {
       /*This is called when the application is being asked to quit: you can ignore this request
        * and let the application carry on running, or call quit() to allow the application to
        * close. */
       try {
          static std::once_flag of; /* function might be called twice during LR shutdown */
          std::call_once(of, [this] {
             if (profile_.ProfileUnsaved() && main_window_) {
                const juce::MessageManagerLock mmLock; /* this may be unnecessary */
                const auto result {juce::NativeMessageBox::showYesNoBox(
                    juce::AlertWindow::WarningIcon, juce::translate("MIDI2LR profiles"),
                    juce::translate("Profile changed. Do you want to save your changes? If you "
                                    "continue without saving, your changes will be lost."))};
                if (result)
                   main_window_->SaveProfile();
             }
             quit();
          });
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
          throw;
       }
    }
Referenced by anotherInstanceStarted().
systemRequestedQuit() [2/2]
void MIDI2LRApplication::systemRequestedQuit () inline override
    {
       /*This is called when the application is being asked to quit: you can ignore this request
        * and let the application carry on running, or call quit() to allow the application to
        * close. */
       try {
          static std::once_flag of; /* function might be called twice during LR shutdown */
          std::call_once(of, [this] {
             if (profile_.ProfileUnsaved() && main_window_) {
                const juce::MessageManagerLock mmLock; /* this may be unnecessary */
                const auto result {juce::NativeMessageBox::showYesNoBox(
                    juce::AlertWindow::WarningIcon, juce::translate("MIDI2LR profiles"),
                    juce::translate("Profile changed. Do you want to save your changes? If you "
                                    "continue without saving, your changes will be lost."))};
                if (result)
                   main_window_->SaveProfile();
             }
             quit();
          });
       }
       catch (const std::exception& e) {
          MIDI2LR_E_RESPONSE;
          throw;
       }
    }
unhandledException() [1/2]
void MIDI2LRApplication::unhandledException (const std::exception * e, const juce::String & source_filename, int lineNumber) inline override
    {
       /* If any unhandled exceptions make it through to the message dispatch loop, this callback
        * will be triggered, in case you want to log them or do some other type of error-handling. If
        * the type of exception is derived from the std::exception class, the pointer passed-in will
        * be valid. If the exception is of unknown type, this pointer will be null. */
       try {
          if (e) {
             constexpr auto msge {"Unhandled exception {}, {} line {}. Total uncaught {}."};
             const auto msgt {juce::translate("unhandled exception").toStdString()
                              + " {}, {} line {}. Total uncaught {}."};
             rsj::LogAndAlertError(fmt::format(msgt, e->what(), source_filename.toStdString(),
                                       lineNumber, std::uncaught_exceptions()),
                 fmt::format(msge, e->what(), source_filename.toStdString(), lineNumber,
                     std::uncaught_exceptions()));
          }
          else {
             constexpr auto msge {"Unhandled exception {} line {}. Total uncaught {}."};
             const auto msgt {juce::translate("unhandled exception").toStdString()
                              + " {} line {}. Total uncaught {}."};
             rsj::LogAndAlertError(fmt::format(msgt, source_filename.toStdString(), lineNumber,
                                       std::uncaught_exceptions()),
                 fmt::format(
                     msge, source_filename.toStdString(), lineNumber, std::uncaught_exceptions()));
          }
       }
       catch (...) {
          /* we'll terminate anyway */
          std::terminate();
       }
       /* can't go on with the program */
       std::terminate();
    }
unhandledException() [2/2]
void MIDI2LRApplication::unhandledException (const std::exception * e, const juce::String & source_filename, int lineNumber) inline override
    {
       /* If any unhandled exceptions make it through to the message dispatch loop, this callback
        * will be triggered, in case you want to log them or do some other type of error-handling. If
        * the type of exception is derived from the std::exception class, the pointer passed-in will
        * be valid. If the exception is of unknown type, this pointer will be null. */
       try {
          if (e) {
             constexpr auto msge {"Unhandled exception {}, {} line {}. Total uncaught {}."};
             const auto msgt {juce::translate("unhandled exception").toStdString()
                              + " {}, {} line {}. Total uncaught {}."};
             rsj::LogAndAlertError(fmt::format(msgt, e->what(), source_filename.toStdString(),
                                       lineNumber, std::uncaught_exceptions()),
                 fmt::format(msge, e->what(), source_filename.toStdString(), lineNumber,
                     std::uncaught_exceptions()));
          }
          else {
             constexpr auto msge {"Unhandled exception {} line {}. Total uncaught {}."};
             const auto msgt {juce::translate("unhandled exception").toStdString()
                              + " {} line {}. Total uncaught {}."};
             rsj::LogAndAlertError(fmt::format(msgt, source_filename.toStdString(), lineNumber,
                                       std::uncaught_exceptions()),
                 fmt::format(
                     msge, source_filename.toStdString(), lineNumber, std::uncaught_exceptions()));
          }
       }
       catch (...) {
          /* we'll terminate anyway */
          std::terminate();
       }
       /* can't go on with the program */
       std::terminate();
    }
Member Data Documentation
command_set_
const CommandSet MIDI2LRApplication::command_set_ {} private
controls_model_
ControlsModel MIDI2LRApplication::controls_model_ {} private
devices_
Devices MIDI2LRApplication::devices_ {} private
dummy_
UpdateCurrentLogger MIDI2LRApplication::dummy_ {logger_.get()} private
logger_
std::unique_ptr< juce::FileLogger > MIDI2LRApplication::logger_ private
Initial value:
{
       juce::FileLogger::createDefaultAppLogger("MIDI2LR", "MIDI2LR.log", "", 32 * 1024)}
look_feel_
LookAndFeelMIDI2LR MIDI2LRApplication::look_feel_ private
lr_ipc_in_
LrIpcIn MIDI2LRApplication::lr_ipc_in_ {controls_model_, profile_manager_, profile_, midi_sender_} private
lr_ipc_out_
LrIpcOut MIDI2LRApplication::lr_ipc_out_ {controls_model_, profile_, midi_sender_, midi_receiver_} private
main_window_
std::unique_ptr< MainWindow > MIDI2LRApplication::main_window_ {nullptr} private
midi_receiver_
MidiReceiver MIDI2LRApplication::midi_receiver_ {devices_} private
midi_sender_
MidiSender MIDI2LRApplication::midi_sender_ {devices_} private
profile_
Profile MIDI2LRApplication::profile_ {command_set_} private
profile_manager_
ProfileManager MIDI2LRApplication::profile_manager_ {controls_model_, profile_, lr_ipc_out_, midi_receiver_} private
settings_manager_
SettingsManager MIDI2LRApplication::settings_manager_ {profile_manager_, lr_ipc_out_} private
version_checker_
VersionChecker MIDI2LRApplication::version_checker_ {settings_manager_} private
The documentation for this class was generated from the following file:
C:/Users/rsjaf/source/repos/MIDI2LR/src/application/Main.cpp