MIDI2LR: ResizableLayout Class Reference
ResizableLayout Class Reference
#include <ResizableLayout.h>
Classes
struct Anchor
struct Rect
struct State
Public Types
enum { anchorUnit = 100 }
enum Style { styleStretch, styleFixedAspect }
Public Member Functions
ResizableLayout (juce::Component *owner)
~ResizableLayout ()
void activateLayout (bool isActive=true) noexcept
void addToLayout (juce::Component *component, const juce::Point< int > &topLeft, const juce::Point< int > &bottomRight=juce::Point< int >{-1, -1}, Style style=styleStretch)
void recalculateLayout () const
void removeFromLayout (juce::Component *component) noexcept
void updateLayoutFor (juce::Component *component) noexcept
Public Member Functions inherited from ResizableChild
ResizableChild () noexcept
virtual ~ResizableChild ()=default
int getMaximumHeight () const noexcept
int getMaximumWidth () const noexcept
int getMinimumHeight () const noexcept
int getMinimumWidth () const noexcept
void setMaximumHeight (int maximumHeight) noexcept
void setMaximumSize (int maximumWidth, int maximumHeight) noexcept
void setMaximumWidth (int maximumWidth) noexcept
void setMinimumHeight (int minimumHeight) noexcept
void setMinimumSize (int minimumWidth, int minimumHeight) noexcept
void setMinimumWidth (int minimumWidth) noexcept
void setSizeLimits (int minimumWidth, int minimumHeight, int maximumWidth, int maximumHeight) noexcept
Static Public Member Functions
static juce::Rectangle< int > calcBoundsOfChildren (juce::Component *parent) noexcept
Private Member Functions
void addStateFor (const Anchor &anchor) noexcept
void componentBeingDeleted (juce::Component &component) noexcept override
void componentMovedOrResized (juce::Component &component, bool wasMoved, bool wasResized) override
void resizeStart () noexcept override
void updateLayout () noexcept
Private Attributes
juce::SortedSet< Anchor > m_anchors
bool m_bFirstTime
bool m_isActive
juce::Component * m_owner
juce::SortedSet< State > m_states
Friends
class TopLevelResizableLayout
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
anchorUnit
 { anchorUnit = 100 };
Style
enum ResizableLayout::Style
Enumerator
styleStretch
styleFixedAspect
 { styleStretch, styleFixedAspect };
Constructor & Destructor Documentation
ResizableLayout()
ResizableLayout::ResizableLayout (juce::Component * owner)
                                                      : m_owner(owner)
 {
    m_bFirstTime = true;
    m_isActive = false;
    m_owner->addComponentListener(this);
 }
References m_bFirstTime, and m_isActive.
~ResizableLayout()
ResizableLayout::~ResizableLayout ()
 {}
Member Function Documentation
activateLayout()
void ResizableLayout::activateLayout (bool isActive = true) noexcept
 {
    if (m_isActive != isActive) {
       if (isActive && m_bFirstTime) {
          updateLayout();
          m_bFirstTime = false;
       }
       m_isActive = isActive;
    }
 }
References m_bFirstTime, m_isActive, and updateLayout().
addStateFor()
void ResizableLayout::addStateFor (const Anchor & anchor) private noexcept
 {
 #pragma warning(suppress : 26496)
    Rect rb = anchor.component->getBounds();
    const auto w = m_owner->getWidth();
    const auto h = m_owner->getHeight();
    State state(anchor.component);
    // secret sauce
    state.margin.top = rb.top - (h * anchor.topLeft.getY()) / anchorUnit;
    state.margin.left = rb.left - (w * anchor.topLeft.getX()) / anchorUnit;
    state.margin.bottom = rb.bottom - (h * anchor.bottomRight.getY()) / anchorUnit;
    state.margin.right = rb.right - (w * anchor.bottomRight.getX()) / anchorUnit;
    state.aspect = double(rb.getWidth()) / rb.getHeight();
 #pragma warning(suppress : 26486)
    m_states.add(state);
 }
References ResizableLayout::Rect::reduce().
addToLayout()
void ResizableLayout::addToLayout (juce::Component * component, const juce::Point< int > & topLeft, const juce::Point< int > & bottomRight = juce::Point<int>{-1, -1}, Style style = styleStretch)
 {
    jassert(topLeft != anchorNone);
    Anchor anchor(component);
    anchor.style = style;
    anchor.topLeft = topLeft;
    if (bottomRight == anchorNone)
       anchor.bottomRight = topLeft;
    else
       anchor.bottomRight = bottomRight;
 #pragma warning(suppress : 26486)
    m_anchors.add(anchor);
    component->addComponentListener(this);
 }
References ResizableLayout::Anchor::style.
calcBoundsOfChildren()
juce::Rectangle< int > ResizableLayout::calcBoundsOfChildren (juce::Component * parent) static noexcept
 {
    juce::Rectangle<int> r;
    for (int i = 0; i < parent->getNumChildComponents(); i++)
       r = r.getUnion(parent->getChildComponent(i)->getBounds());
    return r;
 }
componentBeingDeleted()
void ResizableLayout::componentBeingDeleted (juce::Component & component) override private noexcept
 {
    if (&component != m_owner) {
       m_anchors.removeValue(&component);
       m_states.removeValue(&component);
    }
 }
componentMovedOrResized()
void ResizableLayout::componentMovedOrResized (juce::Component & component, bool wasMoved, bool wasResized) override private
 {
    if (&component == m_owner) {
       if (wasResized) {
          recalculateLayout();
       }
    }
    else {
       updateLayoutFor(&component);
    }
 }
References recalculateLayout().
recalculateLayout()
void ResizableLayout::recalculateLayout () const
 {
    if (m_isActive) {
 #pragma warning(suppress : 26496)
       Rect rp = m_owner->getBounds();
       for (int i = 0; i < m_states.size(); i++) {
 #pragma warning(suppress : 26446)
          auto anchor = m_anchors[i];
 #pragma warning(suppress : 26446)
          const auto state = m_states[i];
          jassert(anchor.component == state.component);
          Rect rb;
          // secret sauce
          rb.top = state.margin.top + (rp.getHeight() * anchor.topLeft.getY()) / anchorUnit;
          rb.left = state.margin.left + (rp.getWidth() * anchor.topLeft.getX()) / anchorUnit;
          rb.bottom =
              state.margin.bottom + (rp.getHeight() * anchor.bottomRight.getY()) / anchorUnit;
          rb.right = state.margin.right + (rp.getWidth() * anchor.bottomRight.getX()) / anchorUnit;
          // prove that there are no rounding issues
          jassert((anchor.bottomRight != anchor.topLeft)
                  || ((rb.getWidth() == anchor.component->getWidth())
                         && (rb.getHeight() == anchor.component->getHeight())));
          if (anchor.style == styleStretch) {
             anchor.component->setBounds(rb);
          }
          else if (anchor.style == styleFixedAspect) {
             Rect r;
             const auto aspect = double(rb.getWidth()) / rb.getHeight();
             if (aspect > state.aspect) {
                r.top = rb.top;
                r.bottom = rb.bottom;
                const auto width = int(state.aspect * r.getHeight());
                r.left = rb.left + (rb.getWidth() - width) / 2;
                r.right = r.left + width;
             }
             else {
                r.left = rb.left;
                r.right = rb.right;
                const auto height = int(1. / state.aspect * r.getWidth());
                r.top = rb.top + (rb.getHeight() - height) / 2;
                r.bottom = r.top + height;
             }
             anchor.component->setBounds(r);
          }
       }
    }
 }
References m_isActive, and ResizableLayout::Rect::reduce().
Referenced by componentMovedOrResized().
removeFromLayout()
void ResizableLayout::removeFromLayout (juce::Component * component) noexcept
 {
    m_anchors.removeValue(component);
    m_states.removeValue(component);
 }
resizeStart()
void ResizableLayout::resizeStart () override private virtual noexcept
Reimplemented from ResizableChild.
 {
    auto haveChildren = false;
    // first recursively call resizeStart() on all children
    for (int i = 0; i < m_anchors.size(); i++) {
       auto child = m_anchors.getUnchecked(i).child;
       if (child) {
          child->resizeStart();
          haveChildren = true;
       }
    }
    // now check our immediate children for constraints
    if (haveChildren) {
       // start with our values
       auto xmin0 = getMinimumWidth();
       auto ymin0 = getMinimumHeight();
       // for each child, use the inverse of the resize function to solve for
       // the min/max
       for (int i = 0; i < m_anchors.size(); i++) {
          auto anchor = m_anchors.getUnchecked(i);
          if (anchor.child) {
             const auto state = m_states.getUnchecked(i);
             jassert(anchor.component == state.component);
             const auto xmin1 = anchor.child->getMinimumWidth();
             const auto ymin1 = anchor.child->getMinimumHeight();
             // int xmax1 = anchor.child->getMaximumWidth();
             // int ymax1 = anchor.child->getMaximumHeight();
             int m; // solution to f'(x)
             auto d = anchor.bottomRight.getX() - anchor.topLeft.getX();
             if (d != 0) {
                m = (xmin1 + state.margin.left - state.margin.right) * anchorUnit / d;
                xmin0 = juce::jmax(xmin0, m);
             }
             d = anchor.bottomRight.getY() - anchor.topLeft.getY();
             if (d != 0) {
                m = (ymin1 + state.margin.top - state.margin.bottom) * anchorUnit / d;
                ymin0 = juce::jmax(ymin0, m);
             }
          }
       }
       // apply adjusted limits
       setMinimumWidth(xmin0);
       setMinimumHeight(ymin0);
    }
 }
updateLayout()
void ResizableLayout::updateLayout () private noexcept
 {
    m_states.clearQuick();
    for (int i = 0; i < m_anchors.size(); i++)
 #pragma warning(suppress : 26446)
       addStateFor(m_anchors[i]);
 }
Referenced by activateLayout().
updateLayoutFor()
void ResizableLayout::updateLayoutFor (juce::Component * component) noexcept
 {
    m_states.removeValue(component);
 #pragma warning(suppress : 26446)
    addStateFor(m_anchors[m_anchors.indexOf(component)]);
 }
Friends And Related Function Documentation
TopLevelResizableLayout
friend class TopLevelResizableLayout friend
Member Data Documentation
m_anchors
juce::SortedSet<Anchor> ResizableLayout::m_anchors private
m_bFirstTime
bool ResizableLayout::m_bFirstTime private
Referenced by activateLayout(), and ResizableLayout().
m_isActive
bool ResizableLayout::m_isActive private
Referenced by activateLayout(), recalculateLayout(), and ResizableLayout().
m_owner
juce::Component* ResizableLayout::m_owner private
m_states
juce::SortedSet<State> ResizableLayout::m_states private
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/ResizableLayout.h
D:/Users/Rory/source/repos/MIDI2LR/Source/ResizableLayout.cpp