MIDI2LR: gsl::span< T > Class Template Reference
gsl::span< T > Class Template Reference
#include <GSL.h>
Public Types
typedef const_pointer const_iterator
typedef T const * const_pointer
typedef T const & const_reference
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::iterator_traits< iterator >::difference_type difference_type
typedef pointer iterator
typedef T * pointer
typedef T & reference
typedef std::reverse_iterator< iterator > reverse_iterator
typedef size_t size_type
typedef T value_type
Public Member Functions
gsl_api gsl_constexpr14 span ()
gsl_api gsl_constexpr14 span (pointer begin_in, pointer end_in)
gsl_api gsl_constexpr14 span (pointer data_in, size_type size_in)
template<class U , size_t N>
gsl_api gsl_constexpr14 span (U(&arr)[N])
template<class Cont >
gsl_api gsl_constexpr14 span (Cont &cont)
gsl_api gsl_constexpr14 span (span const &other)
template<typename U >
gsl_api gsl_constexpr14 span (span< U > const &other)
gsl_api span< const byte > as_bytes () const gsl_noexcept
template<typename U >
gsl_api span< U > as_span () const gsl_noexcept
gsl_api span< byte > as_writeable_bytes () const gsl_noexcept
gsl_api gsl_constexpr14 reference at (size_type index)
gsl_api gsl_constexpr14 const_reference at (size_type index) const
gsl_api gsl_constexpr14 iterator begin () const
gsl_api gsl_constexpr14 size_type bytes () const gsl_noexcept
gsl_api gsl_constexpr14 const_iterator cbegin () const
gsl_api gsl_constexpr14 const_iterator cend () const
gsl_api gsl_constexpr14 const_reverse_iterator crbegin () const
gsl_api gsl_constexpr14 const_reverse_iterator crend () const
gsl_api gsl_constexpr14 pointer data () const gsl_noexcept
gsl_api gsl_constexpr14 bool empty () const gsl_noexcept
gsl_api gsl_constexpr14 iterator end () const
gsl_api gsl_constexpr14 span< value_type > first (size_type count) const gsl_noexcept
gsl_api gsl_constexpr14 span< value_type > last (size_type count) const gsl_noexcept
gsl_api gsl_constexpr14 size_type length () const gsl_noexcept
gsl_api gsl_constexpr14 operator bool () const gsl_noexcept
gsl_api gsl_constexpr14 bool operator!= (span const &other) const gsl_noexcept
gsl_api gsl_constexpr14 bool operator< (span const &other) const gsl_noexcept
gsl_api gsl_constexpr14 bool operator<= (span const &other) const gsl_noexcept
gsl_api span & operator= (span other)
gsl_api gsl_constexpr14 bool operator== (span const &other) const gsl_noexcept
gsl_api gsl_constexpr14 bool operator> (span const &other) const gsl_noexcept
gsl_api gsl_constexpr14 bool operator>= (span const &other) const gsl_noexcept
gsl_api gsl_constexpr14 reference operator[] (size_type index)
gsl_api gsl_constexpr14 const_reference operator[] (size_type index) const
gsl_api gsl_constexpr14 reverse_iterator rbegin () const
gsl_api gsl_constexpr14 reverse_iterator rend () const
gsl_api gsl_constexpr14 size_type size () const gsl_noexcept
gsl_api gsl_constexpr14 span< value_type > subspan (size_type offset) const gsl_noexcept
gsl_api gsl_constexpr14 span< value_type > subspan (size_type offset, size_type count) const gsl_noexcept
gsl_api void swap (span &other) gsl_noexcept
gsl_api gsl_constexpr14 size_type used_bytes () const gsl_noexcept
gsl_api gsl_constexpr14 size_type used_length () const gsl_noexcept
Friends
template<class U >
class span
Detailed Description
template<class T>
class gsl::span< T >
Definition at line 484 of file GSL.h.
Member Typedef Documentation
template<class T > typedef const_pointer gsl::span< T >::const_iterator
Definition at line 497 of file GSL.h.
template<class T > typedef T const* gsl::span< T >::const_pointer
Definition at line 493 of file GSL.h.
template<class T > typedef T const& gsl::span< T >::const_reference
Definition at line 494 of file GSL.h.
template<class T > typedef std::reverse_iterator< const_iterator > gsl::span< T >::const_reverse_iterator
Definition at line 504 of file GSL.h.
template<class T > typedef std::iterator_traits< iterator >::difference_type gsl::span< T >::difference_type
Definition at line 507 of file GSL.h.
template<class T > typedef pointer gsl::span< T >::iterator
Definition at line 496 of file GSL.h.
template<class T > typedef T* gsl::span< T >::pointer
Definition at line 492 of file GSL.h.
template<class T > typedef T& gsl::span< T >::reference
Definition at line 491 of file GSL.h.
template<class T > typedef std::reverse_iterator< iterator > gsl::span< T >::reverse_iterator
Definition at line 503 of file GSL.h.
template<class T > typedef size_t gsl::span< T >::size_type
Definition at line 488 of file GSL.h.
template<class T > typedef T gsl::span< T >::value_type
Definition at line 490 of file GSL.h.
Constructor & Destructor Documentation
template<class T > gsl_api gsl_constexpr14 gsl::span< T >::span () inline
Definition at line 509 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 gsl::span< T >::span (pointer begin_in, pointer end_in) inline
Definition at line 530 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 gsl::span< T >::span (pointer data_in, size_type size_in) inline
Definition at line 536 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > template<class U , size_t N> gsl_api gsl_constexpr14 gsl::span< T >::span (U(&) arr[N]) inline
Definition at line 543 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > template<class Cont > gsl_api gsl_constexpr14 gsl::span< T >::span (Cont & cont) inline
Definition at line 562 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 gsl::span< T >::span (span< T > const & other) inline
Definition at line 571 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > template<typename U > gsl_api gsl_constexpr14 gsl::span< T >::span (span< U > const & other) inline
Definition at line 577 of file GSL.h.
References gsl::span< T >::operator=().
Member Function Documentation
template<class T > gsl_api span< const byte > gsl::span< T >::as_bytes () const inline
Definition at line 729 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > template<typename U > gsl_api span< U > gsl::span< T >::as_span () const inline
Definition at line 738 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api span< byte > gsl::span< T >::as_writeable_bytes () const inline
Definition at line 733 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 reference gsl::span< T >::at (size_type index) inline
Definition at line 685 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 const_reference gsl::span< T >::at (size_type index) const inline
Definition at line 690 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 iterator gsl::span< T >::begin () const inline
Definition at line 616 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 size_type gsl::span< T >::bytes () const inline
Definition at line 715 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 const_iterator gsl::span< T >::cbegin () const inline
Definition at line 624 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 const_iterator gsl::span< T >::cend () const inline
Definition at line 628 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 const_reverse_iterator gsl::span< T >::crbegin () const inline
Definition at line 640 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 const_reverse_iterator gsl::span< T >::crend () const inline
Definition at line 644 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 pointer gsl::span< T >::data () const inline
Definition at line 695 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 bool gsl::span< T >::empty () const inline
Definition at line 699 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 iterator gsl::span< T >::end () const inline
Definition at line 620 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 span< value_type > gsl::span< T >::first (size_type count) const inline
Definition at line 596 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 span< value_type > gsl::span< T >::last (size_type count) const inline
Definition at line 601 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 size_type gsl::span< T >::length () const inline
Definition at line 707 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 gsl::span< T >::operator bool () const inline
Definition at line 648 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 bool gsl::span< T >::operator!= (span< T > const & other) const inline
Definition at line 665 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 bool gsl::span< T >::operator< (span< T > const & other) const inline
Definition at line 669 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 bool gsl::span< T >::operator<= (span< T > const & other) const inline
Definition at line 673 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api span& gsl::span< T >::operator= (span< T > other) inline
Definition at line 585 of file GSL.h.
References gsl::span< T >::operator=().
Referenced by gsl::span< T >::as_bytes(), gsl::span< T >::as_span(), gsl::span< T >::as_writeable_bytes(), gsl::span< T >::at(), gsl::span< T >::begin(), gsl::span< T >::bytes(), gsl::span< T >::cbegin(), gsl::span< T >::cend(), gsl::span< T >::crbegin(), gsl::span< T >::crend(), gsl::span< T >::data(), gsl::span< T >::empty(), gsl::span< T >::end(), gsl::span< T >::first(), gsl::span< T >::last(), gsl::span< T >::length(), gsl::span< T >::operator bool(), gsl::span< T >::operator!=(), gsl::span< T >::operator<(), gsl::span< T >::operator<=(), gsl::span< T >::operator=(), gsl::span< T >::operator==(), gsl::span< T >::operator>(), gsl::span< T >::operator>=(), gsl::span< T >::operator[](), gsl::span< T >::rbegin(), gsl::span< T >::rend(), gsl::span< T >::size(), gsl::span< T >::span(), gsl::span< T >::subspan(), gsl::span< T >::swap(), gsl::span< T >::used_bytes(), and gsl::span< T >::used_length().
template<class T > gsl_api gsl_constexpr14 bool gsl::span< T >::operator== (span< T > const & other) const inline
Definition at line 660 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 bool gsl::span< T >::operator> (span< T > const & other) const inline
Definition at line 677 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 bool gsl::span< T >::operator>= (span< T > const & other) const inline
Definition at line 681 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 reference gsl::span< T >::operator[] (size_type index) inline
Definition at line 652 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 const_reference gsl::span< T >::operator[] (size_type index) const inline
Definition at line 656 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 reverse_iterator gsl::span< T >::rbegin () const inline
Definition at line 632 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 reverse_iterator gsl::span< T >::rend () const inline
Definition at line 636 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 size_type gsl::span< T >::size () const inline
Definition at line 703 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 span< value_type > gsl::span< T >::subspan (size_type offset) const inline
Definition at line 606 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 span< value_type > gsl::span< T >::subspan (size_type offset, size_type count) const inline
Definition at line 611 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api void gsl::span< T >::swap (span< T > & other) inline
Definition at line 723 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 size_type gsl::span< T >::used_bytes () const inline
Definition at line 719 of file GSL.h.
References gsl::span< T >::operator=().
template<class T > gsl_api gsl_constexpr14 size_type gsl::span< T >::used_length () const inline
Definition at line 711 of file GSL.h.
References gsl::span< T >::operator=().
Friends And Related Function Documentation
template<class T > template<class U > friend class span friend
Definition at line 485 of file GSL.h.
The documentation for this class was generated from the following file:
Q:/Documents/GitHub/MIDI2LR/Source/Utilities/GSL.h