MIDI2LR: RSJ::threadsafe_queue< T > Class Template Reference
RSJ::threadsafe_queue< T > Class Template Reference
#include <Utilities.h>
Public Member Functions
threadsafe_queue ()
bool empty () const
void NotifyOther ()
void push (T new_value)
bool try_pop (T &value)
std::shared_ptr< T > try_pop ()
void wait_and_pop (T &value)
std::shared_ptr< T > wait_and_pop ()
Detailed Description
template<typename T>
class RSJ::threadsafe_queue< T >
Definition at line 80 of file Utilities.h.
Constructor & Destructor Documentation
template<typename T > RSJ::threadsafe_queue< T >::threadsafe_queue () inline
Definition at line 87 of file Utilities.h.
Member Function Documentation
template<typename T > bool RSJ::threadsafe_queue< T >::empty () const inline
Definition at line 135 of file Utilities.h.
References RSJ::threadsafe_queue< T >::empty().
Referenced by RSJ::threadsafe_queue< T >::empty(), RSJ::threadsafe_queue< T >::NotifyOther(), RSJ::threadsafe_queue< T >::push(), RSJ::threadsafe_queue< T >::try_pop(), and RSJ::threadsafe_queue< T >::wait_and_pop().
template<typename T > void RSJ::threadsafe_queue< T >::NotifyOther () inline
Definition at line 89 of file Utilities.h.
References RSJ::threadsafe_queue< T >::empty().
template<typename T > void RSJ::threadsafe_queue< T >::push (T new_value) inline
Definition at line 94 of file Utilities.h.
References RSJ::threadsafe_queue< T >::empty().
template<typename T > bool RSJ::threadsafe_queue< T >::try_pop (T & value) inline
Definition at line 116 of file Utilities.h.
References RSJ::threadsafe_queue< T >::empty().
template<typename T > std::shared_ptr<T> RSJ::threadsafe_queue< T >::try_pop () inline
Definition at line 125 of file Utilities.h.
References RSJ::threadsafe_queue< T >::empty().
template<typename T > void RSJ::threadsafe_queue< T >::wait_and_pop (T & value) inline
Definition at line 100 of file Utilities.h.
References RSJ::threadsafe_queue< T >::empty().
template<typename T > std::shared_ptr<T> RSJ::threadsafe_queue< T >::wait_and_pop () inline
Definition at line 107 of file Utilities.h.
References RSJ::threadsafe_queue< T >::empty().
The documentation for this class was generated from the following file:
Q:/Documents/GitHub/MIDI2LR/Source/Utilities/Utilities.h