MIDI2LR: TextButtonAligned Class Reference
TextButtonAligned Class Reference
#include <TextButtonAligned.h>
Public Member Functions
TextButtonAligned (const juce::Justification::Flags alignment)
TextButtonAligned (const juce::String &button_name, const juce::Justification::Flags alignment)
TextButtonAligned (const juce::String &button_name, const juce::String &tool_tip, const juce::Justification::Flags alignment)
void paintButton (juce::Graphics &, bool, bool) override
Private Member Functions
void DrawButtonText (juce::Graphics &g, TextButton &button, bool should_draw_button_as_highlighted, bool should_draw_button_as_down) const
Private Attributes
juce::Justification::Flags alignment_ {juce::Justification::centredLeft}
Constructor & Destructor Documentation
TextButtonAligned() [1/3]
TextButtonAligned::TextButtonAligned (const juce::Justification::Flags alignment) inline explicit
                                                                      : alignment_ {alignment}
   {
   }
TextButtonAligned() [2/3]
TextButtonAligned::TextButtonAligned (const juce::String & button_name, const juce::Justification::Flags alignment) inline
       : juce::TextButton(button_name), alignment_ {alignment}
   {
   }
References TextButtonAligned().
Referenced by TextButtonAligned().
TextButtonAligned() [3/3]
TextButtonAligned::TextButtonAligned (const juce::String & button_name, const juce::String & tool_tip, const juce::Justification::Flags alignment) inline
       : juce::TextButton(button_name, tool_tip), alignment_ {alignment}
   {
   }
References TextButtonAligned().
Referenced by TextButtonAligned().
Member Function Documentation
DrawButtonText()
void TextButtonAligned::DrawButtonText (juce::Graphics & g, TextButton & button, bool should_draw_button_as_highlighted, bool should_draw_button_as_down) const private
{
   /* Based on drawButtonText in LookAndFeel_V2 (V3 doesn't override V2 for this call). Only change
    * in my version is alignment on last line. */
   const auto button_height {button.getHeight()};
   const auto button_width {button.getWidth()};
   const auto font {juce::Component::getLookAndFeel().getTextButtonFont(button, button_height)};
   g.setFont(font);
   g.setColour(button
           .findColour(button.getToggleState() ? juce::TextButton::textColourOnId
                                               : juce::TextButton::textColourOffId)
           .withMultipliedAlpha(button.isEnabled() ? 1.0F : 0.5F));
   const auto y_indent {std::min(4, button.proportionOfHeight(0.3F))}; //-V112
   const auto min_height_width {std::min(button_height, button_width)};
   MIDI2LR_ASSUME(min_height_width >= 0);
   const auto corner_size {min_height_width / 2};
   MIDI2LR_ASSUME(corner_size >= 0);
   const auto font_height {gsl::narrow_cast<int>(font.getHeight() * 0.6F + 0.5F)};
   const auto left_indent {
       std::min(font_height, 2 + corner_size / (button.isConnectedOnLeft() ? 4 : 2))}; //-V112
   const auto right_indent {
       std::min(font_height, 2 + corner_size / (button.isConnectedOnRight() ? 4 : 2))}; //-V112
   if (const auto text_width {button_width - left_indent - right_indent}; text_width > 0) {
      g.drawFittedText(button.getButtonText(), left_indent, y_indent, text_width,
          button_height - y_indent * 2, alignment_, 2);
   }
}
paintButton()
void TextButtonAligned::paintButton (juce::Graphics & g, bool should_draw_button_as_highlighted, bool should_draw_button_as_down) override
{
   /* from TextButton.cpp: only change is second call from lf:: to TextButtonAligned:: */
#pragma warning(suppress : 26812)
   juce::Component::getLookAndFeel().drawButtonBackground(g, *this,
       juce::Component::findColour(juce::Button::getToggleState()
                                       ? juce::TextButton::ColourIds::buttonOnColourId
                                       : juce::TextButton::ColourIds::buttonColourId),
       should_draw_button_as_highlighted, should_draw_button_as_down);
   /* the following normally calls lf.drawButtonText, hijacking the call for specific formatting */
   DrawButtonText(g, *this, should_draw_button_as_highlighted, should_draw_button_as_down);
}
Member Data Documentation
alignment_
juce::Justification::Flags TextButtonAligned::alignment_ {juce::Justification::centredLeft} private
{juce::Justification::centredLeft};
The documentation for this class was generated from the following files:
C:/Users/rsjaf/source/repos/MIDI2LR/src/application/TextButtonAligned.h
C:/Users/rsjaf/source/repos/MIDI2LR/src/application/TextButtonAligned.cpp