MIDI2LR: MainContentComponent Class Reference
MainContentComponent Class Reference final
#include <MainComponent.h>
Public Member Functions
MainContentComponent (const CommandSet &command_set, Profile &profile, ProfileManager &profile_manager, SettingsManager &settings_manager)
MainContentComponent (const MainContentComponent &other)=delete
MainContentComponent (MainContentComponent &&other)=delete
~MainContentComponent ()=default
void Init (std::weak_ptr< LrIpcOut > &&lr_ipc_out, std::shared_ptr< MidiReceiver > midi_receiver, std::shared_ptr< MidiSender > midi_sender)
MainContentComponent & operator= (const MainContentComponent &other)=delete
MainContentComponent & operator= (MainContentComponent &&other)=delete
void SaveProfile ()
Public Member Functions inherited from ResizableLayout
ResizableLayout (juce::Component *owner)
~ResizableLayout ()
void activateLayout (bool isActive=true) noexcept
void addToLayout (juce::Component *component, const juce::Point< int > &topLeft, const juce::Point< int > &bottomRight=juce::Point< int >{-1, -1}, Style style=styleStretch)
void recalculateLayout () const
void removeFromLayout (juce::Component *component) noexcept
void updateLayoutFor (juce::Component *component) noexcept
Public Member Functions inherited from ResizableChild
ResizableChild () noexcept
virtual ~ResizableChild ()=default
int getMaximumHeight () const noexcept
int getMaximumWidth () const noexcept
int getMinimumHeight () const noexcept
int getMinimumWidth () const noexcept
void setMaximumHeight (int maximumHeight) noexcept
void setMaximumSize (int maximumWidth, int maximumHeight) noexcept
void setMaximumWidth (int maximumWidth) noexcept
void setMinimumHeight (int minimumHeight) noexcept
void setMinimumSize (int minimumWidth, int minimumHeight) noexcept
void setMinimumWidth (int minimumWidth) noexcept
void setSizeLimits (int minimumWidth, int minimumHeight, int maximumWidth, int maximumHeight) noexcept
Private Member Functions
void buttonClicked (juce::Button *button) override
void handleAsyncUpdate () override
void LrIpcOutCallback (bool, bool)
void MidiCmdCallback (rsj::MidiMessage)
void paint (juce::Graphics &) override
void ProfileChanged (juce::XmlElement *xml_element, const juce::String &file_name)
void SetLabelSettings (juce::Label &label_to_set)
void timerCallback () override
Private Attributes
juce::Label command_label_ {"Command", ""}
CommandTable command_table_ {"Table", nullptr}
CommandTableModel command_table_model_
juce::Label connection_label_ {"Connection", juce::translate("Not connected to LR")}
juce::TextButton disconnect_button_ {juce::translate("Halt sending to Lightroom")}
juce::String last_command_
juce::TextButton load_button_ {juce::translate("Load")}
std::weak_ptr< LrIpcOut > lr_ipc_out_
std::shared_ptr< MidiReceiver > midi_receiver_ {nullptr}
std::shared_ptr< MidiSender > midi_sender_ {nullptr}
Profile & profile_
ProfileManager & profile_manager_
juce::Label profile_name_label_ {"ProfileNameLabel", ""}
juce::TextButton remove_row_button_ {juce::translate("Clear ALL rows")}
juce::TextButton rescan_button_ {juce::translate("Rescan MIDI devices")}
size_t row_to_select_ {0}
juce::TextButton save_button_ {juce::translate("Save")}
juce::TextButton settings_button_ {juce::translate("Settings")}
std::unique_ptr< juce::DialogWindow > settings_dialog_
SettingsManager & settings_manager_
juce::Label title_label_ {"Title", "MIDI2LR"}
juce::DropShadowEffect title_shadow_
juce::Label version_label_
Additional Inherited Members
Public Types inherited from ResizableLayout
enum { anchorUnit = 100 }
enum Style { styleStretch, styleFixedAspect }
Static Public Member Functions inherited from ResizableLayout
static juce::Rectangle< int > calcBoundsOfChildren (juce::Component *parent) noexcept
Constructor & Destructor Documentation
MainContentComponent() [1/3]
MainContentComponent::MainContentComponent (const CommandSet & command_set, Profile & profile, ProfileManager & profile_manager, SettingsManager & settings_manager)
                                                                             : ResizableLayout {
    this
 }
 , profile_(profile), command_table_model_(command_set, profile), profile_manager_(profile_manager),
     settings_manager_(settings_manager)
 {
    // Set the component size
    setSize(kMainWidth, kMainHeight);
 }
 catch (const std::exception& e)
 {
    rsj::ExceptionResponse(typeid(this).name(), __func__, e);
    throw;
 }
~MainContentComponent()
MainContentComponent::~MainContentComponent () default
MainContentComponent() [2/3]
MainContentComponent::MainContentComponent (const MainContentComponent & other) delete
MainContentComponent() [3/3]
MainContentComponent::MainContentComponent (MainContentComponent && other) delete
Member Function Documentation
buttonClicked()
void MainContentComponent::buttonClicked (juce::Button * button) override private
 { //-V2009 overridden method
    using namespace std::literals::string_literals;
    try {
       if (button == &rescan_button_) {
          // Re-enumerate MIDI IN and OUT devices
          if (midi_receiver_)
             midi_receiver_->RescanDevices();
          if (midi_sender_)
             midi_sender_->RescanDevices();
          // Send new CC parameters to MIDI Out devices
          if (const auto ptr = lr_ipc_out_.lock())
             ptr->SendCommand("FullRefresh 1\n"s);
       }
       else if (button == &remove_row_button_) {
          if (command_table_.getNumRows() > 0) {
             profile_.RemoveAllRows();
             // command_table_model_.removeRow(static_cast<size_t>(command_table_.getSelectedRow()));
             command_table_.updateContent();
          }
       }
       else if (button == &disconnect_button_) {
          if (const auto ptr = lr_ipc_out_.lock()) {
             if (disconnect_button_.getToggleState()) {
                ptr->Stop();
                rsj::Log("Sending halted");
             }
             else {
                ptr->Restart();
                rsj::Log("Sending restarted");
             }
          }
       }
       else if (button == &save_button_) {
          juce::File profile_directory;
          profile_directory = settings_manager_.GetProfileDirectory();
          if (!profile_directory.exists())
             profile_directory = juce::File::getSpecialLocation(juce::File::userDocumentsDirectory);
          juce::FileChooser chooser{
              juce::translate("Save profile"), profile_directory, "*.xml", true};
          if (chooser.browseForFileToSave(true)) {
             const auto selected_file = chooser.getResult().withFileExtension("xml");
             profile_.ToXmlFile(selected_file);
          }
       }
       else if (button == &load_button_) {
          if (profile_.ProfileUnsaved()) {
             const auto result = juce::NativeMessageBox::showYesNoBox(juce::AlertWindow::WarningIcon,
                 juce::translate("MIDI2LR profiles"),
                 juce::translate(
                     "Profile changed. Do you want to save it before loading a new Profile?"));
             if (result)
                SaveProfile();
          }
          juce::File profile_directory;
          profile_directory = settings_manager_.GetProfileDirectory();
          if (!profile_directory.exists())
             profile_directory = juce::File::getSpecialLocation(juce::File::userDocumentsDirectory);
          juce::FileChooser chooser{
              juce::translate("Open profile"), profile_directory, "*.xml", true};
          if (chooser.browseForFileToOpen()) {
             if (const auto parsed{juce::XmlDocument::parse(chooser.getResult())}) {
                std::unique_ptr<juce::XmlElement> xml_element{parsed};
                const auto new_profile = chooser.getResult();
                auto command =
                    "ChangedToFullPath "s + new_profile.getFullPathName().toStdString() + '\n';
                if (const auto ptr = lr_ipc_out_.lock())
                   ptr->SendCommand(std::move(command));
                profile_name_label_.setText(
                    new_profile.getFileName(), juce::NotificationType::dontSendNotification);
                profile_.FromXml(xml_element.get());
                command_table_.updateContent();
                command_table_.repaint();
             }
             else {
                rsj::Log("Unable to load profile " + chooser.getResult().getFullPathName());
             }
          }
       }
       else if (button == &settings_button_) {
          juce::DialogWindow::LaunchOptions dialog_options;
          dialog_options.dialogTitle = juce::translate("Settings");
          // create new object
          auto component = std::make_unique<SettingsComponent>(settings_manager_);
          component->Init();
          dialog_options.content.setOwned(component.release());
          dialog_options.content->setSize(400, 300);
          dialog_options.escapeKeyTriggersCloseButton = true;
          dialog_options.useNativeTitleBar = false;
          settings_dialog_.reset(dialog_options.create());
          settings_dialog_->setVisible(true);
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
handleAsyncUpdate()
void MainContentComponent::handleAsyncUpdate () override private
 {
    try {
       // Update the last command label and set its color to green
       command_label_.setText(last_command_, juce::NotificationType::dontSendNotification);
       command_label_.setColour(juce::Label::backgroundColourId, juce::Colours::greenyellow);
       startTimer(1000);
       // Update the command table to add and/or select row corresponding to midi command
       command_table_.updateContent();
       command_table_.selectRow(gsl::narrow_cast<int>(row_to_select_));
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Init()
void MainContentComponent::Init (std::weak_ptr< LrIpcOut > && lr_ipc_out, std::shared_ptr< MidiReceiver > midi_receiver, std::shared_ptr< MidiSender > midi_sender)
 {
    try {
       lr_ipc_out_ = std::move(lr_ipc_out);
       midi_receiver_ = std::move(midi_receiver);
       midi_sender_ = std::move(midi_sender);
       if (midi_receiver_)
          // Add ourselves as a listener for MIDI commands
          midi_receiver_->AddCallback(this, &MainContentComponent::MidiCmdCallback);
       if (const auto ptr = lr_ipc_out_.lock())
          // Add ourselves as a listener for LR_IPC_OUT events
          ptr->AddCallback(this, &MainContentComponent::LrIpcOutCallback);
       // Add ourselves as a listener for profile changes
       profile_manager_.AddCallback(this, &MainContentComponent::ProfileChanged);
       // Main title
       title_label_.setFont(juce::Font{36.f, juce::Font::bold});
       title_label_.setEditable(false);
       title_label_.setColour(juce::Label::textColourId, juce::Colours::darkgrey);
       title_label_.setComponentEffect(&title_shadow_);
       title_label_.setBounds(kMainLeft, 10, kFullWidth, 30);
       addToLayout(&title_label_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(title_label_);
       // Version label
       SetLabelSettings(version_label_);
       version_label_.setBounds(kMainLeft, 40, kFullWidth, 10);
       addToLayout(&version_label_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(version_label_);
       // Connection status
       connection_label_.setFont(juce::Font{12.f, juce::Font::bold});
       connection_label_.setEditable(false);
       connection_label_.setColour(juce::Label::backgroundColourId, juce::Colours::red);
       connection_label_.setColour(juce::Label::textColourId, juce::Colours::black);
       connection_label_.setJustificationType(juce::Justification::centred);
       connection_label_.setBounds(200, 15, kConnectionLabelWidth, kStandardHeight);
       addToLayout(&connection_label_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(connection_label_);
       // Load button
       load_button_.addListener(this);
       load_button_.setBounds(kFirstButtonX, 60, kButtonWidth, kStandardHeight);
       addToLayout(&load_button_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(load_button_);
       // Save button
       save_button_.addListener(this);
       save_button_.setBounds(kSecondButtonX, 60, kButtonWidth, kStandardHeight);
       addToLayout(&save_button_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(save_button_);
       // Settings button
       settings_button_.addListener(this);
       settings_button_.setBounds(kThirdButtonX, 60, kButtonWidth, kStandardHeight);
       addToLayout(&settings_button_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(settings_button_);
       // Command Table
       command_table_.setModel(&command_table_model_);
       command_table_.setBounds(kMainLeft, 100, kFullWidth, kCommandTableHeight);
       addToLayout(&command_table_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(command_table_);
       // Profile name label
       SetLabelSettings(profile_name_label_);
       profile_name_label_.setBounds(kMainLeft, kProfileNameY, kLabelWidth, kStandardHeight);
       addToLayout(&profile_name_label_, anchorMidLeft, anchorMidRight);
       profile_name_label_.setJustificationType(juce::Justification::centred);
       addAndMakeVisible(profile_name_label_);
       // Last MIDI command
       command_label_.setFont(juce::Font{12.f, juce::Font::bold});
       command_label_.setEditable(false);
       command_label_.setColour(juce::Label::textColourId, juce::Colours::darkgrey);
       command_label_.setBounds(kCommandLabelX, kCommandLabelY, kLabelWidth, kStandardHeight);
       addToLayout(&command_label_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(command_label_);
       // Remove row button
       remove_row_button_.addListener(this);
       remove_row_button_.setBounds(kMainLeft, kRemoveRowY, kFullWidth, kStandardHeight);
       addToLayout(&remove_row_button_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(remove_row_button_);
       // Rescan MIDI button
       rescan_button_.addListener(this);
       rescan_button_.setBounds(kMainLeft, kRescanY, kFullWidth, kStandardHeight);
       addToLayout(&rescan_button_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(rescan_button_);
       // Disconnect button
       disconnect_button_.addListener(this);
       disconnect_button_.setBounds(kMainLeft, kDisconnect, kFullWidth, kStandardHeight);
       disconnect_button_.setClickingTogglesState(true);
       addToLayout(&disconnect_button_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(disconnect_button_);
       // Try to load a default.xml if the user has not set a profile directory
       if (settings_manager_.GetProfileDirectory().isEmpty()) {
          const auto filename = rsj::AppDataFilePath(kDefaultsFile);
          const auto default_profile = juce::File(filename.data());
          if (const auto parsed{juce::XmlDocument::parse(default_profile)}) {
             std::unique_ptr<juce::XmlElement> xml_element{parsed};
             profile_.FromXml(xml_element.get());
             command_table_.updateContent();
          }
       }
       else
          // otherwise use the last profile from the profile directory
          profile_manager_.SwitchToProfile(0);
       // turn it on
       activateLayout();
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), rsj::NumToChars(), and ProfileManager::SwitchToProfile().
LrIpcOutCallback()
void MainContentComponent::LrIpcOutCallback (bool connected, bool sending_blocked) private
 {
    try {
       if (connected) {
          if (sending_blocked) {
             connection_label_.setText(
                 juce::translate("Sending halted"), juce::NotificationType::dontSendNotification);
             connection_label_.setColour(juce::Label::backgroundColourId, juce::Colours::yellow);
          }
          else {
             connection_label_.setText(
                 juce::translate("Connected to LR"), juce::NotificationType::dontSendNotification);
             connection_label_.setColour(
                 juce::Label::backgroundColourId, juce::Colours::greenyellow);
          }
       }
       else {
          connection_label_.setText(
              juce::translate("Not connected to LR"), juce::NotificationType::dontSendNotification);
          connection_label_.setColour(juce::Label::backgroundColourId, juce::Colours::red);
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
MidiCmdCallback()
void MainContentComponent::MidiCmdCallback (rsj::MidiMessage mm) private
 {
    try {
       // Display the CC parameters and add/highlight row in table corresponding to the CC
       auto mt{rsj::MsgIdEnum::kCc};
       juce::String command_type{"CC"};
       switch (mm.message_type_byte) { // this is needed because mapping uses custom structure
       case rsj::kCcFlag:              // this is default for mt and commandtype
          break;
       case rsj::kNoteOnFlag:
          mt = rsj::MsgIdEnum::kNote;
          command_type = "NOTE ON";
          break;
       case rsj::kNoteOffFlag:
          mt = rsj::MsgIdEnum::kNote;
          command_type = "NOTE OFF";
          break;
       case rsj::kPwFlag:
          mt = rsj::MsgIdEnum::kPitchBend;
          command_type = "PITCHBEND";
          break;
       default: // shouldn't receive any messages note categorized above
          Ensures(0);
       }
       mm.channel++; // used to 1-based channel numbers
       last_command_ = juce::String(mm.channel) + ": " + command_type + juce::String(mm.number)
                       + " [" + juce::String(mm.value) + "]";
       const rsj::MidiMessageId msg{mm.channel, mm.number, mt};
       profile_.AddRowUnmapped(msg);
       row_to_select_ = gsl::narrow_cast<size_t>(profile_.GetRowForMessage(msg));
       triggerAsyncUpdate();
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
operator=() [1/2]
MainContentComponent& MainContentComponent::operator= (const MainContentComponent & other) delete
operator=() [2/2]
MainContentComponent& MainContentComponent::operator= (MainContentComponent && other) delete
paint()
void MainContentComponent::paint (juce::Graphics & g) override private
 { //-V2009 overridden method
    try {
       g.fillAll(juce::Colours::white);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
ProfileChanged()
void MainContentComponent::ProfileChanged (juce::XmlElement * xml_element, const juce::String & file_name) private
 { //-V2009 overridden method
    using namespace std::literals::string_literals;
    try {
       {
          const juce::MessageManagerLock mm_lock;
          profile_.FromXml(xml_element);
          command_table_.updateContent();
          command_table_.repaint();
          profile_name_label_.setText(file_name, juce::NotificationType::dontSendNotification);
       }
       // Send new CC parameters to MIDI Out devices
       if (const auto ptr = lr_ipc_out_.lock())
          ptr->SendCommand("FullRefresh 1\n"s);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
SaveProfile()
void MainContentComponent::SaveProfile ()
 {
    try {
       buttonClicked(&save_button_);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
SetLabelSettings()
void MainContentComponent::SetLabelSettings (juce::Label & label_to_set) private
 {
    try {
       label_to_set.setFont(juce::Font{12.f, juce::Font::bold});
       label_to_set.setEditable(false);
       label_to_set.setColour(juce::Label::textColourId, juce::Colours::darkgrey);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
timerCallback()
void MainContentComponent::timerCallback () override private
 {
    try {
       // reset the command label's background to white
       command_label_.setColour(juce::Label::backgroundColourId, juce::Colours::white);
       juce::Timer::stopTimer();
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Member Data Documentation
command_label_
juce::Label MainContentComponent::command_label_ {"Command", ""} private
command_table_
CommandTable MainContentComponent::command_table_ {"Table", nullptr} private
command_table_model_
CommandTableModel MainContentComponent::command_table_model_ private
connection_label_
juce::Label MainContentComponent::connection_label_ {"Connection", juce::translate("Not connected to LR")} private
disconnect_button_
juce::TextButton MainContentComponent::disconnect_button_ {juce::translate("Halt sending to Lightroom")} private
last_command_
juce::String MainContentComponent::last_command_ private
load_button_
juce::TextButton MainContentComponent::load_button_ {juce::translate("Load")} private
lr_ipc_out_
std::weak_ptr<LrIpcOut> MainContentComponent::lr_ipc_out_ private
midi_receiver_
std::shared_ptr<MidiReceiver> MainContentComponent::midi_receiver_ {nullptr} private
midi_sender_
std::shared_ptr<MidiSender> MainContentComponent::midi_sender_ {nullptr} private
profile_
Profile& MainContentComponent::profile_ private
profile_manager_
ProfileManager& MainContentComponent::profile_manager_ private
profile_name_label_
juce::Label MainContentComponent::profile_name_label_ {"ProfileNameLabel", ""} private
remove_row_button_
juce::TextButton MainContentComponent::remove_row_button_ {juce::translate("Clear ALL rows")} private
rescan_button_
juce::TextButton MainContentComponent::rescan_button_ {juce::translate("Rescan MIDI devices")} private
row_to_select_
size_t MainContentComponent::row_to_select_ {0} private
save_button_
juce::TextButton MainContentComponent::save_button_ {juce::translate("Save")} private
settings_button_
juce::TextButton MainContentComponent::settings_button_ {juce::translate("Settings")} private
settings_dialog_
std::unique_ptr<juce::DialogWindow> MainContentComponent::settings_dialog_ private
settings_manager_
SettingsManager& MainContentComponent::settings_manager_ private
title_label_
juce::Label MainContentComponent::title_label_ {"Title", "MIDI2LR"} private
title_shadow_
juce::DropShadowEffect MainContentComponent::title_shadow_ private
version_label_
juce::Label MainContentComponent::version_label_ private
Initial value:
{
       "Version", juce::translate("Version ") + juce::String{ProjectInfo::versionString}}
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/MainComponent.h
D:/Users/Rory/source/repos/MIDI2LR/Source/MainComponent.cpp