MIDI2LR: mir::RecursiveReadWriteMutex Class Reference
mir::RecursiveReadWriteMutex Class Reference
#include <recursive_read_write_mutex.h>
Public Member Functions
void read_lock ()
void read_unlock ()
void write_lock ()
void write_unlock ()
Detailed Description
a recursive read-write mutex. Note that a write lock can be acquired if no other threads have a read lock.
Definition at line 31 of file recursive_read_write_mutex.h.
Member Function Documentation
void mir::RecursiveReadWriteMutex::read_lock ()
Definition at line 25 of file recursive_read_write_mutex.cpp.
Referenced by mir::RecursiveReadLock::RecursiveReadLock().
void mir::RecursiveReadWriteMutex::read_unlock ()
Definition at line 49 of file recursive_read_write_mutex.cpp.
Referenced by mir::RecursiveReadLock::~RecursiveReadLock().
void mir::RecursiveReadWriteMutex::write_lock ()
Definition at line 64 of file recursive_read_write_mutex.cpp.
Referenced by mir::RecursiveWriteLock::RecursiveWriteLock().
void mir::RecursiveReadWriteMutex::write_unlock ()
Definition at line 84 of file recursive_read_write_mutex.cpp.
Referenced by mir::RecursiveWriteLock::~RecursiveWriteLock().
The documentation for this class was generated from the following files:
Q:/Documents/GitHub/MIDI2LR/Source/Utilities/recursive_read_write_mutex.h
Q:/Documents/GitHub/MIDI2LR/Source/Utilities/recursive_read_write_mutex.cpp