MIDI2LR: Profile Class Reference
Profile Class Reference
#include <Profile.h>
Public Member Functions
Profile (const CommandSet &command_set) noexcept
void AddCommandForMessage (size_t command, rsj::MidiMessageId message)
void AddRowMapped (const std::string &command, const rsj::MidiMessageId &message)
void AddRowUnmapped (const rsj::MidiMessageId &message)
bool CommandHasAssociatedMessage (const std::string &command) const
void FromXml (const juce::XmlElement *root)
const std::string & GetCommandForMessage (rsj::MidiMessageId message) const
rsj::MidiMessageId GetMessageForNumber (size_t num) const
std::vector< rsj::MidiMessageId > GetMessagesForCommand (const std::string &command) const
int GetRowForMessage (rsj::MidiMessageId message) const
bool MessageExistsInMap (rsj::MidiMessageId message) const
bool ProfileUnsaved () const
void RemoveAllRows ()
void RemoveMessage (const rsj::MidiMessageId &message)
void RemoveRow (size_t row)
void RemoveUnassignedMessages ()
void Resort (std::pair< int, bool > new_order)
size_t Size () const
void ToXmlFile (const juce::File &file)
Private Member Functions
void AddCommandForMessageI (size_t command, const rsj::MidiMessageId &message)
const std::string & GetCommandForMessageI (rsj::MidiMessageId message) const
rsj::MidiMessageId GetMessageForNumberI (size_t num) const
bool MessageExistsInMapI (rsj::MidiMessageId message) const
void SortI ()
Private Attributes
const CommandSet & command_set_
std::multimap< std::string, rsj::MidiMessageId > command_string_map_ {}
std::vector< rsj::MidiMessageId > command_table_ {}
std::pair< int, bool > current_sort_ {2, true}
std::unordered_map< rsj::MidiMessageId, std::string > message_map_ {}
std::shared_mutex mutex_
bool profile_unsaved_ {false}
std::unordered_map< rsj::MidiMessageId, std::string > saved_map_ {}
Constructor & Destructor Documentation
Profile()
Profile::Profile (const CommandSet & command_set) inline explicit noexcept
 : command_set_ {command_set} {}
References command_set_.
Member Function Documentation
AddCommandForMessage()
void Profile::AddCommandForMessage (size_t command, rsj::MidiMessageId message) inline
 {
    auto guard {std::unique_lock {mutex_}};
    AddCommandForMessageI(command, message);
 }
References AddCommandForMessageI().
AddCommandForMessageI()
void Profile::AddCommandForMessageI (size_t command, const rsj::MidiMessageId & message) private
 {
    try {
       if (command < command_set_.CommandAbbrevSize()) {
          const auto& cmd_abbreviation {command_set_.CommandAbbrevAt(command)};
          message_map_[message] = cmd_abbreviation;
          command_string_map_.emplace(cmd_abbreviation, message);
          SortI();
          profile_unsaved_ = true;
       }
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References profile_unsaved_, and SortI().
Referenced by AddCommandForMessage().
AddRowMapped()
void Profile::AddRowMapped (const std::string & command, const rsj::MidiMessageId & message)
 {
    try {
       auto guard {std::unique_lock {mutex_}};
       if (!MessageExistsInMapI(message)) {
          if (!command_set_.CommandTextIndex(command)) {
             message_map_[message] = CommandSet::kUnassigned;
             command_string_map_.emplace(CommandSet::kUnassigned, message);
          }
          else {
             message_map_[message] = command;
             command_string_map_.emplace(command, message);
          }
          command_table_.push_back(message);
          SortI();
          profile_unsaved_ = true;
       }
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References command_set_, CommandSet::CommandTextIndex(), MessageExistsInMapI(), profile_unsaved_, and SortI().
AddRowUnmapped()
void Profile::AddRowUnmapped (const rsj::MidiMessageId & message)
 {
    try {
       auto guard {std::unique_lock {mutex_}};
       if (!MessageExistsInMapI(message)) {
          AddCommandForMessageI(0, message); /* add an entry for 'no command' */
          command_table_.push_back(message);
          SortI();
          profile_unsaved_ = true;
       }
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References MessageExistsInMapI(), profile_unsaved_, and SortI().
CommandHasAssociatedMessage()
bool Profile::CommandHasAssociatedMessage (const std::string & command) const inline
 {
    auto guard {std::shared_lock {mutex_}};
    return command_string_map_.find(command) != command_string_map_.end();
 }
FromXml()
void Profile::FromXml (const juce::XmlElement * root)
 {
    /* external use only, but will either use external versions of Profile calls to lock individual
     * accesses or manually lock any internal calls instead of using mutex for entire method */
    try {
       if (!root || root->getTagName().compare("settings") != 0)
          return;
       RemoveAllRows();
       const auto* setting {root->getFirstChildElement()};
       while (setting) {
          if (setting->hasAttribute("controller")) {
             const rsj::MidiMessageId message {setting->getIntAttribute("channel"),
                 setting->getIntAttribute("controller"), rsj::MessageType::kCc};
             AddRowMapped(setting->getStringAttribute("command_string").toStdString(), message);
          }
          else if (setting->hasAttribute("note")) {
             const rsj::MidiMessageId note {setting->getIntAttribute("channel"),
                 setting->getIntAttribute("note"), rsj::MessageType::kNoteOn};
             AddRowMapped(setting->getStringAttribute("command_string").toStdString(), note);
          }
          else if (setting->hasAttribute("pitchbend")) {
             const rsj::MidiMessageId pb {
                 setting->getIntAttribute("channel"), 0, rsj::MessageType::kPw};
             AddRowMapped(setting->getStringAttribute("command_string").toStdString(), pb);
          }
          setting = setting->getNextElement();
       }
       auto guard {std::unique_lock {mutex_}};
       SortI();
       saved_map_ = message_map_;
       profile_unsaved_ = false;
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References profile_unsaved_, RemoveAllRows(), and SortI().
GetCommandForMessage()
const std::string & Profile::GetCommandForMessage (rsj::MidiMessageId message) const inline
 {
    auto guard {std::shared_lock {mutex_}};
    return GetCommandForMessageI(message);
 }
References GetCommandForMessageI().
Referenced by LrIpcOut::MidiCmdCallback().
GetCommandForMessageI()
const std::string & Profile::GetCommandForMessageI (rsj::MidiMessageId message) const inline private
 {
    return message_map_.at(message);
 }
Referenced by GetCommandForMessage(), and SortI().
GetMessageForNumber()
rsj::MidiMessageId Profile::GetMessageForNumber (size_t num) const inline
 {
    auto guard {std::shared_lock {mutex_}};
    return GetMessageForNumberI(num);
 }
References GetMessageForNumberI().
GetMessageForNumberI()
rsj::MidiMessageId Profile::GetMessageForNumberI (size_t num) const inline private
 {
    return command_table_.at(num);
 }
Referenced by GetMessageForNumber(), and RemoveRow().
GetMessagesForCommand()
std::vector< rsj::MidiMessageId > Profile::GetMessagesForCommand (const std::string & command) const
 {
    try {
       auto guard {std::shared_lock {mutex_}};
       std::vector<rsj::MidiMessageId> mm;
       const auto [begin, end] {command_string_map_.equal_range(command)};
       std::for_each(begin, end, [&mm](auto&& x) { mm.push_back(x.second); });
       return mm;
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
GetRowForMessage()
int Profile::GetRowForMessage (rsj::MidiMessageId message) const inline
 {
    auto guard {std::shared_lock {mutex_}};
    return gsl::narrow_cast<int>(
        std::find(command_table_.begin(), command_table_.end(), message) - command_table_.begin());
 }
MessageExistsInMap()
bool Profile::MessageExistsInMap (rsj::MidiMessageId message) const inline
 {
    auto guard {std::shared_lock {mutex_}};
    return MessageExistsInMapI(message);
 }
References MessageExistsInMapI().
Referenced by LrIpcOut::MidiCmdCallback().
MessageExistsInMapI()
bool Profile::MessageExistsInMapI (rsj::MidiMessageId message) const inline private
 {
    return message_map_.find(message) != message_map_.end();
 }
Referenced by AddRowMapped(), AddRowUnmapped(), and MessageExistsInMap().
ProfileUnsaved()
bool Profile::ProfileUnsaved () const inline
 {
    auto guard {std::shared_lock {mutex_}};
    return profile_unsaved_ && !command_table_.empty() && saved_map_ != message_map_;
 }
RemoveAllRows()
void Profile::RemoveAllRows ()
 {
    try {
       auto guard {std::unique_lock {mutex_}};
       command_string_map_.clear();
       command_table_.clear();
       message_map_.clear();
       /* no reason for profile_unsaved_ here. nothing to save */
       profile_unsaved_ = false;
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References profile_unsaved_.
Referenced by FromXml().
RemoveMessage()
void Profile::RemoveMessage (const rsj::MidiMessageId & message)
 { /* do not erase command table as that will cause disappearing messages when go from Unassigned to
      assigned */
    try {
       auto guard {std::unique_lock {mutex_}};
       command_string_map_.erase(message_map_.at(message));
       message_map_.erase(message);
       profile_unsaved_ = true;
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References profile_unsaved_.
Referenced by CommandMenu::clicked().
RemoveRow()
void Profile::RemoveRow (size_t row)
 {
    try {
       auto guard {std::unique_lock {mutex_}};
       const auto msg {GetMessageForNumberI(row)};
       command_string_map_.erase(message_map_.at(msg));
       command_table_.erase(command_table_.cbegin() + row);
       message_map_.erase(msg);
       profile_unsaved_ = true;
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References GetMessageForNumberI(), and profile_unsaved_.
Referenced by CommandTableModel::RemoveRow().
RemoveUnassignedMessages()
void Profile::RemoveUnassignedMessages ()
 {
    try {
       auto guard {std::unique_lock {mutex_}};
       auto it {command_string_map_.find("Unassigned")};
       if (it != command_string_map_.end()) {
          profile_unsaved_ = true;
          do {
             message_map_.erase(it->second);
             command_table_.erase(
                 std::remove(command_table_.begin(), command_table_.end(), it->second),
                 command_table_.end());
             command_string_map_.erase(it);
             it = command_string_map_.find("Unassigned");
          } while (it != command_string_map_.end());
       }
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References profile_unsaved_.
Resort()
void Profile::Resort (std::pair< int, bool > new_order)
 {
    try {
       auto guard {std::unique_lock {mutex_}};
       current_sort_ = new_order;
       SortI();
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References SortI().
Size()
size_t Profile::Size () const inline
 {
    auto guard {std::shared_lock {mutex_}};
    return command_table_.size();
 }
SortI()
void Profile::SortI () private
 {
    try {
       const auto msg_idx {[this](const rsj::MidiMessageId a) {
          return command_set_.CommandTextIndex(GetCommandForMessageI(a));
       }};
       const auto msg_sort {[&msg_idx](const rsj::MidiMessageId a, const rsj::MidiMessageId b) {
          return msg_idx(a) < msg_idx(b);
       }};
       if (current_sort_.first == 1)
          if (current_sort_.second)
             std::sort(command_table_.begin(), command_table_.end());
          else
             std::sort(command_table_.rbegin(), command_table_.rend());
       else if (current_sort_.second)
          std::sort(command_table_.begin(), command_table_.end(), msg_sort);
       else
          std::sort(command_table_.rbegin(), command_table_.rend(), msg_sort);
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References rsj::AppLogFilePath(), command_set_, CommandSet::CommandTextIndex(), and GetCommandForMessageI().
Referenced by AddCommandForMessageI(), AddRowMapped(), AddRowUnmapped(), FromXml(), and Resort().
ToXmlFile()
void Profile::ToXmlFile (const juce::File & file)
 {
    try {
       auto guard {std::shared_lock {mutex_}};
       /* don't bother if map is empty */
       if (!message_map_.empty()) {
          /* save the contents of the command map to an xml file */
          juce::XmlElement root {"settings"};
          for (const auto& [msg_id, cmd_str] : message_map_) {
             auto setting {std::make_unique<juce::XmlElement>("setting")};
             setting->setAttribute("channel", msg_id.channel);
             switch (msg_id.msg_id_type) {
             case rsj::MessageType::kNoteOn:
                setting->setAttribute("note", msg_id.control_number);
                break;
             case rsj::MessageType::kCc:
                setting->setAttribute("controller", msg_id.control_number);
                break;
             case rsj::MessageType::kPw:
                setting->setAttribute("pitchbend", 0);
                break;
             case rsj::MessageType::kChanPressure:
             case rsj::MessageType::kKeyPressure:
             case rsj::MessageType::kNoteOff:
             case rsj::MessageType::kPgmChange:
             case rsj::MessageType::kSystem:
                /* can't handle other types */
                continue;
             }
             setting->setAttribute("command_string", cmd_str);
             root.addChildElement(setting.release());
          }
          if (!root.writeTo(file)) {
             /* Give feedback if file-save doesn't work */
             const auto& p {file.getFullPathName()};
             rsj::LogAndAlertError(
                 juce::translate("Unable to save file. Choose a different location and try again.")
                     + ' ' + p,
                 "Unable to save file. Choose a different location and try again. " + p);
          }
          saved_map_ = message_map_;
          profile_unsaved_ = false;
       }
    }
    catch (const std::exception& e) {
       MIDI2LR_E_RESPONSE;
       throw;
    }
 }
References profile_unsaved_.
Member Data Documentation
command_set_
const CommandSet& Profile::command_set_ private
Referenced by Profile(), AddRowMapped(), and SortI().
command_string_map_
std::multimap<std::string, rsj::MidiMessageId> Profile::command_string_map_ {} private
command_table_
std::vector<rsj::MidiMessageId> Profile::command_table_ {} private
current_sort_
std::pair<int, bool> Profile::current_sort_ {2, true} private
message_map_
std::unordered_map<rsj::MidiMessageId, std::string> Profile::message_map_ {} private
mutex_
std::shared_mutex Profile::mutex_ mutable private
profile_unsaved_
bool Profile::profile_unsaved_ {false} private
Referenced by AddCommandForMessageI(), AddRowMapped(), AddRowUnmapped(), FromXml(), RemoveAllRows(), RemoveMessage(), RemoveRow(), RemoveUnassignedMessages(), and ToXmlFile().
saved_map_
std::unordered_map<rsj::MidiMessageId, std::string> Profile::saved_map_ {} private
The documentation for this class was generated from the following files:
C:/Users/rsjaf/source/repos/MIDI2LR/src/application/Profile.h
C:/Users/rsjaf/source/repos/MIDI2LR/src/application/Profile.cpp