MIDI2LR: ResizableChild Class Reference
ResizableChild Class Reference
#include <ResizableLayout.h>
Public Member Functions
ResizableChild () noexcept
virtual ~ResizableChild ()=default
int getMaximumHeight () const noexcept
int getMaximumWidth () const noexcept
int getMinimumHeight () const noexcept
int getMinimumWidth () const noexcept
virtual void resizeStart () noexcept
void setMaximumHeight (int maximumHeight) noexcept
void setMaximumSize (int maximumWidth, int maximumHeight) noexcept
void setMaximumWidth (int maximumWidth) noexcept
void setMinimumHeight (int minimumHeight) noexcept
void setMinimumSize (int minimumWidth, int minimumHeight) noexcept
void setMinimumWidth (int minimumWidth) noexcept
void setSizeLimits (int minimumWidth, int minimumHeight, int maximumWidth, int maximumHeight) noexcept
Private Attributes
int m_maxH
int m_maxW
int m_minH
int m_minW
Detailed Description
Smoothly repositions and resizes child Components without rounding errors, according to caller provided stretching parameters. Usage: 1) Derive your Component from ResizableLayout 2) Give your Component a well defined default size 3) Add child Components and position them according to how they should appear at the default. 4) For each child Component, also call addToLayout() and specify what portion of the owner's growth or reduction should apply to each corner. 5) At the end of your constructor, call activateLayout() to turn it on 6) If you later manually reposition a control (for example, using a ComponentDragger) call updateLayoutFor() on the control that moved, or if you moved all the controls call updateLayout(). 7) You do not need to override resized() to make this work, all you have to do is lay things out when you create your child Components and add anchors as appropriate. Example struct ContentComponent : Component, ResizableLayout { ContentComponent() : ResizableLayout (this) { for layouts to work you must start at some size place controls in a location that is initially correct. setSize(512, 384); TextButton* b; b = new TextButton ("Juce"); b->setBounds (32, 32, 512-64, 32); stretch to fit the width of the window addToLayout (b, anchorTopLeft, anchorTopRight); addAndMakeVisible (b); b = new TextButton ("One"); b->setBounds (32, 96, 128, 32); take up 1/3 of the width of the window addToLayout (b, Point<int>(0,0), Point<int>(33,0)); addAndMakeVisible (b); turn it on activateLayout(); } }
Constructor & Destructor Documentation
ResizableChild()
ResizableChild::ResizableChild () inline noexcept
References m_maxH, m_maxW, m_minH, and m_minW.
                               :
         m_minW(0), m_maxW(0x3fffffff), m_minH(0), m_maxH(0x3fffffff)
     {}
~ResizableChild()
virtual ResizableChild::~ResizableChild () virtual default
Member Function Documentation
getMaximumHeight()
int ResizableChild::getMaximumHeight () const inline noexcept
References m_maxH.
     {
         return m_maxH;
     }
getMaximumWidth()
int ResizableChild::getMaximumWidth () const inline noexcept
References m_maxW.
     {
         return m_maxW;
     }
getMinimumHeight()
int ResizableChild::getMinimumHeight () const inline noexcept
References m_minH.
     {
         return m_minH;
     }
getMinimumWidth()
int ResizableChild::getMinimumWidth () const inline noexcept
References m_minW.
     {
         return m_minW;
     }
resizeStart()
virtual void ResizableChild::resizeStart () inline virtual noexcept
Reimplemented in ResizableLayout.
     {}
setMaximumHeight()
void ResizableChild::setMaximumHeight (int maximumHeight) inline noexcept
References m_maxH.
Referenced by setMaximumSize(), and setSizeLimits().
     {
         m_maxH = maximumHeight;
     }
setMaximumSize()
void ResizableChild::setMaximumSize (int maximumWidth, int maximumHeight) inline noexcept
References setMaximumHeight(), and setMaximumWidth().
     {
         setMaximumWidth(maximumWidth);
         setMaximumHeight(maximumHeight);
     }
setMaximumWidth()
void ResizableChild::setMaximumWidth (int maximumWidth) inline noexcept
References m_maxW.
Referenced by setMaximumSize(), and setSizeLimits().
     {
         m_maxW = maximumWidth;
     }
setMinimumHeight()
void ResizableChild::setMinimumHeight (int minimumHeight) inline noexcept
References m_minH.
Referenced by setMinimumSize(), and setSizeLimits().
     {
         m_minH = minimumHeight;
     }
setMinimumSize()
void ResizableChild::setMinimumSize (int minimumWidth, int minimumHeight) inline noexcept
References setMinimumHeight(), and setMinimumWidth().
     {
         setMinimumWidth(minimumWidth);
         setMinimumHeight(minimumHeight);
     }
setMinimumWidth()
void ResizableChild::setMinimumWidth (int minimumWidth) inline noexcept
References m_minW.
Referenced by setMinimumSize(), and setSizeLimits().
     {
         m_minW = minimumWidth;
     }
setSizeLimits()
void ResizableChild::setSizeLimits (int minimumWidth, int minimumHeight, int maximumWidth, int maximumHeight) inline noexcept
References setMaximumHeight(), setMaximumWidth(), setMinimumHeight(), and setMinimumWidth().
     {
         setMinimumWidth(minimumWidth);
         setMaximumWidth(maximumWidth);
         setMinimumHeight(minimumHeight);
         setMaximumHeight(maximumHeight);
     }
Member Data Documentation
m_maxH
int ResizableChild::m_maxH private
Referenced by getMaximumHeight(), ResizableChild(), and setMaximumHeight().
m_maxW
int ResizableChild::m_maxW private
Referenced by getMaximumWidth(), ResizableChild(), and setMaximumWidth().
m_minH
int ResizableChild::m_minH private
Referenced by getMinimumHeight(), ResizableChild(), and setMinimumHeight().
m_minW
int ResizableChild::m_minW private
Referenced by getMinimumWidth(), ResizableChild(), and setMinimumWidth().
The documentation for this class was generated from the following file:
Q:/Documents/GitHub/MIDI2LR/Source/ResizableLayout.h