MIDI2LR: ControlsModel Class Reference
ControlsModel Class Reference
#include <ControlsModel.h>
Public Member Functions
ControlsModel ()=default
ControlsModel (const ControlsModel &)=delete
ControlsModel (ControlsModel &&)=delete
~ControlsModel ()=default
double ControllerToPlugin (const rsj::MidiMessage &mm)
short GetCcMax (size_t channel, short controlnumber) const
rsj::CCmethod GetCcMethod (size_t channel, short controlnumber) const
short GetCcMin (size_t channel, short controlnumber)
short GetPwMax (size_t channel) const
short GetPwMin (size_t channel) const
short MeasureChange (const rsj::MidiMessage &mm)
short MeasureChange (short controltype, size_t channel, short controlnumber, short value)
ControlsModel & operator= (const ControlsModel &)=delete
ControlsModel & operator= (ControlsModel &&)=delete
short PluginToController (short controltype, size_t channel, short controlnumber, double value)
void SetCc (size_t channel, short controlnumber, short min, short max, rsj::CCmethod controltype)
void SetCcAll (size_t channel, short controlnumber, short min, short max, rsj::CCmethod controltype)
void SetCcMax (size_t channel, short controlnumber, short value)
void SetCcMethod (size_t channel, short controlnumber, rsj::CCmethod value)
void SetCcMin (size_t channel, short controlnumber, short value)
void SetPwMax (size_t channel, short value)
void SetPwMin (size_t channel, short value)
short SetToCenter (const rsj::MidiMessage &mm)
Private Member Functions
template<class Archive >
void serialize (Archive &archive, uint32_t const version)
Private Attributes
std::array< ChannelModel, 16 > all_controls_
Friends
class cereal::access
Constructor & Destructor Documentation
ControlsModel() [1/3]
ControlsModel::ControlsModel () default
~ControlsModel()
ControlsModel::~ControlsModel () default
ControlsModel() [2/3]
ControlsModel::ControlsModel (const ControlsModel &) delete
ControlsModel() [3/3]
ControlsModel::ControlsModel (ControlsModel &&) delete
Member Function Documentation
ControllerToPlugin()
double ControlsModel::ControllerToPlugin (const rsj::MidiMessage & mm) inline
    {
       try {
          return all_controls_.at(mm.channel)
              .ControllerToPlugin(mm.message_type_byte, mm.number, mm.value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
Referenced by LrIpcOut::MidiCmdCallback().
GetCcMax()
short ControlsModel::GetCcMax (size_t channel, short controlnumber) const inline
    {
       try {
          return all_controls_.at(channel).GetCcMax(controlnumber);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
GetCcMethod()
rsj::CCmethod ControlsModel::GetCcMethod (size_t channel, short controlnumber) const inline
{
       try {
          return all_controls_.at(channel).GetCcMethod(controlnumber);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
Referenced by CCoptions::BindToControl(), and LrIpcOut::MidiCmdCallback().
GetCcMin()
short ControlsModel::GetCcMin (size_t channel, short controlnumber) inline
    {
       try {
          return all_controls_.at(channel).GetCcMin(controlnumber);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
GetPwMax()
short ControlsModel::GetPwMax (size_t channel) const inline
{
       try {
          return all_controls_.at(channel).GetPwMax();
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
GetPwMin()
short ControlsModel::GetPwMin (size_t channel) const inline
    {
       try {
          return all_controls_.at(channel).GetPwMin();
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
MeasureChange() [1/2]
short ControlsModel::MeasureChange (const rsj::MidiMessage & mm) inline
    {
       try {
          return all_controls_.at(mm.channel)
              .MeasureChange(mm.message_type_byte, mm.number, mm.value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
Referenced by LrIpcOut::MidiCmdCallback().
MeasureChange() [2/2]
short ControlsModel::MeasureChange (short controltype, size_t channel, short controlnumber, short value) inline
    {
       try {
          return all_controls_.at(channel).MeasureChange(controltype, controlnumber, value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
operator=() [1/2]
ControlsModel& ControlsModel::operator= (const ControlsModel &) delete
operator=() [2/2]
ControlsModel& ControlsModel::operator= (ControlsModel &&) delete
PluginToController()
short ControlsModel::PluginToController (short controltype, size_t channel, short controlnumber, double value) inline
    {
       try {
          return all_controls_.at(channel).PluginToController(controltype, controlnumber, value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
serialize()
template<class Archive > void ControlsModel::serialize (Archive & archive, uint32_t const version) inline private
    {
       if (version == 1) // serialize things by passing them to the archive
          archive(all_controls_);
    }
References cereal::access.
SetCc()
void ControlsModel::SetCc (size_t channel, short controlnumber, short min, short max, rsj::CCmethod controltype) inline
    {
       try {
          all_controls_.at(channel).SetCc(controlnumber, min, max, controltype);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
SetCcAll()
void ControlsModel::SetCcAll (size_t channel, short controlnumber, short min, short max, rsj::CCmethod controltype) inline
    {
       try {
          all_controls_.at(channel).SetCcAll(controlnumber, min, max, controltype);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
SetCcMax()
void ControlsModel::SetCcMax (size_t channel, short controlnumber, short value) inline
    {
       try {
          all_controls_.at(channel).SetCcMax(controlnumber, value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
SetCcMethod()
void ControlsModel::SetCcMethod (size_t channel, short controlnumber, rsj::CCmethod value) inline
    {
       try {
          all_controls_.at(channel).SetCcMethod(controlnumber, value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
Referenced by CCoptions::buttonClicked().
SetCcMin()
void ControlsModel::SetCcMin (size_t channel, short controlnumber, short value) inline
    {
       try {
          all_controls_.at(channel).SetCcMin(controlnumber, value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
SetPwMax()
void ControlsModel::SetPwMax (size_t channel, short value) inline
    {
       try {
          all_controls_.at(channel).SetPwMax(value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
SetPwMin()
void ControlsModel::SetPwMin (size_t channel, short value) inline
    {
       try {
          all_controls_.at(channel).SetPwMin(value);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
SetToCenter()
short ControlsModel::SetToCenter (const rsj::MidiMessage & mm) inline
    {
       try {
          return all_controls_.at(mm.channel).SetToCenter(mm.message_type_byte, mm.number);
       }
       catch (const std::exception& e) {
          rsj::ExceptionResponse(typeid(this).name(), __func__, e);
          throw;
       }
    }
References rsj::AppLogFilePath(), and rsj::ExceptionResponse().
Referenced by LrIpcOut::Recenter::timerCallback().
Friends And Related Function Documentation
cereal::access
friend class cereal::access friend
Referenced by serialize().
Member Data Documentation
all_controls_
std::array<ChannelModel, 16> ControlsModel::all_controls_ private
The documentation for this class was generated from the following file:
D:/Users/Rory/source/repos/MIDI2LR/Source/ControlsModel.h