MIDI2LR: SettingsComponent Class Reference
SettingsComponent Class Reference final
#include <SettingsComponent.h>
Public Member Functions
SettingsComponent (SettingsManager *settings_manager)
SettingsComponent (const SettingsComponent &other)=delete
SettingsComponent (SettingsComponent &&other)=delete
~SettingsComponent ()=default
void Init ()
SettingsComponent & operator= (const SettingsComponent &other)=delete
SettingsComponent & operator= (SettingsComponent &&other)=delete
Private Member Functions
void buttonClicked (juce::Button *button) override
void paint (juce::Graphics &) override
void sliderValueChanged (juce::Slider *slider) override
Private Member Functions inherited from ResizableLayout
ResizableLayout (juce::Component *owner)
~ResizableLayout ()
void activateLayout (bool isActive=true) noexcept
void addToLayout (juce::Component *component, const juce::Point< int > &topLeft, const juce::Point< int > &bottomRight=juce::Point< int >{-1, -1}, Style style=styleStretch)
void recalculateLayout () const
void removeFromLayout (juce::Component *component) noexcept
void updateLayoutFor (juce::Component *component) noexcept
Private Member Functions inherited from ResizableChild
ResizableChild () noexcept
virtual ~ResizableChild ()=default
int getMaximumHeight () const noexcept
int getMaximumWidth () const noexcept
int getMinimumHeight () const noexcept
int getMinimumWidth () const noexcept
void setMaximumHeight (int maximumHeight) noexcept
void setMaximumSize (int maximumWidth, int maximumHeight) noexcept
void setMaximumWidth (int maximumWidth) noexcept
void setMinimumHeight (int minimumHeight) noexcept
void setMinimumSize (int minimumWidth, int minimumHeight) noexcept
void setMinimumWidth (int minimumWidth) noexcept
void setSizeLimits (int minimumWidth, int minimumHeight, int maximumWidth, int maximumHeight) noexcept
Private Attributes
juce::Label autohide_explain_label_ {}
juce::GroupComponent autohide_group_ {}
juce::Slider autohide_setting_
juce::ToggleButton pickup_enabled_ {"Enable Pickup Mode"}
juce::GroupComponent pickup_group_ {}
juce::Label pickup_label_ {"PickupLabel", ""}
juce::GroupComponent profile_group_ {}
juce::TextButton profile_location_button_ {"Choose Profile Folder"}
juce::Label profile_location_label_ {"Profile Label"}
SettingsManager *const settings_manager_
Additional Inherited Members
Private Types inherited from ResizableLayout
enum { anchorUnit = 100 }
enum Style { styleStretch, styleFixedAspect }
Static Private Member Functions inherited from ResizableLayout
static juce::Rectangle< int > calcBoundsOfChildren (juce::Component *parent) noexcept
Constructor & Destructor Documentation
SettingsComponent() [1/3]
SettingsComponent::SettingsComponent (SettingsManager * settings_manager) explicit
References SettingsComponent().
Referenced by SettingsComponent().
     : ResizableLayout{this}, settings_manager_{settings_manager}
 {
 }
~SettingsComponent()
SettingsComponent::~SettingsComponent () default
SettingsComponent() [2/3]
SettingsComponent::SettingsComponent (const SettingsComponent & other) delete
SettingsComponent() [3/3]
SettingsComponent::SettingsComponent (SettingsComponent && other) delete
Member Function Documentation
buttonClicked()
void SettingsComponent::buttonClicked (juce::Button * button) override private
References rsj::ExceptionResponse(), and settings_manager_.
 { //-V2009 overridden method
    try {
       if (button == &pickup_enabled_) {
          if (settings_manager_) {
             const auto pickup_state = pickup_enabled_.getToggleState();
             settings_manager_->SetPickupEnabled(pickup_state);
             rsj::Log(pickup_state ? "Pickup set to enabled" : "Pickup set to disabled");
          }
       }
       else if (button == &profile_location_button_) {
          juce::FileBrowserComponent browser{juce::FileBrowserComponent::canSelectDirectories
                                                 | juce::FileBrowserComponent::openMode,
              juce::File::getCurrentWorkingDirectory(), nullptr, nullptr};
          juce::FileChooserDialogBox dialog_box{"Select Profile Folder",
              "Select a folder containing MIDI2LR Profiles", browser, true,
              juce::Colours::lightgrey};
          if (dialog_box.show()) {
             const auto profile_location = browser.getSelectedFile(0).getFullPathName();
             if (settings_manager_) {
                settings_manager_->SetProfileDirectory(profile_location);
             }
             rsj::Log("Profile location set to " + profile_location);
             profile_location_label_.setText(
                 profile_location, juce::NotificationType::dontSendNotification);
          }
       }
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
Init()
void SettingsComponent::Init ()
References rsj::ExceptionResponse().
 {
    try {
       // for layouts to work you must start at some size
       // place controls in a location that is initially correct.
       setSize(kSettingsWidth, kSettingsHeight);
       pickup_group_.setText("Pick up");
       pickup_group_.setBounds(0, 0, kSettingsWidth, 100);
       addToLayout(&pickup_group_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(pickup_group_);
       pickup_label_.setFont(juce::Font{12.f, juce::Font::bold});
       pickup_label_.setText("Disabling the pickup mode may be better for touchscreen interfaces "
                             "and "
                             "may solve issues with LR not picking up fast fader/knob movements",
           NotificationType::dontSendNotification);
       pickup_label_.setBounds(kSettingsLeft, 15, kSettingsWidth - 2 * kSettingsLeft, 50);
       addToLayout(&pickup_label_, anchorMidLeft, anchorMidRight);
       pickup_label_.setEditable(false);
       pickup_label_.setColour(juce::Label::textColourId, juce::Colours::darkgrey);
       addAndMakeVisible(pickup_label_);
       pickup_enabled_.addListener(this);
       pickup_enabled_.setToggleState(
           settings_manager_->GetPickupEnabled(), juce::NotificationType::dontSendNotification);
       pickup_enabled_.setBounds(kSettingsLeft, 60, kSettingsWidth - 2 * kSettingsLeft,
           32); //"Magic number" 32 false alarm //-V112
       addToLayout(&pickup_enabled_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(pickup_enabled_);
       // ---------------------------- profile section -----------------------------------
       profile_group_.setText("Profile");
       profile_group_.setBounds(0, 100, kSettingsWidth, 100);
       addToLayout(&profile_group_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(profile_group_);
       profile_location_button_.addListener(this);
       profile_location_button_.setBounds(
           kSettingsLeft, 120, kSettingsWidth - 2 * kSettingsLeft, 25);
       addToLayout(&profile_location_button_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(profile_location_button_);
       profile_location_label_.setEditable(false);
       profile_location_label_.setBounds(kSettingsLeft, 145, kSettingsWidth - 2 * kSettingsLeft, 30);
       addToLayout(&profile_location_label_, anchorMidLeft, anchorMidRight);
       profile_location_label_.setColour(juce::Label::textColourId, juce::Colours::darkgrey);
       addAndMakeVisible(profile_location_label_);
       profile_location_label_.setText(
           settings_manager_->GetProfileDirectory(), juce::NotificationType::dontSendNotification);
       autohide_group_.setText("Auto hide");
       autohide_group_.setBounds(0, 200, kSettingsWidth, 100);
       addToLayout(&autohide_group_, anchorMidLeft, anchorMidRight);
       addAndMakeVisible(autohide_group_);
       autohide_explain_label_.setFont(juce::Font{12.f, juce::Font::bold});
       autohide_explain_label_.setText("Autohide the plugin window in x seconds, select 0 for "
                                       "disabling autohide",
           juce::NotificationType::dontSendNotification);
       autohide_explain_label_.setBounds(kSettingsLeft, 215, kSettingsWidth - 2 * kSettingsLeft, 50);
       addToLayout(&autohide_explain_label_, anchorMidLeft, anchorMidRight);
       autohide_explain_label_.setEditable(false);
       autohide_explain_label_.setFont(juce::Font{12.f, juce::Font::bold});
       autohide_explain_label_.setColour(juce::Label::textColourId, juce::Colours::darkgrey);
       addAndMakeVisible(autohide_explain_label_);
       autohide_setting_.setBounds(kSettingsLeft, 245, kSettingsWidth - 2 * kSettingsLeft, 50);
       autohide_setting_.setRange(0, 10, 1);
       autohide_setting_.setValue(
           settings_manager_->GetAutoHideTime(), juce::NotificationType::dontSendNotification);
       addToLayout(&autohide_setting_, anchorMidLeft, anchorMidRight);
       // add this as the lister for the data
       autohide_setting_.addListener(this);
       addAndMakeVisible(autohide_setting_);
       // turn it on
       activateLayout();
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
operator=() [1/2]
SettingsComponent& SettingsComponent::operator= (const SettingsComponent & other) delete
operator=() [2/2]
SettingsComponent& SettingsComponent::operator= (SettingsComponent && other) delete
paint()
void SettingsComponent::paint (juce::Graphics & g) override private
 {                                   //-V2009 overridden method
    g.fillAll(juce::Colours::white); // clear the background
 }
sliderValueChanged()
void SettingsComponent::sliderValueChanged (juce::Slider * slider) override private
 { //-V2009 overridden method
    if (slider && &autohide_setting_ == slider) {
       settings_manager_->SetAutoHideTime(static_cast<int>(
           round(autohide_setting_.getValue()))); //-V2003 intentional cast double to int
       rsj::Log("Autohide time set to " + juce::String(settings_manager_->GetAutoHideTime())
                + " seconds");
    }
 }
Member Data Documentation
autohide_explain_label_
juce::Label SettingsComponent::autohide_explain_label_ {} private
autohide_group_
juce::GroupComponent SettingsComponent::autohide_group_ {} private
autohide_setting_
juce::Slider SettingsComponent::autohide_setting_ private
pickup_enabled_
juce::ToggleButton SettingsComponent::pickup_enabled_ {"Enable Pickup Mode"} private
pickup_group_
juce::GroupComponent SettingsComponent::pickup_group_ {} private
pickup_label_
juce::Label SettingsComponent::pickup_label_ {"PickupLabel", ""} private
profile_group_
juce::GroupComponent SettingsComponent::profile_group_ {} private
profile_location_button_
juce::TextButton SettingsComponent::profile_location_button_ {"Choose Profile Folder"} private
profile_location_label_
juce::Label SettingsComponent::profile_location_label_ {"Profile Label"} private
settings_manager_
SettingsManager* const SettingsComponent::settings_manager_ private
Referenced by buttonClicked().
The documentation for this class was generated from the following files:
Q:/Documents/GitHub/MIDI2LR/Source/SettingsComponent.h
Q:/Documents/GitHub/MIDI2LR/Source/SettingsComponent.cpp