MIDI2LR: CommandMap Class Reference
CommandMap Class Reference
#include <CommandMap.h>
Public Member Functions
CommandMap () noexcept
CommandMap (const CommandMap &)=delete
virtual ~CommandMap ()=default
void AddCommandforMessage (size_t command, const rsj::MidiMessageId &cc)
void AddCommandforMessage (const std::string &command, const rsj::MidiMessageId &cc)
void ClearMap () noexcept
bool CommandHasAssociatedMessage (const std::string &command) const
const std::string & GetCommandforMessage (const rsj::MidiMessageId &message) const
std::vector< const rsj::MidiMessageId * > GetMessagesForCommand (const std::string &command) const
bool MessageExistsInMap (const rsj::MidiMessageId &message) const
CommandMap & operator= (const CommandMap &)=delete
void RemoveMessage (const rsj::MidiMessageId &message)
void ToXmlDocument (const juce::File &file) const
Private Attributes
std::multimap< std::string, rsj::MidiMessageId > command_string_map_
std::unordered_map< rsj::MidiMessageId, std::string > message_map_
Constructor & Destructor Documentation
CommandMap() [1/2]
CommandMap::CommandMap () noexcept
 {}
~CommandMap()
virtual CommandMap::~CommandMap () virtual default
CommandMap() [2/2]
CommandMap::CommandMap (const CommandMap &) delete
Member Function Documentation
AddCommandforMessage() [1/2]
void CommandMap::AddCommandforMessage (size_t command, const rsj::MidiMessageId & cc)
Referenced by CommandTableModel::AddRow().
 {
     // adds a message to the message:command map, and its associated command to the
     // command:message map
     if (command < LrCommandList::LrStringList.size()) {
         message_map_[message] = LrCommandList::LrStringList[command];
         command_string_map_.insert({LrCommandList::LrStringList[command], message});
     }
     else
         message_map_[message] = LrCommandList::NextPrevProfile[command - LrCommandList::LrStringList.size()];
 }
AddCommandforMessage() [2/2]
void CommandMap::AddCommandforMessage (const std::string & command, const rsj::MidiMessageId & cc) inline
 {
     message_map_[message] = command;
     command_string_map_.insert({command, message});
 }
ClearMap()
void CommandMap::ClearMap () inline noexcept
Referenced by CommandTableModel::RemoveAllRows().
 {
     command_string_map_.clear();
     message_map_.clear();
 }
CommandHasAssociatedMessage()
bool CommandMap::CommandHasAssociatedMessage (const std::string & command) const inline
 {
     return command_string_map_.find(command) != command_string_map_.end();
 }
GetCommandforMessage()
const std::string & CommandMap::GetCommandforMessage (const rsj::MidiMessageId & message) const inline
Referenced by ProfileManager::MapCommand(), and CommandTableModel::Sort().
 {
     return message_map_.at(message);
 }
GetMessagesForCommand()
std::vector< const rsj::MidiMessageId * > CommandMap::GetMessagesForCommand (const std::string & command) const
 {
     std::vector<const rsj::MidiMessageId*> mm;
     const auto range = command_string_map_.equal_range(command);
     for (auto it = range.first; it != range.second; ++it)
         mm.push_back(&it->second);
     return mm;
 }
MessageExistsInMap()
bool CommandMap::MessageExistsInMap (const rsj::MidiMessageId & message) const inline
Referenced by CommandTableModel::AddRow(), and ProfileManager::MidiCmdCallback().
 {
     return message_map_.find(message) != message_map_.end();
 }
operator=()
CommandMap& CommandMap::operator= (const CommandMap &) delete
RemoveMessage()
void CommandMap::RemoveMessage (const rsj::MidiMessageId & message) inline
Referenced by CommandMenu::clicked().
 {
     // removes message from the message:command map, and its associated command from
     // the command:message map
     command_string_map_.erase(message_map_[message]);
     message_map_.erase(message);
 }
ToXmlDocument()
void CommandMap::ToXmlDocument (const juce::File & file) const
 {
     if (message_map_.size()) {//don't bother if map is empty
       // save the contents of the command map to an xml file
         juce::XmlElement root{"settings"};
         for (const auto& map_entry : message_map_) {
             auto* setting = new juce::XmlElement{"setting"};
             setting->setAttribute("channel", map_entry.first.channel);
             switch (map_entry.first.msg_id_type) {
                 case rsj::MsgIdEnum::kNote: setting->setAttribute("note", map_entry.first.pitch);
                     break;
                 case rsj::MsgIdEnum::kCc: setting->setAttribute("controller", map_entry.first.controller);
                     break;
                 case rsj::MsgIdEnum::kPitchBend: setting->setAttribute("pitchbend", 0);
                     break;
             }
             setting->setAttribute("command_string", map_entry.second);
             root.addChildElement(setting);
         }
         if (!root.writeToFile(file, ""))
             // Give feedback if file-save doesn't work
             juce::NativeMessageBox::showMessageBox(juce::AlertWindow::WarningIcon, "File Save Error",
                 "Unable to save file as specified. Please try again, and consider saving to a different location.");
     }
 }
Member Data Documentation
command_string_map_
std::multimap<std::string, rsj::MidiMessageId> CommandMap::command_string_map_ private
message_map_
std::unordered_map<rsj::MidiMessageId, std::string> CommandMap::message_map_ private
The documentation for this class was generated from the following files:
Q:/Documents/GitHub/MIDI2LR/Source/CommandMap.h
Q:/Documents/GitHub/MIDI2LR/Source/CommandMap.cpp