MIDI2LR: MainWindow Class Reference
MainWindow Class Reference final
#include <MainWindow.h>
Public Member Functions
MainWindow (const juce::String &name, const CommandSet &command_set, Profile &profile, ProfileManager &profile_manager, SettingsManager &settings_manager, std::weak_ptr< LrIpcOut > &&lr_ipc_out, std::shared_ptr< MidiReceiver > midi_receiver, std::shared_ptr< MidiSender > midi_sender)
MainWindow (const MainWindow &other)=delete
MainWindow (MainWindow &&other)=delete
~MainWindow ()=default
MainWindow & operator= (const MainWindow &other)=delete
MainWindow & operator= (MainWindow &&other)=delete
void SaveProfile () const
Private Member Functions
void closeButtonPressed () override
void timerCallback () override
Private Attributes
MainContentComponent * window_content_
Constructor & Destructor Documentation
MainWindow() [1/3]
MainWindow::MainWindow (const juce::String & name, const CommandSet & command_set, Profile & profile, ProfileManager & profile_manager, SettingsManager & settings_manager, std::weak_ptr< LrIpcOut > && lr_ipc_out, std::shared_ptr< MidiReceiver > midi_receiver, std::shared_ptr< MidiSender > midi_sender)
                                                : juce
    ::DocumentWindow{name, juce::Colours::lightgrey,
        juce::DocumentWindow::minimiseButton | juce::DocumentWindow::closeButton}
    {
       juce::TopLevelWindow::setUsingNativeTitleBar(true);
 #pragma warning(suppress : 26409 24623) // ResizableWindow will manage window_content_ lifetime
       window_content_ =
           new MainContentComponent(command_set, profile, profile_manager, settings_manager);
       juce::ResizableWindow::setContentOwned(window_content_, true);
       juce::Component::centreWithSize(getWidth(), getHeight());
       juce::Component::setVisible(true);
       window_content_->Init(
           std::move(lr_ipc_out), std::move(midi_receiver), std::move(midi_sender));
       const auto hide_sec = settings_manager.GetAutoHideTime();
       if (hide_sec) // don't start timer if time is zero
          juce::Timer::startTimer(1000 * hide_sec);
    }
 catch (const std::exception& e) {
    rsj::ExceptionResponse(typeid(this).name(), __func__, e);
    throw;
 }
~MainWindow()
MainWindow::~MainWindow () default
MainWindow() [2/3]
MainWindow::MainWindow (const MainWindow & other) delete
MainWindow() [3/3]
MainWindow::MainWindow (MainWindow && other) delete
Member Function Documentation
closeButtonPressed()
void MainWindow::closeButtonPressed () inline override private
    {
       // This is called when the user tries to close this window. Here, we'll just
       // ask the app to quit when this happens, but you can change this to do
       // whatever you need.
       juce::JUCEApplication::getInstance()->systemRequestedQuit();
    }
operator=() [1/2]
MainWindow& MainWindow::operator= (const MainWindow & other) delete
operator=() [2/2]
MainWindow& MainWindow::operator= (MainWindow && other) delete
SaveProfile()
void MainWindow::SaveProfile () const
 {
    try {
       if (window_content_)
          window_content_->SaveProfile();
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), rsj::NumToChars(), and window_content_.
timerCallback()
void MainWindow::timerCallback () override private
 {
    try {
       juce::Timer::stopTimer();
       if (!juce::ResizableWindow::isMinimised())
          juce::DocumentWindow::minimiseButtonPressed();
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(typeid(this).name(), __func__, e);
       throw;
    }
 }
References rsj::ExceptionResponse(), and rsj::NumToChars().
Member Data Documentation
window_content_
MainContentComponent* MainWindow::window_content_ private
Referenced by SaveProfile().
The documentation for this class was generated from the following files:
D:/Users/Rory/source/repos/MIDI2LR/Source/MainWindow.h
D:/Users/Rory/source/repos/MIDI2LR/Source/MainWindow.cpp