var dir_74389ed8173ad57b461b9d623a1f3867 =
[
    [ "LRPlugin", "dir_fe5bc542be8441cc1d2e8754ed7848ea.html", "dir_fe5bc542be8441cc1d2e8754ed7848ea" ],
    [ "Utilities", "dir_9004245aaaaa2dad7b2f90fc9db90e30.html", "dir_9004245aaaaa2dad7b2f90fc9db90e30" ],
    [ "CommandMap.cpp", "_command_map_8cpp.html", null ],
    [ "CommandMap.h", "_command_map_8h.html", "_command_map_8h" ],
    [ "CommandMenu.cpp", "_command_menu_8cpp.html", null ],
    [ "CommandMenu.h", "_command_menu_8h.html", "_command_menu_8h" ],
    [ "CommandTable.cpp", "_command_table_8cpp.html", null ],
    [ "CommandTable.h", "_command_table_8h.html", "_command_table_8h" ],
    [ "CommandTableModel.cpp", "_command_table_model_8cpp.html", null ],
    [ "CommandTableModel.h", "_command_table_model_8h.html", "_command_table_model_8h" ],
    [ "LR_IPC_In.cpp", "_l_r___i_p_c___in_8cpp.html", null ],
    [ "LR_IPC_In.h", "_l_r___i_p_c___in_8h.html", "_l_r___i_p_c___in_8h" ],
    [ "LR_IPC_Out.cpp", "_l_r___i_p_c___out_8cpp.html", null ],
    [ "LR_IPC_Out.h", "_l_r___i_p_c___out_8h.html", "_l_r___i_p_c___out_8h" ],
    [ "LRCommands.cpp", "_l_r_commands_8cpp.html", null ],
    [ "LRCommands.h", "_l_r_commands_8h.html", "_l_r_commands_8h" ],
    [ "Main.cpp", "_main_8cpp.html", "_main_8cpp" ],
    [ "MainComponent.cpp", "_main_component_8cpp.html", null ],
    [ "MainComponent.h", "_main_component_8h.html", "_main_component_8h" ],
    [ "MainWindow.cpp", "_main_window_8cpp.html", null ],
    [ "MainWindow.h", "_main_window_8h.html", "_main_window_8h" ],
    [ "MIDIProcessor.cpp", "_m_i_d_i_processor_8cpp.html", null ],
    [ "MIDIProcessor.h", "_m_i_d_i_processor_8h.html", "_m_i_d_i_processor_8h" ],
    [ "MIDISender.cpp", "_m_i_d_i_sender_8cpp.html", null ],
    [ "MIDISender.h", "_m_i_d_i_sender_8h.html", "_m_i_d_i_sender_8h" ],
    [ "NrpnMessage.cpp", "_nrpn_message_8cpp.html", null ],
    [ "NrpnMessage.h", "_nrpn_message_8h.html", [
      [ "NRPN_Filter", "class_n_r_p_n___filter.html", "class_n_r_p_n___filter" ],
      [ "NRPN_Message", "class_n_r_p_n___message.html", "class_n_r_p_n___message" ]
    ] ],
    [ "ProfileManager.cpp", "_profile_manager_8cpp.html", null ],
    [ "ProfileManager.h", "_profile_manager_8h.html", "_profile_manager_8h" ],
    [ "ResizableLayout.cpp", "_resizable_layout_8cpp.html", null ],
    [ "ResizableLayout.h", "_resizable_layout_8h.html", "_resizable_layout_8h" ],
    [ "SendKeys.cpp", "_send_keys_8cpp.html", null ],
    [ "SendKeys.h", "_send_keys_8h.html", [
      [ "SendKeys", "class_send_keys.html", "class_send_keys" ]
    ] ],
    [ "SettingsComponent.cpp", "_settings_component_8cpp.html", null ],
    [ "SettingsComponent.h", "_settings_component_8h.html", "_settings_component_8h" ],
    [ "SettingsManager.cpp", "_settings_manager_8cpp.html", "_settings_manager_8cpp" ],
    [ "SettingsManager.h", "_settings_manager_8h.html", "_settings_manager_8h" ],
    [ "VersionChecker.cpp", "_version_checker_8cpp.html", null ],
    [ "VersionChecker.h", "_version_checker_8h.html", "_version_checker_8h" ]
];