MIDI2LR: rsj Namespace Reference
rsj Namespace Reference
Classes
struct ActiveModifiers
struct MidiMessage
class MidiMessageFactory
struct MidiMessageId
struct Nrpn
class RelaxTTasSpinLock
struct ReversionWrapper
struct SettingsStruct
Enumerations
enum CCmethod : char { CCmethod::kAbsolute, CCmethod::kTwosComplement, CCmethod::kBinaryOffset, CCmethod::kSignMagnitude }
enum MessageType : short {
NoteOff = 0x8, NoteOn = 0x9, KeyPressure = 0xA, Cc = 0xB,
PgmChange = 0xC, ChanPressure = 0xD, Pw = 0xE, System = 0xF
}
Functions
std::string AppDataFilePath (const std::string &file_name)
std::string AppDataMac ()
std::string AppLogFilePath (const std::string &file_name)
std::string AppLogMac ()
template<typename T >
auto begin (ReversionWrapper< T > w)
void CheckPermission (pid_t pid)
template<typename T >
auto end (ReversionWrapper< T > w)
bool EndsWith (std::string_view main_str, std::string_view to_match)
void ExceptionResponse (const char *id, const char *fu, const std::exception &e) noexcept
std::string GetKeyboardLayout ()
void Log (const juce::String &info)
void LogAndAlertError (const juce::String &error_text)
template<class T >
std::string NumToChars (T number)
constexpr bool operator== (const rsj::MidiMessage &lhs, const rsj::MidiMessage &rhs) noexcept
template<class R >
constexpr auto RatioToPrefix ()
template<typename T >
ReversionWrapper< T > Reverse (T &&iterable)
void SendKeyDownUp (const std::string &key, rsj::ActiveModifiers mods) noexcept
template<class Rep , class Period >
auto SleepTimed (const std::chrono::duration< Rep, Period > sleep_duration)
template<class Rep , class Period >
void SleepTimedLogged (std::string_view msg_prefix, const std::chrono::duration< Rep, Period > sleep_duration)
std::string ToLower (std::string_view in)
constexpr MessageType ToMessageType (short from)
void Translate (const std::string &lg)
void Trim (std::string_view &value) noexcept
UniChar Utf8ToUtf16 (const std::string &param)
Variables
static constexpr Nrpn kInvalidNrpn {false, 0, 0}
Enumeration Type Documentation
CCmethod
enum rsj::CCmethod : char strong
Enumerator
kAbsolute
kTwosComplement
kBinaryOffset
kSignMagnitude
 : char { kAbsolute, kTwosComplement, kBinaryOffset, kSignMagnitude };
MessageType
enum rsj::MessageType : short
Enumerator
NoteOff
NoteOn
KeyPressure
Cc
PgmChange
ChanPressure
Pw
System
                     : short {
       NoteOff = 0x8,
       NoteOn = 0x9,
       KeyPressure = 0xA, // Individual Key Pressure
       Cc = 0xB,
       PgmChange = 0xC,
       ChanPressure = 0xD, // Max Key Pressure
       Pw = 0xE,           // Pitch Wheel
       System = 0xF
    };
Function Documentation
AppDataFilePath()
std::string rsj::AppDataFilePath (const std::string & file_name)
 {
    return rsj::AppDataMac() + '/' + file_name;
 }
AppDataMac()
std::string rsj::AppDataMac ()
 {
    NSString* result = (@"~/Library/Application Support/MIDI2LR").stringByExpandingTildeInPath;
    return std::string(result.UTF8String);
 }
AppLogFilePath()
std::string rsj::AppLogFilePath (const std::string & file_name)
 {
    return rsj::AppLogMac() + '/' + file_name;
 }
AppLogMac()
std::string rsj::AppLogMac ()
 {
    NSString* result = (@"~/Library/Logs/MIDI2LR").stringByExpandingTildeInPath;
    return std::string(result.UTF8String);
 }
begin()
template<typename T > auto rsj::begin (ReversionWrapper< T > w)
    {
       return std::rbegin(w.iterable);
    }
CheckPermission()
void rsj::CheckPermission (pid_t pid)
 {
    if (@available(macOS 10.14, *)) {
       AEAddressDesc addressDesc;
       NSString* bundleIdentifier =
           [NSRunningApplication runningApplicationWithProcessIdentifier:pid].bundleIdentifier;
       const char* bundleIdentifierCString =
           [bundleIdentifier cStringUsingEncoding:NSUTF8StringEncoding];
       auto aeresult = AECreateDesc(typeApplicationBundleID, bundleIdentifierCString,
           strlen(bundleIdentifierCString), &addressDesc);
       if (aeresult == noErr) {
          auto status =
              AEDeterminePermissionToAutomateTarget(&addressDesc, typeWildCard, typeWildCard, true);
          AEDisposeDesc(&addressDesc);
          switch (status) {
          case errAEEventWouldRequireUserConsent:
             rsj::Log(
                 juce::String("Automation permission pending for ") + bundleIdentifier.UTF8String);
             break;
          case noErr:
             rsj::Log(
                 juce::String("Automation permission granted for ") + bundleIdentifier.UTF8String);
             break;
          case errAEEventNotPermitted: {
             rsj::Log(
                 juce::String("Automation permission denied for ") + bundleIdentifier.UTF8String);
             auto title =
                 juce::translate("MIDI2LR needs your authorization to send keystrokes to Lightroom");
             auto message = juce::translate(
                 "To authorize MIDI2LR to send keystrokes to Lightroom, please follow these "
                 "steps:\r\n1) Open System Preferences\r\n2) Click on Security & Privacy\r\n3) "
                 "Select the Privacy tab\r\n4) Find and select Accessibility on the left\r\n5) Find "
                 "the checkbox for MIDI2LR on the right\r\n6) Check that checkbox");
             juce::NativeMessageBox::showMessageBox(juce::AlertWindow::WarningIcon, title, message);
             break;
          }
          case procNotFound:
             rsj::Log(
                 juce::String("Automation permission unknown for ") + bundleIdentifier.UTF8String);
             break;
          default:
             break;
          }
       }
       else
          rsj::Log("AECreateDesc returned error " + juce::String(aeresult));
    }
 }
end()
template<typename T > auto rsj::end (ReversionWrapper< T > w)
    {
       return std::rend(w.iterable);
    }
EndsWith()
bool rsj::EndsWith (std::string_view main_str, std::string_view to_match)
 {
    try {
       return main_str.size() >= to_match.size()
              && main_str.compare(main_str.size() - to_match.size(), to_match.size(), to_match) == 0;
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References ExceptionResponse(), and NumToChars().
ExceptionResponse()
void rsj::ExceptionResponse (const char * id, const char * fu, const std::exception & e) noexcept
 {
    try {
       const auto error_text{juce::String("Exception ") + e.what() + ' ' + Demangle<juce::String>(id)
                             + "::" + fu + " Version " + ProjectInfo::versionString};
       rsj::LogAndAlertError(error_text);
    }
    catch (...) { //-V565
    }
 }
Referenced by Profile::AddCommandForMessage_i(), Profile::AddRowMapped(), Profile::AddRowUnmapped(), SettingsComponent::buttonClicked(), MainContentComponent::buttonClicked(), MIDI2LRApplication::CerealLoad(), MIDI2LRApplication::CerealSave(), CommandMenu::clicked(), CommandSet::CommandSet(), CommandSet::CommandTextIndex(), SettingsManager::ConnectionCallback(), ProfileManager::ConnectionCallback(), LrIpcOut::connectionLost(), LrIpcOut::connectionMade(), ControlsModel::ControllerToPlugin(), MIDI2LRApplication::DefaultProfileSave(), MidiReceiver::DispatchMessages(), EndsWith(), Profile::FromXml(), ChannelModel::GetCcMax(), ControlsModel::GetCcMax(), ChannelModel::GetCcMethod(), ControlsModel::GetCcMethod(), ChannelModel::GetCcMin(), ControlsModel::GetCcMin(), Profile::GetMessagesForCommand(), NrpnMessage::GetNrpnIfReady(), NrpnFilter::GetNrpnIfReady(), CommandTableModel::getNumRows(), ControlsModel::GetPwMax(), ControlsModel::GetPwMin(), VersionChecker::handleAsyncUpdate(), MainContentComponent::handleAsyncUpdate(), ProfileManager::handleAsyncUpdate(), MidiReceiver::handleIncomingMidiMessage(), CommandSet::Impl::Impl(), SettingsComponent::Init(), MainContentComponent::Init(), MidiSender::InitDevices(), MidiReceiver::InitDevices(), MIDI2LRApplication::initialise(), NrpnFilter::IsInProcess(), CommandTable::keyPressed(), DebugInfo::LogAndSave(), MainContentComponent::LrIpcOutCallback(), CommandSet::MakeImpl(), ProfileManager::MapCommand(), ControlsModel::MeasureChange(), LrIpcOut::MidiCmdCallback(), MainContentComponent::MidiCmdCallback(), ProfileManager::MidiCmdCallback(), SettingsComponent::paint(), MainContentComponent::paint(), CommandTableModel::paintCell(), CommandTableModel::paintRowBackground(), LrIpcIn::PleaseStopThread(), ControlsModel::PluginToController(), LrIpcIn::ProcessLine(), NrpnMessage::ProcessMidi(), NrpnFilter::ProcessMidi(), MainContentComponent::ProfileChanged(), CommandTableModel::refreshComponentForCell(), Profile::RemoveAllRows(), Profile::RemoveMessage(), Profile::RemoveRow(), MidiSender::RescanDevices(), MidiReceiver::RescanDevices(), Profile::Resort(), LrIpcOut::Restart(), VersionChecker::run(), LrIpcIn::run(), MainWindow::SaveProfile(), MainContentComponent::SaveProfile(), MidiSender::SendCc(), LrIpcOut::SendCommand(), MidiSender::SendNoteOn(), LrIpcOut::SendOut(), MidiSender::SendPitchWheel(), MIDI2LRApplication::SetAppLanguage(), SettingsManager::SetAutoHideTime(), ControlsModel::SetCc(), ControlsModel::SetCcAll(), ControlsModel::SetCcMax(), ChannelModel::SetCcMethod(), ControlsModel::SetCcMethod(), ControlsModel::SetCcMin(), MainContentComponent::SetLabelSettings(), SettingsManager::SetLastVersionFound(), LrIpcOut::Recenter::SetMidiMessage(), SettingsManager::SetPickupEnabled(), SettingsManager::SetProfileDirectory(), ProfileManager::SetProfileDirectory(), ControlsModel::SetPwMax(), ControlsModel::SetPwMin(), CommandMenu::SetSelectedItem(), ControlsModel::SetToCenter(), SettingsComponent::sliderValueChanged(), Profile::Sort_i(), CommandTableModel::sortOrderChanged(), MidiSender::Start(), MidiReceiver::Start(), LrIpcIn::Start(), LrIpcOut::Start(), LrIpcOut::ConnectTimer::Start(), LrIpcOut::Stop(), LrIpcOut::ConnectTimer::Stop(), ProfileManager::SwitchToNextProfile(), ProfileManager::SwitchToPreviousProfile(), ProfileManager::SwitchToProfile(), MIDI2LRApplication::systemRequestedQuit(), LrIpcIn::timerCallback(), MainWindow::timerCallback(), MainContentComponent::timerCallback(), LrIpcOut::ConnectTimer::timerCallback(), LrIpcOut::Recenter::timerCallback(), ToLower(), Profile::ToXmlFile(), Translate(), and MidiReceiver::TryToOpen().
GetKeyboardLayout()
std::string rsj::GetKeyboardLayout ()
 {
    // get current keyboard layout by name
    TISInputSourceRef current_source = TISCopyCurrentKeyboardInputSource();
    if (!current_source) // returns null with Japanese keyboard layout
       current_source = TISCopyCurrentKeyboardLayoutInputSource();
    NSString* s =
        (__bridge NSString*)(TISGetInputSourceProperty(current_source, kTISPropertyInputSourceID));
    NSString* t =
        (__bridge NSString*)(TISGetInputSourceProperty(current_source, kTISPropertyLocalizedName));
    if (current_source)
       CFRelease(current_source);
    if (s and t) {
       return std::string(s.UTF8String) + ' ' + std::string(t.UTF8String);
    }
    return std::string("Could not get keyboard input source ID");
 }
Log()
void rsj::Log (const juce::String & info)
 {
    if (juce::Logger::getCurrentLogger())
       juce::Logger::writeToLog(juce::Time::getCurrentTime().toISO8601(false) + ": " + info);
 }
LogAndAlertError()
void rsj::LogAndAlertError (const juce::String & error_text)
 {
    juce::NativeMessageBox::showMessageBox(juce::AlertWindow::WarningIcon, "Error", error_text);
    rsj::Log(error_text);
 }
NumToChars()
template<class T > std::string rsj::NumToChars (T number)
 { return std::to_string(number); }
Referenced by Profile::AddCommandForMessage_i(), Profile::AddRowMapped(), Profile::AddRowUnmapped(), SettingsComponent::buttonClicked(), MainContentComponent::buttonClicked(), CCoptions::buttonClicked(), MIDI2LRApplication::CerealLoad(), MIDI2LRApplication::CerealSave(), CommandMenu::clicked(), CommandSet::CommandSet(), CommandSet::CommandTextIndex(), SettingsManager::ConnectionCallback(), ProfileManager::ConnectionCallback(), LrIpcOut::connectionLost(), LrIpcOut::connectionMade(), ControlsModel::ControllerToPlugin(), MIDI2LRApplication::DefaultProfileSave(), MidiReceiver::DispatchMessages(), EndsWith(), Profile::FromXml(), ChannelModel::GetCcMax(), ControlsModel::GetCcMax(), ChannelModel::GetCcMethod(), ControlsModel::GetCcMethod(), ChannelModel::GetCcMin(), ControlsModel::GetCcMin(), Profile::GetMessagesForCommand(), NrpnMessage::GetNrpnIfReady(), NrpnFilter::GetNrpnIfReady(), CommandTableModel::getNumRows(), ControlsModel::GetPwMax(), ControlsModel::GetPwMin(), VersionChecker::handleAsyncUpdate(), MainContentComponent::handleAsyncUpdate(), ProfileManager::handleAsyncUpdate(), MidiReceiver::handleIncomingMidiMessage(), CommandSet::Impl::Impl(), SettingsComponent::Init(), MainContentComponent::Init(), MidiSender::InitDevices(), MidiReceiver::InitDevices(), MIDI2LRApplication::initialise(), NrpnFilter::IsInProcess(), CommandTable::keyPressed(), DebugInfo::LogAndSave(), MainContentComponent::LrIpcOutCallback(), CommandSet::MakeImpl(), ProfileManager::MapCommand(), ControlsModel::MeasureChange(), LrIpcOut::MidiCmdCallback(), MainContentComponent::MidiCmdCallback(), ProfileManager::MidiCmdCallback(), SettingsComponent::paint(), MainContentComponent::paint(), CommandTableModel::paintCell(), CommandTableModel::paintRowBackground(), LrIpcIn::PleaseStopThread(), ControlsModel::PluginToController(), LrIpcIn::ProcessLine(), NrpnMessage::ProcessMidi(), NrpnFilter::ProcessMidi(), rsj::MidiMessageFactory::ProcessMidi(), MainContentComponent::ProfileChanged(), CommandTableModel::refreshComponentForCell(), Profile::RemoveAllRows(), Profile::RemoveMessage(), Profile::RemoveRow(), MidiSender::RescanDevices(), MidiReceiver::RescanDevices(), Profile::Resort(), LrIpcOut::Restart(), Reverse(), VersionChecker::run(), LrIpcIn::run(), MainWindow::SaveProfile(), MainContentComponent::SaveProfile(), MidiSender::SendCc(), LrIpcOut::SendCommand(), SendKeyDownUp(), MidiSender::SendNoteOn(), LrIpcOut::SendOut(), MidiSender::SendPitchWheel(), MIDI2LRApplication::SetAppLanguage(), SettingsManager::SetAutoHideTime(), ControlsModel::SetCc(), ControlsModel::SetCcAll(), ControlsModel::SetCcMax(), ChannelModel::SetCcMethod(), ControlsModel::SetCcMethod(), ControlsModel::SetCcMin(), MainContentComponent::SetLabelSettings(), SettingsManager::SetLastVersionFound(), LrIpcOut::Recenter::SetMidiMessage(), SettingsManager::SetPickupEnabled(), SettingsManager::SetProfileDirectory(), ProfileManager::SetProfileDirectory(), ControlsModel::SetPwMax(), ControlsModel::SetPwMin(), CommandMenu::SetSelectedItem(), ControlsModel::SetToCenter(), SleepTimedLogged(), SettingsComponent::sliderValueChanged(), Profile::Sort_i(), CommandTableModel::sortOrderChanged(), MidiSender::Start(), MidiReceiver::Start(), LrIpcIn::Start(), LrIpcOut::Start(), LrIpcOut::ConnectTimer::Start(), LrIpcOut::Stop(), LrIpcOut::ConnectTimer::Stop(), ProfileManager::SwitchToNextProfile(), ProfileManager::SwitchToPreviousProfile(), ProfileManager::SwitchToProfile(), MIDI2LRApplication::systemRequestedQuit(), LrIpcIn::timerCallback(), MainWindow::timerCallback(), MainContentComponent::timerCallback(), LrIpcOut::ConnectTimer::timerCallback(), LrIpcOut::Recenter::timerCallback(), ToLower(), Profile::ToXmlFile(), Translate(), MidiReceiver::TryToOpen(), and MidiReceiver::~MidiReceiver().
operator==()
constexpr bool rsj::operator== (const rsj::MidiMessage & lhs, const rsj::MidiMessage & rhs) noexcept
    {
       return lhs.message_type_byte == rhs.message_type_byte && lhs.channel == rhs.channel
              && lhs.control_number == rhs.control_number && lhs.value == rhs.value;
    }
References rsj::MidiMessage::channel, rsj::MidiMessage::control_number, rsj::MidiMessage::message_type_byte, and rsj::MidiMessage::value.
Referenced by MidiReceiver::DispatchMessages().
RatioToPrefix()
template<class R > constexpr auto rsj::RatioToPrefix ()
    {
       if (R::num == 1) {
          switch (R::den) {
          case 1:
             return "";
          case 10:
             return "deci";
          case 100:
             return "centi";
          case 1000:
             return "milli";
          case 1000000:
             return "micro";
          case 1000000000:
             return "nano";
          case 1000000000000:
             return "pico";
          case 1000000000000000:
             return "femto";
          case 1000000000000000000:
             return "atto";
          default:
              /* empty */;
          }
       }
       if (R::den == 1) {
          switch (R::num) {
          case 10:
             return "deca";
          case 100:
             return "hecto";
          case 1000:
             return "kilo";
          case 1000000:
             return "mega";
          case 1000000000:
             return "giga";
          case 1000000000000:
             return "tera";
          case 1000000000000000:
             return "peta";
          case 1000000000000000000:
             return "exa";
          default:
              /* empty */;
          }
       }
       return "unexpected ratio encountered ";
    }
Reverse()
template<typename T > ReversionWrapper<T> rsj::Reverse (T && iterable)
    {
       return {iterable};
    }
References NumToChars().
SendKeyDownUp()
void rsj::SendKeyDownUp (const std::string & key, rsj::ActiveModifiers mods) noexcept
 {
    try {
       const auto mapped_key = kKeyMap.find(rsj::ToLower(key));
       const auto in_keymap = mapped_key != kKeyMap.end();
 #ifdef _WIN32
       BYTE vk = 0;
       rsj::ActiveModifiers vk_mod{};
       if (in_keymap)
          vk = mapped_key->second;
       else // Translate key code to keyboard-dependent scan code, may be UTF-8
          std::tie(vk, vk_mod) = KeyToVk(key);
       // construct virtual keystroke sequence
       std::vector<WORD> strokes{vk}; // start with actual key, then mods
       if (mods.shift || vk_mod.shift)
          strokes.push_back(VK_SHIFT);
       if (vk_mod.control && vk_mod.alt_opt) {
          strokes.push_back(VK_RMENU); // AltGr
          if (mods.alt_opt)
             strokes.push_back(VK_MENU);
          if (mods.control)
             strokes.push_back(VK_CONTROL);
       }
       else {
          if (mods.alt_opt || vk_mod.alt_opt)
             strokes.push_back(VK_MENU);
          if (mods.control || vk_mod.control)
             strokes.push_back(VK_CONTROL);
       }
       /* ignored for now
       // see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
       if (vk_mod.hankaku)
          strokes.push_back(VK_OEM_AUTO);*/
       WinSendKeyStrokes(strokes);
 #else
       static const pid_t lr_pid{GetPid()};
       if (!lr_pid) {
          rsj::LogAndAlertError("Unable to obtain PID for Lightroom in SendKeys.cpp");
          return;
       }
       CGKeyCode vk{0};
       CGEventFlags flags{0};
       if (in_keymap) {
          vk = mapped_key->second;
       }
       else {
          const UniChar uc{rsj::Utf8ToUtf16(key)};
          const auto key_code_result = KeyCodeForChar(uc);
          if (!key_code_result) {
             rsj::LogAndAlertError("Unsupported character was used: " + key);
             return;
          }
          vk = key_code_result->first;
          if (key_code_result->second)
             flags |= kCGEventFlagMaskShift;
       }
       if (mods.alt_opt)
          flags |= kCGEventFlagMaskAlternate;
       if (mods.command)
          flags |= kCGEventFlagMaskCommand;
       if (mods.control)
          flags |= kCGEventFlagMaskControl;
       if (mods.shift)
          flags |= kCGEventFlagMaskShift;
       MacKeyDownUp(lr_pid, vk, flags);
 #endif
    }
    catch (const std::exception& e) {
       rsj::LogAndAlertError("Exception in key sending function for key: " + key + ". " + e.what());
    }
    catch (...) {
       rsj::LogAndAlertError("Non-standard exception in key sending function for key: " + key + ".");
    }
 }
References rsj::ActiveModifiers::alt_opt, rsj::ActiveModifiers::control, and NumToChars().
SleepTimed()
template<class Rep , class Period > auto rsj::SleepTimed (const std::chrono::duration< Rep, Period > sleep_duration)
    {
       const auto start = std::chrono::high_resolution_clock::now();
       std::this_thread::sleep_for(sleep_duration);
       const auto end = std::chrono::high_resolution_clock::now();
       const std::chrono::duration<double, Period> elapsed = end - start;
       return elapsed;
    }
SleepTimedLogged()
template<class Rep , class Period > void rsj::SleepTimedLogged (std::string_view msg_prefix, const std::chrono::duration< Rep, Period > sleep_duration)
    {
       const auto elapsed = SleepTimed(sleep_duration);
       rsj::Log(juce::String(msg_prefix.data(), msg_prefix.size()) + " thread slept for "
                + juce::String(elapsed.count()) + ' ' + RatioToPrefix<Period>() + "seconds.");
    }
References NumToChars().
ToLower()
std::string rsj::ToLower (std::string_view in)
 {
    try {
       std::string s;
       s.resize(in.size());
       std::transform(in.begin(), in.end(),
           s.begin(), [](unsigned char c) noexcept { return std::tolower(c); });
       return s;
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References ExceptionResponse(), and NumToChars().
ToMessageType()
constexpr MessageType rsj::ToMessageType (short from)
    {
       if (from < 0x9 || from > 0xf)
          throw std::range_error("MessageType range error, must be 0x9 to 0xf");
       return static_cast<MessageType>(from);
    }
Translate()
void rsj::Translate (const std::string & lg)
 {
    try {
       static const std::map<std::string, const char*> kTranslationTable{{"de", de}, {"es", es},
           {"fr", fr}, {"it", it}, {"ja", ja}, {"ko", ko}, {"nl", nl}, {"pt", pt}, {"sv", sv},
           {"zh_cn", zh_cn}, {"zh_tw", zh_tw}};
       if (const auto found = kTranslationTable.find(lg); found != kTranslationTable.end()) {
          const juce::String str(juce::CharPointer_UTF8(found->second));
          auto ls = std::make_unique<juce::LocalisedStrings>(str, false);
          juce::LocalisedStrings::setCurrentMappings(ls.release()); // takes ownership of ls
       }
       else
          juce::LocalisedStrings::setCurrentMappings(nullptr);
    }
    catch (const std::exception& e) {
       rsj::ExceptionResponse(__func__, __func__, e);
       throw;
    }
 }
References ExceptionResponse(), and NumToChars().
Trim()
void rsj::Trim (std::string_view & value) noexcept
 {
    value.remove_prefix(std::min(value.find_first_not_of(" \t\n"), value.size()));
    if (const auto tr = value.find_last_not_of(" \t\n"); tr != std::string_view::npos)
       value.remove_suffix(value.size() - tr - 1);
 }
Utf8ToUtf16()
UniChar rsj::Utf8ToUtf16 (const std::string & param)
 {
    if (!param.empty()) {
       NSString* result = @(param.c_str());
       UniChar ch = [result characterAtIndex:0];
       return ch;
    }
    return 0;
 }
Variable Documentation
kInvalidNrpn
constexpr Nrpn rsj::kInvalidNrpn {false, 0, 0} static
Referenced by NrpnMessage::GetNrpnIfReady().