MIDI2LR: gsl Namespace Reference
gsl Namespace Reference
Namespaces
detail
Classes
class Final_act
struct narrowing_error
class not_null
struct owner
class span
Typedefs
typedef unsigned char byte
typedef span< const char > cstring_span
typedef span< const wchar_t > cwstring_span
typedef const wchar_t * cwzstring
typedef const char * czstring
typedef span< char > string_span
typedef span< wchar_t > wstring_span
typedef char * zstring
typedef wchar_t * zwstring
Functions
template<typename T >
gsl_api gsl_constexpr14 span< T > as_span (T *begin, T *end)
template<typename T >
gsl_api gsl_constexpr14 span< T > as_span (T *begin, size_t size)
template<typename T , size_t N>
gsl_api gsl_constexpr14 span< T > as_span (T(&arr)[N])
template<class T >
gsl_api span< T > as_span (std::vector< T > &cont)
template<class T , size_t N>
gsl_api T & at (T(&arr)[N], size_t index)
template<class Cont >
gsl_api Cont::value_type & at (Cont &cont, size_t index)
template<class T >
gsl_api span< T > ensure_z (T *const &sz, size_t max=std::numeric_limits< size_t >::max())
template<class T , size_t N>
gsl_api span< T > ensure_z (T(&sz)[N])
gsl_api void fail_fast_assert (bool cond)
gsl_api void fail_fast_assert (bool cond, char const *const)
template<class Fn >
gsl_api Final_act finally (Fn const &f)
template<class T , class U >
gsl_api T narrow (U u)
template<class T , class U >
gsl_api T narrow_cast (U u) gsl_noexcept
gsl_api std::string to_string (string_span const &view)
gsl_api std::string to_string (cstring_span const &view)
gsl_api std::wstring to_string (wstring_span const &view)
gsl_api std::wstring to_string (cwstring_span const &view)
Typedef Documentation
typedef unsigned char gsl::byte
Definition at line 477 of file GSL.h.
typedef span< const char > gsl::cstring_span
Definition at line 811 of file GSL.h.
typedef span< const wchar_t > gsl::cwstring_span
Definition at line 812 of file GSL.h.
typedef const wchar_t* gsl::cwzstring
Definition at line 807 of file GSL.h.
typedef const char* gsl::czstring
Definition at line 806 of file GSL.h.
typedef span< char > gsl::string_span
Definition at line 809 of file GSL.h.
typedef span< wchar_t > gsl::wstring_span
Definition at line 810 of file GSL.h.
typedef char* gsl::zstring
Definition at line 804 of file GSL.h.
typedef wchar_t* gsl::zwstring
Definition at line 805 of file GSL.h.
Function Documentation
template<typename T > gsl_api gsl_constexpr14 span<T> gsl::as_span (T * begin, T * end)
Definition at line 767 of file GSL.h.
References as_span().
template<typename T > gsl_api gsl_constexpr14 span<T> gsl::as_span (T * begin, size_t size)
Definition at line 772 of file GSL.h.
References as_span().
template<typename T , size_t N> gsl_api gsl_constexpr14 span<T> gsl::as_span (T(&) arr[N])
Definition at line 777 of file GSL.h.
References as_span().
template<class T > gsl_api span<T> gsl::as_span (std::vector< T > & cont)
Definition at line 795 of file GSL.h.
References as_span().
Referenced by as_span(), at(), ensure_z(), gsl::Final_act::Final_act(), finally(), narrow(), narrow_cast(), and gsl::Final_act::~Final_act().
template<class T , size_t N> gsl_api T& gsl::at (T(&) arr[N], size_t index)
Definition at line 359 of file GSL.h.
References as_span().
template<class Cont > gsl_api Cont::value_type& gsl::at (Cont & cont, size_t index)
Definition at line 374 of file GSL.h.
References as_span().
template<class T > gsl_api span<T> gsl::ensure_z (T *const & sz, size_t max = std::numeric_limits<size_t>::max()) inline
Definition at line 863 of file GSL.h.
References as_span().
template<class T , size_t N> gsl_api span<T> gsl::ensure_z (T(&) sz[N])
Definition at line 868 of file GSL.h.
References as_span().
gsl_api void gsl::fail_fast_assert (bool cond) inline
Definition at line 249 of file GSL.h.
gsl_api void gsl::fail_fast_assert (bool cond, char const * const) inline
Definition at line 254 of file GSL.h.
template<class Fn > gsl_api Final_act gsl::finally (Fn const & f)
Definition at line 309 of file GSL.h.
References as_span().
template<class T , class U > gsl_api T gsl::narrow (U u)
Definition at line 331 of file GSL.h.
References as_span().
template<class T , class U > gsl_api T gsl::narrow_cast (U u)
Definition at line 316 of file GSL.h.
References as_span().
gsl_api std::string gsl::to_string (string_span const & view) inline
Definition at line 816 of file GSL.h.
gsl_api std::string gsl::to_string (cstring_span const & view) inline
Definition at line 820 of file GSL.h.
gsl_api std::wstring gsl::to_string (wstring_span const & view) inline
Definition at line 824 of file GSL.h.
gsl_api std::wstring gsl::to_string (cwstring_span const & view) inline
Definition at line 828 of file GSL.h.