MIDI2LR: MIDI_Message_ID Struct Reference
MIDI_Message_ID Struct Reference
#include <CommandMap.h>
Public Member Functions
MIDI_Message_ID ()
MIDI_Message_ID (int ch, int dat, MessageType msgType)
bool operator< (const MIDI_Message_ID &other) const noexcept
bool operator== (const MIDI_Message_ID &other) const noexcept
Public Attributes
union {
int controller
int data
int pitch
};
int channel
MessageType messageType
Detailed Description
Definition at line 36 of file CommandMap.h.
Constructor & Destructor Documentation
MIDI_Message_ID::MIDI_Message_ID () inline
Definition at line 45 of file CommandMap.h.
References channel, messageType, and NOTE.
MIDI_Message_ID::MIDI_Message_ID (int ch, int dat, MessageType msgType) inline
Definition at line 52 of file CommandMap.h.
References channel, and messageType.
Referenced by CommandTableModel::addRow(), ProfileManager::handleMIDI(), and LR_IPC_OUT::handleMIDI().
Member Function Documentation
bool MIDI_Message_ID::operator< (const MIDI_Message_ID & other) const inline noexcept
Definition at line 61 of file CommandMap.h.
References channel, and messageType.
bool MIDI_Message_ID::operator== (const MIDI_Message_ID & other) const inline noexcept
Definition at line 57 of file CommandMap.h.
References channel, and messageType.
Member Data Documentation
union { ... }
int MIDI_Message_ID::channel
Definition at line 38 of file CommandMap.h.
Referenced by MIDI_Message_ID(), operator<(), and operator==().
int MIDI_Message_ID::controller
Definition at line 40 of file CommandMap.h.
int MIDI_Message_ID::data
Definition at line 42 of file CommandMap.h.
MessageType MIDI_Message_ID::messageType
Definition at line 37 of file CommandMap.h.
Referenced by MIDI_Message_ID(), operator<(), and operator==().
int MIDI_Message_ID::pitch
Definition at line 41 of file CommandMap.h.
The documentation for this struct was generated from the following file:
Q:/Documents/GitHub/MIDI2LR/Source/CommandMap.h