MIDI2LR: Devices::DevInfo Struct Reference
Devices::DevInfo Struct Reference
Public Member Functions
DevInfo (const juce::MidiDeviceInfo &info, juce::String io) noexcept
DevInfo (juce::String n, juce::String i, juce::String io) noexcept
Public Attributes
juce::String i_o
juce::String identifier
juce::String name
Friends
bool operator!= (const DevInfo &lhs, const DevInfo &rhs) noexcept
bool operator< (const DevInfo &lhs, const DevInfo &rhs) noexcept
bool operator<= (const DevInfo &lhs, const DevInfo &rhs) noexcept
bool operator== (const DevInfo &lhs, const DevInfo &rhs) noexcept
bool operator> (const DevInfo &lhs, const DevInfo &rhs) noexcept
bool operator>= (const DevInfo &lhs, const DevInfo &rhs) noexcept
Constructor & Destructor Documentation
DevInfo() [1/2]
Devices::DevInfo::DevInfo (const juce::MidiDeviceInfo & info, juce::String io) inline noexcept
          : name {info.name}, identifier {info.identifier}, i_o {std::move(io)}
      {
      }
References DevInfo().
Referenced by DevInfo().
DevInfo() [2/2]
Devices::DevInfo::DevInfo (juce::String n, juce::String i, juce::String io) inline noexcept
          : name {std::move(n)}, identifier {std::move(i)}, i_o {std::move(io)}
      {
      }
References DevInfo().
Referenced by DevInfo().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const DevInfo & lhs, const DevInfo & rhs) friend
      {
         return !(lhs == rhs);
      }
References operator==.
operator<
bool operator< (const DevInfo & lhs, const DevInfo & rhs) friend
      {
         if (lhs.name < rhs.name) { return true; }
         if (rhs.name < lhs.name) { return false; }
         if (lhs.identifier < rhs.identifier) { return true; }
         if (rhs.identifier < lhs.identifier) { return false; }
         return lhs.i_o < rhs.i_o;
      }
Referenced by operator<=, operator>, and operator>=.
operator<=
bool operator<= (const DevInfo & lhs, const DevInfo & rhs) friend
      {
         return !(rhs < lhs);
      }
References operator<.
operator==
bool operator== (const DevInfo & lhs, const DevInfo & rhs) friend
      {
         return lhs.name == rhs.name && lhs.identifier == rhs.identifier && lhs.i_o == rhs.i_o;
      }
Referenced by operator!=.
operator>
bool operator> (const DevInfo & lhs, const DevInfo & rhs) friend
      {
         return rhs < lhs;
      }
References operator<.
operator>=
bool operator>= (const DevInfo & lhs, const DevInfo & rhs) friend
      {
         return !(lhs < rhs);
      }
References operator<.
Member Data Documentation
i_o
juce::String Devices::DevInfo::i_o
identifier
juce::String Devices::DevInfo::identifier
name
juce::String Devices::DevInfo::name
The documentation for this struct was generated from the following file:
C:/Users/rsjaf/source/repos/MIDI2LR/src/application/Devices.h