MIDI2LR: RSJ::MidiMessageId Struct Reference
RSJ::MidiMessageId Struct Reference
#include <MidiUtilities.h>
Public Member Functions
constexpr MidiMessageId () noexcept
constexpr MidiMessageId (int ch, int dat, MsgIdEnum msgType) noexcept
MidiMessageId (const MidiMessage &rhs) noexcept(ndebug)
constexpr bool operator< (const MidiMessageId &other) const noexcept
constexpr bool operator== (const MidiMessageId &other) const noexcept
Public Attributes
union {
int controller
int data
int pitch
};
int channel
MsgIdEnum msg_id_type
Detailed Description
Definition at line 57 of file MidiUtilities.h.
Constructor & Destructor Documentation
constexpr RSJ::MidiMessageId::MidiMessageId () inline noexcept
Definition at line 66 of file MidiUtilities.h.
References channel, msg_id_type, and RSJ::NOTE.
constexpr RSJ::MidiMessageId::MidiMessageId (int ch, int dat, MsgIdEnum msgType) inline noexcept
Definition at line 73 of file MidiUtilities.h.
References channel, and msg_id_type.
Referenced by CommandTableModel::addRow(), and CommandTableModel::getRowForMessage().
RSJ::MidiMessageId::MidiMessageId (const MidiMessage & rhs) noexcept
Definition at line 56 of file MidiUtilities.cpp.
References RSJ::CC, RSJ::MidiMessage::channel, channel, RSJ::kCCFlag, RSJ::kNoteOnFlag, RSJ::kPWFlag, RSJ::MidiMessage::message_type_byte, msg_id_type, RSJ::NOTE, RSJ::MidiMessage::number, and RSJ::PITCHBEND.
Referenced by LR_IPC_OUT::MIDIcmdCallback().
Member Function Documentation
constexpr bool RSJ::MidiMessageId::operator< (const MidiMessageId & other) const inline noexcept
Definition at line 86 of file MidiUtilities.h.
References channel, and msg_id_type.
constexpr bool RSJ::MidiMessageId::operator== (const MidiMessageId & other) const inline noexcept
Definition at line 81 of file MidiUtilities.h.
References channel, and msg_id_type.
Member Data Documentation
union { ... }
int RSJ::MidiMessageId::channel
Definition at line 59 of file MidiUtilities.h.
Referenced by MidiMessageId(), operator<(), and operator==().
int RSJ::MidiMessageId::controller
Definition at line 61 of file MidiUtilities.h.
int RSJ::MidiMessageId::data
Definition at line 63 of file MidiUtilities.h.
MsgIdEnum RSJ::MidiMessageId::msg_id_type
Definition at line 58 of file MidiUtilities.h.
Referenced by MidiMessageId(), operator<(), and operator==().
int RSJ::MidiMessageId::pitch
Definition at line 62 of file MidiUtilities.h.
The documentation for this struct was generated from the following files:
Q:/Documents/GitHub/MIDI2LR/Source/MidiUtilities.h
Q:/Documents/GitHub/MIDI2LR/Source/MidiUtilities.cpp