MIDI2LR: rsj::SettingsStruct Struct Reference
rsj::SettingsStruct Struct Reference
#include <ControlsModel.h>
Public Member Functions
SettingsStruct (short n=0, short l=0, short h=0x7F, rsj::CCmethod m=rsj::CCmethod::kAbsolute) noexcept
template<class Archive , cereal::traits::DisableIf< cereal::traits::is_text_archive< Archive >::value > = cereal::traits::sfinae>
void serialize (Archive &archive, uint32_t const version)
template<class Archive , cereal::traits::EnableIf< cereal::traits::is_text_archive< Archive >::value > = cereal::traits::sfinae>
void serialize (Archive &archive, uint32_t const version)
Public Attributes
short high
short low
rsj::CCmethod method
short number
Constructor & Destructor Documentation
SettingsStruct()
rsj::SettingsStruct::SettingsStruct (short n = 0, short l = 0, short h = 0x7F, rsj::CCmethod m = rsj::CCmethod::kAbsolute) inline noexcept
           : number{n}, low{l}, high{h}, method{m}
       {
       }
References number.
Member Function Documentation
serialize() [1/2]
template<class Archive , cereal::traits::DisableIf< cereal::traits::is_text_archive< Archive >::value > = cereal::traits::sfinae> void rsj::SettingsStruct::serialize (Archive & archive, uint32_t const version) inline
       {
          switch (version) {
          case 1:
             archive(number, high, low, method);
             break;
          default:
             rsj::LogAndAlertError("Wrong archive number for SettingsStruct");
          }
       }
References serialize().
serialize() [2/2]
template<class Archive , cereal::traits::EnableIf< cereal::traits::is_text_archive< Archive >::value > = cereal::traits::sfinae> void rsj::SettingsStruct::serialize (Archive & archive, uint32_t const version) inline
       {
          switch (version) {
          case 1: {
             std::string methodstr{"undefined"};
             switch (method) {
             case CCmethod::kAbsolute:
                methodstr = "Absolute";
                break;
             case CCmethod::kBinaryOffset:
                methodstr = "BinaryOffset";
                break;
             case CCmethod::kSignMagnitude:
                methodstr = "SignMagnitute";
                break;
             case CCmethod::kTwosComplement:
                methodstr = "TwosComplement";
             default:
                break; // leave "undefined"
             }
             archive(cereal::make_nvp("CC", number), CEREAL_NVP(high), CEREAL_NVP(low),
                 cereal::make_nvp("method", methodstr));
             switch (methodstr.front()) {
             case 'B':
                method = CCmethod::kBinaryOffset;
                break;
             case 'S':
                method = CCmethod::kSignMagnitude;
                break;
             case 'T':
                method = CCmethod::kTwosComplement;
                break;
             case 'A':
             default:
                method = CCmethod::kAbsolute;
                break;
             }
             break;
          }
          default:
             rsj::LogAndAlertError("Wrong archive number for SettingsStruct");
          }
       }
References serialize().
Referenced by serialize().
Member Data Documentation
high
short rsj::SettingsStruct::high
low
short rsj::SettingsStruct::low
method
rsj::CCmethod rsj::SettingsStruct::method
number
short rsj::SettingsStruct::number
Referenced by SettingsStruct().
The documentation for this struct was generated from the following file:
D:/Users/Rory/source/repos/MIDI2LR/Source/ControlsModel.h