MIDI2LR: MIDI_Message Struct Reference
MIDI_Message Struct Reference
encapsulates a MIDI message (Note or CC)
#include <CommandMap.h>
Public Member Functions
MIDI_Message ()
MIDI_Message (int ch, int dat, bool iscc)
bool operator== (const MIDI_Message &other) const
Public Attributes
union {
int controller
int data
int pitch
};
int channel
bool isCC
bool isNRPN
bool isRelative
Detailed Description
encapsulates a MIDI message (Note or CC)
Definition at line 38 of file CommandMap.h.
Constructor & Destructor Documentation
MIDI_Message::MIDI_Message () inline
Definition at line 50 of file CommandMap.h.
References channel, isCC, isNRPN, and isRelative.
MIDI_Message::MIDI_Message (int ch, int dat, bool iscc) inline
Definition at line 59 of file CommandMap.h.
References channel, isCC, isNRPN, and isRelative.
Referenced by CommandTableModel::addRow(), ProfileManager::handleMidiCC(), LR_IPC_OUT::handleMidiCC(), ProfileManager::handleMidiNote(), and LR_IPC_OUT::handleMidiNote().
Member Function Documentation
bool MIDI_Message::operator== (const MIDI_Message & other) const inline
Definition at line 66 of file CommandMap.h.
References channel, and isCC.
Member Data Documentation
union { ... }
int MIDI_Message::channel
Definition at line 43 of file CommandMap.h.
Referenced by MIDI_Message(), and operator==().
int MIDI_Message::controller
Definition at line 45 of file CommandMap.h.
int MIDI_Message::data
Definition at line 47 of file CommandMap.h.
bool MIDI_Message::isCC
Definition at line 40 of file CommandMap.h.
Referenced by MIDI_Message(), and operator==().
bool MIDI_Message::isNRPN
Definition at line 41 of file CommandMap.h.
Referenced by MIDI_Message().
bool MIDI_Message::isRelative
Definition at line 42 of file CommandMap.h.
Referenced by MIDI_Message().
int MIDI_Message::pitch
Definition at line 46 of file CommandMap.h.
The documentation for this struct was generated from the following file:
Q:/Documents/GitHub/MIDI2LR/Source/CommandMap.h