MIDI2LR: ResizableLayout::Rect Struct Reference
ResizableLayout::Rect Struct Reference
Public Member Functions
Rect () noexcept
Rect (int top0, int left0, int bottom0, int right0) noexcept
Rect (const juce::Rectangle< int > &r) noexcept
int getHeight () const noexcept
int getWidth () const noexcept
operator juce::Rectangle< int > () const noexcept
void reduce (int dx, int dy) noexcept
Public Attributes
int bottom {0}
int left {0}
int right {0}
int top {0}
Constructor & Destructor Documentation
Rect() [1/3]
ResizableLayout::Rect::Rect () inline noexcept
         {}
Rect() [2/3]
ResizableLayout::Rect::Rect (int top0, int left0, int bottom0, int right0) inline noexcept
                                                                    : top{top0},
             left{left0}, bottom{bottom0}, right{right0}
         {}
Rect() [3/3]
ResizableLayout::Rect::Rect (const juce::Rectangle< int > & r) inline noexcept
                                                    : top{int(r.getY())},
             left{int(r.getX())}, bottom{int(r.getBottom())},
             right{int(r.getRight())}
         {}
Member Function Documentation
getHeight()
int ResizableLayout::Rect::getHeight () const inline noexcept
References reduce().
         {
             return bottom - top;
         }
getWidth()
int ResizableLayout::Rect::getWidth () const inline noexcept
References reduce().
         {
             return right - left;
         }
operator juce::Rectangle< int >()
ResizableLayout::Rect::operator juce::Rectangle< int > () const inline noexcept
References reduce().
         {
             return juce::Rectangle<int>(left, top, getWidth(), getHeight());
         }
reduce()
void ResizableLayout::Rect::reduce (int dx, int dy) inline noexcept
References reduce().
Referenced by ResizableLayout::addStateFor(), getHeight(), getWidth(), operator juce::Rectangle< int >(), ResizableLayout::recalculateLayout(), and reduce().
         {
             top += dy; left += dx; bottom -= dy; right -= dx;
         }
Member Data Documentation
bottom
int ResizableLayout::Rect::bottom {0}
left
int ResizableLayout::Rect::left {0}
right
int ResizableLayout::Rect::right {0}
top
int ResizableLayout::Rect::top {0}
The documentation for this struct was generated from the following file:
Q:/Documents/GitHub/MIDI2LR/Source/ResizableLayout.h