--[[----------------------------------------------------------------------------

Develop_Params.lua

List of develop params

------------------------------------------------------------------------------]]

DEVELOP_PARAMS = {
    'Temperature',
    'Tint',
    'Exposure',
    'Highlights',
    'Shadows',
    'Contrast',
    'Whites',
    'Blacks',
    'Clarity',
    'Vibrance',
    'Saturation',
    -- Tone
    'ParametricDarks',
    'ParametricLights',
    'ParametricShadows',
    'ParametricHighlights',
    'ParametricShadowSplit',
    'ParametricMidtoneSplit',
    'ParametricHighlightSplit',
    -- Mixer
    'SaturationAdjustmentRed',
    'SaturationAdjustmentOrange',
    'SaturationAdjustmentYellow',
    'SaturationAdjustmentGreen',
    'SaturationAdjustmentAqua',
    'SaturationAdjustmentBlue',
    'SaturationAdjustmentPurple',
    'SaturationAdjustmentMagenta',
    'HueAdjustmentRed',
    'HueAdjustmentOrange',
    'HueAdjustmentYellow',
    'HueAdjustmentGreen',
    'HueAdjustmentAqua',
    'HueAdjustmentBlue',
    'HueAdjustmentPurple',
    'HueAdjustmentMagenta',
    'LuminanceAdjustmentRed',
    'LuminanceAdjustmentOrange',
    'LuminanceAdjustmentYellow',
    'LuminanceAdjustmentGreen',
    'LuminanceAdjustmentAqua',
    'LuminanceAdjustmentBlue',
    'LuminanceAdjustmentPurple',
    'LuminanceAdjustmentMagenta',
    'GrayMixerRed',
    'GrayMixerOrange',
    'GrayMixerYellow',
    'GrayMixerGreen',
    'GrayMixerAqua',
    'GrayMixerBlue',
    'GrayMixerPurple',
    'GrayMixerMagenta',
    -- Split Toning
    'SplitToningShadowHue',
    'SplitToningShadowSaturation',
    'SplitToningHighlightHue',
    'SplitToningHighlightSaturation',
    'SplitToningBalance',
    -- Detail
    'Sharpness',
    'SharpenRadius',
    'SharpenDetail',
    'SharpenEdgeMasking',
    'LuminanceSmoothing',
    'LuminanceNoiseReductionDetail',
    'LuminanceNoiseReductionContrast',
    'ColorNoiseReduction',
    'ColorNoiseReductionDetail',
    'ColorNoiseReductionSmoothness',
    -- Lens Correction
    'LensProfileDistortionScale',
    'LensProfileChromaticAberrationScale',
    'LensProfileVignettingScale',
    'LensManualDistortionAmount',
    'DefringePurpleAmount',
    'DefringePurpleHueLo',
    'DefringePurpleHueHi',
    'DefringeGreenAmount',
    'DefringeGreenHueLo',
    'DefringeGreenHueHi',
    'PerspectiveVertical',
    'PerspectiveHorizontal',
    'PerspectiveRotate',
    'PerspectiveScale',
    'PerspectiveAspect',
    'PerspectiveUpright',
    -- Effects
    'Dehaze',
    'PostCropVignetteAmount',
    'PostCropVignetteMidpoint',
    'PostCropVignetteFeather',
    'PostCropVignetteRoundness',
    'PostCropVignetteStyle',
    'PostCropVignetteHighlightContrast',
    'GrainAmount',
    'GrainSize',
    'GrainFrequency',
    -- Calibrate
    'ShadowTint',
    'RedHue',
    'RedSaturation',
    'GreenHue',
    'GreenSaturation',
    'BlueHue',
    'BlueSaturation',
}