--[[----------------------------------------------------------------------------

MenuListPreTrans.lua
Source of translations and menu for app and plugin
 
This file is part of MIDI2LR. Copyright 2015-2016 by Rory Jaffe.

MIDI2LR is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

MIDI2LR is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
MIDI2LR.  If not, see <http://www.gnu.org/licenses/>. 
------------------------------------------------------------------------------]]

--local function LOC(str) return str end--for debugging

local basicTone = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone")
local calibration = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration")
local colorAdjustments = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments")
local crop = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")
local detail = LOC("$$$/AgDevelop/Panel/Detail=Detail")
local developPreset = LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")
local developPresets = LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets")
local effects = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects")
local gotoToolModulePanel = "Go to Tool, Module, or Panel"
local lensCorrections = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections")
local localizedAdjustments = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LocalAdjustments=Local Adjustments")
local miscellaneous = "Miscellaneous"
local photoActions = "Photo Actions"
local primaryDisplay = LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")
local profile = LOC("$$$/AgDevelop/CameraRawPanel/Profile=Profile:")
local profiles = LOC("$$$/CRaw/Style/Profiles=Profiles")
local reset = LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")
local resetColorAdjustments = reset..' '..colorAdjustments
local secondaryDisplay = LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")
local show = LOC("$$$/AgLibrary/LibraryInfo/Show=Show")
local splitToning = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning")
local toneCurve = LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve")
local viewModes = LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes")
local whiteBalance = LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")

--[[----------------------------------------------------------------------------

MenuList structure
>command
>user-friendly name
>menu group
>button or variable (true if button)
>include in selective paste settings (true if include) [exclude localized adj]
>include in send back values to MIDI controller (true if send back)
>Documentation right column
>experimental (true/false), results in user-friendly name flagged in documentation

Need another structure containing items not included in Menulist (primarily items
from copy/paste selective that are arrays, but also items that are continuous
in lightroom but assigned to buttons in app (e.g., upright mode). These items 
would be added to copy/paste options but not send back values.

unicode to UTF8 decimal mapping at http://www.utf8-chartable.de/unicode-utf8-table.pl
local interrobang = '\226\128\189'
local referencemark = '\226\128\187'
local ldquo = '\226\128\156'
local rdquo = '\226\128\157'
local lsquo = '\226\128\152'
local rsquo = '\226\128\153'
local mdash = '\226\128\148'
------------------------------------------------------------------------------]]

local DataBase = {
  {"WhiteBalanceAs_Shot",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/AsShot=As Shot"),
    basicTone,
    true,
    false,
    false,
    "Use Temperature and Tint as determined by camera. *button*",
    true},
  {"WhiteBalanceAuto",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Auto=Auto"),
    basicTone,
    true,
    false,
    false,
    "Have Lightroom determine Temperature and Tint. *button*",
    true},
  {"WhiteBalanceCloudy",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Cloudy=Cloudy"),
    basicTone,
    true,
    false,
    false,
    "Use cloudy white balance. *button*",
    true},
  {"WhiteBalanceDaylight",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Daylight=Daylight"),
    basicTone,
    true,
    false,
    false,
    "Use daylight white balance. *button*",
    true},
  {"WhiteBalanceFlash",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Flash=Flash"),
    basicTone,
    true,
    false,
    false,
    "Use flash white balance. *button*",
    true},
  {"WhiteBalanceFluorescent",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Fluorescent=Fluorescent"),
    basicTone,
    true,
    false,
    false,
    "Use fluorescent white balance. *button*",
    true},
  {"WhiteBalanceShade",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Shade=Shade"),
    basicTone,
    true,
    false,
    false,
    "Use shade white balance. *button*",
    true},
  {"WhiteBalanceTungsten",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Tungsten=Tungsten"),
    basicTone,
    true,
    false,
    false,
    "Use tungsten white balance. *button*",
    true},
  {"Temperature",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Temperature=Temperature"),
    basicTone,
    false,
    true,
    true,
    "Fine-tunes the white balance using the Kelvin color temperature scale. Move the slider to the left to make the photo appear cooler, and right to warm the photo colors.",
    false},
  {"Tint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Tint=Tint"),
    basicTone,
    false,
    true,
    true,
    "Fine-tunes the white balance to compensate for a green or magenta tint. Move the slider to the left (negative values) to add green to the photo; move it to the right (positive values) to add magenta.",
    false},
  {"Exposure",
    LOC("$$$/AgCameraRawUI/Exposure=Exposure"),
    basicTone,
    false,
    true,
    true,
    "Sets the overall image brightness. Adjust the slider until the photo looks good and the image is the desired brightness.",
    false},
  {"Contrast",
    LOC("$$$/AgCameraRawUI/Contrast=Contrast"),
    basicTone,
    false,
    true,
    true,
    "Increases or decreases image contrast, mainly affecting midtones. When you increase contrast, the middle-to-dark image areas become darker, and the middle-to-light image areas become lighter. The image tones are inversely affected as you decrease contrast.",
    false},
  {"Highlights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Highlights=Highlights")..'(Recovery in PV2003 and PV2010)',
    basicTone,
    false,
    true,
    true,
    "Adjusts bright image areas. Drag to the left to darken highlights and recover \226\128\156blown out\226\128\157 highlight details. Drag to the right to brighten highlights while minimizing clipping.",
    false},
  {"Shadows",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Shadows=Shadows")..'(Fill Light in PV2003 and PV2010)',
    basicTone,
    false,
    true,
    true,
    "Adjusts dark image areas. Drag to the left to darken shadows while minimizing clipping. Drag to the right to brighten shadows and recover shadow details.",
    false},
  {"Whites",
    LOC("$$$/AgCameraRawUI/Whites=Whites")..'(no effect in PV2003 and PV2010)',
    basicTone,
    false,
    true,
    true,
    "Adjusts white clipping. Drag to the left to reduce clipping in highlights. Drag to the right to increase highlight clipping.",
    false},
  {"Blacks",
    LOC("$$$/AgCameraRawUI/Blacks=Blacks"),
    basicTone,
    false,
    true,
    true,
    "Specifies which image values map to black. Moving the slider to the right increases the areas that become black, sometimes creating the impression of increased image contrast. The greatest effect is in the shadows, with much less change in the midtones and highlights.",
    false},
  {"Clarity",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Clarity=Clarity"),
    basicTone,
    false,
    true,
    true,
    "Adds depth to an image by increasing local contrast. When using this setting, it is best to zoom in to 100% or greater.",
    false},
  {"Vibrance",
    LOC("$$$/AgCameraRawUI/Vibrance=Vibrance"),
    basicTone,
    false,
    true,
    true,
    "Adjusts the saturation so that clipping is minimized as colors approach full saturation, changing the saturation of all lower-saturated colors with less effect on the higher-saturated colors. Vibrance also prevents skin tones from becoming over saturated.",
    false},
  {"Saturation",
    LOC("$$$/AgCameraRawUI/Saturation=Saturation"),
    basicTone,
    false,
    true,
    true,
    "Adjusts the saturation of all image colors equally from â€“100 (monochrome) to +100 (double the saturation).",
    false},
  {"ResetTemperature",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Temperature=Temperature"),
    basicTone,
    true,
    false,
    false},
  {"ResetTint",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Tint=Tint"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetExposure",
    reset..' '..LOC("$$$/AgCameraRawUI/Exposure=Exposure"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetContrast",
    reset..' '..LOC("$$$/AgCameraRawUI/Contrast=Contrast"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHighlights",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Highlights=Highlights"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetShadows",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Shadows=Shadows"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetWhites",
    reset..' '..LOC("$$$/AgCameraRawUI/Whites=Whites"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetBlacks",
    reset..' '..LOC("$$$/AgCameraRawUI/Blacks=Blacks"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetClarity",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Clarity=Clarity"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetVibrance",
    reset..' '..LOC("$$$/AgCameraRawUI/Vibrance=Vibrance"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSaturation",
    reset..' '..LOC("$$$/AgCameraRawUI/Saturation=Saturation"),
    basicTone,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ParametricDarks",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneDarks=Dark Tones"),
    toneCurve,
    false,
    true,
    true,
    "Adjust darks.",
    false},
  {"ParametricLights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneLights=Light Tones"),
    toneCurve,
    false,
    true,
    true,
    "Adjust lights.",
    false},
  {"ParametricShadows",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadows=Shadow Tones"),
    toneCurve,
    false,
    true,
    true,
    "Adjust shadows.",
    false},
  {"ParametricHighlights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlights=Highlight Tones"),
    toneCurve,
    false,
    true,
    true,
    "Adjust highlights.",
    false},
  {"ParametricShadowSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadowSplit=Shadow Split"),
    toneCurve,
    false,
    true,
    true,
    "Move division between shadows and darks.",
    false},
  {"ParametricMidtoneSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneMidtoneSplit=Midtone Split"),
    toneCurve,
    false,
    true,
    true,
    "Move division between darks and lights.",
    false},
  {"ParametricHighlightSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlightSplit=Highlight Split"),
    toneCurve,
    false,
    true,
    true,
    "Move division between lights and highlights.",
    false},
  {"ResetParametricDarks",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneDarks=Dark Tones"), 
    toneCurve,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetParametricLights",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneLights=Light Tones"),
    toneCurve,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetParametricShadows",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadows=Shadow Tones"),
    toneCurve,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetParametricHighlights",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlights=Highlight Tones"),
    toneCurve,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetParametricShadowSplit",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadowSplit=Shadow Split"),
    toneCurve,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetParametricMidtoneSplit",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneMidtoneSplit=Midtone Split"),
    toneCurve,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetParametricHighlightSplit",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlightSplit=Highlight Split"),
    toneCurve,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"EnableColorAdjustments",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableColorAdjustments=Enable Color Adjustments"),
    colorAdjustments,
    true,
    false,
    false,
    "Enable or disable color adjustments. *button*",
    true},
  {"SaturationAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentRed=Saturation Adjustment Red"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color vividness or purity of the color.",
    false},
  {"SaturationAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentOrange=Saturation Adjustment Orange"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color vividness or purity of the color.",
    false},
  {"SaturationAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentYellow=Saturation Adjustment Yellow"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color vividness or purity of the color.",
    false},
  {"SaturationAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentGreen=Saturation Adjustment Green"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color vividness or purity of the color.",
    false},
  {"SaturationAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentAqua=Saturation Adjustment Aqua"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color vividness or purity of the color.",
    false},
  {"SaturationAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentBlue=Saturation Adjustment Blue"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color vividness or purity of the color.",
    false},
  {"SaturationAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentPurple=Saturation Adjustment Purple"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color vividness or purity of the color.",
    false},
  {"SaturationAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentMagenta=Saturation Adjustment Magenta"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color vividness or purity of the color.",
    false},
  {"HueAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentRed=Hue Adjustment Red"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color.",
    false},
  {"HueAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentOrange=Hue Adjustment Orange"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color.",
    false},
  {"HueAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentYellow=Hue Adjustment Yellow"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color.",
    false},
  {"HueAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentGreen=Hue Adjustment Green"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color.",
    false},
  {"HueAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentAqua=Hue Adjustment Aqua"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color.",
    false},
  {"HueAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentBlue=Hue Adjustment Blue"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color.",
    false},
  {"HueAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentPurple=Hue Adjustment Purple"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color.",
    false},
  {"HueAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentMagenta=Hue Adjustment Magenta"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the color.",
    false},
  {"LuminanceAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentRed=Luminance Adjustment Red"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the brightness of the color range.",
    false},
  {"LuminanceAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentOrange=Luminance Adjustment Orange"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the brightness of the color range.",
    false},
  {"LuminanceAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentYellow=Luminance Adjustment Yellow"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the brightness of the color range.",
    false},
  {"LuminanceAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentGreen=Luminance Adjustment Green"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the brightness of the color range.",
    false},
  {"LuminanceAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentAqua=Luminance Adjustment Aqua"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the brightness of the color range.",
    false},
  {"LuminanceAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentBlue=Luminance Adjustment Blue"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the brightness of the color range.",
    false},
  {"LuminanceAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentPurple=Luminance Adjustment Purple"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the brightness of the color range.",
    false},
  {"LuminanceAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentMagenta=Luminance Adjustment Magenta"),
    colorAdjustments,
    false,
    true,
    true,
    "Changes the brightness of the color range.",
    false},
  {"ConvertToGrayscale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ConvertToGrayscale=Convert to Grayscale"),
    colorAdjustments,
    true,
    false,
    false,
    "Enable/disable gray scale conversion. *button*",
    true},
  {"EnableGrayscaleMix",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableGrayscaleMix=Enable Grayscale Mix"),
    colorAdjustments,
    true,
    false,
    false,
    "Enable or disable black and white mix. *button*",
    true},
  {"GrayMixerRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerRed=Gray Mixer Red"),
    colorAdjustments,
    false,
    true,
    true,
    "Red contribution to luminance.",
    false},
  {"GrayMixerOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerOrange=Gray Mixer Orange"),
    colorAdjustments,
    false,
    true,
    true,
    "Orange contribution to luminance.",
    false},
  {"GrayMixerYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerYellow=Gray Mixer Yellow"),
    colorAdjustments,
    false,
    true,
    true,
    "Yellow contribution to luminance.",
    false},
  {"GrayMixerGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerGreen=Gray Mixer Green"),
    colorAdjustments,
    false,
    true,
    true,
    "Green contribution to luminance.",
    false},
  {"GrayMixerAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerAqua=Gray Mixer Aqua"),
    colorAdjustments,
    false,
    true,
    true,
    "Aqua contribution to luminance.",
    false},
  {"GrayMixerBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerBlue=Gray Mixer Blue"),
    colorAdjustments,
    false,
    true,
    true,
    "Blue contribution to luminance.",
    false},
  {"GrayMixerPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerPurple=Gray Mixer Purple"),
    colorAdjustments,
    false,
    true,
    true,
    "Purple contribution to luminance.",
    false},
  {"GrayMixerMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerMagenta=Gray Mixer Magenta"),
    colorAdjustments,
    false,
    true,
    true,
    "Magenta contribution to luminance.",
    false},
  {"ResetSaturationAdjustmentRed",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentRed=Saturation Adjustment Red"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSaturationAdjustmentOrange",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentOrange=Saturation Adjustment Orange"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSaturationAdjustmentYellow",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentYellow=Saturation Adjustment Yellow"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSaturationAdjustmentGreen",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentGreen=Saturation Adjustment Green"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSaturationAdjustmentAqua",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentAqua=Saturation Adjustment Aqua"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSaturationAdjustmentBlue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentBlue=Saturation Adjustment Blue"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSaturationAdjustmentPurple",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentPurple=Saturation Adjustment Purple"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSaturationAdjustmentMagenta",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentMagenta=Saturation Adjustment Magenta"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHueAdjustmentRed",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentRed=Hue Adjustment Red"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHueAdjustmentOrange",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentOrange=Hue Adjustment Orange"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHueAdjustmentYellow",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentYellow=Hue Adjustment Yellow"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHueAdjustmentGreen",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentGreen=Hue Adjustment Green"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHueAdjustmentAqua",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentAqua=Hue Adjustment Aqua"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHueAdjustmentBlue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentBlue=Hue Adjustment Blue"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHueAdjustmentPurple",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentPurple=Hue Adjustment Purple"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetHueAdjustmentMagenta",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentMagenta=Hue Adjustment Magenta"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceAdjustmentRed",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentRed=Luminance Adjustment Red"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceAdjustmentOrange",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentOrange=Luminance Adjustment Orange"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceAdjustmentYellow",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentYellow=Luminance Adjustment Yellow"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceAdjustmentGreen",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentGreen=Luminance Adjustment Green"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceAdjustmentAqua",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentAqua=Luminance Adjustment Aqua"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceAdjustmentBlue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentBlue=Luminance Adjustment Blue"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceAdjustmentPurple",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentPurple=Luminance Adjustment Purple"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceAdjustmentMagenta",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentMagenta=Luminance Adjustment Magenta"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrayMixerRed",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerRed=Gray Mixer Red"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrayMixerOrange",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerOrange=Gray Mixer Orange"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrayMixerYellow",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerYellow=Gray Mixer Yellow"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrayMixerGreen",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerGreen=Gray Mixer Green"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrayMixerAqua",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerAqua=Gray Mixer Aqua"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrayMixerBlue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerBlue=Gray Mixer Blue"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrayMixerPurple",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerPurple=Gray Mixer Purple"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrayMixerMagenta",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerMagenta=Gray Mixer Magenta"),
    resetColorAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"EnableSplitToning",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableSplitToning=Enable Split Toning"),
    splitToning,
    true,
    false,
    false,
    "Enable or disable split toning effects. *button*",
    true},
  {"SplitToningShadowHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowHue=Shadow Hue"),
    splitToning,
    false,
    true,
    true,
    "Color of the tone for shadows.",
    false},
  {"SplitToningShadowSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowSaturation=Shadow Saturation"),
    splitToning,
    false,
    true,
    true,
    "Strength of the effect.",
    false},
  {"SplitToningHighlightHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightHue=Highlight Hue"),
    splitToning,
    false,
    true,
    true,
    "Color of the tone for highlights.",
    false},
  {"SplitToningHighlightSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightSaturation=Highlight Saturation"),
    splitToning,
    false,
    true,
    true,
    "Strength of the effect.",
    false},
  {"SplitToningBalance",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningBalance=Split Toning Balance"),
    splitToning,
    false,
    true,
    true,
    "Set the Balance slider to balance the effect between the Highlight and Shadow sliders. Positive values increase the effect of the Highlight sliders; negative values increase the effect of the Shadow sliders.",
    false},
  {"ResetSplitToningShadowHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowHue=Shadow Hue"),
    splitToning,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSplitToningShadowSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowSaturation=Shadow Saturation"),
    splitToning,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSplitToningHighlightHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightHue=Highlight Hue"),
    splitToning,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSplitToningHighlightSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightSaturation=Highlight Saturation"),
    splitToning,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSplitToningBalance",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningBalance=Split Toning Balance"),
    splitToning,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"EnableDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableDetail=Enable Detail"),
    detail,
    true,
    false,
    false,
    "Enable or disable noise reduction and sharpening. *button*",
    true},
  {"Sharpness",
    LOC("$$$/AgDevelop/Localized/Sharpness=Sharpness"),
    detail,
    false,
    true,
    true,
    "Adjusts edge definition. Increase the Amount value to increase sharpening. A value of zero (0) turns off sharpening. In general, set Amount to a lower value for cleaner images. The adjustment locates pixels that differ from surrounding pixels based on the threshold you specify and increases the pixelsâ€™ contrast by the amount you specify.",
    false},
  {"SharpenRadius",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenRadius=Sharpen Radius"),
    detail,
    false,
    true,
    true,
    "Adjusts the size of the details that sharpening is applied to. Photos with very fine details may need a lower radius setting. Photos with larger details may be able to use a larger radius. Using too large a radius generally results in unnatural-looking results.",
    false},
  {"SharpenDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenDetail=Sharpen Detail"),
    detail,
    false,
    true,
    true,
    "Adjusts how much high-frequency information is sharpened in the image and how much the sharpening process emphasizes edges. Lower settings primarily sharpen edges to remove blurring. Higher values are useful for making the textures in the image more pronounced.",
    false},
  {"SharpenEdgeMasking",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenEdgeMasking=Sharpen Edge Masking"),
    detail,
    false,
    true,
    true,
    "Controls an edge mask. With a setting of zero (0), everything in the image receives the same amount of sharpening. With a setting of 100, sharpening is mostly restricted to those areas near the strongest edges.",
    false},
  {"LuminanceSmoothing",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceSmoothing=Luminance Smoothing"),
    detail,
    false,
    true,
    true,
    "Reduces luminance noise.",
    false},
  {"LuminanceNoiseReductionDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionDetail=Luminance Detail"),
    detail,
    false,
    true,
    true,
    "Controls the luminance noise threshold. Useful for very noisy photos. Higher values preserve more detail but may produce noisier results. Lower values produce cleaner results but may also remove some detail.",
    false},
  {"LuminanceNoiseReductionContrast",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionContrast=Luminance Contrast"),
    detail,
    false,
    true,
    true,
    "Controls luminance contrast. Useful for very noisy photos. Higher values preserve contrast but may produce noisy blotches or mottling. Lower values produce smoother results but may also have less contrast.",
    false},
  {"ColorNoiseReduction",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReduction=Color Noise Reduction"),
    detail,
    false,
    true,
    true,
    "Reduces color noise.",
    false},
  {"ColorNoiseReductionDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionDetail=Color Noise Reduction Detail"),
    detail,
    false,
    true,
    true,
    "Controls the color noise threshold. Higher values protect thin, detailed color edges but may result in color speckling. Lower values remove color speckles but may result in color bleeding.",
    false},
  {"ColorNoiseReductionSmoothness",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionSmoothness=Color Noise Reduction Smoothness"),
    detail,
    false,
    true,
    true,
    "Increasing this can prevent artifacts especially in the lower frequencies.",
    false},
  {"ResetSharpness",
    reset..' '..LOC("$$$/AgDevelop/Localized/Sharpness=Sharpness"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSharpenRadius",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenRadius=Sharpen Radius"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSharpenDetail",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenDetail=Sharpen Detail"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetSharpenEdgeMasking",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenEdgeMasking=Sharpen Edge Masking"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceSmoothing",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceSmoothing=Luminance Smoothing"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceNoiseReductionDetail",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionDetail=Luminance Detail"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLuminanceNoiseReductionContrast",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionContrast=Luminance Contrast"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetColorNoiseReduction",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReduction=Color Noise Reduction"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetColorNoiseReductionDetail",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionDetail=Color Noise Reduction Detail"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetColorNoiseReductionSmoothness",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionSmoothness=Color Noise Reduction Smoothness"),
    detail,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"EnableLensCorrections",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableLensCorrections=Enable Lens Corrections"),
    lensCorrections,
    true,
    false,
    false,
    "Enable or disable all lens corrections. *button*",
    true},
  {"LensProfileEnable",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileEnable=Lens Profile Enable"),
    lensCorrections,
    true,
    false,
    false,
    "Automatic correction using a stored lens profile.",
    true},
  {"AutoLateralCA",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RemoveChromaticAberration=Remove Chromatic Aberration"),
    lensCorrections,
    true,
    false,
    false,
    "Automatically corrects blue-yellow and red-green fringes (lateral chromatic aberration).",
    true},
  {"UprightOff",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueOff=Off"),
    lensCorrections,
    true,
    false,
    false,
    "Upright mode off. *button*",
    false},
  {"UprightAuto",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueAuto=Auto"),
    lensCorrections,
    true,
    false,
    false,
    "Balanced level, aspect ratio, and perspective corrections. *button*",
    false},
  {"UprightLevel",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueLevel=Level"),
    lensCorrections,
    true,
    false,
    false,
    "Perspective corrections are weighted toward horizontal details. *button*",
    false},
  {"UprightVertical",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueLevelVertical=Vertical"),
    lensCorrections,
    true,
    false,
    false,
    "Perspective corrections are weighted toward vertical details. *button*",
    false},
  {"UprightFull",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueFull=Full"),
    lensCorrections,
    true,
    false,
    false,
    "Combination of full Level, Vertical, and Auto perspective corrections. *button*",
    false},
  {"ResetPerspectiveUpright",
    LOC("$$$/AgCameraRawNamedSettings/Ops/ResetUprightSettings=Reset Upright Settings"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"LensProfileDistortionScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileDistortionScale=Lens Profile Distortion Scale"),
    lensCorrections,
    false,
    true,
    true,
    "The default value 100 applies 100% of the distortion correction in the profile. Values over 100 apply greater correction to the distortion; values under 100 apply less correction to the distortion.",
    false},
  {"LensProfileChromaticAberrationScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileChromaticAberrationScale=Lens Profile Chromatic Aberration Scale"),
    lensCorrections,
    false,
    true,
    true,
    "The default value 100 applies 100% of the chromatic aberration correction in the profile. Values over 100 apply greater correction to color fringing; values under 100 apply less correction to color fringing.",
    false},
  {"LensProfileVignettingScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileVignettingScale=Lens Profile Vignetting Scale"),
    lensCorrections,
    false,
    true,
    true,
    "The default value 100 applies 100% of the vignetting correction in the profile. Values over 100 apply greater correction to vignetting; values under 100 apply less correction to vignetting.",
    false},
  {"ResetLensProfileDistortionScale",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileDistortionScale=Lens Profile Distortion Scale"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLensProfileChromaticAberrationScale",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileChromaticAberrationScale=Lens Profile Chromatic Aberration Scale"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetLensProfileVignettingScale",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileVignettingScale=Lens Profile Vignetting Scale"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"DefringePurpleAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeAmount=Defringe Purple Amount"),
    lensCorrections,
    false,
    true,
    true,
    "You can adjust the affected purple or green hue range using the Purple Hue and the Green Hue sliders. Drag either end-point control to expand or decrease the range of affected colors. Drag between the end point controls to move the hue range. The minimum space between end points is ten units.",
    false},
  {"DefringePurpleHueLo",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    lensCorrections,
    false,
    true,
    true,
    "",
    false},
  {"DefringePurpleHueHi",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    lensCorrections,
    false,
    true,
    true,
    "",
    false},
  {"DefringeGreenAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeAmount=Defringe Green Amount"),
    lensCorrections,
    false,
    true,
    true,
    "You can adjust the affected purple or green hue range using the Purple Hue and the Green Hue sliders. Drag either end-point control to expand or decrease the range of affected colors. Drag between the end point controls to move the hue range. The minimum space between end points is ten units. The default spacing for the green sliders is narrow to protect green/yellow image colors, like foliage.",
    false},
  {"DefringeGreenHueLo",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    lensCorrections,
    false,
    true,
    true,
    "",
    false},
  {"DefringeGreenHueHi",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    lensCorrections,
    false,
    true,
    true,
    "",
    false},
  {"ResetDefringePurpleAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeAmount=Defringe Purple Amount"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetDefringePurpleHueLo",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetDefringePurpleHueHi",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetDefringeGreenAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeAmount=Defringe Green Amount"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetDefringeGreenHueLo",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetDefringeGreenHueHi",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"LensManualDistortionAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensManualDistortionAmount=Lens Manual Distortion Amount"),
    lensCorrections,
    false,
    true,
    true,
    "Drag to the right to correct barrel distortion and straighten lines that bend away from the center. Drag to the left to correct pincushion distortion and straighten lines that bend toward the center.",
    false},
  {"PerspectiveVertical",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveVertical=Perspective Vertical"),
    lensCorrections,
    false,
    true,
    true,
    "Corrects perspective caused by tilting the camera up or down. Makes vertical lines appear parallel.",
    false},
  {"PerspectiveHorizontal",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveHorizontal=Perspective Horizontal"),
    lensCorrections,
    false,
    true,
    true,
    "Corrects perspective caused by angling the camera left or right. Makes horizontal lines parallel.",
    false},
  {"PerspectiveRotate",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveRotate=Perspective Rotate"),
    lensCorrections,
    false,
    true,
    true,
    "Corrects for camera tilt. Uses the center of the original, uncropped photo as the axis of rotation.",
    false},
  {"PerspectiveScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveScale=Perspective Scale"),
    lensCorrections,
    false,
    true,
    true,
    "Adjusts the image scale up or down. Helps to remove empty areas caused by perspective corrections and distortions. Displays areas of the image that extend beyond the crop boundary.",
    false},
  {"PerspectiveAspect",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveAspect=Perspective Aspect"),
    lensCorrections,
    false,
    true,
    true,
    "Adjusts the amount the image is stretched horizontally or vertically.",
    false},
  {"VignetteAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteAmount=Vignette Amount"),
    lensCorrections,
    false,
    true,
    true,
    "Sets the amount of lightening or darkening along the edges of an image. Corrects images that have darkened corners caused by lens faults or improper lens shading.",
    true},
  {"VignetteMidpoint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteMidpoint=Vignette Midpoint"),
    lensCorrections,
    false,
    true,
    true,
    "Specifies the width of area affected by the Amount slider. Specify a lower number to affect more of the image. Specify a higher number to restrict the effect to the edges of the image.",
    true},
  {"ResetLensManualDistortionAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensManualDistortionAmount=Lens Manual Distortion Amount"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPerspectiveVertical",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveVertical=Perspective Vertical"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPerspectiveHorizontal",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveHorizontal=Perspective Horizontal"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPerspectiveRotate",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveRotate=Perspective Rotate"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPerspectiveScale",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveScale=Perspective Scale"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPerspectiveAspect",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveAspect=Perspective Aspect"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetVignetteAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteAmount=Vignette Amount"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    true},
  {"ResetVignetteMidpoint",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteMidpoint=Vignette Midpoint"),
    lensCorrections,
    true,
    false,
    false,
    "Reset to default. *button*",
    true},
  {"EnableEffects",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableEffects=Enable Effects"),
    effects,
    true,
    false,
    false,
    "Enable or disable effects. *button*",
    true},
  {"Dehaze",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/DehazeAmount=Dehaze Amount"),
    effects,
    false,
    true,
    true,
    "Controls the amount of haze in a photograph. Drag to the right to remove haze; drag to the left to add haze.",
    false},
  {"PostCropVignetteAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteAmount=Post Crop Vignette Amount"),
    effects,
    false,
    true,
    true,
    "Negative values darken the corners of the photo. Positive values lighten the corners.",
    false},
  {"PostCropVignetteMidpoint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteMidpoint=Post Crop Vignette Midpoint"),
    effects,
    false,
    true,
    true,
    "Lower values apply the Amount adjustment to a larger area away from the corners. Higher values restrict the adjustment to an area closer to the corners.",
    false},
  {"PostCropVignetteFeather",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteFeather=Post Crop Vignette Feather"),
    effects,
    false,
    true,
    true,
    "Lower values reduce softening between the vignette and the vignetteâ€™s surrounding pixels. Higher values increase the softening.",
    false},
  {"PostCropVignetteRoundness",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteRoundness=Post Crop Vignette Roundness"),
    effects,
    false,
    true,
    true,
    "Lower values make the vignette effect more oval. Higher values make the vignette effect more circular.",
    false},
  {"PostCropVignetteStyle",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteStyle=Post Crop Vignette Style"),
    effects,
    false,
    true,
    true,
    "Cycles through: **Highlight Priority** Enables highlight recovery but can lead to color shifts in darkened areas of a photo. Suitable for photos with bright image areas such as clipped specular highlights. **Color Priority** Minimizes color shifts in darkened areas of a photo but cannot perform highlight recovery. **Paint Overlay** Mixes the cropped image values with black or white pixels. Can result in a flat appearance.",
    false},
  {"PostCropVignetteHighlightContrast",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteHighlightContrast=Post Crop Vignette Highlight Contrast"),
    effects,
    false,
    true,
    true,
    "(Highlight Priority and Color Priority only) Controls the degree of highlight contrast preserved when Amount is negative. Suitable for photos with small highlights, such as candles and lamps.",
    false},
  {"GrainAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainAmount=Grain Amount"),
    effects,
    false,
    true,
    true,
    "Controls the amount of grain applied to the image. Drag to the right to increase the amount. Set to zero to disable grain.",
    false},
  {"GrainSize",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainSize=Grain Size"),
    effects,
    false,
    true,
    true,
    "Controls grain particle size. At sizes of 25 or greater, blue is added to make the effect look better with noise reduction.",
    false},
  {"GrainFrequency",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainRoughness=Grain Roughness"),
    effects,
    false,
    true,
    true,
    " Controls the regularity of the grain. Drag to the left to make the grain more uniform; drag to the right to make the grain more uneven.",
    false},
  {"ResetDehaze",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/DehazeAmount=Dehaze Amount"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPostCropVignetteAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteAmount=Post Crop Vignette Amount"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPostCropVignetteMidpoint",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteMidpoint=Post Crop Vignette Midpoint"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPostCropVignetteFeather",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteFeather=Post Crop Vignette Feather"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPostCropVignetteRoundness",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteRoundness=Post Crop Vignette Roundness"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPostCropVignetteStyle",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteStyle=Post Crop Vignette Style"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetPostCropVignetteHighlightContrast",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteHighlightContrast=Post Crop Vignette Highlight Contrast"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrainAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainAmount=Grain Amount"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrainSize",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainSize=Grain Size"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"ResetGrainFrequency",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainRoughness=Grain Roughness"),
    effects,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"EnableCalibration",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableCalibration=Enable Calibration"),
    calibration,
    true,
    false,
    false,
    "Enable or disable custom camera calibration. *button*",
    true},
  {"Profile_Adobe_Standard",
    LOC("$$$/CRaw/Style/Profile/AdobeStandard=Adobe Standard"),
    calibration,
    true,
    false,
    false,
    "Applies the Adobe Standard profile. *button*",
    true},
  {"Profile_Camera_Clear",
    LOC("$$$/CRaw/Style/Profile/CameraClear=Camera Clear"),
    calibration,
    true,
    false,
    false,
    "These profiles attempt to match the camera manufacturer\226\128\153s color appearance under specific settings. *button*",
    true},
  {"Profile_Camera_Deep",
    LOC("$$$/CRaw/Style/Profile/CameraDeep=Camera Deep"),
    calibration,
    true,
    false,
    false,
    "These profiles attempt to match the camera manufacturer\226\128\153s color appearance under specific settings. *button*",
    true},
  {"Profile_Camera_Landscape",
    LOC("$$$/CRaw/Style/Profile/CameraLandscape=Camera Landscape"),
    calibration,
    true,
    false,
    false,
    "These profiles attempt to match the camera manufacturer\226\128\153s color appearance under specific settings. *button*",
    true},
  {"Profile_Camera_Light",
    LOC("$$$/CRaw/Style/Profile/CameraLight=Camera Light"),
    calibration,
    true,
    false,
    false,
    "These profiles attempt to match the camera manufacturer\226\128\153s color appearance under specific settings. *button*",
    true},
  {"Profile_Camera_Neutral",
    LOC("$$$/CRaw/Style/Profile/CameraNeutral=Camera Neutral"),
    calibration,
    true,
    false,
    false,
    "These profiles attempt to match the camera manufacturer\226\128\153s color appearance under specific settings. *button*",
    true},
  {"Profile_Camera_Portrait",
    LOC("$$$/CRaw/Style/Profile/CameraPortrait=Camera Portrait"),
    calibration,
    true,
    false,
    false,
    "These profiles attempt to match the camera manufacturer\226\128\153s color appearance under specific settings. *button*",
    true},
  {"Profile_Camera_Standard",
    LOC("$$$/CRaw/Style/Profile/CameraStandard=Camera Standard"),
    calibration,
    true,
    false,
    false,
    "These profiles attempt to match the camera manufacturer\226\128\153s color appearance under specific settings. *button*",
    true},
  {"Profile_Camera_Vivid",
    LOC("$$$/CRaw/Style/Profile/CameraVivid=Camera Vivid"),
    calibration,
    true,
    false,
    false,
    "These profiles attempt to match the camera manufacturer\226\128\153s color appearance under specific settings. *button*",
    true},
  {"ShadowTint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ShadowTintCalibration=Shadow Tint Calibration"),
    calibration,
    false,
    true,
    true,
    "Corrects for any green or magenta tint in the shadow areas of the photo.",
    false},
  {"RedHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedHueCalibration=Red Hue Calibration"),
    calibration,
    false,
    true,
    true,
    "For the red primary. Moving the Hue slider to the left (negative value) is similar to a counterclockwise move on the color wheel; moving it to the right (positive value) is similar to a clockwise move.",
    false},
  {"RedSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedSaturationCalibration=Red Saturation Calibration"),
    calibration,
    false,
    true,
    true,
    "For the red primary. Moving the Saturation slider to the left (negative value) desaturates the color; moving it to the right (positive value) increases saturation.",
    false},
  {"GreenHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenHueCalibration=Green Hue Calibration"),
    calibration,
    false,
    true,
    true,
    "For the green primary. Moving the Hue slider to the left (negative value) is similar to a counterclockwise move on the color wheel; moving it to the right (positive value) is similar to a clockwise move.",
    false},
  {"GreenSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenSaturationCalibration=Green Saturation Calibration"),
    calibration,
    false,
    true,
    true,
    "For the green primary. Moving the Saturation slider to the left (negative value) desaturates the color; moving it to the right (positive value) increases saturation.",
    false},
  {"BlueHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueHueCalibration=Blue Hue Calibration"),
    calibration,
    false,
    true,
    true,
    "For the blue primary. Moving the Hue slider to the left (negative value) is similar to a counterclockwise move on the color wheel; moving it to the right (positive value) is similar to a clockwise move.",
    false},
  {"BlueSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueSaturationCalibration=Blue Saturation Calibration"),
    calibration,
    false,
    true,
    true,
    "For the blue primary. Moving the Saturation slider to the left (negative value) desaturates the color; moving it to the right (positive value) increases saturation.",
    false},
  {"ResetShadowTint",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ShadowTintCalibration=Shadow Tint Calibration"),
    calibration,
    false,
    true,
    true,
    "Reset to default. *button*",
    false},
  {"ResetRedHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedHueCalibration=Red Hue Calibration"),
    calibration,
    false,
    true,
    true,
    "Reset to default. *button*",
    false},
  {"ResetRedSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedSaturationCalibration=Red Saturation Calibration"),
    calibration,
    false,
    true,
    true,
    "Reset to default. *button*",
    false},
  {"ResetGreenHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenHueCalibration=Green Hue Calibration"),
    calibration,
    false,
    true,
    true,
    "Reset to default. *button*",
    false},
  {"ResetGreenSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenSaturationCalibration=Green Saturation Calibration"),
    calibration,
    false,
    true,
    true,
    "Reset to default. *button*",
    false},
  {"ResetBlueHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueHueCalibration=Blue Hue Calibration"),
    calibration,
    false,
    true,
    true,
    "Reset to default. *button*",
    false},
  {"ResetBlueSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueSaturationCalibration=Blue Saturation Calibration"),
    calibration,
    false,
    true,
    true,
    "Reset to default. *button*",
    false},
  {"Pick",
    LOC("$$$/AgLibrary/Help/Shortcuts/SetPick=Set Pick Flag"),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"Reject",
    LOC("$$$/AgLibrary/Help/Shortcuts/SetReject=Set Rejected Flag"),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"Next",
    LOC("$$$/AgDevelopShortcuts/Next_Photo=Next Photo"),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"Prev",
    LOC("$$$/AgDevelopShortcuts/Previous_Photo=Previous Photo"),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"Select1Left",
    LOC("$$$/AgLibrary/Menu/Edit/AddToSelection=Add to Selection")..' '..LOC("$$$/AgWatermarking/Alignment/Left=Left"),
    'Photo Actions',
    true,
    false,
    false,
    "Extend selection one picture to the left. *button*",
    false},
  {"Select1Right",
    LOC("$$$/AgLibrary/Menu/Edit/AddToSelection=Add to Selection")..' '..LOC("$$$/AgWatermarking/Alignment/Right=Right"),
    'Photo Actions',
    true,
    false,
    false,
    "Extend selection one picture to the right. *button*",
    false},
  {"VirtualCopy",
    LOC("$$$/AgLibrary/Bezel/CreateVirtualCopy=Create Virtual Copy"):gsub('&',''),
    photoActions,
    true,
    false,
    false,
    "Creates a virtual copy for each of the currently selected photos and videos. The new virtual copies will be selected. *button*",
    false},
  {"RemoveFlag",
    LOC("$$$/AgLibrary/Menu/Photo/SetPick/Unflagged=Unflagged"):gsub('&',''),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"IncreaseRating",
    LOC("$$$/AgLibrary/Ops/IncreaseRating=Increase Rating"),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"DecreaseRating",
    LOC("$$$/AgLibrary/Ops/DecreaseRating=Decrease Rating"),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"SetRating0",
    LOC("$$$/AgLibrary/Filter/Stars=^1 Stars",'0'),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"SetRating1",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating1=1 Star"):gsub('&',''),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"SetRating2",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating2=&2 Stars"):gsub('&',''),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"SetRating3",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating3=&3 Stars"):gsub('&',''),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"SetRating4",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating4=&4 Stars"):gsub('&',''),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"SetRating5",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating5=&5 Stars"):gsub('&',''),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"ToggleBlue",
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelBlue=Blue")),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"ToggleGreen",
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelGreen=Green")),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"ToggleRed", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelRed=Red")),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"TogglePurple", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelPurple=Purple")),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"ToggleYellow", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelYellow=Yellow")),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"ResetAll",
    LOC("$$$/AgCameraRawNamedSettings/Ops/ResetSettings=Reset Settings"),
    photoActions,
    true,
    false,
    false,
    "Reset to defaults. *button*",
    false},
  {"ResetLast",
    reset..' '..LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified"):gsub(':',''),
    photoActions,
    true,
    false,
    false,
    "Resets the last parameter that was adjusted by an encoder or fader to default. *button*",
    false},
  {"IncrementLastDevelopParameter",
    LOC("$$$/AgCameraRawController/TargetAdjustment/Increase=^1 Increase: ^2",'',LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified")):gsub(':',''):gsub("^%s*(.-)%s*$", "%1"),
    photoActions,
    true,
    false,
    false,
    "Increments the last parameter that was adjusted by an encoder or fader. *button*",
    false},
  {"DecrementLastDevelopParameter",
    LOC("$$$/AgCameraRawController/TargetAdjustment/Decrease=^1 Decrease: ^2",'',LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified")):gsub(':',''):gsub("^%s*(.-)%s*$", "%1"),
    photoActions,
    true,
    false,
    false,
    "Decrements the last parameter that was adjusted by an encoder or fader. *button*",
    false},
  {"Undo",
    LOC("$$$/AgCameraRawController/SoftProofingVirtualCopyPrompt/Undo=Undo"),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"Redo",
    LOC("$$$/Bezel/RedoTitle=Redo"),
    photoActions,
    true,
    false,
    false,
    "*button*",
    false},
  {"CopySettings",
    "Copy Settings",
    photoActions,
    true,
    false,
    false,
    "Copies all develop settings. Application will remember last copy operation and use that for all paste operations until a new *Copy Settings* is done or the application is restarted. *button*",
    false},
  {"PasteSettings",
    LOC("$$$/AgCameraRawNamedSettings/Ops/PasteSettings=Paste Settings"),
    photoActions,
    true,
    false,
    false,
    "Pastes all develop settings. *button*",
    false},
  {"PasteSelectedSettings",
    "Paste Selected Settings",
    photoActions,
    true,
    false,
    false,
    "Pastes only those settings checked in the **Optionsâ‡¢Paste Selections** dialog. *button*",
    false},
  {"Preset_1", 
    developPreset.." 1", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_2", 
    developPreset.." 2", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_3", 
    developPreset.." 3", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_4", 
    developPreset.." 4", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_5", 
    developPreset.." 5", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_6", 
    developPreset.." 6", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_7", 
    developPreset.." 7", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_8", 
    developPreset.." 8", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_9", 
    developPreset.." 9", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_10", 
    developPreset.." 10", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_11", 
    developPreset.." 11", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_12", 
    developPreset.." 12", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_13", 
    developPreset.." 13", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_14", 
    developPreset.." 14", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_15", 
    developPreset.." 15", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_16", 
    developPreset.." 16", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_17", 
    developPreset.." 17", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_18", 
    developPreset.." 18", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_19", 
    developPreset.." 19", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"Preset_20", 
    developPreset.." 20", 
    developPresets,
    true,
    false,
    false,
    "",
    false},
  {"local_Temperature",
    "Local Temperature (PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Temperature for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Tint",
    "Local Tint (PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Tint for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Exposure",
    "Local Exposure (PV2010 and PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Exposure for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Contrast",
    "Local Contrast (PV2010 and PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Contrast for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Highlights",
    "Local Highlights (PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Highlights for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Shadows",
    "Local Shadows (PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Shadows for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Clarity",
    "Local Clarity (PV2010 and PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Clarity for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Saturation",
    "Local Saturation (PV2010 and PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Saturation for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Sharpness",
    "Local Sharpness (PV2010 and PV 2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Sharpness for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_LuminanceNoise",
    "Local Luminance Noise (PV2012)",
    "Localized Adjusments",
    false,
    false,
    true,
    "Adjust Luminance Noise for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Moire",
    "Local Moire (PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Moire for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_Defringe",
    "Local Defringe (PV2012)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Defringe for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"local_ToningLuminance",
    "Local Toning Luminance (PV2010)",
    localizedAdjustments,
    false,
    false,
    true,
    "Adjust Toning Luminance for the currently active tool: Brush, Radial Filter, or Graduated Filter.",
    false},
  {"Resetlocal_Temperature",
    "Reset Local Temperature (PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Tint",
    "Reset Local Tint (PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Exposure",
    "Reset Local Exposure (PV2010 and PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Contrast",
    "Reset Local Contrast (PV2010 and PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Highlights",
    "Reset Local Highlights (PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Shadows",
    "Reset Local Shadows (PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Clarity",
    "Reset Local Clarity (PV2010 and PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Saturation",
    "Reset Local Saturation (PV2010 and PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Sharpness",
    "Reset Local Sharpness (PV2010 and PV 2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_LuminanceNoise",
    "Reset Local Luminance Noise (PV2012)",
    "Localized Adjusments",
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Moire",
    "Reset Local Moire (PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_Defringe",
    "Reset Local Defringe (PV2012)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"Resetlocal_ToningLuminance",
    "Reset Local Toning Luminance (PV2010)",
    localizedAdjustments,
    true,
    false,
    false,
    "Reset to default. *button*",
    false},
  {"EnableCircularGradientBasedCorrections", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableRadialFilter=Enable Radial Filter"),
    localizedAdjustments,
    true,
    false,
    false,
    "Enable or disable radial filter. *button*",
    true},
  {"EnableGradientBasedCorrections", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableGraduatedFilter=Enable Graduated Filter"),
    localizedAdjustments,
    true,
    false,
    false,
    "Enable or disable graduated filter. *button*",
    true},
  {"EnablePaintBasedCorrections",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableBrushAdjustments=Enable Brush Adjustments"),
    localizedAdjustments,
    true,
    false,
    false,
    "Enable or disable brush adjustments. *button*",
    true},
  {"EnableRedEye",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableRedEye=Enable Red-Eye"), 
    localizedAdjustments,
    true,
    false,
    false,
    "Enable or disable red eye correction. *button*",
    true},
  {"EnableRetouch", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableSpotRemoval=Enable Spot Removal"),
    localizedAdjustments,
    true,
    false,
    false,
    "Enable or disable spot removal. *button*",
    true},
  {"ResetCircGrad",
    LOC("$$$/AgLibrary/Ops/ResetRadialFilters=Reset Radial Filters"),
    localizedAdjustments,
    true,
    false,
    false,
    "Delete radial filter. *button*",
    false},
  {"ResetGradient",
    LOC("$$$/AgLibrary/Ops/ResetGraduatedFilters=Reset Graduated Filters"),
    localizedAdjustments,
    true,
    false,
    false,
    "Delete graduated filter. *button*",
    false},
  {"ResetBrushing",
    LOC("$$$/AgLibrary/Ops/ResetBrushing=Reset Brush Corrections"),
    localizedAdjustments,
    true,
    false,
    false,
    "Delete brush adjustments. *button*",
    false},
  {"ResetRedeye",
    LOC("$$$/AgLibrary/Ops/ResetRedeye=Reset Red-Eye"),
    localizedAdjustments,
    true,
    false,
    false,
    "Delete red eye correction. *button*",
    false},
  {"ResetSpotRem",
    LOC("$$$/AgLibrary/Ops/ResetSpotRemoval=Reset Spot Removal"),
    localizedAdjustments,
    true,
    false,
    false,
    "Delete spot removal. *button*",
    false},
  {"ZoomInLargeStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomIn=Zoom In"),
    miscellaneous,
    true,
    false,
    false,
    "*button*",
    false},
  {"ZoomInSmallStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomInSome=Zoom In Some"),
    miscellaneous,
    true,
    false,
    false,
    "*button*",
    false},
  {"ZoomOutSmallStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomOutSome=Zoom Out Some"),
    miscellaneous,
    true,
    false,
    false,
    "*button*",
    false},
  {"ZoomOutLargeStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomOut=Zoom Out"),
    miscellaneous,
    true,
    false,
    false,
    "*button*",
    false},
  {"ToggleZoomOffOn",
    "Toggle Zoom Off/On",
    miscellaneous,
    true,
    false,
    false,
    "*button*",
    false},
  {"CropAngle",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/CropAngle=Crop Angle"),
    miscellaneous,
    false,
    true,
    true,
    "Rotate crop rectangle. This control is constrained to picture boundaries even when \226\128\156constrain to image\226\128\157 is not selected. It also causes the aspect ratio of the crop to change. It may be better to use the [Perspective Rotate in the Lens Corrections](https://github.com/rsjaffe/MIDI2LR/wiki/Commands:-Lens-Correction) set of actions.",
    true},
  {"CropBottom",
    crop..' - '.. LOC("$$$/Layout/Panel/Panel/OutputFormat/PageNumber/Bottom=Bottom"),
    miscellaneous,
    false,
    true,
    true,
    "Adjust bottom of crop rectangle.",
    true},
  {"CropLeft",
    crop..' - '..LOC("$$$/AgWatermarking/Alignment/Left=Left"),
    miscellaneous,
    false,
    true,
    true,
    "Adjust left side of crop rectangle.",
    true},
  {"CropRight",
    crop..' - '..LOC("$$$/AgWatermarking/Alignment/Right=Right"),
    miscellaneous,
    false,
    true,
    true,
    "Adjust right side of crop rectangle.",
    true},
  {"CropTop",
    crop..' - '..LOC("$$$/Layout/Panel/Panel/OutputFormat/PageNumber/Top=Top"),
    miscellaneous,
    false,
    true,
    true,
    "Adjust top of crop rectangle.",
    true},
  {"ResetCrop",
    LOC("$$$/AgLibrary/Ops/ResetCrop=Reset Crop"),
    miscellaneous,
    true,
    false,
    false,
    "Reset the crop angle and frame for the current photo. *button*",
    false},
  {"Loupe",
    show..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/Loupe=Loupe"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Select Loupe View mode in Develop Module. Repeated press toggles in and out of Loupe View. *button*",
    false},
  {"CropOverlay",
    show..' '..crop,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Select Crop Overlay mode in Develop Module. Repeated press toggles Loupe View. *button*",
    false},
  {"SpotRemoval",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SpotRemoval=Spot Removal"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Select Spot Removal mode in Develop Module. Repeated press toggles Loupe View. *button*",
    false},
  {"RedEye",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Redeye=Red-Eye Correction"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Select Red Eye mode in Develop Module. Repeated press toggles Loupe View. *button*",
    false},
  {"GraduatedFilter",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/GraduatedFilters=Graduated Filters"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Select Graduated Filter mode in Develop Module. Repeated press toggles Loupe View. *button*",
    false},
  {"RadialFilter",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/RadialFilters=Radial Filters"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Select Radial Filter View mode in Develop Module. Repeated press toggles Loupe View. *button*",
    false},
  {"AdjustmentBrush",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BrushAdjustments=Brush Adjustments"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Select Adjustment Brush mode in Develop Module. Repeated press toggles Loupe View. *button*",
    false},
  {"SwToMlibrary",
    show..' '..LOC("$$$/AgLibraryModule/ModuleTitle=Library"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Switch to Library module. *button*",
    false},
  {"SwToMdevelop",
    show..' '..LOC("$$$/SmartCollection/Criteria/Heading/Develop=Develop"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Switch to Develop module. *button*",
    false},
  {"SwToMmap",
    show..' '..LOC("$$$/AgLocation/ModuleTitle=Map"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Switch to Map module. *button*",
    false},
  {"SwToMbook",
    show..' '..LOC("$$$/Ag/Layout/Book/ModuleTitle=Book"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Switch to Book module. *button*",
    false},
  {"SwToMslideshow",
    show..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Slideshow=Slideshow"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Switch to Slideshow module. *button*",
    false},
  {"SwToMprint",
    show..' '..LOC("$$$/AgPrint/Menu/File/Print=Print"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Switch to Print module. *button*",
    false},
  {"SwToMweb",
    show..' '..LOC("$$$/WPG/Help/Shortcuts/WebHeader=Web"),
    gotoToolModulePanel,
    true,
    false,
    false,
    "Switch to Web module. *button*",
    false},
  {"RevealPanelAdjust",
    show..' '..basicTone,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Open Basic Adjustments Panel in Develop Module. *button*",
    false},
  {"RevealPanelTone",
    show..' '..toneCurve,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Open Tone Curve Panel in Develop Module. *button*",
    false},
  {"RevealPanelMixer",
    show..' '..colorAdjustments,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Open Mixer Panel in Develop Module. *button*",
    false},
  {"RevealPanelSplit",
    show..' '..splitToning,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Open Split Toning Panel in Develop Module. *button*",
    false},
  {"RevealPanelDetail",
    show..' '..detail,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Open Detail Panel in Develop Module. *button*",
    false},
  {"RevealPanelLens",
    show..' '..lensCorrections,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Open Lens Corrections Panel in Develop Module. *button*",
    false},
  {"RevealPanelEffects",
    show..' '..effects,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Open Effects Panel in Develop Module. *button*",
    false},
  {"RevealPanelCalibrate",
    show..' '..calibration,
    gotoToolModulePanel,
    true,
    false,
    false,
    "Open Camera Calibration Panel in Develop Module. *button*",
    false},
  {"ShoVwloupe",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Loupe=Loupe"),
    viewModes,
    true,
    false,
    false,
    "Displays a single photo. Zoom levels up to 11:1 are available. *button*",
    false},
  {"ShoVwgrid",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Grid=Grid"),
    viewModes,
    true,
    false,
    false,
    "Displays photos as thumbnails in cells, which can be viewed in compact and expanded sizes. *button*",
    false},
  {"ShoVwcompare",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Compare=Compare"),
    viewModes,
    true,
    false,
    false,
    "Displays photos side by side so that you can evaluate them. *button*",
    false},
  {"ShoVwsurvey",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Survey=Survey"), 
    viewModes,
    true,
    false,
    false,
    "Displays the active photo with selected photos so that you can evaluate them. The active photo has the lightest colored cell. *button*",
    false},
  {"ShoVwpeople",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/People=People"), 
    viewModes,
    true,
    false,
    false,
    "In the People view, the different faces are organized by people stacks. *button*",
    false},
  {"ShoVwdevelop_loupe",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/Loupe=Loupe"),
    viewModes,
    true,
    false,
    false,
    "*button*",
    false},
  {"ShoVwdevelop_before_after_horiz",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/BeforeAfterLR=Before/After Left/Right"), 
    viewModes,
    true,
    false,
    false,
    "*button*",
    false},
  {"ShoVwdevelop_before_after_vert",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/BeforeAfterTB=Before/After Top/Bottom"),
    viewModes,
    true,
    false,
    false,
    "*button*",
    false},
  {"ShoVwdevelop_before",
    primaryDisplay..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/Before=Before"),
    viewModes,
    true,
    false,
    false,
    "*button*",
    false},
  {"ShoScndVwloupe", 
    secondaryDisplay..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Loupe=Loupe"),
    viewModes,
    true,
    false,
    false,
    "Shows Loupe view on the secondary screen, or hides the secondary screen if Loupe view was previously being shown. *button*",
    false},
  {"ShoScndVwlive_loupe", 
    secondaryDisplay..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/LiveLoupe=Live Loupe"),
    viewModes,
    true,
    false,
    false,
    "Shows Live Loupe view on the secondary screen, or hides the secondary screen if Live Loupe view was previously being shown. *button*",
    false},
  {"ShoScndVwlocked_loupe", 
    secondaryDisplay..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/LockedLoupe=Locked Loupe"),
    viewModes,
    true,
    false,
    false,
    "Shows Locked Loupe view on the secondary screen, or hides the secondary screen if Locked Loupe view was previously being shown. *button*",
    false},
  {"ShoScndVwgrid",
    secondaryDisplay..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Grid=Grid"),
    viewModes,
    true,
    false,
    false,
    "Shows Grid view on the secondary screen, or hides the secondary screen if Grid view was previously being shown. *button*",
    false},
  {"ShoScndVwcompare", 
    secondaryDisplay..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Compare=Compare"),
    viewModes,
    true,
    false,
    false,
    "Shows Compare view on the secondary screen, or hides the secondary screen if Compare view was previously being shown. *button*",
    false},
  {"ShoScndVwsurvey", 
    secondaryDisplay..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Survey=Survey"),
    viewModes,
    true,
    false,
    false,
    "Shows Survey view on the secondary screen, or hides the secondary screen if Survey view was previously being shown. *button*",
    false},
  {"ShoScndVwslideshow", 
    secondaryDisplay..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Slideshow=Slideshow"),
    viewModes,
    true,
    false,
    false,
    "Shows Slideshow view on the secondary screen, or hides the secondary screen if Slideshow view was previously being shown. *button*",
    false},
  {"ToggleScreenTwo", 
    secondaryDisplay..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Show=Show"), 
    viewModes,
    true,
    false,
    false,
    "Toggles the the secondary window on/off. *button*",
    false},
  {"profile1", 
    profile.." 1", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile2", 
    profile.." 2", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile3", 
    profile.." 3", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile4", 
    profile.." 4", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile5", 
    profile.." 5", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile6", 
    profile.." 6", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile7", 
    profile.." 7", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile8", 
    profile.." 8", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile9", 
    profile.." 9", 
    profiles,
    true,
    false,
    false,
    "",
    false},
  {"profile10", 
    profile.." 10", 
    profiles,
    true,
    false,
    false,
    "",
    false},
}

local MenuList = {}
for _,v in pairs(DataBase) do
  table.insert(MenuList,{v[1],v[2],v[3],v[4]})
end

local serpent = require 'serpent'
local LrPathUtils = import 'LrPathUtils'       
local datafile = LrPathUtils.child(_PLUGIN.path, 'MenuList.lua')
local file = io.open(datafile,'w')
file:write([=[
--[[----------------------------------------------------------------------------
This file was auto-generated by MIDI2LR and contains the translated menus used
by the app and the plugin. Edits to this file will be lost any time MIDI2LR
is updated or the language used by Lightroom changes. Edit MenuListPreTrans.lua
if you want to have persistent changes to the translations or menu structure.
This file is part of MIDI2LR. Copyright 2015-2016 by Rory Jaffe.
MIDI2LR is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.
MIDI2LR is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
MIDI2LR.  If not, see <http://www.gnu.org/licenses/>. 
------------------------------------------------------------------------------]]
local MenuList = ]=],serpent.block(MenuList, {comment = false}), [==[
local MenuListHashed = {}
for i,v in ipairs(MenuList) do
  MenuListHashed[v[1]]={i*100,v[2],v[3],v[4]}
  end
return {
  MenuList = MenuList,
  MenuListHashed = MenuListHashed,
}]==])
file:close()
