  --[[----------------------------------------------------------------------------

  MenuList.lua

  This file was auto-generated by MIDI2LR and contains the translated menus used
  by the app and the plugin. Edits to this file will be lost any time MIDI2LR
  is updated or the language used by Lightroom changes. Edit Database.lua
  if you want to have persistent changes to the translations or menu structure.

  This file is part of MIDI2LR. Copyright 2015 by Rory Jaffe.
  MIDI2LR is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later version.

  MIDI2LR is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
  PARTICULAR PURPOSE.  See the GNU General Public License for more details.
  You should have received a copy of the GNU General Public License along with
  MIDI2LR.  If not, see <http://www.gnu.org/licenses/>.
  ------------------------------------------------------------------------------]]
  local MenuList = {
  {
    "Key1",
    "Touche 1",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key2",
    "Touche 2",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key3",
    "Touche 3",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key4",
    "Touche 4",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key5",
    "Touche 5",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key6",
    "Touche 6",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key7",
    "Touche 7",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key8",
    "Touche 8",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key9",
    "Touche 9",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key10",
    "Touche 10",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key11",
    "Touche 11",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key12",
    "Touche 12",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key13",
    "Touche 13",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key14",
    "Touche 14",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key15",
    "Touche 15",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key16",
    "Touche 16",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key17",
    "Touche 17",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key18",
    "Touche 18",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key19",
    "Touche 19",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key20",
    "Touche 20",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key21",
    "Touche 21",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key22",
    "Touche 22",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key23",
    "Touche 23",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key24",
    "Touche 24",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key25",
    "Touche 25",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key26",
    "Touche 26",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key27",
    "Touche 27",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key28",
    "Touche 28",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key29",
    "Touche 29",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key30",
    "Touche 30",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key31",
    "Touche 31",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key32",
    "Touche 32",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key33",
    "Touche 33",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key34",
    "Touche 34",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key35",
    "Touche 35",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key36",
    "Touche 36",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key37",
    "Touche 37",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key38",
    "Touche 38",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key39",
    "Touche 39",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key40",
    "Touche 40",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key32Key31",
    "Touche 32 – Touche 31",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key34Key33",
    "Touche 34 – Touche 33",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key36Key35",
    "Touche 36 – Touche 35",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key38Key37",
    "Touche 38 – Touche 37",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Key40Key39",
    "Touche 40 – Touche 39",
    "Raccourcis d'interface utilisateur",
    true
  },
  {
    "Filter_1",
    "Filtre de bibliothèque : 1",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_2",
    "Filtre de bibliothèque : 2",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_3",
    "Filtre de bibliothèque : 3",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_4",
    "Filtre de bibliothèque : 4",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_5",
    "Filtre de bibliothèque : 5",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_6",
    "Filtre de bibliothèque : 6",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_7",
    "Filtre de bibliothèque : 7",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_8",
    "Filtre de bibliothèque : 8",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_9",
    "Filtre de bibliothèque : 9",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_10",
    "Filtre de bibliothèque : 10",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_11",
    "Filtre de bibliothèque : 11",
    "Filtre de bibliothèque :",
    true
  },
  {
    "Filter_12",
    "Filtre de bibliothèque : 12",
    "Filtre de bibliothèque :",
    true
  },
  {
    "ShoVwgrid",
    "Fenêtre principale Grille",
    "Général",
    true
  },
  {
    "ShoVwloupe",
    "Fenêtre principale Loupe",
    "Général",
    true
  },
  {
    "ShoVwcompare",
    "Fenêtre principale Comparaison",
    "Général",
    true
  },
  {
    "ShoVwsurvey",
    "Fenêtre principale Ensemble",
    "Général",
    true
  },
  {
    "ToggleZoomOffOn",
    "Activer/Désactiver le mode Zoom",
    "Général",
    true
  },
  {
    "ZoomInOut",
    "Léger zoom avant Léger zoom arrière",
    "Général",
    true
  },
  {
    "ZoomOutIn",
    "Léger zoom arrière Léger zoom avant",
    "Général",
    true
  },
  {
    "ZoomInLargeStep",
    "Zoom avant",
    "Général",
    true
  },
  {
    "ZoomInSmallStep",
    "Léger zoom avant",
    "Général",
    true
  },
  {
    "ZoomOutSmallStep",
    "Léger zoom arrière",
    "Général",
    true
  },
  {
    "ZoomOutLargeStep",
    "Zoom arrière",
    "Général",
    true
  },
  {
    "SelectRightLeft",
    "Ajouter à la sélection Gauche Droite",
    "Général",
    true
  },
  {
    "Select1Left",
    "Ajouter à la sélection Gauche",
    "Général",
    true
  },
  {
    "Select1Right",
    "Ajouter à la sélection Droite",
    "Général",
    true
  },
  {
    "NextPrev",
    "Photo suivante — Photo précédente",
    "Général",
    true
  },
  {
    "Next",
    "Photo suivante",
    "Général",
    true
  },
  {
    "Prev",
    "Photo précédente",
    "Général",
    true
  },
  {
    "ActionSeries1",
    "Série de commandes 1",
    "Général",
    true
  },
  {
    "ActionSeries2",
    "Série de commandes 2",
    "Général",
    true
  },
  {
    "ActionSeries3",
    "Série de commandes 3",
    "Général",
    true
  },
  {
    "ActionSeries4",
    "Série de commandes 4",
    "Général",
    true
  },
  {
    "ActionSeries5",
    "Série de commandes 5",
    "Général",
    true
  },
  {
    "ActionSeries6",
    "Série de commandes 6",
    "Général",
    true
  },
  {
    "ActionSeries7",
    "Série de commandes 7",
    "Général",
    true
  },
  {
    "ActionSeries8",
    "Série de commandes 8",
    "Général",
    true
  },
  {
    "ActionSeries9",
    "Série de commandes 9",
    "Général",
    true
  },
  {
    "SwToMlibrary",
    "Afficher Bibliothèque",
    "Bibliothèque",
    true
  },
  {
    "Pick",
    "Définir un marqueur de retenue",
    "Bibliothèque",
    true
  },
  {
    "Reject",
    "Définir un marqueur de rejet",
    "Bibliothèque",
    true
  },
  {
    "RemoveFlag",
    "Neutre",
    "Bibliothèque",
    true
  },
  {
    "SetRating0",
    "0 étoiles",
    "Bibliothèque",
    true
  },
  {
    "SetRating1",
    "1 étoile",
    "Bibliothèque",
    true
  },
  {
    "SetRating2",
    "2 étoiles",
    "Bibliothèque",
    true
  },
  {
    "SetRating3",
    "3 étoiles",
    "Bibliothèque",
    true
  },
  {
    "SetRating4",
    "4 étoiles",
    "Bibliothèque",
    true
  },
  {
    "SetRating5",
    "5 étoiles",
    "Bibliothèque",
    true
  },
  {
    "IncreaseRating",
    "Augmenter la note",
    "Bibliothèque",
    true
  },
  {
    "DecreaseRating",
    "Baisser la note",
    "Bibliothèque",
    true
  },
  {
    "ToggleBlue",
    "Afficher/Masquer le libellé Bleu",
    "Bibliothèque",
    true
  },
  {
    "ToggleGreen",
    "Afficher/Masquer le libellé Vert",
    "Bibliothèque",
    true
  },
  {
    "ToggleRed",
    "Afficher/Masquer le libellé Rouge",
    "Bibliothèque",
    true
  },
  {
    "TogglePurple",
    "Afficher/Masquer le libellé Pourpre",
    "Bibliothèque",
    true
  },
  {
    "ToggleYellow",
    "Afficher/Masquer le libellé Jaune",
    "Bibliothèque",
    true
  },
  {
    "ShoVwpeople",
    "Fenêtre principale Personnes",
    "Bibliothèque",
    true
  },
  {
    "SwToMdevelop",
    "Afficher Développer",
    "Développer",
    true
  },
  {
    "LRCopy",
    "Lightroom Copier les paramètres...",
    "Développer",
    true
  },
  {
    "LRPaste",
    "Lightroom Coller les paramètres",
    "Développer",
    true
  },
  {
    "CopySettings",
    "Copier les paramètres...",
    "Développer",
    true
  },
  {
    "PasteSettings",
    "Coller les paramètres",
    "Développer",
    true
  },
  {
    "PasteSelectedSettings",
    "Paste Selected Settings",
    "Développer",
    true
  },
  {
    "VirtualCopy",
    "Créer une copie virtuelle",
    "Développer",
    true
  },
  {
    "ResetAll",
    "Réinitialiser les paramètres",
    "Développer",
    true
  },
  {
    "ResetLast",
    "Réinitialiser Date de la dernière modification ",
    "Développer",
    true
  },
  {
    "ChangeLastDevelopParameter",
    "Plus – Moins Date de la dernière modification :",
    "Développer",
    true
  },
  {
    "IncrementLastDevelopParameter",
    "Augmenter   Date de la dernière modification",
    "Développer",
    true
  },
  {
    "DecrementLastDevelopParameter",
    "Réduire   Date de la dernière modification",
    "Développer",
    true
  },
  {
    "ChangeCurrentSlider",
    "Plus – Moins",
    "Développer",
    true
  },
  {
    "SliderIncrease",
    "Plus",
    "Développer",
    true
  },
  {
    "SliderDecrease",
    "Moins",
    "Développer",
    true
  },
  {
    "RedoUndo",
    "Rétablir – Annuler",
    "Développer",
    true
  },
  {
    "Undo",
    "Annuler",
    "Développer",
    true
  },
  {
    "Redo",
    "Rétablir",
    "Développer",
    true
  },
  {
    "ShoVwdevelop_before_after_horiz",
    "Fenêtre principale Avant/Après - Gauche/Droite",
    "Développer",
    true
  },
  {
    "ShoVwdevelop_before_after_vert",
    "Fenêtre principale Avant/Après - Haut/Bas",
    "Développer",
    true
  },
  {
    "ShoVwdevelop_before",
    "Fenêtre principale Avant",
    "Développer",
    true
  },
  {
    "ShoVwRefHoriz",
    "Fenêtre principale Vue de référence - Gauche/Droite",
    "Développer",
    true
  },
  {
    "ShoVwRefVert",
    "Fenêtre principale Vue de référence - Haut/Bas",
    "Développer",
    true
  },
  {
    "ShoVwdevelop_loupe",
    "Fenêtre principale Loupe",
    "Développer",
    true
  },
  {
    "RevealPanelAdjust",
    "Afficher Tonalité simple",
    "Tonalité simple",
    true
  },
  {
    "WhiteBalanceAs_Shot",
    "Balance des blancs Telle quelle",
    "Tonalité simple",
    true
  },
  {
    "WhiteBalanceAuto",
    "Balance des blancs Auto",
    "Tonalité simple",
    true
  },
  {
    "WhiteBalanceCloudy",
    "Balance des blancs Temps nuageux",
    "Tonalité simple",
    true
  },
  {
    "WhiteBalanceDaylight",
    "Balance des blancs Lumière naturelle",
    "Tonalité simple",
    true
  },
  {
    "WhiteBalanceFlash",
    "Balance des blancs Flash",
    "Tonalité simple",
    true
  },
  {
    "WhiteBalanceFluorescent",
    "Balance des blancs Fluorescente",
    "Tonalité simple",
    true
  },
  {
    "WhiteBalanceShade",
    "Balance des blancs Ombre",
    "Tonalité simple",
    true
  },
  {
    "WhiteBalanceTungsten",
    "Balance des blancs Tungstène",
    "Tonalité simple",
    true
  },
  {
    "AutoTone",
    "Tonalité simple Tonalité automatique",
    "Tonalité simple",
    true
  },
  {
    "Temperature",
    "Température",
    "Tonalité simple",
    false
  },
  {
    "Tint",
    "Teinte",
    "Tonalité simple",
    false
  },
  {
    "Exposure",
    "Exposition",
    "Tonalité simple",
    false
  },
  {
    "Contrast",
    "Contraste",
    "Tonalité simple",
    false
  },
  {
    "Highlights",
    "Hautes lumières (Récupération des hautes lumières in PV2003 et PV2010)",
    "Tonalité simple",
    false
  },
  {
    "Brightness",
    "Luminosité",
    "Tonalité simple",
    false
  },
  {
    "Shadows",
    "Ombres (Lumière d'appoint in PV2003 et PV2010)",
    "Tonalité simple",
    false
  },
  {
    "Whites",
    "Blancs (no effect in PV2003 et PV2010)",
    "Tonalité simple",
    false
  },
  {
    "Blacks",
    "Noirs",
    "Tonalité simple",
    false
  },
  {
    "Clarity",
    "Clarté",
    "Tonalité simple",
    false
  },
  {
    "Vibrance",
    "Vibrance",
    "Tonalité simple",
    false
  },
  {
    "Saturation",
    "Saturation",
    "Tonalité simple",
    false
  },
  {
    "ResetTemperature",
    "Réinitialiser Température",
    "Tonalité simple",
    true
  },
  {
    "ResetTint",
    "Réinitialiser Teinte",
    "Tonalité simple",
    true
  },
  {
    "ResetExposure",
    "Réinitialiser Exposition",
    "Tonalité simple",
    true
  },
  {
    "ResetContrast",
    "Réinitialiser Contraste",
    "Tonalité simple",
    true
  },
  {
    "ResetHighlights",
    "Réinitialiser Hautes lumières",
    "Tonalité simple",
    true
  },
  {
    "ResetShadows",
    "Réinitialiser Ombres",
    "Tonalité simple",
    true
  },
  {
    "ResetWhites",
    "Réinitialiser Blancs",
    "Tonalité simple",
    true
  },
  {
    "ResetBlacks",
    "Réinitialiser Noirs",
    "Tonalité simple",
    true
  },
  {
    "ResetClarity",
    "Réinitialiser Clarté",
    "Tonalité simple",
    true
  },
  {
    "ResetVibrance",
    "Réinitialiser Vibrance",
    "Tonalité simple",
    true
  },
  {
    "ResetSaturation",
    "Réinitialiser Saturation",
    "Tonalité simple",
    true
  },
  {
    "RevealPanelTone",
    "Afficher Courbe des tonalités",
    "Courbe des tonalités",
    true
  },
  {
    "EnableToneCurve",
    "Activer la courbe des tonalités",
    "Courbe des tonalités",
    true
  },
  {
    "ParametricDarks",
    "Teintes sombres",
    "Courbe des tonalités",
    false
  },
  {
    "ParametricLights",
    "Teintes claires",
    "Courbe des tonalités",
    false
  },
  {
    "ParametricShadows",
    "Tonalité des ombres",
    "Courbe des tonalités",
    false
  },
  {
    "ParametricHighlights",
    "Tonalité des hautes lumières",
    "Courbe des tonalités",
    false
  },
  {
    "ParametricShadowSplit",
    "Séparation des ombres",
    "Courbe des tonalités",
    false
  },
  {
    "ParametricMidtoneSplit",
    "Séparation des tons moyens",
    "Courbe des tonalités",
    false
  },
  {
    "ParametricHighlightSplit",
    "Séparation des hautes lumières",
    "Courbe des tonalités",
    false
  },
  {
    "ResetParametricDarks",
    "Réinitialiser Teintes sombres",
    "Courbe des tonalités",
    true
  },
  {
    "ResetParametricLights",
    "Réinitialiser Teintes claires",
    "Courbe des tonalités",
    true
  },
  {
    "ResetParametricShadows",
    "Réinitialiser Tonalité des ombres",
    "Courbe des tonalités",
    true
  },
  {
    "ResetParametricHighlights",
    "Réinitialiser Tonalité des hautes lumières",
    "Courbe des tonalités",
    true
  },
  {
    "ResetParametricShadowSplit",
    "Réinitialiser Séparation des ombres",
    "Courbe des tonalités",
    true
  },
  {
    "ResetParametricMidtoneSplit",
    "Réinitialiser Séparation des tons moyens",
    "Courbe des tonalités",
    true
  },
  {
    "ResetParametricHighlightSplit",
    "Réinitialiser Séparation des hautes lumières",
    "Courbe des tonalités",
    true
  },
  {
    "PointCurveLinear",
    "Courbe des tonalités Linéaire",
    "Courbe des tonalités",
    true
  },
  {
    "PointCurveMediumContrast",
    "Courbe des tonalités Contraste moyen",
    "Courbe des tonalités",
    true
  },
  {
    "PointCurveStrongContrast",
    "Courbe des tonalités Contraste fort",
    "Courbe des tonalités",
    true
  },
  {
    "RevealPanelMixer",
    "Afficher Réglages des couleurs",
    "Réglages des couleurs",
    true
  },
  {
    "EnableColorAdjustments",
    "Activer les réglages des couleurs",
    "Réglages des couleurs",
    true
  },
  {
    "SaturationAdjustmentRed",
    "Variation de la saturation du rouge",
    "Réglages des couleurs",
    false
  },
  {
    "SaturationAdjustmentOrange",
    "Variation de la saturation du orange",
    "Réglages des couleurs",
    false
  },
  {
    "SaturationAdjustmentYellow",
    "Variation de la saturation du jaune",
    "Réglages des couleurs",
    false
  },
  {
    "SaturationAdjustmentGreen",
    "Variation de la saturation du vert",
    "Réglages des couleurs",
    false
  },
  {
    "SaturationAdjustmentAqua",
    "Variation de la saturation du bleu vert",
    "Réglages des couleurs",
    false
  },
  {
    "SaturationAdjustmentBlue",
    "Variation de la saturation du bleu",
    "Réglages des couleurs",
    false
  },
  {
    "SaturationAdjustmentPurple",
    "Variation de la saturation du pourpre",
    "Réglages des couleurs",
    false
  },
  {
    "SaturationAdjustmentMagenta",
    "Variation de la saturation du magenta",
    "Réglages des couleurs",
    false
  },
  {
    "AllSaturationAdjustment",
    "All Saturation Adjustment",
    "Réglages des couleurs",
    false
  },
  {
    "HueAdjustmentRed",
    "Variation de la teinte rouge",
    "Réglages des couleurs",
    false
  },
  {
    "HueAdjustmentOrange",
    "Variation de la teinte orange",
    "Réglages des couleurs",
    false
  },
  {
    "HueAdjustmentYellow",
    "Variation de la teinte jaune",
    "Réglages des couleurs",
    false
  },
  {
    "HueAdjustmentGreen",
    "Variation de la teinte verte",
    "Réglages des couleurs",
    false
  },
  {
    "HueAdjustmentAqua",
    "Variation de la teinte bleu vert",
    "Réglages des couleurs",
    false
  },
  {
    "HueAdjustmentBlue",
    "Variation de la teinte bleue",
    "Réglages des couleurs",
    false
  },
  {
    "HueAdjustmentPurple",
    "Variation de la teinte pourpre",
    "Réglages des couleurs",
    false
  },
  {
    "HueAdjustmentMagenta",
    "Variation de la teinte magenta",
    "Réglages des couleurs",
    false
  },
  {
    "LuminanceAdjustmentRed",
    "Variation de la luminance du rouge",
    "Réglages des couleurs",
    false
  },
  {
    "LuminanceAdjustmentOrange",
    "Variation de la luminance du orange",
    "Réglages des couleurs",
    false
  },
  {
    "LuminanceAdjustmentYellow",
    "Variation de la luminance du jaune",
    "Réglages des couleurs",
    false
  },
  {
    "LuminanceAdjustmentGreen",
    "Variation de la luminance du vert",
    "Réglages des couleurs",
    false
  },
  {
    "LuminanceAdjustmentAqua",
    "Variation de la luminance du bleu vert",
    "Réglages des couleurs",
    false
  },
  {
    "LuminanceAdjustmentBlue",
    "Variation de la luminance du bleu",
    "Réglages des couleurs",
    false
  },
  {
    "LuminanceAdjustmentPurple",
    "Variation de la luminance du pourpre",
    "Réglages des couleurs",
    false
  },
  {
    "LuminanceAdjustmentMagenta",
    "Variation de la luminance du magenta",
    "Réglages des couleurs",
    false
  },
  {
    "ConvertToGrayscale",
    "Convertir en noir et blanc",
    "Réglages des couleurs",
    true
  },
  {
    "EnableGrayscaleMix",
    "Activer le mélange noir et blanc",
    "Réglages des couleurs",
    true
  },
  {
    "GrayMixerRed",
    "Niveau de gris rouge",
    "Réglages des couleurs",
    false
  },
  {
    "GrayMixerOrange",
    "Niveau de gris orange",
    "Réglages des couleurs",
    false
  },
  {
    "GrayMixerYellow",
    "Niveau de gris jaune",
    "Réglages des couleurs",
    false
  },
  {
    "GrayMixerGreen",
    "Niveau de gris vert",
    "Réglages des couleurs",
    false
  },
  {
    "GrayMixerAqua",
    "Niveau de gris bleu vert",
    "Réglages des couleurs",
    false
  },
  {
    "GrayMixerBlue",
    "Niveau de gris bleu",
    "Réglages des couleurs",
    false
  },
  {
    "GrayMixerPurple",
    "Niveau de gris pourpre",
    "Réglages des couleurs",
    false
  },
  {
    "GrayMixerMagenta",
    "Niveau de gris magenta",
    "Réglages des couleurs",
    false
  },
  {
    "ResetSaturationAdjustmentRed",
    "Réinitialiser Variation de la saturation du rouge",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetSaturationAdjustmentOrange",
    "Réinitialiser Variation de la saturation du orange",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetSaturationAdjustmentYellow",
    "Réinitialiser Variation de la saturation du jaune",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetSaturationAdjustmentGreen",
    "Réinitialiser Variation de la saturation du vert",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetSaturationAdjustmentAqua",
    "Réinitialiser Variation de la saturation du bleu vert",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetSaturationAdjustmentBlue",
    "Réinitialiser Variation de la saturation du bleu",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetSaturationAdjustmentPurple",
    "Réinitialiser Variation de la saturation du pourpre",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetSaturationAdjustmentMagenta",
    "Réinitialiser Variation de la saturation du magenta",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetAllSaturationAdjustment",
    "Réinitialiser All Saturation Adjustment",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetHueAdjustmentRed",
    "Réinitialiser Variation de la teinte rouge",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetHueAdjustmentOrange",
    "Réinitialiser Variation de la teinte orange",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetHueAdjustmentYellow",
    "Réinitialiser Variation de la teinte jaune",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetHueAdjustmentGreen",
    "Réinitialiser Variation de la teinte verte",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetHueAdjustmentAqua",
    "Réinitialiser Variation de la teinte bleu vert",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetHueAdjustmentBlue",
    "Réinitialiser Variation de la teinte bleue",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetHueAdjustmentPurple",
    "Réinitialiser Variation de la teinte pourpre",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetHueAdjustmentMagenta",
    "Réinitialiser Variation de la teinte magenta",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetLuminanceAdjustmentRed",
    "Réinitialiser Variation de la luminance du rouge",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetLuminanceAdjustmentOrange",
    "Réinitialiser Variation de la luminance du orange",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetLuminanceAdjustmentYellow",
    "Réinitialiser Variation de la luminance du jaune",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetLuminanceAdjustmentGreen",
    "Réinitialiser Variation de la luminance du vert",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetLuminanceAdjustmentAqua",
    "Réinitialiser Variation de la luminance du bleu vert",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetLuminanceAdjustmentBlue",
    "Réinitialiser Variation de la luminance du bleu",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetLuminanceAdjustmentPurple",
    "Réinitialiser Variation de la luminance du pourpre",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetLuminanceAdjustmentMagenta",
    "Réinitialiser Variation de la luminance du magenta",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetGrayMixerRed",
    "Réinitialiser Niveau de gris rouge",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetGrayMixerOrange",
    "Réinitialiser Niveau de gris orange",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetGrayMixerYellow",
    "Réinitialiser Niveau de gris jaune",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetGrayMixerGreen",
    "Réinitialiser Niveau de gris vert",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetGrayMixerAqua",
    "Réinitialiser Niveau de gris bleu vert",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetGrayMixerBlue",
    "Réinitialiser Niveau de gris bleu",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetGrayMixerPurple",
    "Réinitialiser Niveau de gris pourpre",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "ResetGrayMixerMagenta",
    "Réinitialiser Niveau de gris magenta",
    "Réinitialiser Réglages des couleurs",
    true
  },
  {
    "RevealPanelSplit",
    "Afficher Virage partiel",
    "Virage partiel",
    true
  },
  {
    "EnableSplitToning",
    "Activer le virage partiel",
    "Virage partiel",
    true
  },
  {
    "SplitToningShadowHue",
    "Teinte des ombres",
    "Virage partiel",
    false
  },
  {
    "SplitToningShadowSaturation",
    "Saturation des ombres",
    "Virage partiel",
    false
  },
  {
    "SplitToningHighlightHue",
    "Teinte des hautes lumières",
    "Virage partiel",
    false
  },
  {
    "SplitToningHighlightSaturation",
    "Saturation des hautes lumières",
    "Virage partiel",
    false
  },
  {
    "SplitToningBalance",
    "Balance du virage partiel",
    "Virage partiel",
    false
  },
  {
    "ResetSplitToningShadowHue",
    "Réinitialiser Teinte des ombres",
    "Virage partiel",
    true
  },
  {
    "ResetSplitToningShadowSaturation",
    "Réinitialiser Saturation des ombres",
    "Virage partiel",
    true
  },
  {
    "ResetSplitToningHighlightHue",
    "Réinitialiser Teinte des hautes lumières",
    "Virage partiel",
    true
  },
  {
    "ResetSplitToningHighlightSaturation",
    "Réinitialiser Saturation des hautes lumières",
    "Virage partiel",
    true
  },
  {
    "ResetSplitToningBalance",
    "Réinitialiser Balance du virage partiel",
    "Virage partiel",
    true
  },
  {
    "RevealPanelDetail",
    "Afficher Détail",
    "Détail",
    true
  },
  {
    "EnableDetail",
    "Activer le détail",
    "Détail",
    true
  },
  {
    "Sharpness",
    "Netteté",
    "Détail",
    false
  },
  {
    "SharpenRadius",
    "Accentuer le rayon",
    "Détail",
    false
  },
  {
    "SharpenDetail",
    "Accentuer le détail",
    "Détail",
    false
  },
  {
    "SharpenEdgeMasking",
    "Masque de contour",
    "Détail",
    false
  },
  {
    "LuminanceSmoothing",
    "Lissage de la luminance",
    "Détail",
    false
  },
  {
    "LuminanceNoiseReductionDetail",
    "Détail de luminance",
    "Détail",
    false
  },
  {
    "LuminanceNoiseReductionContrast",
    "Contraste de luminance",
    "Détail",
    false
  },
  {
    "ColorNoiseReduction",
    "Réduction du bruit chromatique",
    "Détail",
    false
  },
  {
    "ColorNoiseReductionDetail",
    "Détail de la couleur",
    "Détail",
    false
  },
  {
    "ColorNoiseReductionSmoothness",
    "Lissage des couleurs",
    "Détail",
    false
  },
  {
    "ResetSharpness",
    "Réinitialiser Netteté",
    "Détail",
    true
  },
  {
    "ResetSharpenRadius",
    "Réinitialiser Accentuer le rayon",
    "Détail",
    true
  },
  {
    "ResetSharpenDetail",
    "Réinitialiser Accentuer le détail",
    "Détail",
    true
  },
  {
    "ResetSharpenEdgeMasking",
    "Réinitialiser Masque de contour",
    "Détail",
    true
  },
  {
    "ResetLuminanceSmoothing",
    "Réinitialiser Lissage de la luminance",
    "Détail",
    true
  },
  {
    "ResetLuminanceNoiseReductionDetail",
    "Réinitialiser Détail de luminance",
    "Détail",
    true
  },
  {
    "ResetLuminanceNoiseReductionContrast",
    "Réinitialiser Contraste de luminance",
    "Détail",
    true
  },
  {
    "ResetColorNoiseReduction",
    "Réinitialiser Réduction du bruit chromatique",
    "Détail",
    true
  },
  {
    "ResetColorNoiseReductionDetail",
    "Réinitialiser Détail de la couleur",
    "Détail",
    true
  },
  {
    "ResetColorNoiseReductionSmoothness",
    "Réinitialiser Lissage des couleurs",
    "Détail",
    true
  },
  {
    "RevealPanelLens",
    "Afficher Corrections de l'objectif",
    "Corrections de l'objectif",
    true
  },
  {
    "EnableLensCorrections",
    "Activer les corrections de l'objectif",
    "Corrections de l'objectif",
    true
  },
  {
    "LensProfileEnable",
    "Activer le profil de l'objectif",
    "Corrections de l'objectif",
    true
  },
  {
    "AutoLateralCA",
    "Supprimer l'aberration chromatique",
    "Corrections de l'objectif",
    true
  },
  {
    "LensProfileDistortionScale",
    "Echelle de distorsion",
    "Corrections de l'objectif",
    false
  },
  {
    "LensProfileChromaticAberrationScale",
    "Echelle d'aberration chromatique",
    "Corrections de l'objectif",
    false
  },
  {
    "LensProfileVignettingScale",
    "Echelle de vignetage",
    "Corrections de l'objectif",
    false
  },
  {
    "CropConstrainToWarp",
    "Contraindre le recadrage",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetLensProfileDistortionScale",
    "Réinitialiser Echelle de distorsion",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetLensProfileChromaticAberrationScale",
    "Réinitialiser Echelle d'aberration chromatique",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetLensProfileVignettingScale",
    "Réinitialiser Echelle de vignetage",
    "Corrections de l'objectif",
    true
  },
  {
    "DefringePurpleAmount",
    "Valeur de violet pour la suppression des franges",
    "Corrections de l'objectif",
    false
  },
  {
    "DefringePurpleHueLo",
    "Teinte de violet pour la suppression des franges - Faible",
    "Corrections de l'objectif",
    false
  },
  {
    "DefringePurpleHueHi",
    "Teinte de violet pour la suppression des franges - Elevé",
    "Corrections de l'objectif",
    false
  },
  {
    "DefringeGreenAmount",
    "Valeur de vert pour la suppression des franges",
    "Corrections de l'objectif",
    false
  },
  {
    "DefringeGreenHueLo",
    "Teinte de vert pour la suppression des franges - Faible",
    "Corrections de l'objectif",
    false
  },
  {
    "DefringeGreenHueHi",
    "Teinte de vert pour la suppression des franges - Elevé",
    "Corrections de l'objectif",
    false
  },
  {
    "ResetDefringePurpleAmount",
    "Réinitialiser Valeur de violet pour la suppression des franges",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetDefringePurpleHueLo",
    "Réinitialiser Teinte de violet pour la suppression des franges - Faible",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetDefringePurpleHueHi",
    "Réinitialiser Teinte de violet pour la suppression des franges - Elevé",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetDefringeGreenAmount",
    "Réinitialiser Valeur de vert pour la suppression des franges",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetDefringeGreenHueLo",
    "Réinitialiser Teinte de vert pour la suppression des franges - Faible",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetDefringeGreenHueHi",
    "Réinitialiser Teinte de vert pour la suppression des franges - Elevé",
    "Corrections de l'objectif",
    true
  },
  {
    "LensManualDistortionAmount",
    "Quantité de distorsion",
    "Corrections de l'objectif",
    false
  },
  {
    "VignetteAmount",
    "Quantité de vignettage",
    "Corrections de l'objectif",
    false
  },
  {
    "VignetteMidpoint",
    "Milieu de vignette",
    "Corrections de l'objectif",
    false
  },
  {
    "ResetLensManualDistortionAmount",
    "Réinitialiser Quantité de distorsion",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetVignetteAmount",
    "Réinitialiser Quantité de vignettage",
    "Corrections de l'objectif",
    true
  },
  {
    "ResetVignetteMidpoint",
    "Réinitialiser Milieu de vignette",
    "Corrections de l'objectif",
    true
  },
  {
    "RevealPanelTransform",
    "Afficher Transformation",
    "Transformation",
    true
  },
  {
    "EnableTransform",
    "Activer la transformation",
    "Transformation",
    true
  },
  {
    "UprightOff",
    "Perspective Upright Désactivé",
    "Transformation",
    true
  },
  {
    "UprightAuto",
    "Perspective Upright Auto",
    "Transformation",
    true
  },
  {
    "UprightLevel",
    "Perspective Upright Niveau",
    "Transformation",
    true
  },
  {
    "UprightVertical",
    "Perspective Upright Vertical",
    "Transformation",
    true
  },
  {
    "UprightGuided",
    "Perspective Upright Avec repères",
    "Transformation",
    true
  },
  {
    "UprightFull",
    "Perspective Upright Complète",
    "Transformation",
    true
  },
  {
    "ResetPerspectiveUpright",
    "Réinitialiser les paramètres Upright",
    "Transformation",
    true
  },
  {
    "PerspectiveVertical",
    "Perspective verticale",
    "Transformation",
    false
  },
  {
    "PerspectiveHorizontal",
    "Perspective horizontale",
    "Transformation",
    false
  },
  {
    "PerspectiveRotate",
    "Rotation en perspective",
    "Transformation",
    false
  },
  {
    "PerspectiveScale",
    "Echelle de perspective",
    "Transformation",
    false
  },
  {
    "PerspectiveAspect",
    "Aspect en perspective",
    "Transformation",
    false
  },
  {
    "PerspectiveX",
    "Décalage X",
    "Transformation",
    false
  },
  {
    "PerspectiveY",
    "Décalage Y",
    "Transformation",
    false
  },
  {
    "ResetPerspectiveVertical",
    "Réinitialiser Perspective verticale",
    "Transformation",
    true
  },
  {
    "ResetPerspectiveHorizontal",
    "Réinitialiser Perspective horizontale",
    "Transformation",
    true
  },
  {
    "ResetPerspectiveRotate",
    "Réinitialiser Rotation en perspective",
    "Transformation",
    true
  },
  {
    "ResetPerspectiveScale",
    "Réinitialiser Echelle de perspective",
    "Transformation",
    true
  },
  {
    "ResetPerspectiveAspect",
    "Réinitialiser Aspect en perspective",
    "Transformation",
    true
  },
  {
    "ResetPerspectiveX",
    "Réinitialiser Décalage X",
    "Transformation",
    true
  },
  {
    "ResetPerspectiveY",
    "Réinitialiser Décalage Y",
    "Transformation",
    true
  },
  {
    "RevealPanelEffects",
    "Afficher Effets",
    "Effets",
    true
  },
  {
    "EnableEffects",
    "Activer les effets",
    "Effets",
    true
  },
  {
    "Dehaze",
    "Niveau de correction du voile",
    "Effets",
    false
  },
  {
    "PostCropVignetteAmount",
    "Quantité de vignettage après recadrage",
    "Effets",
    false
  },
  {
    "PostCropVignetteMidpoint",
    "Milieu de vignette après recadrage",
    "Effets",
    false
  },
  {
    "PostCropVignetteFeather",
    "Contour progressif de la vignette après recadrage",
    "Effets",
    false
  },
  {
    "PostCropVignetteRoundness",
    "Arrondi de la vignette après recadrage",
    "Effets",
    false
  },
  {
    "PostCropVignetteStyle",
    "Style de vignette après recadrage",
    "Effets",
    false
  },
  {
    "PostCropVignetteStyleHighlightPriority",
    "Priorité des hautes lumières",
    "Effets",
    true
  },
  {
    "PostCropVignetteStyleColorPriority",
    "Priorité de la couleur",
    "Effets",
    true
  },
  {
    "PostCropVignetteStylePaintOverlay",
    "Incrustation de peinture",
    "Effets",
    true
  },
  {
    "PostCropVignetteHighlightContrast",
    "Hautes lumières des vignettes après recadrage",
    "Effets",
    false
  },
  {
    "GrainAmount",
    "Niveau de grain",
    "Effets",
    false
  },
  {
    "GrainSize",
    "Taille du grain",
    "Effets",
    false
  },
  {
    "GrainFrequency",
    "Rugosité du grain",
    "Effets",
    false
  },
  {
    "ResetDehaze",
    "Réinitialiser Niveau de correction du voile",
    "Effets",
    true
  },
  {
    "ResetPostCropVignetteAmount",
    "Réinitialiser Quantité de vignettage après recadrage",
    "Effets",
    true
  },
  {
    "ResetPostCropVignetteMidpoint",
    "Réinitialiser Milieu de vignette après recadrage",
    "Effets",
    true
  },
  {
    "ResetPostCropVignetteFeather",
    "Réinitialiser Contour progressif de la vignette après recadrage",
    "Effets",
    true
  },
  {
    "ResetPostCropVignetteRoundness",
    "Réinitialiser Arrondi de la vignette après recadrage",
    "Effets",
    true
  },
  {
    "ResetPostCropVignetteStyle",
    "Réinitialiser Style de vignette après recadrage",
    "Effets",
    true
  },
  {
    "ResetPostCropVignetteHighlightContrast",
    "Réinitialiser Hautes lumières des vignettes après recadrage",
    "Effets",
    true
  },
  {
    "ResetGrainAmount",
    "Réinitialiser Niveau de grain",
    "Effets",
    true
  },
  {
    "ResetGrainSize",
    "Réinitialiser Taille du grain",
    "Effets",
    true
  },
  {
    "ResetGrainFrequency",
    "Réinitialiser Rugosité du grain",
    "Effets",
    true
  },
  {
    "RevealPanelCalibrate",
    "Afficher Etalonnage",
    "Etalonnage",
    true
  },
  {
    "EnableCalibration",
    "Activer l'étalonnage",
    "Etalonnage",
    true
  },
  {
    "Profile_Adobe_Standard",
    "Adobe Standard",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Clear",
    "Appareil photo - Net",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Darker_Skin_Tone",
    "Appareil photo - Coloration de la peau plus foncée",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Deep",
    "Appareil photo - Profond",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Faithful",
    "Appareil photo - Fidèle",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Flat",
    "Appareil photo - Plat",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Landscape",
    "Appareil photo - Paysage",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Light",
    "Appareil photo - Clair",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Lighter_Skin_Tone",
    "Appareil photo - Coloration de la peau plus claire",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Monochrome",
    "Appareil photo - Monochrome",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Monotone",
    "Appareil photo - Tonalité unique",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Muted",
    "Appareil photo - Discret",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Natural",
    "Appareil photo - Naturel",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Neutral",
    "Appareil photo - Neutre",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Portrait",
    "Appareil photo - Portrait",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Positive_Film",
    "Appareil photo - Film positif",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Standard",
    "Appareil photo - Standard",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Vivid",
    "Appareil photo - Vif",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Vivid_Blue",
    "Appareil photo - Bleu vif",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Vivid_Green",
    "Appareil photo - Vert vif",
    "Etalonnage",
    true
  },
  {
    "Profile_Camera_Vivid_Red",
    "Appareil photo - Rouge vif",
    "Etalonnage",
    true
  },
  {
    "ShadowTint",
    "Teinte foncée d'étalonnage",
    "Etalonnage",
    false
  },
  {
    "RedHue",
    "Teinte du rouge d'étalonnage",
    "Etalonnage",
    false
  },
  {
    "RedSaturation",
    "Saturation du rouge d'étalonnage",
    "Etalonnage",
    false
  },
  {
    "GreenHue",
    "Teinte du vert d'étalonnage",
    "Etalonnage",
    false
  },
  {
    "GreenSaturation",
    "Saturation du vert d'étalonnage",
    "Etalonnage",
    false
  },
  {
    "BlueHue",
    "Teinte du bleu d'étalonnage",
    "Etalonnage",
    false
  },
  {
    "BlueSaturation",
    "Saturation du bleu d'étalonnage",
    "Etalonnage",
    false
  },
  {
    "ResetShadowTint",
    "Réinitialiser Teinte foncée d'étalonnage",
    "Etalonnage",
    true
  },
  {
    "ResetRedHue",
    "Réinitialiser Teinte du rouge d'étalonnage",
    "Etalonnage",
    true
  },
  {
    "ResetRedSaturation",
    "Réinitialiser Saturation du rouge d'étalonnage",
    "Etalonnage",
    true
  },
  {
    "ResetGreenHue",
    "Réinitialiser Teinte du vert d'étalonnage",
    "Etalonnage",
    true
  },
  {
    "ResetGreenSaturation",
    "Réinitialiser Saturation du vert d'étalonnage",
    "Etalonnage",
    true
  },
  {
    "ResetBlueHue",
    "Réinitialiser Teinte du bleu d'étalonnage",
    "Etalonnage",
    true
  },
  {
    "ResetBlueSaturation",
    "Réinitialiser Saturation du bleu d'étalonnage",
    "Etalonnage",
    true
  },
  {
    "Preset_1",
    "Paramètre prédéfini de développement 1",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_2",
    "Paramètre prédéfini de développement 2",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_3",
    "Paramètre prédéfini de développement 3",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_4",
    "Paramètre prédéfini de développement 4",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_5",
    "Paramètre prédéfini de développement 5",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_6",
    "Paramètre prédéfini de développement 6",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_7",
    "Paramètre prédéfini de développement 7",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_8",
    "Paramètre prédéfini de développement 8",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_9",
    "Paramètre prédéfini de développement 9",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_10",
    "Paramètre prédéfini de développement 10",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_11",
    "Paramètre prédéfini de développement 11",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_12",
    "Paramètre prédéfini de développement 12",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_13",
    "Paramètre prédéfini de développement 13",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_14",
    "Paramètre prédéfini de développement 14",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_15",
    "Paramètre prédéfini de développement 15",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_16",
    "Paramètre prédéfini de développement 16",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_17",
    "Paramètre prédéfini de développement 17",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_18",
    "Paramètre prédéfini de développement 18",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_19",
    "Paramètre prédéfini de développement 19",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_20",
    "Paramètre prédéfini de développement 20",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_21",
    "Paramètre prédéfini de développement 21",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_22",
    "Paramètre prédéfini de développement 22",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_23",
    "Paramètre prédéfini de développement 23",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_24",
    "Paramètre prédéfini de développement 24",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_25",
    "Paramètre prédéfini de développement 25",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_26",
    "Paramètre prédéfini de développement 26",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_27",
    "Paramètre prédéfini de développement 27",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_28",
    "Paramètre prédéfini de développement 28",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_29",
    "Paramètre prédéfini de développement 29",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_30",
    "Paramètre prédéfini de développement 30",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_31",
    "Paramètre prédéfini de développement 31",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_32",
    "Paramètre prédéfini de développement 32",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_33",
    "Paramètre prédéfini de développement 33",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_34",
    "Paramètre prédéfini de développement 34",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_35",
    "Paramètre prédéfini de développement 35",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_36",
    "Paramètre prédéfini de développement 36",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_37",
    "Paramètre prédéfini de développement 37",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_38",
    "Paramètre prédéfini de développement 38",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_39",
    "Paramètre prédéfini de développement 39",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_40",
    "Paramètre prédéfini de développement 40",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_41",
    "Paramètre prédéfini de développement 41",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_42",
    "Paramètre prédéfini de développement 42",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_43",
    "Paramètre prédéfini de développement 43",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_44",
    "Paramètre prédéfini de développement 44",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_45",
    "Paramètre prédéfini de développement 45",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_46",
    "Paramètre prédéfini de développement 46",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_47",
    "Paramètre prédéfini de développement 47",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_48",
    "Paramètre prédéfini de développement 48",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_49",
    "Paramètre prédéfini de développement 49",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_50",
    "Paramètre prédéfini de développement 50",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_51",
    "Paramètre prédéfini de développement 51",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_52",
    "Paramètre prédéfini de développement 52",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_53",
    "Paramètre prédéfini de développement 53",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_54",
    "Paramètre prédéfini de développement 54",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_55",
    "Paramètre prédéfini de développement 55",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_56",
    "Paramètre prédéfini de développement 56",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_57",
    "Paramètre prédéfini de développement 57",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_58",
    "Paramètre prédéfini de développement 58",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_59",
    "Paramètre prédéfini de développement 59",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_60",
    "Paramètre prédéfini de développement 60",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_61",
    "Paramètre prédéfini de développement 61",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_62",
    "Paramètre prédéfini de développement 62",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_63",
    "Paramètre prédéfini de développement 63",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_64",
    "Paramètre prédéfini de développement 64",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_65",
    "Paramètre prédéfini de développement 65",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_66",
    "Paramètre prédéfini de développement 66",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_67",
    "Paramètre prédéfini de développement 67",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_68",
    "Paramètre prédéfini de développement 68",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_69",
    "Paramètre prédéfini de développement 69",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_70",
    "Paramètre prédéfini de développement 70",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_71",
    "Paramètre prédéfini de développement 71",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_72",
    "Paramètre prédéfini de développement 72",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_73",
    "Paramètre prédéfini de développement 73",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_74",
    "Paramètre prédéfini de développement 74",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_75",
    "Paramètre prédéfini de développement 75",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_76",
    "Paramètre prédéfini de développement 76",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_77",
    "Paramètre prédéfini de développement 77",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_78",
    "Paramètre prédéfini de développement 78",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_79",
    "Paramètre prédéfini de développement 79",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Preset_80",
    "Paramètre prédéfini de développement 80",
    "Paramètres prédéfinis de développement",
    true
  },
  {
    "Keyword1",
    "Mot-clé 1",
    "Mots-clés",
    true
  },
  {
    "Keyword2",
    "Mot-clé 2",
    "Mots-clés",
    true
  },
  {
    "Keyword3",
    "Mot-clé 3",
    "Mots-clés",
    true
  },
  {
    "Keyword4",
    "Mot-clé 4",
    "Mots-clés",
    true
  },
  {
    "Keyword5",
    "Mot-clé 5",
    "Mots-clés",
    true
  },
  {
    "Keyword6",
    "Mot-clé 6",
    "Mots-clés",
    true
  },
  {
    "Keyword7",
    "Mot-clé 7",
    "Mots-clés",
    true
  },
  {
    "Keyword8",
    "Mot-clé 8",
    "Mots-clés",
    true
  },
  {
    "Keyword9",
    "Mot-clé 9",
    "Mots-clés",
    true
  },
  {
    "Keyword10",
    "Mot-clé 10",
    "Mots-clés",
    true
  },
  {
    "Keyword11",
    "Mot-clé 11",
    "Mots-clés",
    true
  },
  {
    "Keyword12",
    "Mot-clé 12",
    "Mots-clés",
    true
  },
  {
    "Keyword13",
    "Mot-clé 13",
    "Mots-clés",
    true
  },
  {
    "Keyword14",
    "Mot-clé 14",
    "Mots-clés",
    true
  },
  {
    "Keyword15",
    "Mot-clé 15",
    "Mots-clés",
    true
  },
  {
    "Keyword16",
    "Mot-clé 16",
    "Mots-clés",
    true
  },
  {
    "GraduatedFilter",
    "Afficher Filtre gradué",
    "Réglages locaux",
    true
  },
  {
    "RadialFilter",
    "Afficher Filtre radial",
    "Réglages locaux",
    true
  },
  {
    "RedEye",
    "Afficher Correction des yeux rouges",
    "Réglages locaux",
    true
  },
  {
    "SpotRemoval",
    "Afficher Suppression des défauts",
    "Réglages locaux",
    true
  },
  {
    "AdjustmentBrush",
    "Afficher Réglage du pinceau",
    "Réglages locaux",
    true
  },
  {
    "ChangeBrushSize",
    "Pinceau — Taille",
    "Réglages locaux",
    true
  },
  {
    "BrushSizeSmaller",
    "Pinceau — Taille — Très petite",
    "Réglages locaux",
    true
  },
  {
    "BrushSizeLarger",
    "Pinceau — Taille — Très grande",
    "Réglages locaux",
    true
  },
  {
    "ChangeFeatherSize",
    "Pinceau — Contour progressif",
    "Réglages locaux",
    true
  },
  {
    "BrushFeatherSmaller",
    "Pinceau — Contour progressif — Très petite",
    "Réglages locaux",
    true
  },
  {
    "BrushFeatherLarger",
    "Pinceau — Contour progressif — Très grande",
    "Réglages locaux",
    true
  },
  {
    "local_Temperature",
    "Réglages locaux Température (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Tint",
    "Réglages locaux Teinte (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Exposure",
    "Réglages locaux Exposition (PV2010 and PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Contrast",
    "Réglages locaux Contraste (PV2010 and PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Highlights",
    "Réglages locaux Hautes lumières (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Shadows",
    "Réglages locaux Ombres (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Whites2012",
    "Réglages locaux Blancs (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Blacks2012",
    "Réglages locaux Noirs (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Clarity",
    "Réglages locaux Clarté (PV2010 and PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Dehaze",
    "Réglages locaux Correction du voile (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Saturation",
    "Réglages locaux Saturation (PV2010 and PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Sharpness",
    "Réglages locaux Netteté (PV2010 and PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_LuminanceNoise",
    "Réglages locaux Bruit (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Moire",
    "Réglages locaux Moiré (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_Defringe",
    "Réglages locaux Supprimer la frange (PV2012)",
    "Réglages locaux",
    false
  },
  {
    "local_ToningLuminance",
    "Local Toning Luminance (PV2010)",
    "Réglages locaux",
    false
  },
  {
    "Resetlocal_Temperature",
    "Réinitialiser Réglages locaux Température (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Tint",
    "Réinitialiser Réglages locaux Teinte (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Exposure",
    "Réinitialiser Réglages locaux Exposition (PV2010 and PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Contrast",
    "Réinitialiser Réglages locaux Contraste (PV2010 and PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Highlights",
    "Réinitialiser Réglages locaux Hautes lumières (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Shadows",
    "Réinitialiser Réglages locaux Ombres (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Whites2012",
    "Réinitialiser Réglages locaux Blancs (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Blacks2012",
    "Réinitialiser Réglages locaux Noirs (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Clarity",
    "Réinitialiser Réglages locaux Clarté (PV2010 and PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Dehaze",
    "Réinitialiser Réglages locaux Correction du voile (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Saturation",
    "Réinitialiser Réglages locaux Saturation (PV2010 and PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Sharpness",
    "Réinitialiser Réglages locaux Netteté (PV2010 and PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_LuminanceNoise",
    "Réinitialiser Réglages locaux Bruit (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Moire",
    "Réinitialiser Réglages locaux Moiré (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_Defringe",
    "Réinitialiser Réglages locaux Supprimer la frange (PV2012)",
    "Réglages locaux",
    true
  },
  {
    "Resetlocal_ToningLuminance",
    "Reset Local Toning Luminance (PV2010)",
    "Réglages locaux",
    true
  },
  {
    "EnableCircularGradientBasedCorrections",
    "Activer le filtre radial",
    "Réglages locaux",
    true
  },
  {
    "EnableGradientBasedCorrections",
    "Activer le filtre gradué",
    "Réglages locaux",
    true
  },
  {
    "EnablePaintBasedCorrections",
    "Activer les réglages du pinceau",
    "Réglages locaux",
    true
  },
  {
    "EnableRedEye",
    "Activer la correction des yeux rouges",
    "Réglages locaux",
    true
  },
  {
    "EnableRetouch",
    "Activer la suppression des défauts",
    "Réglages locaux",
    true
  },
  {
    "ResetCircGrad",
    "Réinitialiser le filtre radial",
    "Réglages locaux",
    true
  },
  {
    "ResetGradient",
    "Réinitialiser le filtre gradué",
    "Réglages locaux",
    true
  },
  {
    "ResetBrushing",
    "Annuler tous les réglages au pinceau",
    "Réglages locaux",
    true
  },
  {
    "ResetRedeye",
    "Réinitialiser les yeux rouges",
    "Réglages locaux",
    true
  },
  {
    "ResetSpotRem",
    "Réinitialiser la suppression des défauts",
    "Réglages locaux",
    true
  },
  {
    "ShowMaskOverlay",
    "Afficher l'incrustation de masque sélectionnée",
    "Réglages locaux",
    true
  },
  {
    "CycleMaskOverlayColor",
    "Alterner entre les couleurs d'incrustation",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset1",
    "Réglages prédéfinis locaux 1",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset2",
    "Réglages prédéfinis locaux 2",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset3",
    "Réglages prédéfinis locaux 3",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset4",
    "Réglages prédéfinis locaux 4",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset5",
    "Réglages prédéfinis locaux 5",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset6",
    "Réglages prédéfinis locaux 6",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset7",
    "Réglages prédéfinis locaux 7",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset8",
    "Réglages prédéfinis locaux 8",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset9",
    "Réglages prédéfinis locaux 9",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset10",
    "Réglages prédéfinis locaux 10",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset11",
    "Réglages prédéfinis locaux 11",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset12",
    "Réglages prédéfinis locaux 12",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset13",
    "Réglages prédéfinis locaux 13",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset14",
    "Réglages prédéfinis locaux 14",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset15",
    "Réglages prédéfinis locaux 15",
    "Réglages locaux",
    true
  },
  {
    "LocalPreset16",
    "Réglages prédéfinis locaux 16",
    "Réglages locaux",
    true
  },
  {
    "straightenAngle",
    "Angle de redressement",
    "Recadrage",
    false
  },
  {
    "CropAngle",
    "Angle de recadrage",
    "Recadrage",
    false
  },
  {
    "CropBottom",
    "Recadrage - Bas",
    "Recadrage",
    false
  },
  {
    "CropLeft",
    "Recadrage - Gauche",
    "Recadrage",
    false
  },
  {
    "CropRight",
    "Recadrage - Droite",
    "Recadrage",
    false
  },
  {
    "CropTop",
    "Recadrage - Haut",
    "Recadrage",
    false
  },
  {
    "ResetCrop",
    "Réinitialiser le cadrage",
    "Recadrage",
    true
  },
  {
    "ResetstraightenAngle",
    "Réinitialiser Angle de redressement",
    "Recadrage",
    true
  },
  {
    "CropOverlay",
    "Afficher Recadrage",
    "Recadrage",
    true
  },
  {
    "Loupe",
    "Afficher Loupe",
    "Sélectionner Outils, Modules  et Panneaux",
    true
  },
  {
    "SwToMmap",
    "Afficher Cartes",
    "Sélectionner Outils, Modules  et Panneaux",
    true
  },
  {
    "SwToMbook",
    "Afficher Livres",
    "Sélectionner Outils, Modules  et Panneaux",
    true
  },
  {
    "SwToMslideshow",
    "Afficher Diaporama",
    "Sélectionner Outils, Modules  et Panneaux",
    true
  },
  {
    "SwToMprint",
    "Afficher Imprimer",
    "Sélectionner Outils, Modules  et Panneaux",
    true
  },
  {
    "SwToMweb",
    "Afficher Raccourcis du module web",
    "Sélectionner Outils, Modules  et Panneaux",
    true
  },
  {
    "ShoScndVwloupe",
    "Affichage secondaire Loupe",
    "Affichage secondaire",
    true
  },
  {
    "ShoScndVwlive_loupe",
    "Affichage secondaire Loupe interactive",
    "Affichage secondaire",
    true
  },
  {
    "ShoScndVwlocked_loupe",
    "Affichage secondaire Loupe verrouillée",
    "Affichage secondaire",
    true
  },
  {
    "ShoScndVwgrid",
    "Affichage secondaire Grille",
    "Affichage secondaire",
    true
  },
  {
    "ShoScndVwcompare",
    "Affichage secondaire Comparaison",
    "Affichage secondaire",
    true
  },
  {
    "ShoScndVwsurvey",
    "Affichage secondaire Ensemble",
    "Affichage secondaire",
    true
  },
  {
    "ShoScndVwslideshow",
    "Affichage secondaire Diaporama",
    "Affichage secondaire",
    true
  },
  {
    "ToggleScreenTwo",
    "Affichage secondaire Afficher",
    "Affichage secondaire",
    true
  },
  {
    "profile1",
    "Profil : 1",
    "Profils",
    true
  },
  {
    "profile2",
    "Profil : 2",
    "Profils",
    true
  },
  {
    "profile3",
    "Profil : 3",
    "Profils",
    true
  },
  {
    "profile4",
    "Profil : 4",
    "Profils",
    true
  },
  {
    "profile5",
    "Profil : 5",
    "Profils",
    true
  },
  {
    "profile6",
    "Profil : 6",
    "Profils",
    true
  },
  {
    "profile7",
    "Profil : 7",
    "Profils",
    true
  },
  {
    "profile8",
    "Profil : 8",
    "Profils",
    true
  },
  {
    "profile9",
    "Profil : 9",
    "Profils",
    true
  },
  {
    "profile10",
    "Profil : 10",
    "Profils",
    true
  },
  {
    "FullRefresh",
    "Actualisation manuelle",
    "Profils",
    true
  }
}

return MenuList

