--[[----------------------------------------------------------------------------
This file was auto-generated by MIDI2LR and contains the translated menus used
by the app and the plugin. Edits to this file will be lost any time MIDI2LR
is updated or the language used by Lightroom changes. Edit MenuListPreTrans.lua
if you want to have persistent changes to the translations or menu structure.

This file is part of MIDI2LR. Copyright 2015-2016 by Rory Jaffe.
MIDI2LR is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

MIDI2LR is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
MIDI2LR.  If not, see <http://www.gnu.org/licenses/>. 
------------------------------------------------------------------------------]]
  local MenuList = {
  {
    "WhiteBalanceAs_Shot",
    "White Balance As Shot",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceAuto",
    "White Balance Auto",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceCloudy",
    "White Balance Cloudy",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceDaylight",
    "White Balance Daylight",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceFlash",
    "White Balance Flash",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceFluorescent",
    "White Balance Fluorescent",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceShade",
    "White Balance Shade",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceTungsten",
    "White Balance Tungsten",
    "Basic Tone",
    true
  },
  {
    "Temperature",
    "Temperature",
    "Basic Tone",
    false
  },
  {
    "Tint",
    "Tint",
    "Basic Tone",
    false
  },
  {
    "Exposure",
    "Exposure",
    "Basic Tone",
    false
  },
  {
    "Contrast",
    "Contrast",
    "Basic Tone",
    false
  },
  {
    "Highlights",
    "Highlights(Recovery in PV2003 and PV2010)",
    "Basic Tone",
    false
  },
  {
    "Shadows",
    "Shadows(Fill Light in PV2003 and PV2010)",
    "Basic Tone",
    false
  },
  {
    "Whites",
    "Whites(no effect in PV2003 and PV2010)",
    "Basic Tone",
    false
  },
  {
    "Blacks",
    "Blacks",
    "Basic Tone",
    false
  },
  {
    "Clarity",
    "Clarity",
    "Basic Tone",
    false
  },
  {
    "Vibrance",
    "Vibrance",
    "Basic Tone",
    false
  },
  {
    "Saturation",
    "Saturation",
    "Basic Tone",
    false
  },
  {
    "ResetTemperature",
    "Reset Temperature",
    "Basic Tone",
    true
  },
  {
    "ResetTint",
    "Reset Tint",
    "Basic Tone",
    true
  },
  {
    "ResetExposure",
    "Reset Exposure",
    "Basic Tone",
    true
  },
  {
    "ResetContrast",
    "Reset Contrast",
    "Basic Tone",
    true
  },
  {
    "ResetHighlights",
    "Reset Highlights",
    "Basic Tone",
    true
  },
  {
    "ResetShadows",
    "Reset Shadows",
    "Basic Tone",
    true
  },
  {
    "ResetWhites",
    "Reset Whites",
    "Basic Tone",
    true
  },
  {
    "ResetBlacks",
    "Reset Blacks",
    "Basic Tone",
    true
  },
  {
    "ResetClarity",
    "Reset Clarity",
    "Basic Tone",
    true
  },
  {
    "ResetVibrance",
    "Reset Vibrance",
    "Basic Tone",
    true
  },
  {
    "ResetSaturation",
    "Reset Saturation",
    "Basic Tone",
    true
  },
  {
    "ParametricDarks",
    "Dark Tones",
    "Tone Curve",
    false
  },
  {
    "ParametricLights",
    "Light Tones",
    "Tone Curve",
    false
  },
  {
    "ParametricShadows",
    "Shadow Tones",
    "Tone Curve",
    false
  },
  {
    "ParametricHighlights",
    "Highlight Tones",
    "Tone Curve",
    false
  },
  {
    "ParametricShadowSplit",
    "Shadow Split",
    "Tone Curve",
    false
  },
  {
    "ParametricMidtoneSplit",
    "Midtone Split",
    "Tone Curve",
    false
  },
  {
    "ParametricHighlightSplit",
    "Highlight Split",
    "Tone Curve",
    false
  },
  {
    "ResetParametricDarks",
    "Reset Dark Tones",
    "Tone Curve",
    true
  },
  {
    "ResetParametricLights",
    "Reset Light Tones",
    "Tone Curve",
    true
  },
  {
    "ResetParametricShadows",
    "Reset Shadow Tones",
    "Tone Curve",
    true
  },
  {
    "ResetParametricHighlights",
    "Reset Highlight Tones",
    "Tone Curve",
    true
  },
  {
    "ResetParametricShadowSplit",
    "Reset Shadow Split",
    "Tone Curve",
    true
  },
  {
    "ResetParametricMidtoneSplit",
    "Reset Midtone Split",
    "Tone Curve",
    true
  },
  {
    "ResetParametricHighlightSplit",
    "Reset Highlight Split",
    "Tone Curve",
    true
  },
  {
    "EnableColorAdjustments",
    "Enable Color Adjustments",
    "Color Adjustments",
    true
  },
  {
    "SaturationAdjustmentRed",
    "Saturation Adjustment Red",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentOrange",
    "Saturation Adjustment Orange",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentYellow",
    "Saturation Adjustment Yellow",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentGreen",
    "Saturation Adjustment Green",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentAqua",
    "Saturation Adjustment Aqua",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentBlue",
    "Saturation Adjustment Blue",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentPurple",
    "Saturation Adjustment Purple",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentMagenta",
    "Saturation Adjustment Magenta",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentRed",
    "Hue Adjustment Red",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentOrange",
    "Hue Adjustment Orange",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentYellow",
    "Hue Adjustment Yellow",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentGreen",
    "Hue Adjustment Green",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentAqua",
    "Hue Adjustment Aqua",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentBlue",
    "Hue Adjustment Blue",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentPurple",
    "Hue Adjustment Purple",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentMagenta",
    "Hue Adjustment Magenta",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentRed",
    "Luminance Adjustment Red",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentOrange",
    "Luminance Adjustment Orange",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentYellow",
    "Luminance Adjustment Yellow",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentGreen",
    "Luminance Adjustment Green",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentAqua",
    "Luminance Adjustment Aqua",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentBlue",
    "Luminance Adjustment Blue",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentPurple",
    "Luminance Adjustment Purple",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentMagenta",
    "Luminance Adjustment Magenta",
    "Color Adjustments",
    false
  },
  {
    "ConvertToGrayscale",
    "Convert to Grayscale",
    "Color Adjustments",
    true
  },
  {
    "EnableGrayscaleMix",
    "Enable Grayscale Mix",
    "Color Adjustments",
    true
  },
  {
    "GrayMixerRed",
    "Gray Mixer Red",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerOrange",
    "Gray Mixer Orange",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerYellow",
    "Gray Mixer Yellow",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerGreen",
    "Gray Mixer Green",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerAqua",
    "Gray Mixer Aqua",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerBlue",
    "Gray Mixer Blue",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerPurple",
    "Gray Mixer Purple",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerMagenta",
    "Gray Mixer Magenta",
    "Color Adjustments",
    false
  },
  {
    "ResetSaturationAdjustmentRed",
    "Reset Saturation Adjustment Red",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentOrange",
    "Reset Saturation Adjustment Orange",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentYellow",
    "Reset Saturation Adjustment Yellow",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentGreen",
    "Reset Saturation Adjustment Green",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentAqua",
    "Reset Saturation Adjustment Aqua",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentBlue",
    "Reset Saturation Adjustment Blue",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentPurple",
    "Reset Saturation Adjustment Purple",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentMagenta",
    "Reset Saturation Adjustment Magenta",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentRed",
    "Reset Hue Adjustment Red",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentOrange",
    "Reset Hue Adjustment Orange",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentYellow",
    "Reset Hue Adjustment Yellow",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentGreen",
    "Reset Hue Adjustment Green",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentAqua",
    "Reset Hue Adjustment Aqua",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentBlue",
    "Reset Hue Adjustment Blue",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentPurple",
    "Reset Hue Adjustment Purple",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentMagenta",
    "Reset Hue Adjustment Magenta",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentRed",
    "Reset Luminance Adjustment Red",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentOrange",
    "Reset Luminance Adjustment Orange",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentYellow",
    "Reset Luminance Adjustment Yellow",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentGreen",
    "Reset Luminance Adjustment Green",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentAqua",
    "Reset Luminance Adjustment Aqua",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentBlue",
    "Reset Luminance Adjustment Blue",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentPurple",
    "Reset Luminance Adjustment Purple",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentMagenta",
    "Reset Luminance Adjustment Magenta",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerRed",
    "Reset Gray Mixer Red",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerOrange",
    "Reset Gray Mixer Orange",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerYellow",
    "Reset Gray Mixer Yellow",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerGreen",
    "Reset Gray Mixer Green",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerAqua",
    "Reset Gray Mixer Aqua",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerBlue",
    "Reset Gray Mixer Blue",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerPurple",
    "Reset Gray Mixer Purple",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerMagenta",
    "Reset Gray Mixer Magenta",
    "Reset Color Adjustments",
    true
  },
  {
    "EnableSplitToning",
    "Enable Split Toning",
    "Split Toning",
    true
  },
  {
    "SplitToningShadowHue",
    "Shadow Hue",
    "Split Toning",
    false
  },
  {
    "SplitToningShadowSaturation",
    "Shadow Saturation",
    "Split Toning",
    false
  },
  {
    "SplitToningHighlightHue",
    "Highlight Hue",
    "Split Toning",
    false
  },
  {
    "SplitToningHighlightSaturation",
    "Highlight Saturation",
    "Split Toning",
    false
  },
  {
    "SplitToningBalance",
    "Split Toning Balance",
    "Split Toning",
    false
  },
  {
    "ResetSplitToningShadowHue",
    "Reset Shadow Hue",
    "Split Toning",
    true
  },
  {
    "ResetSplitToningShadowSaturation",
    "Reset Shadow Saturation",
    "Split Toning",
    true
  },
  {
    "ResetSplitToningHighlightHue",
    "Reset Highlight Hue",
    "Split Toning",
    true
  },
  {
    "ResetSplitToningHighlightSaturation",
    "Reset Highlight Saturation",
    "Split Toning",
    true
  },
  {
    "ResetSplitToningBalance",
    "Reset Split Toning Balance",
    "Split Toning",
    true
  },
  {
    "EnableDetail",
    "Enable Detail",
    "Detail",
    true
  },
  {
    "Sharpness",
    "Sharpness",
    "Detail",
    false
  },
  {
    "SharpenRadius",
    "Sharpen Radius",
    "Detail",
    false
  },
  {
    "SharpenDetail",
    "Sharpen Detail",
    "Detail",
    false
  },
  {
    "SharpenEdgeMasking",
    "Sharpen Edge Masking",
    "Detail",
    false
  },
  {
    "LuminanceSmoothing",
    "Luminance Smoothing",
    "Detail",
    false
  },
  {
    "LuminanceNoiseReductionDetail",
    "Luminance Detail",
    "Detail",
    false
  },
  {
    "LuminanceNoiseReductionContrast",
    "Luminance Contrast",
    "Detail",
    false
  },
  {
    "ColorNoiseReduction",
    "Color Noise Reduction",
    "Detail",
    false
  },
  {
    "ColorNoiseReductionDetail",
    "Color Noise Reduction Detail",
    "Detail",
    false
  },
  {
    "ColorNoiseReductionSmoothness",
    "Color Noise Reduction Smoothness",
    "Detail",
    false
  },
  {
    "ResetSharpness",
    "Reset Sharpness",
    "Detail",
    true
  },
  {
    "ResetSharpenRadius",
    "Reset Sharpen Radius",
    "Detail",
    true
  },
  {
    "ResetSharpenDetail",
    "Reset Sharpen Detail",
    "Detail",
    true
  },
  {
    "ResetSharpenEdgeMasking",
    "Reset Sharpen Edge Masking",
    "Detail",
    true
  },
  {
    "ResetLuminanceSmoothing",
    "Reset Luminance Smoothing",
    "Detail",
    true
  },
  {
    "ResetLuminanceNoiseReductionDetail",
    "Reset Luminance Detail",
    "Detail",
    true
  },
  {
    "ResetLuminanceNoiseReductionContrast",
    "Reset Luminance Contrast",
    "Detail",
    true
  },
  {
    "ResetColorNoiseReduction",
    "Reset Color Noise Reduction",
    "Detail",
    true
  },
  {
    "ResetColorNoiseReductionDetail",
    "Reset Color Noise Reduction Detail",
    "Detail",
    true
  },
  {
    "ResetColorNoiseReductionSmoothness",
    "Reset Color Noise Reduction Smoothness",
    "Detail",
    true
  },
  {
    "EnableLensCorrections",
    "Enable Lens Corrections",
    "Lens Corrections",
    true
  },
  {
    "LensProfileEnable",
    "Lens Profile Enable",
    "Lens Corrections",
    true
  },
  {
    "AutoLateralCA",
    "Remove Chromatic Aberration",
    "Lens Corrections",
    true
  },
  {
    "UprightOff",
    "Perspective Correction Off",
    "Lens Corrections",
    true
  },
  {
    "UprightAuto",
    "Perspective Correction Auto",
    "Lens Corrections",
    true
  },
  {
    "UprightLevel",
    "Perspective Correction Level",
    "Lens Corrections",
    true
  },
  {
    "UprightVertical",
    "Perspective Correction Vertical",
    "Lens Corrections",
    true
  },
  {
    "UprightFull",
    "Perspective Correction Full",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveUpright",
    "Reset Upright Settings",
    "Lens Corrections",
    true
  },
  {
    "LensProfileDistortionScale",
    "Lens Profile Distortion Scale",
    "Lens Corrections",
    false
  },
  {
    "LensProfileChromaticAberrationScale",
    "Lens Profile Chromatic Aberration Scale",
    "Lens Corrections",
    false
  },
  {
    "LensProfileVignettingScale",
    "Lens Profile Vignetting Scale",
    "Lens Corrections",
    false
  },
  {
    "ResetLensProfileDistortionScale",
    "Reset Lens Profile Distortion Scale",
    "Lens Corrections",
    true
  },
  {
    "ResetLensProfileChromaticAberrationScale",
    "Reset Lens Profile Chromatic Aberration Scale",
    "Lens Corrections",
    true
  },
  {
    "ResetLensProfileVignettingScale",
    "Reset Lens Profile Vignetting Scale",
    "Lens Corrections",
    true
  },
  {
    "DefringePurpleAmount",
    "Defringe Purple Amount",
    "Lens Corrections",
    false
  },
  {
    "DefringePurpleHueLo",
    "Defringe Purple Hue - Low",
    "Lens Corrections",
    false
  },
  {
    "DefringePurpleHueHi",
    "Defringe Purple Hue - High",
    "Lens Corrections",
    false
  },
  {
    "DefringeGreenAmount",
    "Defringe Green Amount",
    "Lens Corrections",
    false
  },
  {
    "DefringeGreenHueLo",
    "Defringe Green Hue - Low",
    "Lens Corrections",
    false
  },
  {
    "DefringeGreenHueHi",
    "Defringe Green Hue - High",
    "Lens Corrections",
    false
  },
  {
    "ResetDefringePurpleAmount",
    "Reset Defringe Purple Amount",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringePurpleHueLo",
    "Reset Defringe Purple Hue - Low",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringePurpleHueHi",
    "Reset Defringe Purple Hue - High",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringeGreenAmount",
    "Reset Defringe Green Amount",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringeGreenHueLo",
    "Reset Defringe Green Hue - Low",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringeGreenHueHi",
    "Reset Defringe Green Hue - High",
    "Lens Corrections",
    true
  },
  {
    "LensManualDistortionAmount",
    "Lens Manual Distortion Amount",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveVertical",
    "Perspective Vertical",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveHorizontal",
    "Perspective Horizontal",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveRotate",
    "Perspective Rotate",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveScale",
    "Perspective Scale",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveAspect",
    "Perspective Aspect",
    "Lens Corrections",
    false
  },
  {
    "VignetteAmount",
    "Vignette Amount",
    "Lens Corrections",
    false
  },
  {
    "VignetteMidpoint",
    "Vignette Midpoint",
    "Lens Corrections",
    false
  },
  {
    "ResetLensManualDistortionAmount",
    "Reset Lens Manual Distortion Amount",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveVertical",
    "Reset Perspective Vertical",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveHorizontal",
    "Reset Perspective Horizontal",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveRotate",
    "Reset Perspective Rotate",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveScale",
    "Reset Perspective Scale",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveAspect",
    "Reset Perspective Aspect",
    "Lens Corrections",
    true
  },
  {
    "ResetVignetteAmount",
    "Reset Vignette Amount",
    "Lens Corrections",
    true
  },
  {
    "ResetVignetteMidpoint",
    "Reset Vignette Midpoint",
    "Lens Corrections",
    true
  },
  {
    "EnableEffects",
    "Enable Effects",
    "Effects",
    true
  },
  {
    "Dehaze",
    "Dehaze Amount",
    "Effects",
    false
  },
  {
    "PostCropVignetteAmount",
    "Post Crop Vignette Amount",
    "Effects",
    false
  },
  {
    "PostCropVignetteMidpoint",
    "Post Crop Vignette Midpoint",
    "Effects",
    false
  },
  {
    "PostCropVignetteFeather",
    "Post Crop Vignette Feather",
    "Effects",
    false
  },
  {
    "PostCropVignetteRoundness",
    "Post Crop Vignette Roundness",
    "Effects",
    false
  },
  {
    "PostCropVignetteStyle",
    "Post Crop Vignette Style",
    "Effects",
    false
  },
  {
    "PostCropVignetteHighlightContrast",
    "Post Crop Vignette Highlight Contrast",
    "Effects",
    false
  },
  {
    "GrainAmount",
    "Grain Amount",
    "Effects",
    false
  },
  {
    "GrainSize",
    "Grain Size",
    "Effects",
    false
  },
  {
    "GrainFrequency",
    "Grain Roughness",
    "Effects",
    false
  },
  {
    "ResetDehaze",
    "Reset Dehaze Amount",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteAmount",
    "Reset Post Crop Vignette Amount",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteMidpoint",
    "Reset Post Crop Vignette Midpoint",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteFeather",
    "Reset Post Crop Vignette Feather",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteRoundness",
    "Reset Post Crop Vignette Roundness",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteStyle",
    "Reset Post Crop Vignette Style",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteHighlightContrast",
    "Reset Post Crop Vignette Highlight Contrast",
    "Effects",
    true
  },
  {
    "ResetGrainAmount",
    "Reset Grain Amount",
    "Effects",
    true
  },
  {
    "ResetGrainSize",
    "Reset Grain Size",
    "Effects",
    true
  },
  {
    "ResetGrainFrequency",
    "Reset Grain Roughness",
    "Effects",
    true
  },
  {
    "EnableCalibration",
    "Enable Calibration",
    "Calibration",
    true
  },
  {
    "Profile_Adobe_Standard",
    "Adobe Standard",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Clear",
    "Camera Clear",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Deep",
    "Camera Deep",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Landscape",
    "Camera Landscape",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Light",
    "Camera Light",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Neutral",
    "Camera Neutral",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Portrait",
    "Camera Portrait",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Standard",
    "Camera Standard",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Vivid",
    "Camera Vivid",
    "Calibration",
    true
  },
  {
    "ShadowTint",
    "Shadow Tint Calibration",
    "Calibration",
    false
  },
  {
    "RedHue",
    "Red Hue Calibration",
    "Calibration",
    false
  },
  {
    "RedSaturation",
    "Red Saturation Calibration",
    "Calibration",
    false
  },
  {
    "GreenHue",
    "Green Hue Calibration",
    "Calibration",
    false
  },
  {
    "GreenSaturation",
    "Green Saturation Calibration",
    "Calibration",
    false
  },
  {
    "BlueHue",
    "Blue Hue Calibration",
    "Calibration",
    false
  },
  {
    "BlueSaturation",
    "Blue Saturation Calibration",
    "Calibration",
    false
  },
  {
    "ResetShadowTint",
    "Reset Shadow Tint Calibration",
    "Calibration",
    true
  },
  {
    "ResetRedHue",
    "Reset Red Hue Calibration",
    "Calibration",
    true
  },
  {
    "ResetRedSaturation",
    "Reset Red Saturation Calibration",
    "Calibration",
    true
  },
  {
    "ResetGreenHue",
    "Reset Green Hue Calibration",
    "Calibration",
    true
  },
  {
    "ResetGreenSaturation",
    "Reset Green Saturation Calibration",
    "Calibration",
    true
  },
  {
    "ResetBlueHue",
    "Reset Blue Hue Calibration",
    "Calibration",
    true
  },
  {
    "ResetBlueSaturation",
    "Reset Blue Saturation Calibration",
    "Calibration",
    true
  },
  {
    "Pick",
    "Set Pick Flag",
    "Photo Actions",
    true
  },
  {
    "Reject",
    "Set Rejected Flag",
    "Photo Actions",
    true
  },
  {
    "Next",
    "Next Photo",
    "Photo Actions",
    true
  },
  {
    "Prev",
    "Previous Photo",
    "Photo Actions",
    true
  },
  {
    "Select1Left",
    "Add to Selection Left",
    "Photo Actions",
    true
  },
  {
    "Select1Right",
    "Add to Selection Right",
    "Photo Actions",
    true
  },
  {
    "VirtualCopy",
    "Create Virtual Copy",
    "Photo Actions",
    true
  },
  {
    "RemoveFlag",
    "Unflagged",
    "Photo Actions",
    true
  },
  {
    "IncreaseRating",
    "Increase Rating",
    "Photo Actions",
    true
  },
  {
    "DecreaseRating",
    "Decrease Rating",
    "Photo Actions",
    true
  },
  {
    "SetRating0",
    "0 Stars",
    "Photo Actions",
    true
  },
  {
    "SetRating1",
    "1 Star",
    "Photo Actions",
    true
  },
  {
    "SetRating2",
    "2 Stars",
    "Photo Actions",
    true
  },
  {
    "SetRating3",
    "3 Stars",
    "Photo Actions",
    true
  },
  {
    "SetRating4",
    "4 Stars",
    "Photo Actions",
    true
  },
  {
    "SetRating5",
    "5 Stars",
    "Photo Actions",
    true
  },
  {
    "ToggleBlue",
    "Label Blue Enable/Disable",
    "Photo Actions",
    true
  },
  {
    "ToggleGreen",
    "Label Green Enable/Disable",
    "Photo Actions",
    true
  },
  {
    "ToggleRed",
    "Label Red Enable/Disable",
    "Photo Actions",
    true
  },
  {
    "TogglePurple",
    "Label Purple Enable/Disable",
    "Photo Actions",
    true
  },
  {
    "ToggleYellow",
    "Label Yellow Enable/Disable",
    "Photo Actions",
    true
  },
  {
    "ResetAll",
    "Reset Settings",
    "Photo Actions",
    true
  },
  {
    "ResetLast",
    "Reset Last Modified",
    "Photo Actions",
    true
  },
  {
    "IncrementLastDevelopParameter",
    "Increase Last Modified",
    "Photo Actions",
    true
  },
  {
    "DecrementLastDevelopParameter",
    "Decrease Last Modified",
    "Photo Actions",
    true
  },
  {
    "Undo",
    "Undo",
    "Photo Actions",
    true
  },
  {
    "Redo",
    "Redo",
    "Photo Actions",
    true
  },
  {
    "CopySettings",
    "Copy Settings",
    "Photo Actions",
    true
  },
  {
    "PasteSettings",
    "Paste Settings",
    "Photo Actions",
    true
  },
  {
    "PasteSelectedSettings",
    "Paste Selected Settings",
    "Photo Actions",
    true
  },
  {
    "Preset_1",
    "Develop Preset 1",
    "Develop Presets",
    true
  },
  {
    "Preset_2",
    "Develop Preset 2",
    "Develop Presets",
    true
  },
  {
    "Preset_3",
    "Develop Preset 3",
    "Develop Presets",
    true
  },
  {
    "Preset_4",
    "Develop Preset 4",
    "Develop Presets",
    true
  },
  {
    "Preset_5",
    "Develop Preset 5",
    "Develop Presets",
    true
  },
  {
    "Preset_6",
    "Develop Preset 6",
    "Develop Presets",
    true
  },
  {
    "Preset_7",
    "Develop Preset 7",
    "Develop Presets",
    true
  },
  {
    "Preset_8",
    "Develop Preset 8",
    "Develop Presets",
    true
  },
  {
    "Preset_9",
    "Develop Preset 9",
    "Develop Presets",
    true
  },
  {
    "Preset_10",
    "Develop Preset 10",
    "Develop Presets",
    true
  },
  {
    "Preset_11",
    "Develop Preset 11",
    "Develop Presets",
    true
  },
  {
    "Preset_12",
    "Develop Preset 12",
    "Develop Presets",
    true
  },
  {
    "Preset_13",
    "Develop Preset 13",
    "Develop Presets",
    true
  },
  {
    "Preset_14",
    "Develop Preset 14",
    "Develop Presets",
    true
  },
  {
    "Preset_15",
    "Develop Preset 15",
    "Develop Presets",
    true
  },
  {
    "Preset_16",
    "Develop Preset 16",
    "Develop Presets",
    true
  },
  {
    "Preset_17",
    "Develop Preset 17",
    "Develop Presets",
    true
  },
  {
    "Preset_18",
    "Develop Preset 18",
    "Develop Presets",
    true
  },
  {
    "Preset_19",
    "Develop Preset 19",
    "Develop Presets",
    true
  },
  {
    "Preset_20",
    "Develop Preset 20",
    "Develop Presets",
    true
  },
  {
    "local_Temperature",
    "Local Temperature (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Tint",
    "Local Tint (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Exposure",
    "Local Exposure (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Contrast",
    "Local Contrast (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Highlights",
    "Local Highlights (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Shadows",
    "Local Shadows (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Clarity",
    "Local Clarity (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Saturation",
    "Local Saturation (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Sharpness",
    "Local Sharpness (PV2010 and PV 2012)",
    "Local Adjustments",
    false
  },
  {
    "local_LuminanceNoise",
    "Local Luminance Noise (PV2012)",
    "Localized Adjusments",
    false
  },
  {
    "local_Moire",
    "Local Moire (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Defringe",
    "Local Defringe (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_ToningLuminance",
    "Local Toning Luminance (PV2010)",
    "Local Adjustments",
    false
  },
  {
    "Resetlocal_Temperature",
    "Reset Local Temperature (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Tint",
    "Reset Local Tint (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Exposure",
    "Reset Local Exposure (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Contrast",
    "Reset Local Contrast (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Highlights",
    "Reset Local Highlights (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Shadows",
    "Reset Local Shadows (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Clarity",
    "Reset Local Clarity (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Saturation",
    "Reset Local Saturation (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Sharpness",
    "Reset Local Sharpness (PV2010 and PV 2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_LuminanceNoise",
    "Reset Local Luminance Noise (PV2012)",
    "Localized Adjusments",
    true
  },
  {
    "Resetlocal_Moire",
    "Reset Local Moire (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Defringe",
    "Reset Local Defringe (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_ToningLuminance",
    "Reset Local Toning Luminance (PV2010)",
    "Local Adjustments",
    true
  },
  {
    "EnableCircularGradientBasedCorrections",
    "Enable Radial Filter",
    "Local Adjustments",
    true
  },
  {
    "EnableGradientBasedCorrections",
    "Enable Graduated Filter",
    "Local Adjustments",
    true
  },
  {
    "EnablePaintBasedCorrections",
    "Enable Brush Adjustments",
    "Local Adjustments",
    true
  },
  {
    "EnableRedEye",
    "Enable Red-Eye",
    "Local Adjustments",
    true
  },
  {
    "EnableRetouch",
    "Enable Spot Removal",
    "Local Adjustments",
    true
  },
  {
    "ResetCircGrad",
    "Reset Radial Filters",
    "Local Adjustments",
    true
  },
  {
    "ResetGradient",
    "Reset Graduated Filters",
    "Local Adjustments",
    true
  },
  {
    "ResetBrushing",
    "Reset Brush Corrections",
    "Local Adjustments",
    true
  },
  {
    "ResetRedeye",
    "Reset Red-Eye",
    "Local Adjustments",
    true
  },
  {
    "ResetSpotRem",
    "Reset Spot Removal",
    "Local Adjustments",
    true
  },
  {
    "ZoomInLargeStep",
    "Zoom In",
    "Miscellaneous",
    true
  },
  {
    "ZoomInSmallStep",
    "Zoom In Some",
    "Miscellaneous",
    true
  },
  {
    "ZoomOutSmallStep",
    "Zoom Out Some",
    "Miscellaneous",
    true
  },
  {
    "ZoomOutLargeStep",
    "Zoom Out",
    "Miscellaneous",
    true
  },
  {
    "ToggleZoomOffOn",
    "Toggle Zoom Off/On",
    "Miscellaneous",
    true
  },
  {
    "CropAngle",
    "Crop Angle",
    "Miscellaneous",
    false
  },
  {
    "CropBottom",
    "Crop - Bottom",
    "Miscellaneous",
    false
  },
  {
    "CropLeft",
    "Crop - Left",
    "Miscellaneous",
    false
  },
  {
    "CropRight",
    "Crop - Right",
    "Miscellaneous",
    false
  },
  {
    "CropTop",
    "Crop - Top",
    "Miscellaneous",
    false
  },
  {
    "ResetCrop",
    "Reset Crop",
    "Miscellaneous",
    true
  },
  {
    "Loupe",
    "Show Loupe",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "CropOverlay",
    "Show Crop",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "SpotRemoval",
    "Show Spot Removal",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RedEye",
    "Show Red-Eye Correction",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "GraduatedFilter",
    "Show Graduated Filters",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RadialFilter",
    "Show Radial Filters",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "AdjustmentBrush",
    "Show Brush Adjustments",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "SwToMlibrary",
    "Show Library",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "SwToMdevelop",
    "Show Develop",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "SwToMmap",
    "Show Map",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "SwToMbook",
    "Show Book",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "SwToMslideshow",
    "Show Slideshow",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "SwToMprint",
    "Show Print",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "SwToMweb",
    "Show Web",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RevealPanelAdjust",
    "Show Basic Tone",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RevealPanelTone",
    "Show Tone Curve",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RevealPanelMixer",
    "Show Color Adjustments",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RevealPanelSplit",
    "Show Split Toning",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RevealPanelDetail",
    "Show Detail",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RevealPanelLens",
    "Show Lens Corrections",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RevealPanelEffects",
    "Show Effects",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "RevealPanelCalibrate",
    "Show Calibration",
    "Go to Tool, Module, or Panel",
    true
  },
  {
    "ShoVwloupe",
    "Primary Display Loupe",
    "View Modes",
    true
  },
  {
    "ShoVwgrid",
    "Primary Display Grid",
    "View Modes",
    true
  },
  {
    "ShoVwcompare",
    "Primary Display Compare",
    "View Modes",
    true
  },
  {
    "ShoVwsurvey",
    "Primary Display Survey",
    "View Modes",
    true
  },
  {
    "ShoVwpeople",
    "Primary Display People",
    "View Modes",
    true
  },
  {
    "ShoVwdevelop_loupe",
    "Primary Display Loupe",
    "View Modes",
    true
  },
  {
    "ShoVwdevelop_before_after_horiz",
    "Primary Display Before/After Left/Right",
    "View Modes",
    true
  },
  {
    "ShoVwdevelop_before_after_vert",
    "Primary Display Before/After Top/Bottom",
    "View Modes",
    true
  },
  {
    "ShoVwdevelop_before",
    "Primary Display Before",
    "View Modes",
    true
  },
  {
    "ShoScndVwloupe",
    "Secondary Display Loupe",
    "View Modes",
    true
  },
  {
    "ShoScndVwlive_loupe",
    "Secondary Display Live Loupe",
    "View Modes",
    true
  },
  {
    "ShoScndVwlocked_loupe",
    "Secondary Display Locked Loupe",
    "View Modes",
    true
  },
  {
    "ShoScndVwgrid",
    "Secondary Display Grid",
    "View Modes",
    true
  },
  {
    "ShoScndVwcompare",
    "Secondary Display Compare",
    "View Modes",
    true
  },
  {
    "ShoScndVwsurvey",
    "Secondary Display Survey",
    "View Modes",
    true
  },
  {
    "ShoScndVwslideshow",
    "Secondary Display Slideshow",
    "View Modes",
    true
  },
  {
    "ToggleScreenTwo",
    "Secondary Display Show",
    "View Modes",
    true
  },
  {
    "profile1",
    "Profile: 1",
    "Profiles",
    true
  },
  {
    "profile2",
    "Profile: 2",
    "Profiles",
    true
  },
  {
    "profile3",
    "Profile: 3",
    "Profiles",
    true
  },
  {
    "profile4",
    "Profile: 4",
    "Profiles",
    true
  },
  {
    "profile5",
    "Profile: 5",
    "Profiles",
    true
  },
  {
    "profile6",
    "Profile: 6",
    "Profiles",
    true
  },
  {
    "profile7",
    "Profile: 7",
    "Profiles",
    true
  },
  {
    "profile8",
    "Profile: 8",
    "Profiles",
    true
  },
  {
    "profile9",
    "Profile: 9",
    "Profiles",
    true
  },
  {
    "profile10",
    "Profile: 10",
    "Profiles",
    true
  }
}