--[[----------------------------------------------------------------------------

MenuListPreTrans.lua
Source of translations and menu for app and plugin
 
This file is part of MIDI2LR. Copyright 2015-2016 by Rory Jaffe.

MIDI2LR is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

MIDI2LR is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
MIDI2LR.  If not, see <http://www.gnu.org/licenses/>. 
------------------------------------------------------------------------------]]

local MenuList = {
  {"WhiteBalanceAs_Shot",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/AsShot=As Shot"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"WhiteBalanceAuto",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Auto=Auto"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"WhiteBalanceCloudy",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Cloudy=Cloudy"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"WhiteBalanceDaylight",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Daylight=Daylight"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"WhiteBalanceFlash",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Flash=Flash"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"WhiteBalanceFluorescent",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Fluorescent=Fluorescent"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"WhiteBalanceShade",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Shade=Shade"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"WhiteBalanceTungsten",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Tungsten=Tungsten"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"Temperature",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Temperature=Temperature"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Tint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Tint=Tint"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Exposure",
    LOC("$$$/AgCameraRawUI/Exposure=Exposure"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Contrast",
    LOC("$$$/AgCameraRawUI/Contrast=Contrast"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Highlights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Highlights=Highlights"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Shadows",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Shadows=Shadows"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Whites",
    LOC("$$$/AgCameraRawUI/Whites=Whites"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Blacks",
    LOC("$$$/AgCameraRawUI/Blacks=Blacks"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Clarity",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Clarity=Clarity"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Vibrance",
    LOC("$$$/AgCameraRawUI/Vibrance=Vibrance"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"Saturation",
    LOC("$$$/AgCameraRawUI/Saturation=Saturation"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    false},
  {"ResetTemperature",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Temperature=Temperature"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetTint",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Tint=Tint"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetExposure",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawUI/Exposure=Exposure"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetContrast",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawUI/Contrast=Contrast"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetHighlights",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Highlights=Highlights"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetShadows",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Shadows=Shadows"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetWhites",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawUI/Whites=Whites"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetBlacks",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawUI/Blacks=Blacks"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetClarity",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Clarity=Clarity"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetVibrance",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawUI/Vibrance=Vibrance"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ResetSaturation",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawUI/Saturation=Saturation"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone"),
    true},
  {"ParametricDarks",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneDarks=Dark Tones"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    false},
  {"ParametricLights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneLights=Light Tones"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    false},
  {"ParametricShadows",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadows=Shadow Tones"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    false},
  {"ParametricHighlights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlights=Highlight Tones"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    false},
  {"ParametricShadowSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadowSplit=Shadow Split"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    false},
  {"ParametricMidtoneSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneMidtoneSplit=Midtone Split"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    false},
  {"ParametricHighlightSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlightSplit=Highlight Split"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    false},
  {"ResetParametricDarks",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneDarks=Dark Tones"), 
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    true},
  {"ResetParametricLights",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneLights=Light Tones"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    true},
  {"ResetParametricShadows",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadows=Shadow Tones"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    true},
  {"ResetParametricHighlights",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlights=Highlight Tones"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    true},
  {"ResetParametricShadowSplit",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadowSplit=Shadow Split"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    true},
  {"ResetParametricMidtoneSplit",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneMidtoneSplit=Midtone Split"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    true},
  {"ResetParametricHighlightSplit",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlightSplit=Highlight Split"),
    LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve"),
    true},
  {"EnableColorAdjustments",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableColorAdjustments=Enable Color Adjustments"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"SaturationAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentRed=Saturation Adjustment Red"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"SaturationAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentOrange=Saturation Adjustment Orange"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"SaturationAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentYellow=Saturation Adjustment Yellow"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"SaturationAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentGreen=Saturation Adjustment Green"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"SaturationAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentAqua=Saturation Adjustment Aqua"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"SaturationAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentBlue=Saturation Adjustment Blue"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"SaturationAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentPurple=Saturation Adjustment Purple"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"SaturationAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentMagenta=Saturation Adjustment Magenta"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"HueAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentRed=Hue Adjustment Red"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"HueAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentOrange=Hue Adjustment Orange"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"HueAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentYellow=Hue Adjustment Yellow"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"HueAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentGreen=Hue Adjustment Green"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"HueAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentAqua=Hue Adjustment Aqua"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"HueAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentBlue=Hue Adjustment Blue"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"HueAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentPurple=Hue Adjustment Purple"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"HueAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentMagenta=Hue Adjustment Magenta"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"LuminanceAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentRed=Luminance Adjustment Red"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"LuminanceAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentOrange=Luminance Adjustment Orange"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"LuminanceAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentYellow=Luminance Adjustment Yellow"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"LuminanceAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentGreen=Luminance Adjustment Green"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"LuminanceAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentAqua=Luminance Adjustment Aqua"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"LuminanceAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentBlue=Luminance Adjustment Blue"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"LuminanceAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentPurple=Luminance Adjustment Purple"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"LuminanceAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentMagenta=Luminance Adjustment Magenta"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"ConvertToGrayscale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ConvertToGrayscale=Convert to Grayscale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"EnableGrayscaleMix",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableGrayscaleMix=Enable Grayscale Mix"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"GrayMixerRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerRed=Gray Mixer Red"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"GrayMixerOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerOrange=Gray Mixer Orange"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"GrayMixerYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerYellow=Gray Mixer Yellow"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"GrayMixerGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerGreen=Gray Mixer Green"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"GrayMixerAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerAqua=Gray Mixer Aqua"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"GrayMixerBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerBlue=Gray Mixer Blue"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"GrayMixerPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerPurple=Gray Mixer Purple"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"GrayMixerMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerMagenta=Gray Mixer Magenta"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    false},
  {"ResetSaturationAdjustmentRed",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentRed=Saturation Adjustment Red"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetSaturationAdjustmentOrange",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentOrange=Saturation Adjustment Orange"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetSaturationAdjustmentYellow",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentYellow=Saturation Adjustment Yellow"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetSaturationAdjustmentGreen",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentGreen=Saturation Adjustment Green"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetSaturationAdjustmentAqua",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentAqua=Saturation Adjustment Aqua"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetSaturationAdjustmentBlue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentBlue=Saturation Adjustment Blue"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetSaturationAdjustmentPurple",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentPurple=Saturation Adjustment Purple"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetSaturationAdjustmentMagenta",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentMagenta=Saturation Adjustment Magenta"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetHueAdjustmentRed",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentRed=Hue Adjustment Red"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetHueAdjustmentOrange",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentOrange=Hue Adjustment Orange"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetHueAdjustmentYellow",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentYellow=Hue Adjustment Yellow"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetHueAdjustmentGreen",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentGreen=Hue Adjustment Green"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetHueAdjustmentAqua",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentAqua=Hue Adjustment Aqua"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetHueAdjustmentBlue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentBlue=Hue Adjustment Blue"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetHueAdjustmentPurple",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentPurple=Hue Adjustment Purple"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetHueAdjustmentMagenta",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentMagenta=Hue Adjustment Magenta"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetLuminanceAdjustmentRed",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentRed=Luminance Adjustment Red"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetLuminanceAdjustmentOrange",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentOrange=Luminance Adjustment Orange"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetLuminanceAdjustmentYellow",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentYellow=Luminance Adjustment Yellow"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetLuminanceAdjustmentGreen",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentGreen=Luminance Adjustment Green"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetLuminanceAdjustmentAqua",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentAqua=Luminance Adjustment Aqua"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetLuminanceAdjustmentBlue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentBlue=Luminance Adjustment Blue"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetLuminanceAdjustmentPurple",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentPurple=Luminance Adjustment Purple"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetLuminanceAdjustmentMagenta",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentMagenta=Luminance Adjustment Magenta"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetGrayMixerRed",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerRed=Gray Mixer Red"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetGrayMixerOrange",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerOrange=Gray Mixer Orange"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetGrayMixerYellow",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerYellow=Gray Mixer Yellow"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetGrayMixerGreen",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerGreen=Gray Mixer Green"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetGrayMixerAqua",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerAqua=Gray Mixer Aqua"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetGrayMixerBlue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerBlue=Gray Mixer Blue"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetGrayMixerPurple",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerPurple=Gray Mixer Purple"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"ResetGrayMixerMagenta",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerMagenta=Gray Mixer Magenta"),
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments"),
    true},
  {"EnableSplitToning",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableSplitToning=Enable Split Toning"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    true},
  {"SplitToningShadowHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowHue=Shadow Hue"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    false},
  {"SplitToningShadowSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowSaturation=Shadow Saturation"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    false},
  {"SplitToningHighlightHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightHue=Highlight Hue"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    false},
  {"SplitToningHighlightSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightSaturation=Highlight Saturation"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    false},
  {"SplitToningBalance",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningBalance=Split Toning Balance"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    false},
  {"ResetSplitToningShadowHue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowHue=Shadow Hue"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    true},
  {"ResetSplitToningShadowSaturation",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowSaturation=Shadow Saturation"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    true},
  {"ResetSplitToningHighlightHue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightHue=Highlight Hue"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    true},
  {"ResetSplitToningHighlightSaturation",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightSaturation=Highlight Saturation"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    true},
  {"ResetSplitToningBalance",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningBalance=Split Toning Balance"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning"),
    true},
  {"EnableDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableDetail=Enable Detail"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"Sharpness",
    LOC("$$$/AgDevelop/Localized/Sharpness=Sharpness"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"SharpenRadius",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenRadius=Sharpen Radius"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"SharpenDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenDetail=Sharpen Detail"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"SharpenEdgeMasking",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenEdgeMasking=Sharpen Edge Masking"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"LuminanceSmoothing",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceSmoothing=Luminance Smoothing"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"LuminanceNoiseReductionDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionDetail=Luminance Detail"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"LuminanceNoiseReductionContrast",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionContrast=Luminance Contrast"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"ColorNoiseReduction",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReduction=Color Noise Reduction"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"ColorNoiseReductionDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionDetail=Color Noise Reduction Detail"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"ColorNoiseReductionSmoothness",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionSmoothness=Color Noise Reduction Smoothness"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    false},
  {"ResetSharpness",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgDevelop/Localized/Sharpness=Sharpness"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetSharpenRadius",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenRadius=Sharpen Radius"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetSharpenDetail",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenDetail=Sharpen Detail"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetSharpenEdgeMasking",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenEdgeMasking=Sharpen Edge Masking"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetLuminanceSmoothing",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceSmoothing=Luminance Smoothing"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetLuminanceNoiseReductionDetail",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionDetail=Luminance Detail"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetLuminanceNoiseReductionContrast",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionContrast=Luminance Contrast"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetColorNoiseReduction",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReduction=Color Noise Reduction"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetColorNoiseReductionDetail",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionDetail=Color Noise Reduction Detail"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"ResetColorNoiseReductionSmoothness",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionSmoothness=Color Noise Reduction Smoothness"),
    LOC("$$$/AgDevelop/Panel/Detail=Detail"),
    true},
  {"EnableLensCorrections",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableLensCorrections=Enable Lens Corrections"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"LensProfileEnable",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileEnable=Lens Profile Enable"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"AutoLateralCA",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RemoveChromaticAberration=Remove Chromatic Aberration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"UprightOff",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueOff=Off"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"UprightAuto",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueAuto=Auto"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"UprightLevel",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueLevel=Level"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"UprightVertical",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueLevelVertical=Vertical"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"UprightFull",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueFull=Full"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetPerspectiveUpright",
    LOC("$$$/AgCameraRawNamedSettings/Ops/ResetUprightSettings=Reset Upright Settings"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"LensProfileDistortionScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileDistortionScale=Lens Profile Distortion Scale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"LensProfileChromaticAberrationScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileChromaticAberrationScale=Lens Profile Chromatic Aberration Scale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"LensProfileVignettingScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileVignettingScale=Lens Profile Vignetting Scale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"ResetLensProfileDistortionScale",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileDistortionScale=Lens Profile Distortion Scale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetLensProfileChromaticAberrationScale",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileChromaticAberrationScale=Lens Profile Chromatic Aberration Scale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetLensProfileVignettingScale",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileVignettingScale=Lens Profile Vignetting Scale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"DefringePurpleAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeAmount=Defringe Purple Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"DefringePurpleHueLo",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"DefringePurpleHueHi",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"DefringeGreenAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeAmount=Defringe Green Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"DefringeGreenHueLo",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"DefringeGreenHueHi",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"ResetDefringePurpleAmount",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeAmount=Defringe Purple Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetDefringePurpleHueLo",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetDefringePurpleHueHi",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetDefringeGreenAmount",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeAmount=Defringe Green Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetDefringeGreenHueLo",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetDefringeGreenHueHi",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"LensManualDistortionAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensManualDistortionAmount=Lens Manual Distortion Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"PerspectiveVertical",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveVertical=Perspective Vertical"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"PerspectiveHorizontal",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveHorizontal=Perspective Horizontal"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"PerspectiveRotate",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveRotate=Perspective Rotate"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"PerspectiveScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveScale=Perspective Scale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"PerspectiveAspect",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveAspect=Perspective Aspect"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"VignetteAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteAmount=Vignette Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"VignetteMidpoint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteMidpoint=Vignette Midpoint"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    false},
  {"ResetLensManualDistortionAmount",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensManualDistortionAmount=Lens Manual Distortion Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetPerspectiveVertical",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveVertical=Perspective Vertical"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetPerspectiveHorizontal",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveHorizontal=Perspective Horizontal"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetPerspectiveRotate",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveRotate=Perspective Rotate"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetPerspectiveScale",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveScale=Perspective Scale"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetPerspectiveAspect",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveAspect=Perspective Aspect"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetVignetteAmount",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteAmount=Vignette Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"ResetVignetteMidpoint",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteMidpoint=Vignette Midpoint"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections"),
    true},
  {"EnableEffects",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableEffects=Enable Effects"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"Dehaze",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/DehazeAmount=Dehaze Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"PostCropVignetteAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteAmount=Post Crop Vignette Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"PostCropVignetteMidpoint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteMidpoint=Post Crop Vignette Midpoint"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"PostCropVignetteFeather",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteFeather=Post Crop Vignette Feather"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"PostCropVignetteRoundness",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteRoundness=Post Crop Vignette Roundness"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"PostCropVignetteStyle",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteStyle=Post Crop Vignette Style"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"PostCropVignetteHighlightContrast",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteHighlightContrast=Post Crop Vignette Highlight Contrast"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"GrainAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainAmount=Grain Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"GrainSize",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainSize=Grain Size"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"GrainFrequency",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainRoughness=Grain Roughness"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    false},
  {"ResetDehaze",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/DehazeAmount=Dehaze Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetPostCropVignetteAmount",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteAmount=Post Crop Vignette Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetPostCropVignetteMidpoint",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteMidpoint=Post Crop Vignette Midpoint"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetPostCropVignetteFeather",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteFeather=Post Crop Vignette Feather"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetPostCropVignetteRoundness",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteRoundness=Post Crop Vignette Roundness"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetPostCropVignetteStyle",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteStyle=Post Crop Vignette Style"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetPostCropVignetteHighlightContrast",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteHighlightContrast=Post Crop Vignette Highlight Contrast"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetGrainAmount",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainAmount=Grain Amount"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetGrainSize",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainSize=Grain Size"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"ResetGrainFrequency",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainRoughness=Grain Roughness"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects"),
    true},
  {"EnableCalibration",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableCalibration=Enable Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Adobe_Standard",
    LOC("$$$/CRaw/Style/Profile/AdobeStandard=Adobe Standard"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Camera_Clear",
    LOC("$$$/CRaw/Style/Profile/CameraClear=Camera Clear"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Camera_Deep",
    LOC("$$$/CRaw/Style/Profile/CameraDeep=Camera Deep"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Camera_Landscape",
    LOC("$$$/CRaw/Style/Profile/CameraLandscape=Camera Landscape"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Camera_Light",
    LOC("$$$/CRaw/Style/Profile/CameraLight=Camera Light"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Camera_Neutral",
    LOC("$$$/CRaw/Style/Profile/CameraNeutral=Camera Neutral"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Camera_Portrait",
    LOC("$$$/CRaw/Style/Profile/CameraPortrait=Camera Portrait"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Camera_Standard",
    LOC("$$$/CRaw/Style/Profile/CameraStandard=Camera Standard"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"Profile_Camera_Vivid",
    LOC("$$$/CRaw/Style/Profile/CameraVivid=Camera Vivid"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    true},
  {"ShadowTint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ShadowTintCalibration=Shadow Tint Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"RedHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedHueCalibration=Red Hue Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"RedSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedSaturationCalibration=Red Saturation Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"GreenHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenHueCalibration=Green Hue Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"GreenSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenSaturationCalibration=Green Saturation Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"BlueHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueHueCalibration=Blue Hue Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"BlueSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueSaturationCalibration=Blue Saturation Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"ResetShadowTint",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ShadowTintCalibration=Shadow Tint Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"ResetRedHue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedHueCalibration=Red Hue Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"ResetRedSaturation",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedSaturationCalibration=Red Saturation Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"ResetGreenHue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenHueCalibration=Green Hue Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"ResetGreenSaturation",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenSaturationCalibration=Green Saturation Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"ResetBlueHue",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueHueCalibration=Blue Hue Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"ResetBlueSaturation",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueSaturationCalibration=Blue Saturation Calibration"),
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration"),
    false},
  {"Pick",
    LOC("$$$/AgLibrary/Help/Shortcuts/SetPick=Set Pick Flag"),
    "Photo Actions",
    true},
  {"Reject",
    LOC("$$$/AgLibrary/Help/Shortcuts/SetReject=Set Rejected Flag"),
    "Photo Actions",
    true},
  {"Next",
    LOC("$$$/AgDevelopShortcuts/Next_Photo=Next Photo"),
    "Photo Actions",
    true},
  {"Prev",
    LOC("$$$/AgDevelopShortcuts/Previous_Photo=Previous Photo"),
    "Photo Actions",
    true},
  {"VirtualCopy",
    LOC("$$$/AgLibrary/Bezel/CreateVirtualCopy=Create Virtual Copy"):gsub('&',''),
    "Photo Actions",
    true},
  {"RemoveFlag",
    LOC("$$$/AgLibrary/Menu/Photo/SetPick/Unflagged=Unflagged"):gsub('&',''),
    "Photo Actions",
    true},
  {"IncreaseRating",
    LOC("$$$/AgLibrary/Ops/IncreaseRating=Increase Rating"),
    "Photo Actions",
    true},
  {"DecreaseRating",
    LOC("$$$/AgLibrary/Ops/DecreaseRating=Decrease Rating"),
    "Photo Actions",
    true},
  {"SetRating0",
    LOC("$$$/AgLibrary/Filter/Stars=^1 Stars",'0'),
    "Photo Actions",
    true},
  {"SetRating1",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating1=1 Star"):gsub('&',''),
    "Photo Actions",
    true},
  {"SetRating2",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating2=&2 Stars"):gsub('&',''),
    "Photo Actions",
    true},
  {"SetRating3",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating3=&3 Stars"):gsub('&',''),
    "Photo Actions",
    true},
  {"SetRating4",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating4=&4 Stars"):gsub('&',''),
    "Photo Actions",
    true},
  {"SetRating5",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating5=&5 Stars"):gsub('&',''),
    "Photo Actions",
    true},
  {"ToggleBlue",
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelBlue=Blue")),
    "Photo Actions",
    true},
  {"ToggleGreen",
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelGreen=Green")),
    "Photo Actions",
    true},
  {"ToggleRed", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelRed=Red")),
    "Photo Actions",
    true},
  {"TogglePurple", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelPurple=Purple")),
    "Photo Actions",
    true},
  {"ToggleYellow", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelYellow=Yellow")),
    "Photo Actions",
    true},
  {"ResetAll",
    LOC("$$$/AgCameraRawNamedSettings/Ops/ResetSettings=Reset Settings"),
    "Photo Actions",
    true},
  {"ResetLast",
    LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")..' '..LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified"):gsub(':',''),
    "Photo Actions",
    true},
  {"IncrementLastDevelopParameter",
    LOC("$$$/AgCameraRawController/TargetAdjustment/Increase=^1 erhöhen: ^2",LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified")):gsub(':',''),
    "Photo Actions",
    true},
  {"DecrementLastDevelopParameter",
    LOC("$$$/AgCameraRawController/TargetAdjustment/Decrease=^1 decrease: ^2",LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified")):gsub(':',''),
    "Photo Actions",
    true},
  {"Undo",
    LOC("$$$/AgCameraRawController/SoftProofingVirtualCopyPrompt/Undo=Undo"),
    "Photo Actions",
    true},
  {"Redo",
    LOC("$$$/Bezel/RedoTitle=Redo"),
    "Photo Actions",
    true},
  {"CopySettings",
    "Copy Settings",
    "Photo Actions",
    true},
  {"PasteSettings",
    LOC("$$$/AgCameraRawNamedSettings/Ops/PasteSettings=Paste Settings"),
    "Photo Actions",
    true},
  {"PasteSelectedSettings",
    "Paste Selected Settings",
    "Photo Actions",
    true},
  {"Preset_1", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."1", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_2", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."2", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_3", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."3", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_4", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."4", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_5", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."5", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_6", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."6", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_7", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."7", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_8", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."8", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_9", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."9", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_10", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."10", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_11", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."11", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_12", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."12", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_13", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."13", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_14", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."14", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_15", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."15", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_16", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."16", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_17", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."17", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_18", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."18", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_19", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."19", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"Preset_20", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")..' '.."20", 
    LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets"),
    true},
  {"ZoomInLargeStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomIn=Zoom In"),
    "Miscellaneous",
    true},
  {"ZoomInSmallStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomInSome=Zoom In Some"),
    "Miscellaneous",
    true},
  {"ZoomOutSmallStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomOutSome=Zoom Out Some"),
    "Miscellaneous",
    true},
  {"ZoomOutLargeStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomOut=Zoom Out"),
    "Miscellaneous",
    true},
  {"ToggleZoomOffOn",
    "Toggle Zoom Off/On",
    "Miscellaneous",
    true},
  {"CropAngle",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/CropAngle=Crop Angle"),
    "Miscellaneous",
    false},
  {"CropBottom",
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")..' - '.. LOC("$$$/Layout/Panel/Panel/OutputFormat/PageNumber/Bottom=Bottom"),
    "Miscellaneous",
    false},
  {"CropLeft",
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")..' - '..LOC("$$$/AgWatermarking/Alignment/Left=Left"),
    "Miscellaneous",
    false},
  {"CropRight",
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")..' - '..LOC("$$$/AgWatermarking/Alignment/Right=Right"),
    "Miscellaneous",
    false},
  {"CropTop",
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")..' - '..LOC("$$$/Layout/Panel/Panel/OutputFormat/PageNumber/Top=Top"),
    "Miscellaneous",
    false},
  {"ResetCrop",
    LOC("$$$/AgLibrary/Ops/ResetCrop=Reset Crop"),
    "Miscellaneous",
    true},
  {"EnableCircularGradientBasedCorrections", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableRadialFilter=Enable Radial Filter"),
    "Miscellaneous",
    true},
  {"EnableGradientBasedCorrections", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableGraduatedFilter=Enable Graduated Filter"),
    "Miscellaneous",
    true},
  {"EnablePaintBasedCorrections",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableBrushAdjustments=Enable Brush Adjustments"),
    "Miscellaneous",
    true},
  {"EnableRedEye",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableRedEye=Enable Red-Eye"), 
    "Miscellaneous",
    true},
  {"EnableRetouch", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableSpotRemoval=Enable Spot Removal"),
    "Miscellaneous",
    true},
  {"ResetCircGrad",
    LOC("$$$/AgLibrary/Ops/ResetRadialFilters=Reset Radial Filters"),
    "Miscellaneous",
    true},
  {"ResetGradient",
    LOC("$$$/AgLibrary/Ops/ResetGraduatedFilters=Reset Graduated Filters"),
    "Miscellaneous",
    true},
  {"ResetBrushing",
    LOC("$$$/AgLibrary/Ops/ResetBrushing=Reset Brush Corrections"),
    "Miscellaneous",
    true},
  {"ResetRedeye",
    LOC("$$$/AgLibrary/Ops/ResetRedeye=Reset Red-Eye"),
    "Miscellaneous",
    true},
  {"ResetSpotRem",
    LOC("$$$/AgLibrary/Ops/ResetSpotRemoval=Reset Spot Removal"),
    "Miscellaneous",
    true},
  {"Loupe",
    "Loupe Tool",
    "Miscellaneous",
    true},
  {"CropOverlay",
    LOC("$$$/AgDevelop/Menu/View/Crop=Crop"):gsub('&',''),
    "Go to Tool, Module, or Panel",
    true},
  {"SpotRemoval",
    LOC("$$$/AgDevelop/Menu/View/SpotRemoval=Spot Removal"):gsub('&',''),
    "Go to Tool, Module, or Panel",
    true},
  {"RedEye",
    "Red Eye Tool",
    "Go to Tool, Module, or Panel",
    true},
  {"GraduatedFilter",
    "Graduated Filter Tool",
    "Go to Tool, Module, or Panel",
    true},
  {"RadialFilter",
    "Radial Filter Tool",
    "Go to Tool, Module, or Panel",
    true},
  {"AdjustmentBrush",
    LOC("$$$/AgDevelop/Menu/View/AdjustmentBrush=Adjustment Brush"),
    "Go to Tool, Module, or Panel",
    true},
  {"SwToMlibrary",
    "Library Module",
    "Go to Tool, Module, or Panel",
    true},
  {"SwToMdevelop",
    "Develop Module",
    "Go to Tool, Module, or Panel",
    true},
  {"SwToMmap",
    "Map Module",
    "Go to Tool, Module, or Panel",
    true},
  {"SwToMbook",
    "Book Module",
    "Go to Tool, Module, or Panel",
    true},
  {"SwToMslideshow",
    "Slideshow Module",
    "Go to Tool, Module, or Panel",
    true},
  {"SwToMprint",
    "Print Module",
    "Go to Tool, Module, or Panel",
    true},
  {"SwToMweb",
    "Web Module",
    "Go to Tool, Module, or Panel",
    true},
  {"RevealPanelAdjust",
    "Basic Adjustments Panel", 
    "Go to Tool, Module, or Panel",
    true},
  {"RevealPanelTone",
    "Tone Curve Panel",
    "Go to Tool, Module, or Panel",
    true},
  {"RevealPanelMixer",
    "Mixer Panel",
    "Go to Tool, Module, or Panel",
    true},
  {"RevealPanelSplit",
    "Split Toning Panel",
    "Go to Tool, Module, or Panel",
    true},
  {"RevealPanelDetail",
    "Detail Panel",
    "Go to Tool, Module, or Panel",
    true},
  {"RevealPanelLens",
    "Lens Corrections Panel",
    "Go to Tool, Module, or Panel",
    true},
  {"RevealPanelEffects",
    "Effects Panel",
    "Go to Tool, Module, or Panel",
    true},
  {"RevealPanelCalibrate",
    "Camera Calibration Panel",
    "Go to Tool, Module, or Panel",
    true},
  {"ShoVwloupe",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Loupe=Loupe"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoVwgrid",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Grid=Grid"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoVwcompare",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Compare=Compare"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoVwsurvey",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Survey=Survey"), 
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoVwpeople",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/People=People"), 
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoVwdevelop_loupe",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/Loupe=Loupe"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoVwdevelop_before_after_horiz",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/BeforeAfterLR=Before/After Left/Right"), 
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoVwdevelop_before_after_vert",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/BeforeAfterTB=Before/After Top/Bottom"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoVwdevelop_before",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/Before=Before"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoScndVwloupe", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Loupe=Loupe"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoScndVwlive_loupe", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/LiveLoupe=Live Loupe"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoScndVwlocked_loupe", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/LockedLoupe=Locked Loupe"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoScndVwgrid",
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Grid=Grid"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoScndVwcompare", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Compare=Compare"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoScndVwsurvey", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Survey=Survey"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ShoScndVwslideshow", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Slideshow=Slideshow"),
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"ToggleScreenTwo", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Show=Show"), 
    LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes"),
    true},
  {"profile1", "Profile 1", "Profiles",
    true},
  {"profile2", "Profile 2", "Profiles",
    true},
  {"profile3", "Profile 3", "Profiles",
    true},
  {"profile4", "Profile 4", "Profiles",
    true},
  {"profile5", "Profile 5", "Profiles",
    true},
  {"profile6", "Profile 6", "Profiles",
    true},
  {"profile7", "Profile 7", "Profiles",
    true},
  {"profile8", "Profile 8", "Profiles",
    true},
  {"profile9", "Profile 9", "Profiles",
    true},
  {"profile10", "Profile 10", "Profiles",
    true},
}

return {
  MenuList = MenuList,
}