--[[----------------------------------------------------------------------------

MenuListPreTrans.lua
Source of translations and menu for app and plugin
 
This file is part of MIDI2LR. Copyright 2015-2016 by Rory Jaffe.

MIDI2LR is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

MIDI2LR is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
MIDI2LR.  If not, see <http://www.gnu.org/licenses/>. 
------------------------------------------------------------------------------]]

local basicTone = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BasicTone=Basic Tone")
local calibration = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Calibration=Calibration")
local colorAdjustments = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/ColorAdjustments=Color Adjustments")
local detail = LOC("$$$/AgDevelop/Panel/Detail=Detail")
local developPreset = LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Single=Develop Preset")
local developPresets = LOC("$$$/AgLibrary/Filter/BrowserCriteria/DevelopPreset/Plural=Develop Presets")
local effects = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Effects=Effects")
local gotoToolModulePanel = "Go to Tool, Module, or Panel"
local lensCorrections = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/LensCorrections=Lens Corrections")
local localizedAdjustments = "Localized Adjustments"
local miscellaneous = "Miscellaneous"
local photoActions = "Photo Actions"
local profile = LOC("$$$/AgDevelop/CameraRawPanel/Profile=Profile:")
local profiles = LOC("$$$/CRaw/Style/Profiles=Profiles")
local reset = LOC("$$$/AgDevelop/LensCorrection/Upright/Reset=Reset")
local resetColorAdjustments = reset..' '..colorAdjustments
local show = LOC("$$$/AgLibrary/LibraryInfo/Show=Show")
local splitToning = LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SplitToning=Split Toning")
local toneCurve = LOC("$$$/AgDevelop/CameraRawPanel/TargetName/ToneCurve=Tone Curve")
local viewModes = LOC("$$$/AgDevelop/Toolbar/ViewModesTool=View Modes")
local whiteBalance = LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/WhiteBalance=White Balance")

local MenuList = {
  {"WhiteBalanceAs_Shot",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/AsShot=As Shot"),
    basicTone,
    true},
  {"WhiteBalanceAuto",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Auto=Auto"),
    basicTone,
    true},
  {"WhiteBalanceCloudy",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Cloudy=Cloudy"),
    basicTone,
    true},
  {"WhiteBalanceDaylight",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Daylight=Daylight"),
    basicTone,
    true},
  {"WhiteBalanceFlash",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Flash=Flash"),
    basicTone,
    true},
  {"WhiteBalanceFluorescent",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Fluorescent=Fluorescent"),
    basicTone,
    true},
  {"WhiteBalanceShade",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Shade=Shade"),
    basicTone,
    true},
  {"WhiteBalanceTungsten",
    whiteBalance..' '..LOC("$$$/AgCameraRawUI/WhiteBalance/Tungsten=Tungsten"),
    basicTone,
    true},
  {"Temperature",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Temperature=Temperature"),
    basicTone,
    false},
  {"Tint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Tint=Tint"),
    basicTone,
    false},
  {"Exposure",
    LOC("$$$/AgCameraRawUI/Exposure=Exposure"),
    basicTone,
    false},
  {"Contrast",
    LOC("$$$/AgCameraRawUI/Contrast=Contrast"),
    basicTone,
    false},
  {"Highlights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Highlights=Highlights"),
    basicTone,
    false},
  {"Shadows",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Shadows=Shadows"),
    basicTone,
    false},
  {"Whites",
    LOC("$$$/AgCameraRawUI/Whites=Whites"),
    basicTone,
    false},
  {"Blacks",
    LOC("$$$/AgCameraRawUI/Blacks=Blacks"),
    basicTone,
    false},
  {"Clarity",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Clarity=Clarity"),
    basicTone,
    false},
  {"Vibrance",
    LOC("$$$/AgCameraRawUI/Vibrance=Vibrance"),
    basicTone,
    false},
  {"Saturation",
    LOC("$$$/AgCameraRawUI/Saturation=Saturation"),
    basicTone,
    false},
  {"ResetTemperature",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Temperature=Temperature"),
    basicTone,
    true},
  {"ResetTint",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Tint=Tint"),
    basicTone,
    true},
  {"ResetExposure",
    reset..' '..LOC("$$$/AgCameraRawUI/Exposure=Exposure"),
    basicTone,
    true},
  {"ResetContrast",
    reset..' '..LOC("$$$/AgCameraRawUI/Contrast=Contrast"),
    basicTone,
    true},
  {"ResetHighlights",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Highlights=Highlights"),
    basicTone,
    true},
  {"ResetShadows",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Shadows=Shadows"),
    basicTone,
    true},
  {"ResetWhites",
    reset..' '..LOC("$$$/AgCameraRawUI/Whites=Whites"),
    basicTone,
    true},
  {"ResetBlacks",
    reset..' '..LOC("$$$/AgCameraRawUI/Blacks=Blacks"),
    basicTone,
    true},
  {"ResetClarity",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Clarity=Clarity"),
    basicTone,
    true},
  {"ResetVibrance",
    reset..' '..LOC("$$$/AgCameraRawUI/Vibrance=Vibrance"),
    basicTone,
    true},
  {"ResetSaturation",
    reset..' '..LOC("$$$/AgCameraRawUI/Saturation=Saturation"),
    basicTone,
    true},
  {"ParametricDarks",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneDarks=Dark Tones"),
    toneCurve,
    false},
  {"ParametricLights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneLights=Light Tones"),
    toneCurve,
    false},
  {"ParametricShadows",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadows=Shadow Tones"),
    toneCurve,
    false},
  {"ParametricHighlights",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlights=Highlight Tones"),
    toneCurve,
    false},
  {"ParametricShadowSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadowSplit=Shadow Split"),
    toneCurve,
    false},
  {"ParametricMidtoneSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneMidtoneSplit=Midtone Split"),
    toneCurve,
    false},
  {"ParametricHighlightSplit",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlightSplit=Highlight Split"),
    toneCurve,
    false},
  {"ResetParametricDarks",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneDarks=Dark Tones"), 
    toneCurve,
    true},
  {"ResetParametricLights",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneLights=Light Tones"),
    toneCurve,
    true},
  {"ResetParametricShadows",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadows=Shadow Tones"),
    toneCurve,
    true},
  {"ResetParametricHighlights",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlights=Highlight Tones"),
    toneCurve,
    true},
  {"ResetParametricShadowSplit",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneShadowSplit=Shadow Split"),
    toneCurve,
    true},
  {"ResetParametricMidtoneSplit",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneMidtoneSplit=Midtone Split"),
    toneCurve,
    true},
  {"ResetParametricHighlightSplit",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ToneHighlightSplit=Highlight Split"),
    toneCurve,
    true},
  {"EnableColorAdjustments",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableColorAdjustments=Enable Color Adjustments"),
    colorAdjustments,
    true},
  {"SaturationAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentRed=Saturation Adjustment Red"),
    colorAdjustments,
    false},
  {"SaturationAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentOrange=Saturation Adjustment Orange"),
    colorAdjustments,
    false},
  {"SaturationAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentYellow=Saturation Adjustment Yellow"),
    colorAdjustments,
    false},
  {"SaturationAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentGreen=Saturation Adjustment Green"),
    colorAdjustments,
    false},
  {"SaturationAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentAqua=Saturation Adjustment Aqua"),
    colorAdjustments,
    false},
  {"SaturationAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentBlue=Saturation Adjustment Blue"),
    colorAdjustments,
    false},
  {"SaturationAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentPurple=Saturation Adjustment Purple"),
    colorAdjustments,
    false},
  {"SaturationAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentMagenta=Saturation Adjustment Magenta"),
    colorAdjustments,
    false},
  {"HueAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentRed=Hue Adjustment Red"),
    colorAdjustments,
    false},
  {"HueAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentOrange=Hue Adjustment Orange"),
    colorAdjustments,
    false},
  {"HueAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentYellow=Hue Adjustment Yellow"),
    colorAdjustments,
    false},
  {"HueAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentGreen=Hue Adjustment Green"),
    colorAdjustments,
    false},
  {"HueAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentAqua=Hue Adjustment Aqua"),
    colorAdjustments,
    false},
  {"HueAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentBlue=Hue Adjustment Blue"),
    colorAdjustments,
    false},
  {"HueAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentPurple=Hue Adjustment Purple"),
    colorAdjustments,
    false},
  {"HueAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentMagenta=Hue Adjustment Magenta"),
    colorAdjustments,
    false},
  {"LuminanceAdjustmentRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentRed=Luminance Adjustment Red"),
    colorAdjustments,
    false},
  {"LuminanceAdjustmentOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentOrange=Luminance Adjustment Orange"),
    colorAdjustments,
    false},
  {"LuminanceAdjustmentYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentYellow=Luminance Adjustment Yellow"),
    colorAdjustments,
    false},
  {"LuminanceAdjustmentGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentGreen=Luminance Adjustment Green"),
    colorAdjustments,
    false},
  {"LuminanceAdjustmentAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentAqua=Luminance Adjustment Aqua"),
    colorAdjustments,
    false},
  {"LuminanceAdjustmentBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentBlue=Luminance Adjustment Blue"),
    colorAdjustments,
    false},
  {"LuminanceAdjustmentPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentPurple=Luminance Adjustment Purple"),
    colorAdjustments,
    false},
  {"LuminanceAdjustmentMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentMagenta=Luminance Adjustment Magenta"),
    colorAdjustments,
    false},
  {"ConvertToGrayscale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ConvertToGrayscale=Convert to Grayscale"),
    colorAdjustments,
    true},
  {"EnableGrayscaleMix",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableGrayscaleMix=Enable Grayscale Mix"),
    colorAdjustments,
    true},
  {"GrayMixerRed",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerRed=Gray Mixer Red"),
    colorAdjustments,
    false},
  {"GrayMixerOrange",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerOrange=Gray Mixer Orange"),
    colorAdjustments,
    false},
  {"GrayMixerYellow",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerYellow=Gray Mixer Yellow"),
    colorAdjustments,
    false},
  {"GrayMixerGreen",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerGreen=Gray Mixer Green"),
    colorAdjustments,
    false},
  {"GrayMixerAqua",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerAqua=Gray Mixer Aqua"),
    colorAdjustments,
    false},
  {"GrayMixerBlue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerBlue=Gray Mixer Blue"),
    colorAdjustments,
    false},
  {"GrayMixerPurple",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerPurple=Gray Mixer Purple"),
    colorAdjustments,
    false},
  {"GrayMixerMagenta",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerMagenta=Gray Mixer Magenta"),
    colorAdjustments,
    false},
  {"ResetSaturationAdjustmentRed",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentRed=Saturation Adjustment Red"),
    resetColorAdjustments,
    true},
  {"ResetSaturationAdjustmentOrange",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentOrange=Saturation Adjustment Orange"),
    resetColorAdjustments,
    true},
  {"ResetSaturationAdjustmentYellow",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentYellow=Saturation Adjustment Yellow"),
    resetColorAdjustments,
    true},
  {"ResetSaturationAdjustmentGreen",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentGreen=Saturation Adjustment Green"),
    resetColorAdjustments,
    true},
  {"ResetSaturationAdjustmentAqua",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentAqua=Saturation Adjustment Aqua"),
    resetColorAdjustments,
    true},
  {"ResetSaturationAdjustmentBlue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentBlue=Saturation Adjustment Blue"),
    resetColorAdjustments,
    true},
  {"ResetSaturationAdjustmentPurple",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentPurple=Saturation Adjustment Purple"),
    resetColorAdjustments,
    true},
  {"ResetSaturationAdjustmentMagenta",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SaturationAdjustmentMagenta=Saturation Adjustment Magenta"),
    resetColorAdjustments,
    true},
  {"ResetHueAdjustmentRed",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentRed=Hue Adjustment Red"),
    resetColorAdjustments,
    true},
  {"ResetHueAdjustmentOrange",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentOrange=Hue Adjustment Orange"),
    resetColorAdjustments,
    true},
  {"ResetHueAdjustmentYellow",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentYellow=Hue Adjustment Yellow"),
    resetColorAdjustments,
    true},
  {"ResetHueAdjustmentGreen",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentGreen=Hue Adjustment Green"),
    resetColorAdjustments,
    true},
  {"ResetHueAdjustmentAqua",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentAqua=Hue Adjustment Aqua"),
    resetColorAdjustments,
    true},
  {"ResetHueAdjustmentBlue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentBlue=Hue Adjustment Blue"),
    resetColorAdjustments,
    true},
  {"ResetHueAdjustmentPurple",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentPurple=Hue Adjustment Purple"),
    resetColorAdjustments,
    true},
  {"ResetHueAdjustmentMagenta",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/HueAdjustmentMagenta=Hue Adjustment Magenta"),
    resetColorAdjustments,
    true},
  {"ResetLuminanceAdjustmentRed",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentRed=Luminance Adjustment Red"),
    resetColorAdjustments,
    true},
  {"ResetLuminanceAdjustmentOrange",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentOrange=Luminance Adjustment Orange"),
    resetColorAdjustments,
    true},
  {"ResetLuminanceAdjustmentYellow",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentYellow=Luminance Adjustment Yellow"),
    resetColorAdjustments,
    true},
  {"ResetLuminanceAdjustmentGreen",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentGreen=Luminance Adjustment Green"),
    resetColorAdjustments,
    true},
  {"ResetLuminanceAdjustmentAqua",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentAqua=Luminance Adjustment Aqua"),
    resetColorAdjustments,
    true},
  {"ResetLuminanceAdjustmentBlue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentBlue=Luminance Adjustment Blue"),
    resetColorAdjustments,
    true},
  {"ResetLuminanceAdjustmentPurple",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentPurple=Luminance Adjustment Purple"),
    resetColorAdjustments,
    true},
  {"ResetLuminanceAdjustmentMagenta",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceAdjustmentMagenta=Luminance Adjustment Magenta"),
    resetColorAdjustments,
    true},
  {"ResetGrayMixerRed",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerRed=Gray Mixer Red"),
    resetColorAdjustments,
    true},
  {"ResetGrayMixerOrange",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerOrange=Gray Mixer Orange"),
    resetColorAdjustments,
    true},
  {"ResetGrayMixerYellow",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerYellow=Gray Mixer Yellow"),
    resetColorAdjustments,
    true},
  {"ResetGrayMixerGreen",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerGreen=Gray Mixer Green"),
    resetColorAdjustments,
    true},
  {"ResetGrayMixerAqua",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerAqua=Gray Mixer Aqua"),
    resetColorAdjustments,
    true},
  {"ResetGrayMixerBlue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerBlue=Gray Mixer Blue"),
    resetColorAdjustments,
    true},
  {"ResetGrayMixerPurple",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerPurple=Gray Mixer Purple"),
    resetColorAdjustments,
    true},
  {"ResetGrayMixerMagenta",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrayMixerMagenta=Gray Mixer Magenta"),
    resetColorAdjustments,
    true},
  {"EnableSplitToning",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableSplitToning=Enable Split Toning"),
    splitToning,
    true},
  {"SplitToningShadowHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowHue=Shadow Hue"),
    splitToning,
    false},
  {"SplitToningShadowSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowSaturation=Shadow Saturation"),
    splitToning,
    false},
  {"SplitToningHighlightHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightHue=Highlight Hue"),
    splitToning,
    false},
  {"SplitToningHighlightSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightSaturation=Highlight Saturation"),
    splitToning,
    false},
  {"SplitToningBalance",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningBalance=Split Toning Balance"),
    splitToning,
    false},
  {"ResetSplitToningShadowHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowHue=Shadow Hue"),
    splitToning,
    true},
  {"ResetSplitToningShadowSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningShadowSaturation=Shadow Saturation"),
    splitToning,
    true},
  {"ResetSplitToningHighlightHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightHue=Highlight Hue"),
    splitToning,
    true},
  {"ResetSplitToningHighlightSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningHighlightSaturation=Highlight Saturation"),
    splitToning,
    true},
  {"ResetSplitToningBalance",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SplitToningBalance=Split Toning Balance"),
    splitToning,
    true},
  {"EnableDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableDetail=Enable Detail"),
    detail,
    true},
  {"Sharpness",
    LOC("$$$/AgDevelop/Localized/Sharpness=Sharpness"),
    detail,
    false},
  {"SharpenRadius",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenRadius=Sharpen Radius"),
    detail,
    false},
  {"SharpenDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenDetail=Sharpen Detail"),
    detail,
    false},
  {"SharpenEdgeMasking",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenEdgeMasking=Sharpen Edge Masking"),
    detail,
    false},
  {"LuminanceSmoothing",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceSmoothing=Luminance Smoothing"),
    detail,
    false},
  {"LuminanceNoiseReductionDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionDetail=Luminance Detail"),
    detail,
    false},
  {"LuminanceNoiseReductionContrast",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionContrast=Luminance Contrast"),
    detail,
    false},
  {"ColorNoiseReduction",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReduction=Color Noise Reduction"),
    detail,
    false},
  {"ColorNoiseReductionDetail",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionDetail=Color Noise Reduction Detail"),
    detail,
    false},
  {"ColorNoiseReductionSmoothness",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionSmoothness=Color Noise Reduction Smoothness"),
    detail,
    false},
  {"ResetSharpness",
    reset..' '..LOC("$$$/AgDevelop/Localized/Sharpness=Sharpness"),
    detail,
    true},
  {"ResetSharpenRadius",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenRadius=Sharpen Radius"),
    detail,
    true},
  {"ResetSharpenDetail",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenDetail=Sharpen Detail"),
    detail,
    true},
  {"ResetSharpenEdgeMasking",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/SharpenEdgeMasking=Sharpen Edge Masking"),
    detail,
    true},
  {"ResetLuminanceSmoothing",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceSmoothing=Luminance Smoothing"),
    detail,
    true},
  {"ResetLuminanceNoiseReductionDetail",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionDetail=Luminance Detail"),
    detail,
    true},
  {"ResetLuminanceNoiseReductionContrast",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LuminanceNoiseReductionContrast=Luminance Contrast"),
    detail,
    true},
  {"ResetColorNoiseReduction",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReduction=Color Noise Reduction"),
    detail,
    true},
  {"ResetColorNoiseReductionDetail",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionDetail=Color Noise Reduction Detail"),
    detail,
    true},
  {"ResetColorNoiseReductionSmoothness",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ColorNoiseReductionSmoothness=Color Noise Reduction Smoothness"),
    detail,
    true},
  {"EnableLensCorrections",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableLensCorrections=Enable Lens Corrections"),
    lensCorrections,
    true},
  {"LensProfileEnable",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileEnable=Lens Profile Enable"),
    lensCorrections,
    true},
  {"AutoLateralCA",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RemoveChromaticAberration=Remove Chromatic Aberration"),
    lensCorrections,
    true},
  {"UprightOff",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueOff=Off"),
    lensCorrections,
    true},
  {"UprightAuto",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueAuto=Auto"),
    lensCorrections,
    true},
  {"UprightLevel",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueLevel=Level"),
    lensCorrections,
    true},
  {"UprightVertical",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueLevelVertical=Vertical"),
    lensCorrections,
    true},
  {"UprightFull",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/UprightPerspectiveCorrection=Perspective Correction")..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ValueFull=Full"),
    lensCorrections,
    true},
  {"ResetPerspectiveUpright",
    LOC("$$$/AgCameraRawNamedSettings/Ops/ResetUprightSettings=Reset Upright Settings"),
    lensCorrections,
    true},
  {"LensProfileDistortionScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileDistortionScale=Lens Profile Distortion Scale"),
    lensCorrections,
    false},
  {"LensProfileChromaticAberrationScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileChromaticAberrationScale=Lens Profile Chromatic Aberration Scale"),
    lensCorrections,
    false},
  {"LensProfileVignettingScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileVignettingScale=Lens Profile Vignetting Scale"),
    lensCorrections,
    false},
  {"ResetLensProfileDistortionScale",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileDistortionScale=Lens Profile Distortion Scale"),
    lensCorrections,
    true},
  {"ResetLensProfileChromaticAberrationScale",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileChromaticAberrationScale=Lens Profile Chromatic Aberration Scale"),
    lensCorrections,
    true},
  {"ResetLensProfileVignettingScale",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensProfileVignettingScale=Lens Profile Vignetting Scale"),
    lensCorrections,
    true},
  {"DefringePurpleAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeAmount=Defringe Purple Amount"),
    lensCorrections,
    false},
  {"DefringePurpleHueLo",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    lensCorrections,
    false},
  {"DefringePurpleHueHi",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    lensCorrections,
    false},
  {"DefringeGreenAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeAmount=Defringe Green Amount"),
    lensCorrections,
    false},
  {"DefringeGreenHueLo",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    lensCorrections,
    false},
  {"DefringeGreenHueHi",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    lensCorrections,
    false},
  {"ResetDefringePurpleAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeAmount=Defringe Purple Amount"),
    lensCorrections,
    true},
  {"ResetDefringePurpleHueLo",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    lensCorrections,
    true},
  {"ResetDefringePurpleHueHi",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PurpleDefringeHueLo=Defringe Purple Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    lensCorrections,
    true},
  {"ResetDefringeGreenAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeAmount=Defringe Green Amount"),
    lensCorrections,
    true},
  {"ResetDefringeGreenHueLo",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/Low=Low"),
    lensCorrections,
    true},
  {"ResetDefringeGreenHueHi",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenDefringeHueLo=Defringe Green Hue")..' - '..LOC("$$$/Slideshow/Panels/PanAndZoom/High=High"),
    lensCorrections,
    true},
  {"LensManualDistortionAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensManualDistortionAmount=Lens Manual Distortion Amount"),
    lensCorrections,
    false},
  {"PerspectiveVertical",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveVertical=Perspective Vertical"),
    lensCorrections,
    false},
  {"PerspectiveHorizontal",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveHorizontal=Perspective Horizontal"),
    lensCorrections,
    false},
  {"PerspectiveRotate",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveRotate=Perspective Rotate"),
    lensCorrections,
    false},
  {"PerspectiveScale",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveScale=Perspective Scale"),
    lensCorrections,
    false},
  {"PerspectiveAspect",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveAspect=Perspective Aspect"),
    lensCorrections,
    false},
  {"VignetteAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteAmount=Vignette Amount"),
    lensCorrections,
    false},
  {"VignetteMidpoint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteMidpoint=Vignette Midpoint"),
    lensCorrections,
    false},
  {"ResetLensManualDistortionAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/LensManualDistortionAmount=Lens Manual Distortion Amount"),
    lensCorrections,
    true},
  {"ResetPerspectiveVertical",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveVertical=Perspective Vertical"),
    lensCorrections,
    true},
  {"ResetPerspectiveHorizontal",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveHorizontal=Perspective Horizontal"),
    lensCorrections,
    true},
  {"ResetPerspectiveRotate",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveRotate=Perspective Rotate"),
    lensCorrections,
    true},
  {"ResetPerspectiveScale",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveScale=Perspective Scale"),
    lensCorrections,
    true},
  {"ResetPerspectiveAspect",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PerspectiveAspect=Perspective Aspect"),
    lensCorrections,
    true},
  {"ResetVignetteAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteAmount=Vignette Amount"),
    lensCorrections,
    true},
  {"ResetVignetteMidpoint",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/VignetteMidpoint=Vignette Midpoint"),
    lensCorrections,
    true},
  {"EnableEffects",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableEffects=Enable Effects"),
    effects,
    true},
  {"Dehaze",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/DehazeAmount=Dehaze Amount"),
    effects,
    false},
  {"PostCropVignetteAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteAmount=Post Crop Vignette Amount"),
    effects,
    false},
  {"PostCropVignetteMidpoint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteMidpoint=Post Crop Vignette Midpoint"),
    effects,
    false},
  {"PostCropVignetteFeather",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteFeather=Post Crop Vignette Feather"),
    effects,
    false},
  {"PostCropVignetteRoundness",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteRoundness=Post Crop Vignette Roundness"),
    effects,
    false},
  {"PostCropVignetteStyle",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteStyle=Post Crop Vignette Style"),
    effects,
    false},
  {"PostCropVignetteHighlightContrast",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteHighlightContrast=Post Crop Vignette Highlight Contrast"),
    effects,
    false},
  {"GrainAmount",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainAmount=Grain Amount"),
    effects,
    false},
  {"GrainSize",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainSize=Grain Size"),
    effects,
    false},
  {"GrainFrequency",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainRoughness=Grain Roughness"),
    effects,
    false},
  {"ResetDehaze",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/DehazeAmount=Dehaze Amount"),
    effects,
    true},
  {"ResetPostCropVignetteAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteAmount=Post Crop Vignette Amount"),
    effects,
    true},
  {"ResetPostCropVignetteMidpoint",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteMidpoint=Post Crop Vignette Midpoint"),
    effects,
    true},
  {"ResetPostCropVignetteFeather",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteFeather=Post Crop Vignette Feather"),
    effects,
    true},
  {"ResetPostCropVignetteRoundness",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteRoundness=Post Crop Vignette Roundness"),
    effects,
    true},
  {"ResetPostCropVignetteStyle",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteStyle=Post Crop Vignette Style"),
    effects,
    true},
  {"ResetPostCropVignetteHighlightContrast",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/PostCropVignetteHighlightContrast=Post Crop Vignette Highlight Contrast"),
    effects,
    true},
  {"ResetGrainAmount",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainAmount=Grain Amount"),
    effects,
    true},
  {"ResetGrainSize",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainSize=Grain Size"),
    effects,
    true},
  {"ResetGrainFrequency",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GrainRoughness=Grain Roughness"),
    effects,
    true},
  {"EnableCalibration",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableCalibration=Enable Calibration"),
    calibration,
    true},
  {"Profile_Adobe_Standard",
    LOC("$$$/CRaw/Style/Profile/AdobeStandard=Adobe Standard"),
    calibration,
    true},
  {"Profile_Camera_Clear",
    LOC("$$$/CRaw/Style/Profile/CameraClear=Camera Clear"),
    calibration,
    true},
  {"Profile_Camera_Deep",
    LOC("$$$/CRaw/Style/Profile/CameraDeep=Camera Deep"),
    calibration,
    true},
  {"Profile_Camera_Landscape",
    LOC("$$$/CRaw/Style/Profile/CameraLandscape=Camera Landscape"),
    calibration,
    true},
  {"Profile_Camera_Light",
    LOC("$$$/CRaw/Style/Profile/CameraLight=Camera Light"),
    calibration,
    true},
  {"Profile_Camera_Neutral",
    LOC("$$$/CRaw/Style/Profile/CameraNeutral=Camera Neutral"),
    calibration,
    true},
  {"Profile_Camera_Portrait",
    LOC("$$$/CRaw/Style/Profile/CameraPortrait=Camera Portrait"),
    calibration,
    true},
  {"Profile_Camera_Standard",
    LOC("$$$/CRaw/Style/Profile/CameraStandard=Camera Standard"),
    calibration,
    true},
  {"Profile_Camera_Vivid",
    LOC("$$$/CRaw/Style/Profile/CameraVivid=Camera Vivid"),
    calibration,
    true},
  {"ShadowTint",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ShadowTintCalibration=Shadow Tint Calibration"),
    calibration,
    false},
  {"RedHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedHueCalibration=Red Hue Calibration"),
    calibration,
    false},
  {"RedSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedSaturationCalibration=Red Saturation Calibration"),
    calibration,
    false},
  {"GreenHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenHueCalibration=Green Hue Calibration"),
    calibration,
    false},
  {"GreenSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenSaturationCalibration=Green Saturation Calibration"),
    calibration,
    false},
  {"BlueHue",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueHueCalibration=Blue Hue Calibration"),
    calibration,
    false},
  {"BlueSaturation",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueSaturationCalibration=Blue Saturation Calibration"),
    calibration,
    false},
  {"ResetShadowTint",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/ShadowTintCalibration=Shadow Tint Calibration"),
    calibration,
    false},
  {"ResetRedHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedHueCalibration=Red Hue Calibration"),
    calibration,
    false},
  {"ResetRedSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/RedSaturationCalibration=Red Saturation Calibration"),
    calibration,
    false},
  {"ResetGreenHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenHueCalibration=Green Hue Calibration"),
    calibration,
    false},
  {"ResetGreenSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/GreenSaturationCalibration=Green Saturation Calibration"),
    calibration,
    false},
  {"ResetBlueHue",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueHueCalibration=Blue Hue Calibration"),
    calibration,
    false},
  {"ResetBlueSaturation",
    reset..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/BlueSaturationCalibration=Blue Saturation Calibration"),
    calibration,
    false},
  {"Pick",
    LOC("$$$/AgLibrary/Help/Shortcuts/SetPick=Set Pick Flag"),
    photoActions,
    true},
  {"Reject",
    LOC("$$$/AgLibrary/Help/Shortcuts/SetReject=Set Rejected Flag"),
    photoActions,
    true},
  {"Next",
    LOC("$$$/AgDevelopShortcuts/Next_Photo=Next Photo"),
    photoActions,
    true},
  {"Prev",
    LOC("$$$/AgDevelopShortcuts/Previous_Photo=Previous Photo"),
    photoActions,
    true},
  {"Select1Left",
    LOC("$$$/AgLibrary/Menu/Edit/AddToSelection=Add to Selection")..' '..LOC("$$$/AgWatermarking/Alignment/Left=Left"),
    'Photo Actions',
    true},
  {"Select1Right",
    LOC("$$$/AgLibrary/Menu/Edit/AddToSelection=Add to Selection")..' '..LOC("$$$/AgWatermarking/Alignment/Right=Right"),
    'Photo Actions',
    true},
  {"VirtualCopy",
    LOC("$$$/AgLibrary/Bezel/CreateVirtualCopy=Create Virtual Copy"):gsub('&',''),
    photoActions,
    true},
  {"RemoveFlag",
    LOC("$$$/AgLibrary/Menu/Photo/SetPick/Unflagged=Unflagged"):gsub('&',''),
    photoActions,
    true},
  {"IncreaseRating",
    LOC("$$$/AgLibrary/Ops/IncreaseRating=Increase Rating"),
    photoActions,
    true},
  {"DecreaseRating",
    LOC("$$$/AgLibrary/Ops/DecreaseRating=Decrease Rating"),
    photoActions,
    true},
  {"SetRating0",
    LOC("$$$/AgLibrary/Filter/Stars=^1 Stars",'0'),
    photoActions,
    true},
  {"SetRating1",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating1=1 Star"):gsub('&',''),
    photoActions,
    true},
  {"SetRating2",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating2=&2 Stars"):gsub('&',''),
    photoActions,
    true},
  {"SetRating3",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating3=&3 Stars"):gsub('&',''),
    photoActions,
    true},
  {"SetRating4",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating4=&4 Stars"):gsub('&',''),
    photoActions,
    true},
  {"SetRating5",
    LOC("$$$/AgLibrary/Menu/Photo/SetRating/Win/Rating5=&5 Stars"):gsub('&',''),
    photoActions,
    true},
  {"ToggleBlue",
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelBlue=Blue")),
    photoActions,
    true},
  {"ToggleGreen",
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelGreen=Green")),
    photoActions,
    true},
  {"ToggleRed", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelRed=Red")),
    photoActions,
    true},
  {"TogglePurple", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelPurple=Purple")),
    photoActions,
    true},
  {"ToggleYellow", 
    LOC("$$$/AgLibrary/Undo/ToggleColorLabel=Label ^1 Enable/Disable",LOC("$$$/LibraryImporter/ColorLabelYellow=Yellow")),
    photoActions,
    true},
  {"ResetAll",
    LOC("$$$/AgCameraRawNamedSettings/Ops/ResetSettings=Reset Settings"),
    photoActions,
    true},
  {"ResetLast",
    reset..' '..LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified"):gsub(':',''),
    photoActions,
    true},
  {"IncrementLastDevelopParameter",
    LOC("$$$/AgCameraRawController/TargetAdjustment/Increase=^1 Increase: ^2",'',LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified")):gsub(':',''):gsub("^%s*(.-)%s*$", "%1"),
    photoActions,
    true},
  {"DecrementLastDevelopParameter",
    LOC("$$$/AgCameraRawController/TargetAdjustment/Decrease=^1 Decrease: ^2",'',LOC("$$$/LibraryUpgradeCatalogUtils/CatalogInfo/LastModified/Label=Last Modified")):gsub(':',''):gsub("^%s*(.-)%s*$", "%1"),
    photoActions,
    true},
  {"Undo",
    LOC("$$$/AgCameraRawController/SoftProofingVirtualCopyPrompt/Undo=Undo"),
    photoActions,
    true},
  {"Redo",
    LOC("$$$/Bezel/RedoTitle=Redo"),
    photoActions,
    true},
  {"CopySettings",
    "Copy Settings",
    photoActions,
    true},
  {"PasteSettings",
    LOC("$$$/AgCameraRawNamedSettings/Ops/PasteSettings=Paste Settings"),
    photoActions,
    true},
  {"PasteSelectedSettings",
    "Paste Selected Settings",
    photoActions,
    true},
  {"Preset_1", 
    developPreset.." 1", 
    developPresets,
    true},
  {"Preset_2", 
    developPreset.." 2", 
    developPresets,
    true},
  {"Preset_3", 
    developPreset.." 3", 
    developPresets,
    true},
  {"Preset_4", 
    developPreset.." 4", 
    developPresets,
    true},
  {"Preset_5", 
    developPreset.." 5", 
    developPresets,
    true},
  {"Preset_6", 
    developPreset.." 6", 
    developPresets,
    true},
  {"Preset_7", 
    developPreset.." 7", 
    developPresets,
    true},
  {"Preset_8", 
    developPreset.." 8", 
    developPresets,
    true},
  {"Preset_9", 
    developPreset.." 9", 
    developPresets,
    true},
  {"Preset_10", 
    developPreset.." 10", 
    developPresets,
    true},
  {"Preset_11", 
    developPreset.." 11", 
    developPresets,
    true},
  {"Preset_12", 
    developPreset.." 12", 
    developPresets,
    true},
  {"Preset_13", 
    developPreset.." 13", 
    developPresets,
    true},
  {"Preset_14", 
    developPreset.." 14", 
    developPresets,
    true},
  {"Preset_15", 
    developPreset.." 15", 
    developPresets,
    true},
  {"Preset_16", 
    developPreset.." 16", 
    developPresets,
    true},
  {"Preset_17", 
    developPreset.." 17", 
    developPresets,
    true},
  {"Preset_18", 
    developPreset.." 18", 
    developPresets,
    true},
  {"Preset_19", 
    developPreset.." 19", 
    developPresets,
    true},
  {"Preset_20", 
    developPreset.." 20", 
    developPresets,
    true},
  {"local_Temperature",
    "Local Temperature (PV2012)",
    localizedAdjustments,
    false},
  {"local_Tint",
    "Local Tint (PV2012)",
    localizedAdjustments,
    false},
  {"local_Exposure",
    "Local Exposure (PV2010 and PV2012)",
    localizedAdjustments,
    false},
  {"local_Contrast",
    "Local Contrast (PV2010 and PV2012)",
    localizedAdjustments,
    false},
  {"local_Highlights",
    "Local Highlights (PV2012)",
    localizedAdjustments,
    false},
  {"local_Shadows",
    "Local Shadows (PV2012)",
    localizedAdjustments,
    false},
  {"local_Clarity",
    "Local Clarity (PV2010 and PV2012)",
    localizedAdjustments,
    false},
  {"local_Saturation",
    "Local Saturation (PV2010 and PV2012)",
    localizedAdjustments,
    false},
  {"local_Sharpness",
    "Local Sharpness (PV2010 and PV 2012)",
    localizedAdjustments,
    false},
  {"local_LuminanceNoise",
    "Local Luminance Noise (PV2012)",
    "Localized Adjusments",
    false},
  {"local_Moire",
    "Local Moire (PV2012)",
    localizedAdjustments,
    false},
  {"local_Defringe",
    "Local Defringe (PV2012)",
    localizedAdjustments,
    false},
  {"local_ToningLuminance",
    "Local Toning Luminance (PV2010)",
    localizedAdjustments,
    false},
  {"Resetlocal_Temperature",
    "Reset Local Temperature (PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Tint",
    "Reset Local Tint (PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Exposure",
    "Reset Local Exposure (PV2010 and PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Contrast",
    "Reset Local Contrast (PV2010 and PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Highlights",
    "Reset Local Highlights (PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Shadows",
    "Reset Local Shadows (PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Clarity",
    "Reset Local Clarity (PV2010 and PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Saturation",
    "Reset Local Saturation (PV2010 and PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Sharpness",
    "Reset Local Sharpness (PV2010 and PV 2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_LuminanceNoise",
    "Reset Local Luminance Noise (PV2012)",
    "Localized Adjusments",
    true},
  {"Resetlocal_Moire",
    "Reset Local Moire (PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_Defringe",
    "Reset Local Defringe (PV2012)",
    localizedAdjustments,
    true},
  {"Resetlocal_ToningLuminance",
    "Reset Local Toning Luminance (PV2010)",
    localizedAdjustments,
    true},
    {"EnableCircularGradientBasedCorrections", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableRadialFilter=Enable Radial Filter"),
    localizedAdjustments,
    true},
  {"EnableGradientBasedCorrections", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableGraduatedFilter=Enable Graduated Filter"),
    localizedAdjustments,
    true},
  {"EnablePaintBasedCorrections",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableBrushAdjustments=Enable Brush Adjustments"),
    localizedAdjustments,
    true},
  {"EnableRedEye",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableRedEye=Enable Red-Eye"), 
    localizedAdjustments,
    true},
  {"EnableRetouch", 
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/EnableSpotRemoval=Enable Spot Removal"),
    localizedAdjustments,
    true},
  {"ResetCircGrad",
    LOC("$$$/AgLibrary/Ops/ResetRadialFilters=Reset Radial Filters"),
    localizedAdjustments,
    true},
  {"ResetGradient",
    LOC("$$$/AgLibrary/Ops/ResetGraduatedFilters=Reset Graduated Filters"),
    localizedAdjustments,
    true},
  {"ResetBrushing",
    LOC("$$$/AgLibrary/Ops/ResetBrushing=Reset Brush Corrections"),
    localizedAdjustments,
    true},
  {"ResetRedeye",
    LOC("$$$/AgLibrary/Ops/ResetRedeye=Reset Red-Eye"),
    localizedAdjustments,
    true},
  {"ResetSpotRem",
    LOC("$$$/AgLibrary/Ops/ResetSpotRemoval=Reset Spot Removal"),
    localizedAdjustments,
    true},
  {"ZoomInLargeStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomIn=Zoom In"),
    miscellaneous,
    true},
  {"ZoomInSmallStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomInSome=Zoom In Some"),
    miscellaneous,
    true},
  {"ZoomOutSmallStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomOutSome=Zoom Out Some"),
    miscellaneous,
    true},
  {"ZoomOutLargeStep",
    LOC("$$$/AgApplication/Menu/Window/SecondMonitor/ZoomOut=Zoom Out"),
    miscellaneous,
    true},
  {"ToggleZoomOffOn",
    "Toggle Zoom Off/On",
    miscellaneous,
    true},
  {"CropAngle",
    LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/CropAngle=Crop Angle"),
    miscellaneous,
    false},
  {"CropBottom",
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")..' - '.. LOC("$$$/Layout/Panel/Panel/OutputFormat/PageNumber/Bottom=Bottom"),
    miscellaneous,
    false},
  {"CropLeft",
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")..' - '..LOC("$$$/AgWatermarking/Alignment/Left=Left"),
    miscellaneous,
    false},
  {"CropRight",
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")..' - '..LOC("$$$/AgWatermarking/Alignment/Right=Right"),
    miscellaneous,
    false},
  {"CropTop",
    LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop")..' - '..LOC("$$$/Layout/Panel/Panel/OutputFormat/PageNumber/Top=Top"),
    miscellaneous,
    false},
  {"ResetCrop",
    LOC("$$$/AgLibrary/Ops/ResetCrop=Reset Crop"),
    miscellaneous,
    true},
  {"Loupe",
    show..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/Loupe=Loupe"),
    gotoToolModulePanel,
    true},
  {"CropOverlay",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/Crop=Crop"),
    gotoToolModulePanel,
    true},
  {"SpotRemoval",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/SpotRemoval=Spot Removal"),
    gotoToolModulePanel,
    true},
  {"RedEye",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/CameraRawSettingMapping/Redeye=Red-Eye Correction"),
    gotoToolModulePanel,
    true},
  {"GraduatedFilter",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/GraduatedFilters=Graduated Filters"),
    gotoToolModulePanel,
    true},
  {"RadialFilter",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/RadialFilters=Radial Filters"),
    gotoToolModulePanel,
    true},
  {"AdjustmentBrush",
    show..' '..LOC("$$$/AgCameraRawNamedSettings/SaveNamedDialog/BrushAdjustments=Brush Adjustments"),
    gotoToolModulePanel,
    true},
  {"SwToMlibrary",
    show..' '..LOC("$$$/AgLibraryModule/ModuleTitle=Library"),
    gotoToolModulePanel,
    true},
  {"SwToMdevelop",
    show..' '..LOC("$$$/SmartCollection/Criteria/Heading/Develop=Develop"),
    gotoToolModulePanel,
    true},
  {"SwToMmap",
    show..' '..LOC("$$$/AgLocation/ModuleTitle=Map"),
    gotoToolModulePanel,
    true},
  {"SwToMbook",
    show..' '..LOC("$$$/Ag/Layout/Book/ModuleTitle=Book"),
    gotoToolModulePanel,
    true},
  {"SwToMslideshow",
    show..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Slideshow=Slideshow"),
    gotoToolModulePanel,
    true},
  {"SwToMprint",
    show..' '..LOC("$$$/AgPrint/Menu/File/Print=Print"),
    gotoToolModulePanel,
    true},
  {"SwToMweb",
    show..' '..LOC("$$$/WPG/Help/Shortcuts/WebHeader=Web"),
    gotoToolModulePanel,
    true},
  {"RevealPanelAdjust",
    show..' '..basicTone,
    gotoToolModulePanel,
    true},
  {"RevealPanelTone",
    show..' '..toneCurve,
    gotoToolModulePanel,
    true},
  {"RevealPanelMixer",
    show..' '..colorAdjustments,
    gotoToolModulePanel,
    true},
  {"RevealPanelSplit",
    show..' '..splitToning,
    gotoToolModulePanel,
    true},
  {"RevealPanelDetail",
    show..' '..detail,
    gotoToolModulePanel,
    true},
  {"RevealPanelLens",
    show..' '..lensCorrections,
    gotoToolModulePanel,
    true},
  {"RevealPanelEffects",
    show..' '..effects,
    gotoToolModulePanel,
    true},
  {"RevealPanelCalibrate",
    show..' '..calibration,
    gotoToolModulePanel,
    true},
  {"ShoVwloupe",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Loupe=Loupe"),
    viewModes,
    true},
  {"ShoVwgrid",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Grid=Grid"),
    viewModes,
    true},
  {"ShoVwcompare",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Compare=Compare"),
    viewModes,
    true},
  {"ShoVwsurvey",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/Survey=Survey"), 
    viewModes,
    true},
  {"ShoVwpeople",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Library/People=People"), 
    viewModes,
    true},
  {"ShoVwdevelop_loupe",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/Loupe=Loupe"),
    viewModes,
    true},
  {"ShoVwdevelop_before_after_horiz",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/BeforeAfterLR=Before/After Left/Right"), 
    viewModes,
    true},
  {"ShoVwdevelop_before_after_vert",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/BeforeAfterTB=Before/After Top/Bottom"),
    viewModes,
    true},
  {"ShoVwdevelop_before",
    LOC("$$$/AgPhotoBin/Tooltip/PrimaryViewMode=Primary Display")..' '..LOC("$$$/AgPhotoBin/ViewMode/Develop/Before=Before"),
    viewModes,
    true},
  {"ShoScndVwloupe", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Loupe=Loupe"),
    viewModes,
    true},
  {"ShoScndVwlive_loupe", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/LiveLoupe=Live Loupe"),
    viewModes,
    true},
  {"ShoScndVwlocked_loupe", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/LockedLoupe=Locked Loupe"),
    viewModes,
    true},
  {"ShoScndVwgrid",
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Grid=Grid"),
    viewModes,
    true},
  {"ShoScndVwcompare", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Compare=Compare"),
    viewModes,
    true},
  {"ShoScndVwsurvey", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Survey=Survey"),
    viewModes,
    true},
  {"ShoScndVwslideshow", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Slideshow=Slideshow"),
    viewModes,
    true},
  {"ToggleScreenTwo", 
    LOC("$$$/AgApplication/Menu/Window/SecondaryDisplay=Secondary Display")..' '..LOC("$$$/AgApplication/Menu/Window/SecondMonitor/Show=Show"), 
    viewModes,
    true},
  {"profile1", 
    profile.." 1", 
    profiles,
    true},
  {"profile2", 
    profile.." 2", 
    profiles,
    true},
  {"profile3", 
    profile.." 3", 
    profiles,
    true},
  {"profile4", 
    profile.." 4", 
    profiles,
    true},
  {"profile5", 
    profile.." 5", 
    profiles,
    true},
  {"profile6", 
    profile.." 6", 
    profiles,
    true},
  {"profile7", 
    profile.." 7", 
    profiles,
    true},
  {"profile8", 
    profile.." 8", 
    profiles,
    true},
  {"profile9", 
    profile.." 9", 
    profiles,
    true},
  {"profile10", 
    profile.." 10", 
    profiles,
    true},
}

return {
  MenuList = MenuList,
}