  --[[----------------------------------------------------------------------------

  MenuList.lua

  This file was auto-generated by MIDI2LR and contains the translated menus used
  by the app and the plugin. Edits to this file will be lost any time MIDI2LR
  is updated or the language used by Lightroom changes. Edit Database.lua
  if you want to have persistent changes to the translations or menu structure.

  This file is part of MIDI2LR. Copyright 2015-2016 by Rory Jaffe.
  MIDI2LR is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later version.

  MIDI2LR is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
  PARTICULAR PURPOSE.  See the GNU General Public License for more details.
  You should have received a copy of the GNU General Public License along with
  MIDI2LR.  If not, see <http://www.gnu.org/licenses/>. 
  ------------------------------------------------------------------------------]]
  local MenuList = {
  {
    "Key1",
    "Key 1",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key2",
    "Key 2",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key3",
    "Key 3",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key4",
    "Key 4",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key5",
    "Key 5",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key6",
    "Key 6",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key7",
    "Key 7",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key8",
    "Key 8",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key9",
    "Key 9",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key10",
    "Key 10",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key11",
    "Key 11",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key12",
    "Key 12",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key13",
    "Key 13",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key14",
    "Key 14",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key15",
    "Key 15",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key16",
    "Key 16",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key17",
    "Key 17",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key18",
    "Key 18",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key19",
    "Key 19",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key20",
    "Key 20",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key21",
    "Key 21",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key22",
    "Key 22",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key23",
    "Key 23",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key24",
    "Key 24",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key25",
    "Key 25",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key26",
    "Key 26",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key27",
    "Key 27",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key28",
    "Key 28",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key29",
    "Key 29",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key30",
    "Key 30",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key31",
    "Key 31",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key32",
    "Key 32",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key33",
    "Key 33",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key34",
    "Key 34",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key35",
    "Key 35",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key36",
    "Key 36",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key37",
    "Key 37",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key38",
    "Key 38",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key39",
    "Key 39",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "Key40",
    "Key 40",
    "Keyboard Shortcuts for User",
    true
  },
  {
    "ShoVwgrid",
    "Primary Display Grid",
    "General",
    true
  },
  {
    "ShoVwloupe",
    "Primary Display Loupe",
    "General",
    true
  },
  {
    "ShoVwcompare",
    "Primary Display Compare",
    "General",
    true
  },
  {
    "ShoVwsurvey",
    "Primary Display Survey",
    "General",
    true
  },
  {
    "ToggleZoomOffOn",
    "Enable/Disable Zoom",
    "General",
    true
  },
  {
    "ZoomInLargeStep",
    "Zoom In",
    "General",
    true
  },
  {
    "ZoomInSmallStep",
    "Zoom In Some",
    "General",
    true
  },
  {
    "ZoomOutSmallStep",
    "Zoom Out Some",
    "General",
    true
  },
  {
    "ZoomOutLargeStep",
    "Zoom Out",
    "General",
    true
  },
  {
    "Select1Left",
    "Add to Selection Left",
    "General",
    true
  },
  {
    "Select1Right",
    "Add to Selection Right",
    "General",
    true
  },
  {
    "Next",
    "Next Photo",
    "General",
    true
  },
  {
    "Prev",
    "Previous Photo",
    "General",
    true
  },
  {
    "SwToMlibrary",
    "Show Library",
    "Library",
    true
  },
  {
    "Pick",
    "Set Pick Flag",
    "Library",
    true
  },
  {
    "Reject",
    "Set Rejected Flag",
    "Library",
    true
  },
  {
    "RemoveFlag",
    "Unflagged",
    "Library",
    true
  },
  {
    "SetRating0",
    "0 Stars",
    "Library",
    true
  },
  {
    "SetRating1",
    "1 Star",
    "Library",
    true
  },
  {
    "SetRating2",
    "2 Stars",
    "Library",
    true
  },
  {
    "SetRating3",
    "3 Stars",
    "Library",
    true
  },
  {
    "SetRating4",
    "4 Stars",
    "Library",
    true
  },
  {
    "SetRating5",
    "5 Stars",
    "Library",
    true
  },
  {
    "IncreaseRating",
    "Increase Rating",
    "Library",
    true
  },
  {
    "DecreaseRating",
    "Decrease Rating",
    "Library",
    true
  },
  {
    "ToggleBlue",
    "Label Blue Enable/Disable",
    "Library",
    true
  },
  {
    "ToggleGreen",
    "Label Green Enable/Disable",
    "Library",
    true
  },
  {
    "ToggleRed",
    "Label Red Enable/Disable",
    "Library",
    true
  },
  {
    "TogglePurple",
    "Label Purple Enable/Disable",
    "Library",
    true
  },
  {
    "ToggleYellow",
    "Label Yellow Enable/Disable",
    "Library",
    true
  },
  {
    "ShoVwpeople",
    "Primary Display People",
    "Library",
    true
  },
  {
    "SwToMdevelop",
    "Show Develop",
    "Develop",
    true
  },
  {
    "CopySettings",
    "Copy Settings",
    "Develop",
    true
  },
  {
    "PasteSettings",
    "Paste Settings",
    "Develop",
    true
  },
  {
    "PasteSelectedSettings",
    "Paste Selected Settings",
    "Develop",
    true
  },
  {
    "VirtualCopy",
    "Create Virtual Copy",
    "Develop",
    true
  },
  {
    "ResetAll",
    "Reset Settings",
    "Develop",
    true
  },
  {
    "ResetLast",
    "Reset Last Modified",
    "Develop",
    true
  },
  {
    "IncrementLastDevelopParameter",
    "Increase Last Modified",
    "Develop",
    true
  },
  {
    "DecrementLastDevelopParameter",
    "Decrease Last Modified",
    "Develop",
    true
  },
  {
    "Undo",
    "Undo",
    "Develop",
    true
  },
  {
    "Redo",
    "Redo",
    "Develop",
    true
  },
  {
    "ShoVwdevelop_before_after_horiz",
    "Primary Display Before/After Left/Right",
    "Develop",
    true
  },
  {
    "ShoVwdevelop_before_after_vert",
    "Primary Display Before/After Top/Bottom",
    "Develop",
    true
  },
  {
    "ShoVwdevelop_before",
    "Primary Display Before",
    "Develop",
    true
  },
  {
    "ShoVwdevelop_loupe",
    "Primary Display Loupe",
    "Develop",
    true
  },
  {
    "RevealPanelAdjust",
    "Show Basic Tone",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceAs_Shot",
    "White Balance As Shot",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceAuto",
    "White Balance Auto",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceCloudy",
    "White Balance Cloudy",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceDaylight",
    "White Balance Daylight",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceFlash",
    "White Balance Flash",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceFluorescent",
    "White Balance Fluorescent",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceShade",
    "White Balance Shade",
    "Basic Tone",
    true
  },
  {
    "WhiteBalanceTungsten",
    "White Balance Tungsten",
    "Basic Tone",
    true
  },
  {
    "Temperature",
    "Temperature",
    "Basic Tone",
    false
  },
  {
    "Tint",
    "Tint",
    "Basic Tone",
    false
  },
  {
    "Exposure",
    "Exposure",
    "Basic Tone",
    false
  },
  {
    "Contrast",
    "Contrast",
    "Basic Tone",
    false
  },
  {
    "Highlights",
    "Highlights (Highlight Recovery in PV2003 and PV2010)",
    "Basic Tone",
    false
  },
  {
    "Brightness",
    "Brightness",
    "Basic Tone",
    false
  },
  {
    "Shadows",
    "Shadows (Fill Light in PV2003 and PV2010)",
    "Basic Tone",
    false
  },
  {
    "Whites",
    "Whites (no effect in PV2003 and PV2010)",
    "Basic Tone",
    false
  },
  {
    "Blacks",
    "Blacks",
    "Basic Tone",
    false
  },
  {
    "Clarity",
    "Clarity",
    "Basic Tone",
    false
  },
  {
    "Vibrance",
    "Vibrance",
    "Basic Tone",
    false
  },
  {
    "Saturation",
    "Saturation",
    "Basic Tone",
    false
  },
  {
    "ResetTemperature",
    "Reset Temperature",
    "Basic Tone",
    true
  },
  {
    "ResetTint",
    "Reset Tint",
    "Basic Tone",
    true
  },
  {
    "ResetExposure",
    "Reset Exposure",
    "Basic Tone",
    true
  },
  {
    "ResetContrast",
    "Reset Contrast",
    "Basic Tone",
    true
  },
  {
    "ResetHighlights",
    "Reset Highlights",
    "Basic Tone",
    true
  },
  {
    "ResetShadows",
    "Reset Shadows",
    "Basic Tone",
    true
  },
  {
    "ResetWhites",
    "Reset Whites",
    "Basic Tone",
    true
  },
  {
    "ResetBlacks",
    "Reset Blacks",
    "Basic Tone",
    true
  },
  {
    "ResetClarity",
    "Reset Clarity",
    "Basic Tone",
    true
  },
  {
    "ResetVibrance",
    "Reset Vibrance",
    "Basic Tone",
    true
  },
  {
    "ResetSaturation",
    "Reset Saturation",
    "Basic Tone",
    true
  },
  {
    "RevealPanelTone",
    "Show Tone Curve",
    "Tone Curve",
    true
  },
  {
    "EnableToneCurve",
    "Enable Tone Curve",
    "Tone Curve",
    true
  },
  {
    "ParametricDarks",
    "Dark Tones",
    "Tone Curve",
    false
  },
  {
    "ParametricLights",
    "Light Tones",
    "Tone Curve",
    false
  },
  {
    "ParametricShadows",
    "Shadow Tones",
    "Tone Curve",
    false
  },
  {
    "ParametricHighlights",
    "Highlight Tones",
    "Tone Curve",
    false
  },
  {
    "ParametricShadowSplit",
    "Shadow Split",
    "Tone Curve",
    false
  },
  {
    "ParametricMidtoneSplit",
    "Midtone Split",
    "Tone Curve",
    false
  },
  {
    "ParametricHighlightSplit",
    "Highlight Split",
    "Tone Curve",
    false
  },
  {
    "ResetParametricDarks",
    "Reset Dark Tones",
    "Tone Curve",
    true
  },
  {
    "ResetParametricLights",
    "Reset Light Tones",
    "Tone Curve",
    true
  },
  {
    "ResetParametricShadows",
    "Reset Shadow Tones",
    "Tone Curve",
    true
  },
  {
    "ResetParametricHighlights",
    "Reset Highlight Tones",
    "Tone Curve",
    true
  },
  {
    "ResetParametricShadowSplit",
    "Reset Shadow Split",
    "Tone Curve",
    true
  },
  {
    "ResetParametricMidtoneSplit",
    "Reset Midtone Split",
    "Tone Curve",
    true
  },
  {
    "ResetParametricHighlightSplit",
    "Reset Highlight Split",
    "Tone Curve",
    true
  },
  {
    "RevealPanelMixer",
    "Show Color Adjustments",
    "Color Adjustments",
    true
  },
  {
    "EnableColorAdjustments",
    "Enable Color Adjustments",
    "Color Adjustments",
    true
  },
  {
    "SaturationAdjustmentRed",
    "Saturation Adjustment Red",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentOrange",
    "Saturation Adjustment Orange",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentYellow",
    "Saturation Adjustment Yellow",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentGreen",
    "Saturation Adjustment Green",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentAqua",
    "Saturation Adjustment Aqua",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentBlue",
    "Saturation Adjustment Blue",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentPurple",
    "Saturation Adjustment Purple",
    "Color Adjustments",
    false
  },
  {
    "SaturationAdjustmentMagenta",
    "Saturation Adjustment Magenta",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentRed",
    "Hue Adjustment Red",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentOrange",
    "Hue Adjustment Orange",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentYellow",
    "Hue Adjustment Yellow",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentGreen",
    "Hue Adjustment Green",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentAqua",
    "Hue Adjustment Aqua",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentBlue",
    "Hue Adjustment Blue",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentPurple",
    "Hue Adjustment Purple",
    "Color Adjustments",
    false
  },
  {
    "HueAdjustmentMagenta",
    "Hue Adjustment Magenta",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentRed",
    "Luminance Adjustment Red",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentOrange",
    "Luminance Adjustment Orange",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentYellow",
    "Luminance Adjustment Yellow",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentGreen",
    "Luminance Adjustment Green",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentAqua",
    "Luminance Adjustment Aqua",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentBlue",
    "Luminance Adjustment Blue",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentPurple",
    "Luminance Adjustment Purple",
    "Color Adjustments",
    false
  },
  {
    "LuminanceAdjustmentMagenta",
    "Luminance Adjustment Magenta",
    "Color Adjustments",
    false
  },
  {
    "ConvertToGrayscale",
    "Convert to Grayscale",
    "Color Adjustments",
    true
  },
  {
    "EnableGrayscaleMix",
    "Enable Grayscale Mix",
    "Color Adjustments",
    true
  },
  {
    "GrayMixerRed",
    "Gray Mixer Red",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerOrange",
    "Gray Mixer Orange",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerYellow",
    "Gray Mixer Yellow",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerGreen",
    "Gray Mixer Green",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerAqua",
    "Gray Mixer Aqua",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerBlue",
    "Gray Mixer Blue",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerPurple",
    "Gray Mixer Purple",
    "Color Adjustments",
    false
  },
  {
    "GrayMixerMagenta",
    "Gray Mixer Magenta",
    "Color Adjustments",
    false
  },
  {
    "ResetSaturationAdjustmentRed",
    "Reset Saturation Adjustment Red",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentOrange",
    "Reset Saturation Adjustment Orange",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentYellow",
    "Reset Saturation Adjustment Yellow",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentGreen",
    "Reset Saturation Adjustment Green",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentAqua",
    "Reset Saturation Adjustment Aqua",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentBlue",
    "Reset Saturation Adjustment Blue",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentPurple",
    "Reset Saturation Adjustment Purple",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetSaturationAdjustmentMagenta",
    "Reset Saturation Adjustment Magenta",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentRed",
    "Reset Hue Adjustment Red",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentOrange",
    "Reset Hue Adjustment Orange",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentYellow",
    "Reset Hue Adjustment Yellow",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentGreen",
    "Reset Hue Adjustment Green",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentAqua",
    "Reset Hue Adjustment Aqua",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentBlue",
    "Reset Hue Adjustment Blue",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentPurple",
    "Reset Hue Adjustment Purple",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetHueAdjustmentMagenta",
    "Reset Hue Adjustment Magenta",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentRed",
    "Reset Luminance Adjustment Red",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentOrange",
    "Reset Luminance Adjustment Orange",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentYellow",
    "Reset Luminance Adjustment Yellow",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentGreen",
    "Reset Luminance Adjustment Green",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentAqua",
    "Reset Luminance Adjustment Aqua",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentBlue",
    "Reset Luminance Adjustment Blue",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentPurple",
    "Reset Luminance Adjustment Purple",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetLuminanceAdjustmentMagenta",
    "Reset Luminance Adjustment Magenta",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerRed",
    "Reset Gray Mixer Red",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerOrange",
    "Reset Gray Mixer Orange",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerYellow",
    "Reset Gray Mixer Yellow",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerGreen",
    "Reset Gray Mixer Green",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerAqua",
    "Reset Gray Mixer Aqua",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerBlue",
    "Reset Gray Mixer Blue",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerPurple",
    "Reset Gray Mixer Purple",
    "Reset Color Adjustments",
    true
  },
  {
    "ResetGrayMixerMagenta",
    "Reset Gray Mixer Magenta",
    "Reset Color Adjustments",
    true
  },
  {
    "RevealPanelSplit",
    "Show Split Toning",
    "Split Toning",
    true
  },
  {
    "EnableSplitToning",
    "Enable Split Toning",
    "Split Toning",
    true
  },
  {
    "SplitToningShadowHue",
    "Shadow Hue",
    "Split Toning",
    false
  },
  {
    "SplitToningShadowSaturation",
    "Shadow Saturation",
    "Split Toning",
    false
  },
  {
    "SplitToningHighlightHue",
    "Highlight Hue",
    "Split Toning",
    false
  },
  {
    "SplitToningHighlightSaturation",
    "Highlight Saturation",
    "Split Toning",
    false
  },
  {
    "SplitToningBalance",
    "Split Toning Balance",
    "Split Toning",
    false
  },
  {
    "ResetSplitToningShadowHue",
    "Reset Shadow Hue",
    "Split Toning",
    true
  },
  {
    "ResetSplitToningShadowSaturation",
    "Reset Shadow Saturation",
    "Split Toning",
    true
  },
  {
    "ResetSplitToningHighlightHue",
    "Reset Highlight Hue",
    "Split Toning",
    true
  },
  {
    "ResetSplitToningHighlightSaturation",
    "Reset Highlight Saturation",
    "Split Toning",
    true
  },
  {
    "ResetSplitToningBalance",
    "Reset Split Toning Balance",
    "Split Toning",
    true
  },
  {
    "RevealPanelDetail",
    "Show Detail",
    "Detail",
    true
  },
  {
    "EnableDetail",
    "Enable Detail",
    "Detail",
    true
  },
  {
    "Sharpness",
    "Sharpness",
    "Detail",
    false
  },
  {
    "SharpenRadius",
    "Sharpen Radius",
    "Detail",
    false
  },
  {
    "SharpenDetail",
    "Sharpen Detail",
    "Detail",
    false
  },
  {
    "SharpenEdgeMasking",
    "Sharpen Edge Masking",
    "Detail",
    false
  },
  {
    "LuminanceSmoothing",
    "Luminance Smoothing",
    "Detail",
    false
  },
  {
    "LuminanceNoiseReductionDetail",
    "Luminance Detail",
    "Detail",
    false
  },
  {
    "LuminanceNoiseReductionContrast",
    "Luminance Contrast",
    "Detail",
    false
  },
  {
    "ColorNoiseReduction",
    "Color Noise Reduction",
    "Detail",
    false
  },
  {
    "ColorNoiseReductionDetail",
    "Color Noise Reduction Detail",
    "Detail",
    false
  },
  {
    "ColorNoiseReductionSmoothness",
    "Color Noise Reduction Smoothness",
    "Detail",
    false
  },
  {
    "ResetSharpness",
    "Reset Sharpness",
    "Detail",
    true
  },
  {
    "ResetSharpenRadius",
    "Reset Sharpen Radius",
    "Detail",
    true
  },
  {
    "ResetSharpenDetail",
    "Reset Sharpen Detail",
    "Detail",
    true
  },
  {
    "ResetSharpenEdgeMasking",
    "Reset Sharpen Edge Masking",
    "Detail",
    true
  },
  {
    "ResetLuminanceSmoothing",
    "Reset Luminance Smoothing",
    "Detail",
    true
  },
  {
    "ResetLuminanceNoiseReductionDetail",
    "Reset Luminance Detail",
    "Detail",
    true
  },
  {
    "ResetLuminanceNoiseReductionContrast",
    "Reset Luminance Contrast",
    "Detail",
    true
  },
  {
    "ResetColorNoiseReduction",
    "Reset Color Noise Reduction",
    "Detail",
    true
  },
  {
    "ResetColorNoiseReductionDetail",
    "Reset Color Noise Reduction Detail",
    "Detail",
    true
  },
  {
    "ResetColorNoiseReductionSmoothness",
    "Reset Color Noise Reduction Smoothness",
    "Detail",
    true
  },
  {
    "RevealPanelLens",
    "Show Lens Corrections",
    "Lens Corrections",
    true
  },
  {
    "EnableLensCorrections",
    "Enable Lens Corrections",
    "Lens Corrections",
    true
  },
  {
    "UprightOff",
    "Perspective Correction Off",
    "Lens Corrections",
    true
  },
  {
    "UprightAuto",
    "Perspective Correction Auto",
    "Lens Corrections",
    true
  },
  {
    "UprightLevel",
    "Perspective Correction Level",
    "Lens Corrections",
    true
  },
  {
    "UprightVertical",
    "Perspective Correction Vertical",
    "Lens Corrections",
    true
  },
  {
    "UprightFull",
    "Perspective Correction Full",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveUpright",
    "Reset Upright Settings",
    "Lens Corrections",
    true
  },
  {
    "LensProfileDistortionScale",
    "Lens Profile Distortion Scale",
    "Lens Corrections",
    false
  },
  {
    "LensProfileChromaticAberrationScale",
    "Lens Profile Chromatic Aberration Scale",
    "Lens Corrections",
    false
  },
  {
    "LensProfileVignettingScale",
    "Lens Profile Vignetting Scale",
    "Lens Corrections",
    false
  },
  {
    "ResetLensProfileDistortionScale",
    "Reset Lens Profile Distortion Scale",
    "Lens Corrections",
    true
  },
  {
    "ResetLensProfileChromaticAberrationScale",
    "Reset Lens Profile Chromatic Aberration Scale",
    "Lens Corrections",
    true
  },
  {
    "ResetLensProfileVignettingScale",
    "Reset Lens Profile Vignetting Scale",
    "Lens Corrections",
    true
  },
  {
    "DefringePurpleAmount",
    "Defringe Purple Amount",
    "Lens Corrections",
    false
  },
  {
    "DefringePurpleHueLo",
    "Defringe Purple Hue - Low",
    "Lens Corrections",
    false
  },
  {
    "DefringePurpleHueHi",
    "Defringe Purple Hue - High",
    "Lens Corrections",
    false
  },
  {
    "DefringeGreenAmount",
    "Defringe Green Amount",
    "Lens Corrections",
    false
  },
  {
    "DefringeGreenHueLo",
    "Defringe Green Hue - Low",
    "Lens Corrections",
    false
  },
  {
    "DefringeGreenHueHi",
    "Defringe Green Hue - High",
    "Lens Corrections",
    false
  },
  {
    "ResetDefringePurpleAmount",
    "Reset Defringe Purple Amount",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringePurpleHueLo",
    "Reset Defringe Purple Hue - Low",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringePurpleHueHi",
    "Reset Defringe Purple Hue - High",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringeGreenAmount",
    "Reset Defringe Green Amount",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringeGreenHueLo",
    "Reset Defringe Green Hue - Low",
    "Lens Corrections",
    true
  },
  {
    "ResetDefringeGreenHueHi",
    "Reset Defringe Green Hue - High",
    "Lens Corrections",
    true
  },
  {
    "LensManualDistortionAmount",
    "Lens Manual Distortion Amount",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveVertical",
    "Perspective Vertical",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveHorizontal",
    "Perspective Horizontal",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveRotate",
    "Perspective Rotate",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveScale",
    "Perspective Scale",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveAspect",
    "Perspective Aspect",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveX ",
    "Perspective X",
    "Lens Corrections",
    false
  },
  {
    "PerspectiveY ",
    "Perspective Y",
    "Lens Corrections",
    false
  },
  {
    "VignetteAmount",
    "Vignette Amount",
    "Lens Corrections",
    false
  },
  {
    "VignetteMidpoint",
    "Vignette Midpoint",
    "Lens Corrections",
    false
  },
  {
    "ResetLensManualDistortionAmount",
    "Reset Lens Manual Distortion Amount",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveVertical",
    "Reset Perspective Vertical",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveHorizontal",
    "Reset Perspective Horizontal",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveRotate",
    "Reset Perspective Rotate",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveScale",
    "Reset Perspective Scale",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveAspect",
    "Reset Perspective Aspect",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveX",
    "Reset Perspective X",
    "Lens Corrections",
    true
  },
  {
    "ResetPerspectiveY",
    "Reset Perspective Y",
    "Lens Corrections",
    true
  },
  {
    "ResetVignetteAmount",
    "Reset Vignette Amount",
    "Lens Corrections",
    true
  },
  {
    "ResetVignetteMidpoint",
    "Reset Vignette Midpoint",
    "Lens Corrections",
    true
  },
  {
    "RevealPanelEffects",
    "Show Effects",
    "Effects",
    true
  },
  {
    "EnableEffects",
    "Enable Effects",
    "Effects",
    true
  },
  {
    "Dehaze",
    "Dehaze Amount",
    "Effects",
    false
  },
  {
    "PostCropVignetteAmount",
    "Post Crop Vignette Amount",
    "Effects",
    false
  },
  {
    "PostCropVignetteMidpoint",
    "Post Crop Vignette Midpoint",
    "Effects",
    false
  },
  {
    "PostCropVignetteFeather",
    "Post Crop Vignette Feather",
    "Effects",
    false
  },
  {
    "PostCropVignetteRoundness",
    "Post Crop Vignette Roundness",
    "Effects",
    false
  },
  {
    "PostCropVignetteStyle",
    "Post Crop Vignette Style",
    "Effects",
    false
  },
  {
    "PostCropVignetteHighlightContrast",
    "Post Crop Vignette Highlight Contrast",
    "Effects",
    false
  },
  {
    "GrainAmount",
    "Grain Amount",
    "Effects",
    false
  },
  {
    "GrainSize",
    "Grain Size",
    "Effects",
    false
  },
  {
    "GrainFrequency",
    "Grain Roughness",
    "Effects",
    false
  },
  {
    "ResetDehaze",
    "Reset Dehaze Amount",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteAmount",
    "Reset Post Crop Vignette Amount",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteMidpoint",
    "Reset Post Crop Vignette Midpoint",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteFeather",
    "Reset Post Crop Vignette Feather",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteRoundness",
    "Reset Post Crop Vignette Roundness",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteStyle",
    "Reset Post Crop Vignette Style",
    "Effects",
    true
  },
  {
    "ResetPostCropVignetteHighlightContrast",
    "Reset Post Crop Vignette Highlight Contrast",
    "Effects",
    true
  },
  {
    "ResetGrainAmount",
    "Reset Grain Amount",
    "Effects",
    true
  },
  {
    "ResetGrainSize",
    "Reset Grain Size",
    "Effects",
    true
  },
  {
    "ResetGrainFrequency",
    "Reset Grain Roughness",
    "Effects",
    true
  },
  {
    "RevealPanelCalibrate",
    "Show Calibration",
    "Calibration",
    true
  },
  {
    "EnableCalibration",
    "Enable Calibration",
    "Calibration",
    true
  },
  {
    "Profile_Adobe_Standard",
    "Adobe Standard",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Clear",
    "Camera Clear",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Darker_Skin_Tone",
    "Camera Darker Skin Tone",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Deep",
    "Camera Deep",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Faithful",
    "Camera Faithful",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Flat",
    "Camera Flat",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Landscape",
    "Camera Landscape",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Light",
    "Camera Light",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Lighter_Skin_Tone",
    "Camera Lighter Skin Tone",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Monochrome",
    "Camera Monochrome",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Monotone",
    "Camera Monotone",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Muted",
    "Camera Muted",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Natural",
    "Camera Natural",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Neutral",
    "Camera Neutral",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Portrait",
    "Camera Portrait",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Positive_Film",
    "Camera Positive Film",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Standard",
    "Camera Standard",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Vivid",
    "Camera Vivid",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Vivid_Blue",
    "Camera Vivid Blue",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Vivid_Green",
    "Camera Vivid Green",
    "Calibration",
    true
  },
  {
    "Profile_Camera_Vivid_Red",
    "Camera Vivid Red",
    "Calibration",
    true
  },
  {
    "ShadowTint",
    "Shadow Tint Calibration",
    "Calibration",
    false
  },
  {
    "RedHue",
    "Red Hue Calibration",
    "Calibration",
    false
  },
  {
    "RedSaturation",
    "Red Saturation Calibration",
    "Calibration",
    false
  },
  {
    "GreenHue",
    "Green Hue Calibration",
    "Calibration",
    false
  },
  {
    "GreenSaturation",
    "Green Saturation Calibration",
    "Calibration",
    false
  },
  {
    "BlueHue",
    "Blue Hue Calibration",
    "Calibration",
    false
  },
  {
    "BlueSaturation",
    "Blue Saturation Calibration",
    "Calibration",
    false
  },
  {
    "ResetShadowTint",
    "Reset Shadow Tint Calibration",
    "Calibration",
    true
  },
  {
    "ResetRedHue",
    "Reset Red Hue Calibration",
    "Calibration",
    true
  },
  {
    "ResetRedSaturation",
    "Reset Red Saturation Calibration",
    "Calibration",
    true
  },
  {
    "ResetGreenHue",
    "Reset Green Hue Calibration",
    "Calibration",
    true
  },
  {
    "ResetGreenSaturation",
    "Reset Green Saturation Calibration",
    "Calibration",
    true
  },
  {
    "ResetBlueHue",
    "Reset Blue Hue Calibration",
    "Calibration",
    true
  },
  {
    "ResetBlueSaturation",
    "Reset Blue Saturation Calibration",
    "Calibration",
    true
  },
  {
    "Preset_1",
    "Develop Preset 1",
    "Develop Presets",
    true
  },
  {
    "Preset_2",
    "Develop Preset 2",
    "Develop Presets",
    true
  },
  {
    "Preset_3",
    "Develop Preset 3",
    "Develop Presets",
    true
  },
  {
    "Preset_4",
    "Develop Preset 4",
    "Develop Presets",
    true
  },
  {
    "Preset_5",
    "Develop Preset 5",
    "Develop Presets",
    true
  },
  {
    "Preset_6",
    "Develop Preset 6",
    "Develop Presets",
    true
  },
  {
    "Preset_7",
    "Develop Preset 7",
    "Develop Presets",
    true
  },
  {
    "Preset_8",
    "Develop Preset 8",
    "Develop Presets",
    true
  },
  {
    "Preset_9",
    "Develop Preset 9",
    "Develop Presets",
    true
  },
  {
    "Preset_10",
    "Develop Preset 10",
    "Develop Presets",
    true
  },
  {
    "Preset_11",
    "Develop Preset 11",
    "Develop Presets",
    true
  },
  {
    "Preset_12",
    "Develop Preset 12",
    "Develop Presets",
    true
  },
  {
    "Preset_13",
    "Develop Preset 13",
    "Develop Presets",
    true
  },
  {
    "Preset_14",
    "Develop Preset 14",
    "Develop Presets",
    true
  },
  {
    "Preset_15",
    "Develop Preset 15",
    "Develop Presets",
    true
  },
  {
    "Preset_16",
    "Develop Preset 16",
    "Develop Presets",
    true
  },
  {
    "Preset_17",
    "Develop Preset 17",
    "Develop Presets",
    true
  },
  {
    "Preset_18",
    "Develop Preset 18",
    "Develop Presets",
    true
  },
  {
    "Preset_19",
    "Develop Preset 19",
    "Develop Presets",
    true
  },
  {
    "Preset_20",
    "Develop Preset 20",
    "Develop Presets",
    true
  },
  {
    "Preset_21",
    "Develop Preset 21",
    "Develop Presets",
    true
  },
  {
    "Preset_22",
    "Develop Preset 22",
    "Develop Presets",
    true
  },
  {
    "Preset_23",
    "Develop Preset 23",
    "Develop Presets",
    true
  },
  {
    "Preset_24",
    "Develop Preset 24",
    "Develop Presets",
    true
  },
  {
    "Preset_25",
    "Develop Preset 25",
    "Develop Presets",
    true
  },
  {
    "Preset_26",
    "Develop Preset 26",
    "Develop Presets",
    true
  },
  {
    "Preset_27",
    "Develop Preset 27",
    "Develop Presets",
    true
  },
  {
    "Preset_28",
    "Develop Preset 28",
    "Develop Presets",
    true
  },
  {
    "Preset_29",
    "Develop Preset 29",
    "Develop Presets",
    true
  },
  {
    "Preset_30",
    "Develop Preset 30",
    "Develop Presets",
    true
  },
  {
    "Preset_31",
    "Develop Preset 31",
    "Develop Presets",
    true
  },
  {
    "Preset_32",
    "Develop Preset 32",
    "Develop Presets",
    true
  },
  {
    "Preset_33",
    "Develop Preset 33",
    "Develop Presets",
    true
  },
  {
    "Preset_34",
    "Develop Preset 34",
    "Develop Presets",
    true
  },
  {
    "Preset_35",
    "Develop Preset 35",
    "Develop Presets",
    true
  },
  {
    "Preset_36",
    "Develop Preset 36",
    "Develop Presets",
    true
  },
  {
    "Preset_37",
    "Develop Preset 37",
    "Develop Presets",
    true
  },
  {
    "Preset_38",
    "Develop Preset 38",
    "Develop Presets",
    true
  },
  {
    "Preset_39",
    "Develop Preset 39",
    "Develop Presets",
    true
  },
  {
    "Preset_40",
    "Develop Preset 40",
    "Develop Presets",
    true
  },
  {
    "GraduatedFilter",
    "Show Graduated Filters",
    "Local Adjustments",
    true
  },
  {
    "RadialFilter",
    "Show Radial Filters",
    "Local Adjustments",
    true
  },
  {
    "RedEye",
    "Show Red-Eye Correction",
    "Local Adjustments",
    true
  },
  {
    "SpotRemoval",
    "Show Spot Removal",
    "Local Adjustments",
    true
  },
  {
    "AdjustmentBrush",
    "Show Brush Adjustments",
    "Local Adjustments",
    true
  },
  {
    "local_Temperature",
    "Local Adjustments Temp. (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Tint",
    "Local Adjustments Tint (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Exposure",
    "Local Adjustments Exposure (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Contrast",
    "Local Adjustments Contrast (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Highlights",
    "Local Adjustments Highlights (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Shadows",
    "Local Adjustments Shadows (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Whites2012",
    "Local Adjustments Whites (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Blacks2012",
    "Local Adjustments Blacks (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Clarity",
    "Local Adjustments Clarity (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Dehaze",
    "Local Adjustments Dehaze (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Saturation",
    "Local Adjustments Saturation (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Sharpness",
    "Local Adjustments Sharpness (PV2010 and PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_LuminanceNoise",
    "Local Adjustments Luminence Noise Reduction (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Moire",
    "Local Adjustments Moire (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_Defringe",
    "Local Adjustments Defringe (PV2012)",
    "Local Adjustments",
    false
  },
  {
    "local_ToningLuminance",
    "Local Toning Luminance (PV2010)",
    "Local Adjustments",
    false
  },
  {
    "Resetlocal_Temperature",
    "Reset Local Adjustments Temp. (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Tint",
    "Reset Local Adjustments Tint (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Exposure",
    "Reset Local Adjustments Exposure (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Contrast",
    "Reset Local Adjustments Contrast (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Highlights",
    "Reset Local Adjustments Highlights (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Shadows",
    "Reset Local Adjustments Shadows (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Whites2012",
    "Reset Local Adjustments Whites (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Blacks2012",
    "Reset Local Adjustments Blacks (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Clarity",
    "Reset Local Adjustments Clarity (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Dehaze",
    "Reset Local Adjustments Dehaze (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Saturation",
    "Reset Local Adjustments Saturation (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Sharpness",
    "Reset Local Adjustments Sharpness (PV2010 and PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_LuminanceNoise",
    "Reset Local Adjustments Luminence Noise Reduction (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Moire",
    "Reset Local Adjustments Moire (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_Defringe",
    "Reset Local Adjustments Defringe (PV2012)",
    "Local Adjustments",
    true
  },
  {
    "Resetlocal_ToningLuminance",
    "Reset Local Toning Luminance (PV2010)",
    "Local Adjustments",
    true
  },
  {
    "EnableCircularGradientBasedCorrections",
    "Enable Radial Filter",
    "Local Adjustments",
    true
  },
  {
    "EnableGradientBasedCorrections",
    "Enable Graduated Filter",
    "Local Adjustments",
    true
  },
  {
    "EnablePaintBasedCorrections",
    "Enable Brush Adjustments",
    "Local Adjustments",
    true
  },
  {
    "EnableRedEye",
    "Enable Red-Eye",
    "Local Adjustments",
    true
  },
  {
    "EnableRetouch",
    "Enable Spot Removal",
    "Local Adjustments",
    true
  },
  {
    "ResetCircGrad",
    "Reset Radial Filters",
    "Local Adjustments",
    true
  },
  {
    "ResetGradient",
    "Reset Graduated Filters",
    "Local Adjustments",
    true
  },
  {
    "ResetBrushing",
    "Reset Brush Corrections",
    "Local Adjustments",
    true
  },
  {
    "ResetRedeye",
    "Reset Red-Eye",
    "Local Adjustments",
    true
  },
  {
    "ResetSpotRem",
    "Reset Spot Removal",
    "Local Adjustments",
    true
  },
  {
    "straightenAngle",
    "Straighten Angle",
    "Crop",
    false
  },
  {
    "CropAngle",
    "Crop Angle",
    "Crop",
    false
  },
  {
    "CropBottom",
    "Crop - Bottom",
    "Crop",
    false
  },
  {
    "CropLeft",
    "Crop - Left",
    "Crop",
    false
  },
  {
    "CropRight",
    "Crop - Right",
    "Crop",
    false
  },
  {
    "CropTop",
    "Crop - Top",
    "Crop",
    false
  },
  {
    "ResetCrop",
    "Reset Crop",
    "Crop",
    true
  },
  {
    "ResetstraightenAngle",
    "Reset Straighten Angle",
    "Crop",
    true
  },
  {
    "CropOverlay",
    "Show Crop",
    "Crop",
    true
  },
  {
    "Loupe",
    "Show Loupe",
    "Select Tools, Modules and Panels",
    true
  },
  {
    "SwToMmap",
    "Show Map",
    "Select Tools, Modules and Panels",
    true
  },
  {
    "SwToMbook",
    "Show Book",
    "Select Tools, Modules and Panels",
    true
  },
  {
    "SwToMslideshow",
    "Show Slideshow",
    "Select Tools, Modules and Panels",
    true
  },
  {
    "SwToMprint",
    "Show Print",
    "Select Tools, Modules and Panels",
    true
  },
  {
    "SwToMweb",
    "Show Web",
    "Select Tools, Modules and Panels",
    true
  },
  {
    "ShoScndVwloupe",
    "Secondary Display Loupe",
    "Secondary Display",
    true
  },
  {
    "ShoScndVwlive_loupe",
    "Secondary Display Live Loupe",
    "Secondary Display",
    true
  },
  {
    "ShoScndVwlocked_loupe",
    "Secondary Display Locked Loupe",
    "Secondary Display",
    true
  },
  {
    "ShoScndVwgrid",
    "Secondary Display Grid",
    "Secondary Display",
    true
  },
  {
    "ShoScndVwcompare",
    "Secondary Display Compare",
    "Secondary Display",
    true
  },
  {
    "ShoScndVwsurvey",
    "Secondary Display Survey",
    "Secondary Display",
    true
  },
  {
    "ShoScndVwslideshow",
    "Secondary Display Slideshow",
    "Secondary Display",
    true
  },
  {
    "ToggleScreenTwo",
    "Secondary Display Show",
    "Secondary Display",
    true
  },
  {
    "profile1",
    "Profile: 1",
    "Profiles",
    true
  },
  {
    "profile2",
    "Profile: 2",
    "Profiles",
    true
  },
  {
    "profile3",
    "Profile: 3",
    "Profiles",
    true
  },
  {
    "profile4",
    "Profile: 4",
    "Profiles",
    true
  },
  {
    "profile5",
    "Profile: 5",
    "Profiles",
    true
  },
  {
    "profile6",
    "Profile: 6",
    "Profiles",
    true
  },
  {
    "profile7",
    "Profile: 7",
    "Profiles",
    true
  },
  {
    "profile8",
    "Profile: 8",
    "Profiles",
    true
  },
  {
    "profile9",
    "Profile: 9",
    "Profiles",
    true
  },
  {
    "profile10",
    "Profile: 10",
    "Profiles",
    true
  },
  {
    "FullRefresh",
    "Manual Update",
    "Profiles",
    true
  }
}