--[[----------------------------------------------------------------------------
This file was auto-generated by MIDI2LR and contains the parameters used by the
plugin. Edits to this file will be lost any time MIDI2LR is updated or the 
language used by Lightroom changes. Edit MenuListPreTrans.lua if you want to have 
persistent changes to the translations or menu structure.

This file is part of MIDI2LR. Copyright 2015-2016 by Rory Jaffe.
MIDI2LR is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

MIDI2LR is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
MIDI2LR.  If not, see <http://www.gnu.org/licenses/>. 
------------------------------------------------------------------------------]]
local SelectivePasteMenu = {
  {
    "ProcessVersion",
    "Process Version"
  },
  {
    "WhiteBalance",
    "White Balance"
  },
  {
    "AutoBrightness",
    "Automatic Brightness"
  },
  {
    "AutoContrast",
    "Automatic Contrast"
  },
  {
    "AutoExposure",
    "Automatic Exposure"
  },
  {
    "AutoShadows",
    "Automatic Shadows"
  },
  {
    "Temperature",
    "Temperature"
  },
  {
    "Tint",
    "Tint"
  },
  {
    "Exposure",
    "Exposure"
  },
  {
    "Contrast",
    "Contrast"
  },
  {
    "Highlights",
    "Highlights (Recovery in PV2003 and PV2010)"
  },
  {
    "Brightness",
    "Brightness"
  },
  {
    "HighlightRecovery",
    "Highlight Recovery (PV2003 and PV2010)"
  },
  {
    "Shadows2012",
    "Shadows"
  },
  {
    "FillLight",
    "Fill Light (PV2003 and PV2010)"
  },
  {
    "Whites2012",
    "Whites (no effect in PV2003 and PV2010)"
  },
  {
    "Blacks2012",
    "Blacks"
  },
  {
    "Clarity",
    "Clarity"
  },
  {
    "Vibrance",
    "Vibrance"
  },
  {
    "Saturation",
    "Saturation"
  },
  {
    "ToneCurve",
    "Tone Curve"
  },
  {
    "ParametricDarks",
    "Dark Tones"
  },
  {
    "ParametricLights",
    "Light Tones"
  },
  {
    "ParametricShadows",
    "Shadow Tones"
  },
  {
    "ParametricHighlights",
    "Highlight Tones"
  },
  {
    "ParametricShadowSplit",
    "Shadow Split"
  },
  {
    "ParametricMidtoneSplit",
    "Midtone Split"
  },
  {
    "ParametricHighlightSplit",
    "Highlight Split"
  },
  {
    "EnableColorAdjustments",
    "Enable Color Adjustments"
  },
  {
    "SaturationAdjustmentRed",
    "Saturation Adjustment Red"
  },
  {
    "SaturationAdjustmentOrange",
    "Saturation Adjustment Orange"
  },
  {
    "SaturationAdjustmentYellow",
    "Saturation Adjustment Yellow"
  },
  {
    "SaturationAdjustmentGreen",
    "Saturation Adjustment Green"
  },
  {
    "SaturationAdjustmentAqua",
    "Saturation Adjustment Aqua"
  },
  {
    "SaturationAdjustmentBlue",
    "Saturation Adjustment Blue"
  },
  {
    "SaturationAdjustmentPurple",
    "Saturation Adjustment Purple"
  },
  {
    "SaturationAdjustmentMagenta",
    "Saturation Adjustment Magenta"
  },
  {
    "HueAdjustmentRed",
    "Hue Adjustment Red"
  },
  {
    "HueAdjustmentOrange",
    "Hue Adjustment Orange"
  },
  {
    "HueAdjustmentYellow",
    "Hue Adjustment Yellow"
  },
  {
    "HueAdjustmentGreen",
    "Hue Adjustment Green"
  },
  {
    "HueAdjustmentAqua",
    "Hue Adjustment Aqua"
  },
  {
    "HueAdjustmentBlue",
    "Hue Adjustment Blue"
  },
  {
    "HueAdjustmentPurple",
    "Hue Adjustment Purple"
  },
  {
    "HueAdjustmentMagenta",
    "Hue Adjustment Magenta"
  },
  {
    "LuminanceAdjustmentRed",
    "Luminance Adjustment Red"
  },
  {
    "LuminanceAdjustmentOrange",
    "Luminance Adjustment Orange"
  },
  {
    "LuminanceAdjustmentYellow",
    "Luminance Adjustment Yellow"
  },
  {
    "LuminanceAdjustmentGreen",
    "Luminance Adjustment Green"
  },
  {
    "LuminanceAdjustmentAqua",
    "Luminance Adjustment Aqua"
  },
  {
    "LuminanceAdjustmentBlue",
    "Luminance Adjustment Blue"
  },
  {
    "LuminanceAdjustmentPurple",
    "Luminance Adjustment Purple"
  },
  {
    "LuminanceAdjustmentMagenta",
    "Luminance Adjustment Magenta"
  },
  {
    "ConvertToGrayscale",
    "Convert to Grayscale"
  },
  {
    "EnableGrayscaleMix",
    "Enable Grayscale Mix"
  },
  {
    "GrayMixerRed",
    "Gray Mixer Red"
  },
  {
    "GrayMixerOrange",
    "Gray Mixer Orange"
  },
  {
    "GrayMixerYellow",
    "Gray Mixer Yellow"
  },
  {
    "GrayMixerGreen",
    "Gray Mixer Green"
  },
  {
    "GrayMixerAqua",
    "Gray Mixer Aqua"
  },
  {
    "GrayMixerBlue",
    "Gray Mixer Blue"
  },
  {
    "GrayMixerPurple",
    "Gray Mixer Purple"
  },
  {
    "GrayMixerMagenta",
    "Gray Mixer Magenta"
  },
  {
    "EnableSplitToning",
    "Enable Split Toning"
  },
  {
    "SplitToningShadowHue",
    "Shadow Hue"
  },
  {
    "SplitToningShadowSaturation",
    "Shadow Saturation"
  },
  {
    "SplitToningHighlightHue",
    "Highlight Hue"
  },
  {
    "SplitToningHighlightSaturation",
    "Highlight Saturation"
  },
  {
    "SplitToningBalance",
    "Split Toning Balance"
  },
  {
    "EnableDetail",
    "Enable Detail"
  },
  {
    "Sharpness",
    "Sharpness"
  },
  {
    "SharpenRadius",
    "Sharpen Radius"
  },
  {
    "SharpenDetail",
    "Sharpen Detail"
  },
  {
    "SharpenEdgeMasking",
    "Sharpen Edge Masking"
  },
  {
    "LuminanceSmoothing",
    "Luminance Smoothing"
  },
  {
    "LuminanceNoiseReductionDetail",
    "Luminance Detail"
  },
  {
    "LuminanceNoiseReductionContrast",
    "Luminance Contrast"
  },
  {
    "ColorNoiseReduction",
    "Color Noise Reduction"
  },
  {
    "ColorNoiseReductionDetail",
    "Color Noise Reduction Detail"
  },
  {
    "ColorNoiseReductionSmoothness",
    "Color Noise Reduction Smoothness"
  },
  {
    "EnableLensCorrections",
    "Enable Lens Corrections"
  },
  {
    "LensProfileEnable",
    "Lens Profile Enable"
  },
  {
    "LensProfileSetup",
    "Lens Profile Setup"
  },
  {
    "AutoLateralCA",
    "Remove Chromatic Aberration"
  },
  {
    "ChromaticAberrationB",
    "Blue Chromatic Aberration"
  },
  {
    "ChromaticAberrationR",
    "Red Chromatic Aberration"
  },
  {
    "PerspectiveUpright",
    "Perspective Upright"
  },
  {
    "LensProfileDistortionScale",
    "Lens Profile Distortion Scale"
  },
  {
    "LensProfileChromaticAberrationScale",
    "Lens Profile Chromatic Aberration Scale"
  },
  {
    "LensProfileVignettingScale",
    "Lens Profile Vignetting Scale"
  },
  {
    "DefringePurpleAmount",
    "Defringe Purple Amount"
  },
  {
    "DefringePurpleHueLo",
    "Defringe Purple Hue - Low"
  },
  {
    "DefringePurpleHueHi",
    "Defringe Purple Hue - High"
  },
  {
    "DefringeGreenAmount",
    "Defringe Green Amount"
  },
  {
    "DefringeGreenHueLo",
    "Defringe Green Hue - Low"
  },
  {
    "DefringeGreenHueHi",
    "Defringe Green Hue - High"
  },
  {
    "LensManualDistortionAmount",
    "Lens Manual Distortion Amount"
  },
  {
    "PerspectiveVertical",
    "Perspective Vertical"
  },
  {
    "PerspectiveHorizontal",
    "Perspective Horizontal"
  },
  {
    "PerspectiveRotate",
    "Perspective Rotate"
  },
  {
    "PerspectiveScale",
    "Perspective Scale"
  },
  {
    "PerspectiveAspect",
    "Perspective Aspect"
  },
  {
    "VignetteAmount",
    "Vignette Amount"
  },
  {
    "VignetteMidpoint",
    "Vignette Midpoint"
  },
  {
    "EnableEffects",
    "Enable Effects"
  },
  {
    "Dehaze",
    "Dehaze Amount"
  },
  {
    "PostCropVignetteAmount",
    "Post Crop Vignette Amount"
  },
  {
    "PostCropVignetteMidpoint",
    "Post Crop Vignette Midpoint"
  },
  {
    "PostCropVignetteFeather",
    "Post Crop Vignette Feather"
  },
  {
    "PostCropVignetteRoundness",
    "Post Crop Vignette Roundness"
  },
  {
    "PostCropVignetteStyle",
    "Post Crop Vignette Style"
  },
  {
    "PostCropVignetteHighlightContrast",
    "Post Crop Vignette Highlight Contrast"
  },
  {
    "GrainAmount",
    "Grain Amount"
  },
  {
    "GrainSize",
    "Grain Size"
  },
  {
    "GrainFrequency",
    "Grain Roughness"
  },
  {
    "EnableCalibration",
    "Enable Calibration"
  },
  {
    "CameraProfile",
    "Camera Profile"
  },
  {
    "ShadowTint",
    "Shadow Tint Calibration"
  },
  {
    "RedHue",
    "Red Hue Calibration"
  },
  {
    "RedSaturation",
    "Red Saturation Calibration"
  },
  {
    "GreenHue",
    "Green Hue Calibration"
  },
  {
    "GreenSaturation",
    "Green Saturation Calibration"
  },
  {
    "BlueHue",
    "Blue Hue Calibration"
  },
  {
    "BlueSaturation",
    "Blue Saturation Calibration"
  },
  {
    "EnableCircularGradientBasedCorrections",
    "Enable Radial Filter"
  },
  {
    "EnableGradientBasedCorrections",
    "Enable Graduated Filter"
  },
  {
    "EnablePaintBasedCorrections",
    "Enable Brush Adjustments"
  },
  {
    "EnableRedEye",
    "Enable Red-Eye"
  },
  {
    "EnableRetouch",
    "Enable Spot Removal"
  },
  {
    "RetouchInfo",
    "RetouchInfo"
  },
  {
    "orientation",
    "orientation"
  },
  {
    "CropConstrainToWarp",
    "Constrain to Warp"
  },
  {
    "CropAngle",
    "Crop Angle"
  },
  {
    "CropBottom",
    "Crop - Bottom"
  },
  {
    "CropLeft",
    "Crop - Left"
  },
  {
    "CropRight",
    "Crop - Right"
  },
  {
    "CropTop",
    "Crop - Top"
  },
  {
    "RedEyeInfo",
    "Red-Eye Information"
  },
  {
    "TrimEnd",
    "TrimEnd"
  },
  {
    "TrimStart",
    "TrimStart"
  }
}
local SelectivePasteHidden = {
  Clarity2012 = "Clarity",
  Contrast2012 = "Contrast",
  Exposure2012 = "Exposure",
  ToneCurveName = "ToneCurve",
  ToneCurveName2012 = "ToneCurve",
  ToneCurvePV2012 = "ToneCurve",
  ToneCurvePV2012Blue = "ToneCurve",
  ToneCurvePV2012Green = "ToneCurve",
  ToneCurvePV2012Red = "ToneCurve"
}
local SelectivePasteIteration = {
  "ProcessVersion",
  "WhiteBalance",
  "AutoBrightness",
  "AutoContrast",
  "AutoExposure",
  "AutoShadows",
  "Temperature",
  "Tint",
  "Exposure",
  "Exposure2012",
  "Contrast",
  "Contrast2012",
  "Highlights",
  "Brightness",
  "HighlightRecovery",
  "Shadows2012",
  "FillLight",
  "Whites2012",
  "Blacks2012",
  "Clarity",
  "Clarity2012",
  "Vibrance",
  "Saturation",
  "ToneCurve",
  "ToneCurveName",
  "ToneCurveName2012",
  "ToneCurvePV2012",
  "ToneCurvePV2012Blue",
  "ToneCurvePV2012Green",
  "ToneCurvePV2012Red",
  "ParametricDarks",
  "ParametricLights",
  "ParametricShadows",
  "ParametricHighlights",
  "ParametricShadowSplit",
  "ParametricMidtoneSplit",
  "ParametricHighlightSplit",
  "EnableColorAdjustments",
  "SaturationAdjustmentRed",
  "SaturationAdjustmentOrange",
  "SaturationAdjustmentYellow",
  "SaturationAdjustmentGreen",
  "SaturationAdjustmentAqua",
  "SaturationAdjustmentBlue",
  "SaturationAdjustmentPurple",
  "SaturationAdjustmentMagenta",
  "HueAdjustmentRed",
  "HueAdjustmentOrange",
  "HueAdjustmentYellow",
  "HueAdjustmentGreen",
  "HueAdjustmentAqua",
  "HueAdjustmentBlue",
  "HueAdjustmentPurple",
  "HueAdjustmentMagenta",
  "LuminanceAdjustmentRed",
  "LuminanceAdjustmentOrange",
  "LuminanceAdjustmentYellow",
  "LuminanceAdjustmentGreen",
  "LuminanceAdjustmentAqua",
  "LuminanceAdjustmentBlue",
  "LuminanceAdjustmentPurple",
  "LuminanceAdjustmentMagenta",
  "ConvertToGrayscale",
  "EnableGrayscaleMix",
  "GrayMixerRed",
  "GrayMixerOrange",
  "GrayMixerYellow",
  "GrayMixerGreen",
  "GrayMixerAqua",
  "GrayMixerBlue",
  "GrayMixerPurple",
  "GrayMixerMagenta",
  "EnableSplitToning",
  "SplitToningShadowHue",
  "SplitToningShadowSaturation",
  "SplitToningHighlightHue",
  "SplitToningHighlightSaturation",
  "SplitToningBalance",
  "EnableDetail",
  "Sharpness",
  "SharpenRadius",
  "SharpenDetail",
  "SharpenEdgeMasking",
  "LuminanceSmoothing",
  "LuminanceNoiseReductionDetail",
  "LuminanceNoiseReductionContrast",
  "ColorNoiseReduction",
  "ColorNoiseReductionDetail",
  "ColorNoiseReductionSmoothness",
  "EnableLensCorrections",
  "LensProfileEnable",
  "LensProfileSetup",
  "AutoLateralCA",
  "ChromaticAberrationB",
  "ChromaticAberrationR",
  "PerspectiveUpright",
  "LensProfileDistortionScale",
  "LensProfileChromaticAberrationScale",
  "LensProfileVignettingScale",
  "DefringePurpleAmount",
  "DefringePurpleHueLo",
  "DefringePurpleHueHi",
  "DefringeGreenAmount",
  "DefringeGreenHueLo",
  "DefringeGreenHueHi",
  "LensManualDistortionAmount",
  "PerspectiveVertical",
  "PerspectiveHorizontal",
  "PerspectiveRotate",
  "PerspectiveScale",
  "PerspectiveAspect",
  "VignetteAmount",
  "VignetteMidpoint",
  "EnableEffects",
  "Dehaze",
  "PostCropVignetteAmount",
  "PostCropVignetteMidpoint",
  "PostCropVignetteFeather",
  "PostCropVignetteRoundness",
  "PostCropVignetteStyle",
  "PostCropVignetteHighlightContrast",
  "GrainAmount",
  "GrainSize",
  "GrainFrequency",
  "EnableCalibration",
  "CameraProfile",
  "ShadowTint",
  "RedHue",
  "RedSaturation",
  "GreenHue",
  "GreenSaturation",
  "BlueHue",
  "BlueSaturation",
  "EnableCircularGradientBasedCorrections",
  "EnableGradientBasedCorrections",
  "EnablePaintBasedCorrections",
  "EnableRedEye",
  "EnableRetouch",
  "RetouchInfo",
  "orientation",
  "CropConstrainToWarp",
  "CropAngle",
  "CropBottom",
  "CropLeft",
  "CropRight",
  "CropTop",
  "RedEyeInfo",
  "TrimEnd",
  "TrimStart"
}
local SelectivePasteGroups = {
  basicTone = {
    "ProcessVersion",
    "WhiteBalance",
    "AutoBrightness",
    "AutoContrast",
    "AutoExposure",
    "AutoShadows",
    "Temperature",
    "Tint",
    "Exposure",
    "Contrast",
    "Highlights",
    "Brightness",
    "HighlightRecovery",
    "Shadows2012",
    "FillLight",
    "Whites2012",
    "Blacks2012",
    "Clarity",
    "Vibrance",
    "Saturation"
  },
  calibratePanel = {
    "EnableCalibration",
    "CameraProfile",
    "ShadowTint",
    "RedHue",
    "RedSaturation",
    "GreenHue",
    "GreenSaturation",
    "BlueHue",
    "BlueSaturation"
  },
  colorAdjustments = {
    "EnableColorAdjustments",
    "SaturationAdjustmentRed",
    "SaturationAdjustmentOrange",
    "SaturationAdjustmentYellow",
    "SaturationAdjustmentGreen",
    "SaturationAdjustmentAqua",
    "SaturationAdjustmentBlue",
    "SaturationAdjustmentPurple",
    "SaturationAdjustmentMagenta",
    "HueAdjustmentRed",
    "HueAdjustmentOrange",
    "HueAdjustmentYellow",
    "HueAdjustmentGreen",
    "HueAdjustmentAqua",
    "HueAdjustmentBlue",
    "HueAdjustmentPurple",
    "HueAdjustmentMagenta",
    "LuminanceAdjustmentRed",
    "LuminanceAdjustmentOrange",
    "LuminanceAdjustmentYellow",
    "LuminanceAdjustmentGreen",
    "LuminanceAdjustmentAqua",
    "LuminanceAdjustmentBlue",
    "LuminanceAdjustmentPurple",
    "LuminanceAdjustmentMagenta",
    "ConvertToGrayscale",
    "EnableGrayscaleMix",
    "GrayMixerRed",
    "GrayMixerOrange",
    "GrayMixerYellow",
    "GrayMixerGreen",
    "GrayMixerAqua",
    "GrayMixerBlue",
    "GrayMixerPurple",
    "GrayMixerMagenta"
  },
  detailPanel = {
    "EnableDetail",
    "Sharpness",
    "SharpenRadius",
    "SharpenDetail",
    "SharpenEdgeMasking",
    "LuminanceSmoothing",
    "LuminanceNoiseReductionDetail",
    "LuminanceNoiseReductionContrast",
    "ColorNoiseReduction",
    "ColorNoiseReductionDetail",
    "ColorNoiseReductionSmoothness"
  },
  effectsPanel = {
    "EnableEffects",
    "Dehaze",
    "PostCropVignetteAmount",
    "PostCropVignetteMidpoint",
    "PostCropVignetteFeather",
    "PostCropVignetteRoundness",
    "PostCropVignetteStyle",
    "PostCropVignetteHighlightContrast",
    "GrainAmount",
    "GrainSize",
    "GrainFrequency"
  },
  lensCorrectionsPanel = {
    "EnableLensCorrections",
    "LensProfileEnable",
    "LensProfileSetup",
    "AutoLateralCA",
    "ChromaticAberrationB",
    "ChromaticAberrationR",
    "PerspectiveUpright",
    "LensProfileDistortionScale",
    "LensProfileChromaticAberrationScale",
    "LensProfileVignettingScale",
    "DefringePurpleAmount",
    "DefringePurpleHueLo",
    "DefringePurpleHueHi",
    "DefringeGreenAmount",
    "DefringeGreenHueLo",
    "DefringeGreenHueHi",
    "LensManualDistortionAmount",
    "PerspectiveVertical",
    "PerspectiveHorizontal",
    "PerspectiveRotate",
    "PerspectiveScale",
    "PerspectiveAspect",
    "VignetteAmount",
    "VignetteMidpoint"
  },
  localizedAdjustments = {
    "EnableCircularGradientBasedCorrections",
    "EnableGradientBasedCorrections",
    "EnablePaintBasedCorrections",
    "EnableRedEye",
    "EnableRetouch",
    "RetouchInfo",
    "RedEyeInfo"
  },
  miscellaneous = {
    "orientation",
    "CropConstrainToWarp",
    "CropAngle",
    "CropBottom",
    "CropLeft",
    "CropRight",
    "CropTop"
  },
  splitToningPanel = {
    "EnableSplitToning",
    "SplitToningShadowHue",
    "SplitToningShadowSaturation",
    "SplitToningHighlightHue",
    "SplitToningHighlightSaturation",
    "SplitToningBalance"
  },
  toneCurve = {
    "ToneCurve",
    "ParametricDarks",
    "ParametricLights",
    "ParametricShadows",
    "ParametricHighlights",
    "ParametricShadowSplit",
    "ParametricMidtoneSplit",
    "ParametricHighlightSplit"
  }
}
local LimitEligible = {
  Blacks = {
    "Blacks",
    29
  },
  BlueHue = {
    "Blue Hue Calibration",
    250
  },
  BlueSaturation = {
    "Blue Saturation Calibration",
    251
  },
  Brightness = {
    "Brightness",
    22
  },
  Clarity = {
    "Clarity",
    31
  },
  ColorNoiseReduction = {
    "Color Noise Reduction",
    153
  },
  ColorNoiseReductionDetail = {
    "Color Noise Reduction Detail",
    154
  },
  ColorNoiseReductionSmoothness = {
    "Color Noise Reduction Smoothness",
    155
  },
  Contrast = {
    "Contrast",
    19
  },
  CropAngle = {
    "Crop Angle",
    353
  },
  CropBottom = {
    "Crop - Bottom",
    354
  },
  CropLeft = {
    "Crop - Left",
    355
  },
  CropRight = {
    "Crop - Right",
    356
  },
  CropTop = {
    "Crop - Top",
    357
  },
  DefringeGreenAmount = {
    "Defringe Green Amount",
    188
  },
  DefringeGreenHueHi = {
    "Defringe Green Hue - High",
    190
  },
  DefringeGreenHueLo = {
    "Defringe Green Hue - Low",
    189
  },
  DefringePurpleAmount = {
    "Defringe Purple Amount",
    185
  },
  DefringePurpleHueHi = {
    "Defringe Purple Hue - High",
    187
  },
  DefringePurpleHueLo = {
    "Defringe Purple Hue - Low",
    186
  },
  Dehaze = {
    "Dehaze Amount",
    214
  },
  Exposure = {
    "Exposure",
    17
  },
  GrainAmount = {
    "Grain Amount",
    221
  },
  GrainFrequency = {
    "Grain Roughness",
    223
  },
  GrainSize = {
    "Grain Size",
    222
  },
  GrayMixerAqua = {
    "Gray Mixer Aqua",
    98
  },
  GrayMixerBlue = {
    "Gray Mixer Blue",
    99
  },
  GrayMixerGreen = {
    "Gray Mixer Green",
    97
  },
  GrayMixerMagenta = {
    "Gray Mixer Magenta",
    101
  },
  GrayMixerOrange = {
    "Gray Mixer Orange",
    95
  },
  GrayMixerPurple = {
    "Gray Mixer Purple",
    100
  },
  GrayMixerRed = {
    "Gray Mixer Red",
    94
  },
  GrayMixerYellow = {
    "Gray Mixer Yellow",
    96
  },
  GreenHue = {
    "Green Hue Calibration",
    248
  },
  GreenSaturation = {
    "Green Saturation Calibration",
    249
  },
  Highlights = {
    "Highlights (Recovery in PV2003 and PV2010)",
    21
  },
  HueAdjustmentAqua = {
    "Hue Adjustment Aqua",
    80
  },
  HueAdjustmentBlue = {
    "Hue Adjustment Blue",
    81
  },
  HueAdjustmentGreen = {
    "Hue Adjustment Green",
    79
  },
  HueAdjustmentMagenta = {
    "Hue Adjustment Magenta",
    83
  },
  HueAdjustmentOrange = {
    "Hue Adjustment Orange",
    77
  },
  HueAdjustmentPurple = {
    "Hue Adjustment Purple",
    82
  },
  HueAdjustmentRed = {
    "Hue Adjustment Red",
    76
  },
  HueAdjustmentYellow = {
    "Hue Adjustment Yellow",
    78
  },
  LensManualDistortionAmount = {
    "Lens Manual Distortion Amount",
    197
  },
  LensProfileChromaticAberrationScale = {
    "Lens Profile Chromatic Aberration Scale",
    180
  },
  LensProfileDistortionScale = {
    "Lens Profile Distortion Scale",
    179
  },
  LensProfileVignettingScale = {
    "Lens Profile Vignetting Scale",
    181
  },
  LuminanceAdjustmentAqua = {
    "Luminance Adjustment Aqua",
    88
  },
  LuminanceAdjustmentBlue = {
    "Luminance Adjustment Blue",
    89
  },
  LuminanceAdjustmentGreen = {
    "Luminance Adjustment Green",
    87
  },
  LuminanceAdjustmentMagenta = {
    "Luminance Adjustment Magenta",
    91
  },
  LuminanceAdjustmentOrange = {
    "Luminance Adjustment Orange",
    85
  },
  LuminanceAdjustmentPurple = {
    "Luminance Adjustment Purple",
    90
  },
  LuminanceAdjustmentRed = {
    "Luminance Adjustment Red",
    84
  },
  LuminanceAdjustmentYellow = {
    "Luminance Adjustment Yellow",
    86
  },
  LuminanceNoiseReductionContrast = {
    "Luminance Contrast",
    152
  },
  LuminanceNoiseReductionDetail = {
    "Luminance Detail",
    151
  },
  LuminanceSmoothing = {
    "Luminance Smoothing",
    150
  },
  ParametricDarks = {
    "Dark Tones",
    53
  },
  ParametricHighlightSplit = {
    "Highlight Split",
    59
  },
  ParametricHighlights = {
    "Highlight Tones",
    56
  },
  ParametricLights = {
    "Light Tones",
    54
  },
  ParametricMidtoneSplit = {
    "Midtone Split",
    58
  },
  ParametricShadowSplit = {
    "Shadow Split",
    57
  },
  ParametricShadows = {
    "Shadow Tones",
    55
  },
  PerspectiveAspect = {
    "Perspective Aspect",
    202
  },
  PerspectiveHorizontal = {
    "Perspective Horizontal",
    199
  },
  PerspectiveRotate = {
    "Perspective Rotate",
    200
  },
  PerspectiveScale = {
    "Perspective Scale",
    201
  },
  PerspectiveVertical = {
    "Perspective Vertical",
    198
  },
  PostCropVignetteAmount = {
    "Post Crop Vignette Amount",
    215
  },
  PostCropVignetteFeather = {
    "Post Crop Vignette Feather",
    217
  },
  PostCropVignetteHighlightContrast = {
    "Post Crop Vignette Highlight Contrast",
    220
  },
  PostCropVignetteMidpoint = {
    "Post Crop Vignette Midpoint",
    216
  },
  PostCropVignetteRoundness = {
    "Post Crop Vignette Roundness",
    218
  },
  PostCropVignetteStyle = {
    "Post Crop Vignette Style",
    219
  },
  RedHue = {
    "Red Hue Calibration",
    246
  },
  RedSaturation = {
    "Red Saturation Calibration",
    247
  },
  Saturation = {
    "Saturation",
    34
  },
  SaturationAdjustmentAqua = {
    "Saturation Adjustment Aqua",
    72
  },
  SaturationAdjustmentBlue = {
    "Saturation Adjustment Blue",
    73
  },
  SaturationAdjustmentGreen = {
    "Saturation Adjustment Green",
    71
  },
  SaturationAdjustmentMagenta = {
    "Saturation Adjustment Magenta",
    75
  },
  SaturationAdjustmentOrange = {
    "Saturation Adjustment Orange",
    69
  },
  SaturationAdjustmentPurple = {
    "Saturation Adjustment Purple",
    74
  },
  SaturationAdjustmentRed = {
    "Saturation Adjustment Red",
    68
  },
  SaturationAdjustmentYellow = {
    "Saturation Adjustment Yellow",
    70
  },
  ShadowTint = {
    "Shadow Tint Calibration",
    245
  },
  Shadows = {
    "Shadows (Fill Light in PV2003 and PV2010)",
    24
  },
  SharpenDetail = {
    "Sharpen Detail",
    148
  },
  SharpenEdgeMasking = {
    "Sharpen Edge Masking",
    149
  },
  SharpenRadius = {
    "Sharpen Radius",
    147
  },
  Sharpness = {
    "Sharpness",
    146
  },
  SplitToningBalance = {
    "Split Toning Balance",
    139
  },
  SplitToningHighlightHue = {
    "Highlight Hue",
    137
  },
  SplitToningHighlightSaturation = {
    "Highlight Saturation",
    138
  },
  SplitToningShadowHue = {
    "Shadow Hue",
    135
  },
  SplitToningShadowSaturation = {
    "Shadow Saturation",
    136
  },
  Temperature = {
    "Temperature",
    15
  },
  Tint = {
    "Tint",
    16
  },
  Vibrance = {
    "Vibrance",
    33
  },
  VignetteAmount = {
    "Vignette Amount",
    203
  },
  VignetteMidpoint = {
    "Vignette Midpoint",
    204
  },
  Whites = {
    "Whites (no effect in PV2003 and PV2010)",
    27
  },
  local_Clarity = {
    "Local Clarity (PV2010 and PV2012)",
    315
  },
  local_Contrast = {
    "Local Contrast (PV2010 and PV2012)",
    312
  },
  local_Defringe = {
    "Local Defringe (PV2012)",
    320
  },
  local_Exposure = {
    "Local Exposure (PV2010 and PV2012)",
    311
  },
  local_Highlights = {
    "Local Highlights (PV2012)",
    313
  },
  local_LuminanceNoise = {
    "Local Luminance Noise (PV2012)",
    318
  },
  local_Moire = {
    "Local Moire (PV2012)",
    319
  },
  local_Saturation = {
    "Local Saturation (PV2010 and PV2012)",
    316
  },
  local_Shadows = {
    "Local Shadows (PV2012)",
    314
  },
  local_Sharpness = {
    "Local Sharpness (PV2010 and PV 2012)",
    317
  },
  local_Temperature = {
    "Local Temperature (PV2012)",
    309
  },
  local_Tint = {
    "Local Tint (PV2012)",
    310
  },
  local_ToningLuminance = {
    "Local Toning Luminance (PV2010)",
    321
  }
}
local SendToMidi = {
  "Temperature",
  "Tint",
  "Exposure",
  "Contrast",
  "Highlights",
  "Brightness",
  "Shadows",
  "Whites",
  "Blacks",
  "Clarity",
  "Vibrance",
  "Saturation",
  "ParametricDarks",
  "ParametricLights",
  "ParametricShadows",
  "ParametricHighlights",
  "ParametricShadowSplit",
  "ParametricMidtoneSplit",
  "ParametricHighlightSplit",
  "SaturationAdjustmentRed",
  "SaturationAdjustmentOrange",
  "SaturationAdjustmentYellow",
  "SaturationAdjustmentGreen",
  "SaturationAdjustmentAqua",
  "SaturationAdjustmentBlue",
  "SaturationAdjustmentPurple",
  "SaturationAdjustmentMagenta",
  "HueAdjustmentRed",
  "HueAdjustmentOrange",
  "HueAdjustmentYellow",
  "HueAdjustmentGreen",
  "HueAdjustmentAqua",
  "HueAdjustmentBlue",
  "HueAdjustmentPurple",
  "HueAdjustmentMagenta",
  "LuminanceAdjustmentRed",
  "LuminanceAdjustmentOrange",
  "LuminanceAdjustmentYellow",
  "LuminanceAdjustmentGreen",
  "LuminanceAdjustmentAqua",
  "LuminanceAdjustmentBlue",
  "LuminanceAdjustmentPurple",
  "LuminanceAdjustmentMagenta",
  "GrayMixerRed",
  "GrayMixerOrange",
  "GrayMixerYellow",
  "GrayMixerGreen",
  "GrayMixerAqua",
  "GrayMixerBlue",
  "GrayMixerPurple",
  "GrayMixerMagenta",
  "SplitToningShadowHue",
  "SplitToningShadowSaturation",
  "SplitToningHighlightHue",
  "SplitToningHighlightSaturation",
  "SplitToningBalance",
  "Sharpness",
  "SharpenRadius",
  "SharpenDetail",
  "SharpenEdgeMasking",
  "LuminanceSmoothing",
  "LuminanceNoiseReductionDetail",
  "LuminanceNoiseReductionContrast",
  "ColorNoiseReduction",
  "ColorNoiseReductionDetail",
  "ColorNoiseReductionSmoothness",
  "LensProfileDistortionScale",
  "LensProfileChromaticAberrationScale",
  "LensProfileVignettingScale",
  "DefringePurpleAmount",
  "DefringePurpleHueLo",
  "DefringePurpleHueHi",
  "DefringeGreenAmount",
  "DefringeGreenHueLo",
  "DefringeGreenHueHi",
  "LensManualDistortionAmount",
  "PerspectiveVertical",
  "PerspectiveHorizontal",
  "PerspectiveRotate",
  "PerspectiveScale",
  "PerspectiveAspect",
  "VignetteAmount",
  "VignetteMidpoint",
  "Dehaze",
  "PostCropVignetteAmount",
  "PostCropVignetteMidpoint",
  "PostCropVignetteFeather",
  "PostCropVignetteRoundness",
  "PostCropVignetteStyle",
  "PostCropVignetteHighlightContrast",
  "GrainAmount",
  "GrainSize",
  "GrainFrequency",
  "ShadowTint",
  "RedHue",
  "RedSaturation",
  "GreenHue",
  "GreenSaturation",
  "BlueHue",
  "BlueSaturation",
  "local_Temperature",
  "local_Tint",
  "local_Exposure",
  "local_Contrast",
  "local_Highlights",
  "local_Shadows",
  "local_Clarity",
  "local_Saturation",
  "local_Sharpness",
  "local_LuminanceNoise",
  "local_Moire",
  "local_Defringe",
  "local_ToningLuminance",
  "CropAngle",
  "CropBottom",
  "CropLeft",
  "CropRight",
  "CropTop"
}
local ProfileMap = {
  AutoLateralCA = "lensCorrectionsPanel",
  Blacks = "adjustPanel",
  BlueHue = "calibratePanel",
  BlueSaturation = "calibratePanel",
  Brightness = "adjustPanel",
  Clarity = "adjustPanel",
  ColorNoiseReduction = "detailPanel",
  ColorNoiseReductionDetail = "detailPanel",
  ColorNoiseReductionSmoothness = "detailPanel",
  Contrast = "adjustPanel",
  ConvertToGrayscale = "tonePanel",
  CropAngle = "crop",
  CropBottom = "crop",
  CropLeft = "crop",
  CropRight = "crop",
  CropTop = "crop",
  DefringeGreenAmount = "lensCorrectionsPanel",
  DefringeGreenHueHi = "lensCorrectionsPanel",
  DefringeGreenHueLo = "lensCorrectionsPanel",
  DefringePurpleAmount = "lensCorrectionsPanel",
  DefringePurpleHueHi = "lensCorrectionsPanel",
  DefringePurpleHueLo = "lensCorrectionsPanel",
  Dehaze = "effectsPanel",
  EnableCalibration = "calibratePanel",
  EnableColorAdjustments = "tonePanel",
  EnableDetail = "detailPanel",
  EnableEffects = "effectsPanel",
  EnableGrayscaleMix = "tonePanel",
  EnableLensCorrections = "lensCorrectionsPanel",
  EnableSplitToning = "splitToningPanel",
  Exposure = "adjustPanel",
  GrainAmount = "effectsPanel",
  GrainFrequency = "effectsPanel",
  GrainSize = "effectsPanel",
  GrayMixerAqua = "tonePanel",
  GrayMixerBlue = "tonePanel",
  GrayMixerGreen = "tonePanel",
  GrayMixerMagenta = "tonePanel",
  GrayMixerOrange = "tonePanel",
  GrayMixerPurple = "tonePanel",
  GrayMixerRed = "tonePanel",
  GrayMixerYellow = "tonePanel",
  GreenHue = "calibratePanel",
  GreenSaturation = "calibratePanel",
  Highlights = "adjustPanel",
  HueAdjustmentAqua = "tonePanel",
  HueAdjustmentBlue = "tonePanel",
  HueAdjustmentGreen = "tonePanel",
  HueAdjustmentMagenta = "tonePanel",
  HueAdjustmentOrange = "tonePanel",
  HueAdjustmentPurple = "tonePanel",
  HueAdjustmentRed = "tonePanel",
  HueAdjustmentYellow = "tonePanel",
  LensManualDistortionAmount = "lensCorrectionsPanel",
  LensProfileChromaticAberrationScale = "lensCorrectionsPanel",
  LensProfileDistortionScale = "lensCorrectionsPanel",
  LensProfileEnable = "lensCorrectionsPanel",
  LensProfileVignettingScale = "lensCorrectionsPanel",
  Loupe = "loupe",
  LuminanceAdjustmentAqua = "tonePanel",
  LuminanceAdjustmentBlue = "tonePanel",
  LuminanceAdjustmentGreen = "tonePanel",
  LuminanceAdjustmentMagenta = "tonePanel",
  LuminanceAdjustmentOrange = "tonePanel",
  LuminanceAdjustmentPurple = "tonePanel",
  LuminanceAdjustmentRed = "tonePanel",
  LuminanceAdjustmentYellow = "tonePanel",
  LuminanceNoiseReductionContrast = "detailPanel",
  LuminanceNoiseReductionDetail = "detailPanel",
  LuminanceSmoothing = "detailPanel",
  ParametricDarks = "tonePanel",
  ParametricHighlightSplit = "tonePanel",
  ParametricHighlights = "tonePanel",
  ParametricLights = "tonePanel",
  ParametricMidtoneSplit = "tonePanel",
  ParametricShadowSplit = "tonePanel",
  ParametricShadows = "tonePanel",
  PerspectiveAspect = "lensCorrectionsPanel",
  PerspectiveHorizontal = "lensCorrectionsPanel",
  PerspectiveRotate = "lensCorrectionsPanel",
  PerspectiveScale = "lensCorrectionsPanel",
  PerspectiveVertical = "lensCorrectionsPanel",
  PostCropVignetteAmount = "effectsPanel",
  PostCropVignetteFeather = "effectsPanel",
  PostCropVignetteHighlightContrast = "effectsPanel",
  PostCropVignetteMidpoint = "effectsPanel",
  PostCropVignetteRoundness = "effectsPanel",
  PostCropVignetteStyle = "effectsPanel",
  Profile_Adobe_Standard = "calibratePanel",
  Profile_Camera_Clear = "calibratePanel",
  Profile_Camera_Deep = "calibratePanel",
  Profile_Camera_Landscape = "calibratePanel",
  Profile_Camera_Light = "calibratePanel",
  Profile_Camera_Neutral = "calibratePanel",
  Profile_Camera_Portrait = "calibratePanel",
  Profile_Camera_Standard = "calibratePanel",
  Profile_Camera_Vivid = "calibratePanel",
  RedHue = "calibratePanel",
  RedSaturation = "calibratePanel",
  ResetBlacks = "adjustPanel",
  ResetBlueHue = "calibratePanel",
  ResetBlueSaturation = "calibratePanel",
  ResetClarity = "adjustPanel",
  ResetColorNoiseReduction = "detailPanel",
  ResetColorNoiseReductionDetail = "detailPanel",
  ResetColorNoiseReductionSmoothness = "detailPanel",
  ResetContrast = "adjustPanel",
  ResetCrop = "crop",
  ResetDefringeGreenAmount = "lensCorrectionsPanel",
  ResetDefringeGreenHueHi = "lensCorrectionsPanel",
  ResetDefringeGreenHueLo = "lensCorrectionsPanel",
  ResetDefringePurpleAmount = "lensCorrectionsPanel",
  ResetDefringePurpleHueHi = "lensCorrectionsPanel",
  ResetDefringePurpleHueLo = "lensCorrectionsPanel",
  ResetDehaze = "effectsPanel",
  ResetExposure = "adjustPanel",
  ResetGrainAmount = "effectsPanel",
  ResetGrainFrequency = "effectsPanel",
  ResetGrainSize = "effectsPanel",
  ResetGrayMixerAqua = "tonePanel",
  ResetGrayMixerBlue = "tonePanel",
  ResetGrayMixerGreen = "tonePanel",
  ResetGrayMixerMagenta = "tonePanel",
  ResetGrayMixerOrange = "tonePanel",
  ResetGrayMixerPurple = "tonePanel",
  ResetGrayMixerRed = "tonePanel",
  ResetGrayMixerYellow = "tonePanel",
  ResetGreenHue = "calibratePanel",
  ResetGreenSaturation = "calibratePanel",
  ResetHighlights = "adjustPanel",
  ResetHueAdjustmentAqua = "tonePanel",
  ResetHueAdjustmentBlue = "tonePanel",
  ResetHueAdjustmentGreen = "tonePanel",
  ResetHueAdjustmentMagenta = "tonePanel",
  ResetHueAdjustmentOrange = "tonePanel",
  ResetHueAdjustmentPurple = "tonePanel",
  ResetHueAdjustmentRed = "tonePanel",
  ResetHueAdjustmentYellow = "tonePanel",
  ResetLensManualDistortionAmount = "lensCorrectionsPanel",
  ResetLensProfileChromaticAberrationScale = "lensCorrectionsPanel",
  ResetLensProfileDistortionScale = "lensCorrectionsPanel",
  ResetLensProfileVignettingScale = "lensCorrectionsPanel",
  ResetLuminanceAdjustmentAqua = "tonePanel",
  ResetLuminanceAdjustmentBlue = "tonePanel",
  ResetLuminanceAdjustmentGreen = "tonePanel",
  ResetLuminanceAdjustmentMagenta = "tonePanel",
  ResetLuminanceAdjustmentOrange = "tonePanel",
  ResetLuminanceAdjustmentPurple = "tonePanel",
  ResetLuminanceAdjustmentRed = "tonePanel",
  ResetLuminanceAdjustmentYellow = "tonePanel",
  ResetLuminanceNoiseReductionContrast = "detailPanel",
  ResetLuminanceNoiseReductionDetail = "detailPanel",
  ResetLuminanceSmoothing = "detailPanel",
  ResetParametricDarks = "tonePanel",
  ResetParametricHighlightSplit = "tonePanel",
  ResetParametricHighlights = "tonePanel",
  ResetParametricLights = "tonePanel",
  ResetParametricMidtoneSplit = "tonePanel",
  ResetParametricShadowSplit = "tonePanel",
  ResetParametricShadows = "tonePanel",
  ResetPerspectiveAspect = "lensCorrectionsPanel",
  ResetPerspectiveHorizontal = "lensCorrectionsPanel",
  ResetPerspectiveRotate = "lensCorrectionsPanel",
  ResetPerspectiveScale = "lensCorrectionsPanel",
  ResetPerspectiveUpright = "lensCorrectionsPanel",
  ResetPerspectiveVertical = "lensCorrectionsPanel",
  ResetPostCropVignetteAmount = "effectsPanel",
  ResetPostCropVignetteFeather = "effectsPanel",
  ResetPostCropVignetteHighlightContrast = "effectsPanel",
  ResetPostCropVignetteMidpoint = "effectsPanel",
  ResetPostCropVignetteRoundness = "effectsPanel",
  ResetPostCropVignetteStyle = "effectsPanel",
  ResetRedHue = "calibratePanel",
  ResetRedSaturation = "calibratePanel",
  ResetSaturation = "adjustPanel",
  ResetSaturationAdjustmentAqua = "tonePanel",
  ResetSaturationAdjustmentBlue = "tonePanel",
  ResetSaturationAdjustmentGreen = "tonePanel",
  ResetSaturationAdjustmentMagenta = "tonePanel",
  ResetSaturationAdjustmentOrange = "tonePanel",
  ResetSaturationAdjustmentPurple = "tonePanel",
  ResetSaturationAdjustmentRed = "tonePanel",
  ResetSaturationAdjustmentYellow = "tonePanel",
  ResetShadowTint = "calibratePanel",
  ResetShadows = "adjustPanel",
  ResetSharpenDetail = "detailPanel",
  ResetSharpenEdgeMasking = "detailPanel",
  ResetSharpenRadius = "detailPanel",
  ResetSharpness = "detailPanel",
  ResetSplitToningBalance = "splitToningPanel",
  ResetSplitToningHighlightHue = "splitToningPanel",
  ResetSplitToningHighlightSaturation = "splitToningPanel",
  ResetSplitToningShadowHue = "splitToningPanel",
  ResetSplitToningShadowSaturation = "splitToningPanel",
  ResetTemperature = "adjustPanel",
  ResetTint = "adjustPanel",
  ResetVibrance = "adjustPanel",
  ResetVignetteAmount = "lensCorrectionsPanel",
  ResetVignetteMidpoint = "lensCorrectionsPanel",
  ResetWhites = "adjustPanel",
  Saturation = "adjustPanel",
  SaturationAdjustmentAqua = "tonePanel",
  SaturationAdjustmentBlue = "tonePanel",
  SaturationAdjustmentGreen = "tonePanel",
  SaturationAdjustmentMagenta = "tonePanel",
  SaturationAdjustmentOrange = "tonePanel",
  SaturationAdjustmentPurple = "tonePanel",
  SaturationAdjustmentRed = "tonePanel",
  SaturationAdjustmentYellow = "tonePanel",
  ShadowTint = "calibratePanel",
  Shadows = "adjustPanel",
  SharpenDetail = "detailPanel",
  SharpenEdgeMasking = "detailPanel",
  SharpenRadius = "detailPanel",
  Sharpness = "detailPanel",
  SplitToningBalance = "splitToningPanel",
  SplitToningHighlightHue = "splitToningPanel",
  SplitToningHighlightSaturation = "splitToningPanel",
  SplitToningShadowHue = "splitToningPanel",
  SplitToningShadowSaturation = "splitToningPanel",
  Temperature = "adjustPanel",
  Tint = "adjustPanel",
  UprightAuto = "lensCorrectionsPanel",
  UprightFull = "lensCorrectionsPanel",
  UprightLevel = "lensCorrectionsPanel",
  UprightOff = "lensCorrectionsPanel",
  UprightVertical = "lensCorrectionsPanel",
  Vibrance = "adjustPanel",
  VignetteAmount = "lensCorrectionsPanel",
  VignetteMidpoint = "lensCorrectionsPanel",
  WhiteBalanceAs_Shot = "adjustPanel",
  WhiteBalanceAuto = "adjustPanel",
  WhiteBalanceCloudy = "adjustPanel",
  WhiteBalanceDaylight = "adjustPanel",
  WhiteBalanceFlash = "adjustPanel",
  WhiteBalanceFluorescent = "adjustPanel",
  WhiteBalanceShade = "adjustPanel",
  WhiteBalanceTungsten = "adjustPanel",
  Whites = "adjustPanel"
}
return {
  SelectivePasteMenu = SelectivePasteMenu,
  SelectivePasteHidden = SelectivePasteHidden,
  SelectivePasteIteration = SelectivePasteIteration,
  SelectivePasteGroups = SelectivePasteGroups,
  LimitEligible = LimitEligible,
  SendToMidi = SendToMidi,
  ProfileMap = ProfileMap,
  }